// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

import android.graphics.Point;
import android.graphics.PointF;
import android.graphics.Rect;
import com.fotoable.photocollage.model.res.collage.TPhotoCollageComposeInfo;
import com.wantu.model.res.EResType;
import java.util.ArrayList;
import java.util.List;

public class lo
{

    public static Rect a(int i, int j, int k, int l)
    {
        return new Rect(i, j, i + k, j + l);
    }

    public static List a()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_1.jpg";
        tphotocollagecomposeinfo.name = "oneframe_1";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 306));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_9.jpg";
        tphotocollagecomposeinfo.name = "oneframe_9";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 255, 255));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_10.jpg";
        tphotocollagecomposeinfo.name = "oneframe_10";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 255, 306));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_11.jpg";
        tphotocollagecomposeinfo.name = "oneframe_11";
        arraylist1 = new ArrayList();
        arraylist1.add(a(50, 50, 206, 206));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_2.jpg";
        tphotocollagecomposeinfo.name = "oneframe_2";
        arraylist1 = new ArrayList();
        arraylist1.add(a(40, 3, 226, 300));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_3.jpg";
        tphotocollagecomposeinfo.name = "oneframe_3";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 40, 306, 226));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_5.jpg";
        tphotocollagecomposeinfo.name = "oneframe_5";
        arraylist1 = new ArrayList();
        arraylist1.add(a(80, 5, 146, 306));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_6.jpg";
        tphotocollagecomposeinfo.name = "oneframe_6";
        arraylist1 = new ArrayList();
        arraylist1.add(a(5, 40, 296, 146));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle/oneframe_12.jpg");
        tphotocollagecomposeinfo.name = "oneframe_12";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(153, 10));
        arraylist2.add(new Point(25, 80));
        arraylist2.add(new Point(25, 220));
        arraylist2.add(new Point(153, 296));
        arraylist2.add(new Point(281, 220));
        arraylist2.add(new Point(281, 80));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.0F, -1F));
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist2.add(new PointF(0.0F, 1.0F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle/oneframe_13.jpg");
        tphotocollagecomposeinfo.name = "oneframe_13";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(80, 25));
        arraylist2.add(new Point(10, 153));
        arraylist2.add(new Point(80, 281));
        arraylist2.add(new Point(226, 281));
        arraylist2.add(new Point(296, 153));
        arraylist2.add(new Point(226, 25));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, 0.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(-1F, 0.0F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle/oneframe_15.jpg");
        tphotocollagecomposeinfo.name = "oneframe_15";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 25));
        arraylist2.add(new Point(0, 266));
        arraylist2.add(new Point(153, 226));
        arraylist2.add(new Point(306, 266));
        arraylist2.add(new Point(306, 25));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist2.add(new PointF(0.0F, 1.0F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }

    public static List b()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle43/oneframe_r1.jpg");
        tphotocollagecomposeinfo.name = "oneframe_r1";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 408));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle43/oneframe_r2.jpg");
        tphotocollagecomposeinfo.name = "oneframe_r2";
        arraylist1 = new ArrayList();
        arraylist1.add(a(10, 10, 286, 388));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle43/oneframe_r3.jpg");
        tphotocollagecomposeinfo.name = "oneframe_r3";
        arraylist1 = new ArrayList();
        arraylist1.add(a(10, 10, 290, 314));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle43/oneframe_r4.jpg");
        tphotocollagecomposeinfo.name = "oneframe_r4";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 204));
        arraylist2.add(new Point(153, 0));
        arraylist2.add(new Point(306, 204));
        arraylist2.add(new Point(153, 408));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, 0.0F));
        arraylist2.add(new PointF(0.0F, -1F));
        arraylist2.add(new PointF(-1F, 0.0F));
        arraylist2.add(new PointF(0.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_9.jpg";
        tphotocollagecomposeinfo.name = "oneframe_9";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 280, 361));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_10.jpg";
        tphotocollagecomposeinfo.name = "oneframe_10";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 255, 408));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_11.jpg";
        tphotocollagecomposeinfo.name = "oneframe_11";
        arraylist1 = new ArrayList();
        arraylist1.add(a(40, 40, 226, 328));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_5.jpg";
        tphotocollagecomposeinfo.name = "oneframe_5";
        arraylist1 = new ArrayList();
        arraylist1.add(a(75, 0, 156, 408));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/oneframe_6.jpg";
        tphotocollagecomposeinfo.name = "oneframe_6";
        arraylist1 = new ArrayList();
        arraylist1.add(a(5, 40, 296, 200));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.setIcon("fixComposeStyle/oneframe_15.jpg");
        tphotocollagecomposeinfo.name = "oneframe_15";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 40));
        arraylist2.add(new Point(0, 338));
        arraylist2.add(new Point(153, 300));
        arraylist2.add(new Point(306, 338));
        arraylist2.add(new Point(306, 40));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist2.add(new PointF(0.0F, 1.0F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }
}
