// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

import android.graphics.PointF;
import android.graphics.Rect;
import com.fotoable.photocollage.model.res.collage.TPhotoCollageComposeInfo;
import com.wantu.model.res.EResType;
import java.util.ArrayList;
import java.util.List;

public class lp
{

    public static Rect a(int i, int j, int k, int l)
    {
        return new Rect(i, j, i + k, j + l);
    }

    public static List a()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/tenframe_1.jpg";
        tphotocollagecomposeinfo.name = "tenframe_1";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 102, 102));
        arraylist1.add(a(0, 102, 102, 102));
        arraylist1.add(a(0, 204, 102, 102));
        arraylist1.add(a(102, 0, 102, 76));
        arraylist1.add(a(102, 76, 102, 77));
        arraylist1.add(a(102, 153, 102, 77));
        arraylist1.add(a(102, 230, 102, 76));
        arraylist1.add(a(204, 0, 102, 102));
        arraylist1.add(a(204, 102, 102, 102));
        arraylist1.add(a(204, 204, 102, 102));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }

    public static List b()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/tenframe_r1.jpg";
        tphotocollagecomposeinfo.name = "tenframe_r1";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 102, 136));
        arraylist1.add(a(0, 136, 102, 136));
        arraylist1.add(a(0, 272, 102, 136));
        arraylist1.add(a(102, 0, 102, 102));
        arraylist1.add(a(102, 102, 102, 102));
        arraylist1.add(a(102, 204, 102, 102));
        arraylist1.add(a(102, 306, 102, 102));
        arraylist1.add(a(204, 0, 102, 136));
        arraylist1.add(a(204, 136, 102, 136));
        arraylist1.add(a(204, 272, 102, 136));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/tenframe_r2.jpg";
        tphotocollagecomposeinfo.name = "tenframe_r2";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 102, 136));
        arraylist1.add(a(102, 0, 102, 136));
        arraylist1.add(a(204, 0, 102, 136));
        arraylist1.add(a(0, 136, 76, 136));
        arraylist1.add(a(76, 136, 77, 136));
        arraylist1.add(a(153, 136, 77, 136));
        arraylist1.add(a(230, 136, 76, 136));
        arraylist1.add(a(0, 272, 102, 136));
        arraylist1.add(a(102, 272, 102, 136));
        arraylist1.add(a(204, 272, 102, 136));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/tenframe_r3.jpg";
        tphotocollagecomposeinfo.name = "tenframe_r3";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 76, 136));
        arraylist1.add(a(76, 0, 77, 136));
        arraylist1.add(a(153, 0, 77, 136));
        arraylist1.add(a(230, 0, 76, 136));
        arraylist1.add(a(0, 136, 153, 136));
        arraylist1.add(a(153, 136, 153, 136));
        arraylist1.add(a(0, 272, 76, 136));
        arraylist1.add(a(76, 272, 77, 136));
        arraylist1.add(a(153, 272, 77, 136));
        arraylist1.add(a(230, 272, 76, 136));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }
}
