// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

import android.graphics.Point;
import android.graphics.PointF;
import android.graphics.Rect;
import com.fotoable.photocollage.model.res.collage.TPhotoCollageComposeInfo;
import com.wantu.model.res.EResType;
import java.util.ArrayList;
import java.util.List;

public class lq
{

    public static Rect a(int i, int j, int k, int l)
    {
        return new Rect(i, j, i + k, j + l);
    }

    public static List a()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_2.jpg";
        tphotocollagecomposeinfo.name = "twoframe_2";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 306));
        arraylist1.add(a(153, 0, 153, 306));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_4.jpg";
        tphotocollagecomposeinfo.name = "twoframe_4";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 153));
        arraylist1.add(a(0, 153, 306, 153));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_6.jpg";
        tphotocollagecomposeinfo.name = "twoframe_6";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 118, 306));
        arraylist1.add(a(118, 0, 188, 306));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_14.jpg";
        tphotocollagecomposeinfo.name = "twoframe_14";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 108));
        arraylist1.add(a(0, 108, 306, 198));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_18.jpg";
        tphotocollagecomposeinfo.name = "twoframe_18";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 306));
        arraylist1.add(a(10, 150, 146, 146));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_11.jpg";
        tphotocollagecomposeinfo.name = "twoframe_11";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 85, 153, 153));
        arraylist1.add(a(153, 85, 153, 153));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_10.jpg";
        tphotocollagecomposeinfo.name = "twoframe_10";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 38, 153, 230));
        arraylist1.add(a(153, 38, 153, 230));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_29.jpg";
        tphotocollagecomposeinfo.name = "twoframe_29";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(5, 5));
        arraylist2.add(new Point(145, 5));
        arraylist2.add(new Point(145, 145));
        arraylist2.add(new Point(5, 145));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(145, 77));
        arraylist2.add(new Point(301, 77));
        arraylist2.add(new Point(301, 301));
        arraylist2.add(new Point(77, 301));
        arraylist2.add(new Point(77, 145));
        arraylist2.add(new Point(145, 145));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_26.jpg";
        tphotocollagecomposeinfo.name = "twoframe_26";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 153));
        arraylist1.add(a(153, 153, 153, 153));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_7.jpg";
        tphotocollagecomposeinfo.name = "twoframe_7";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 220));
        arraylist1.add(a(153, 86, 153, 220));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_16.jpg";
        tphotocollagecomposeinfo.name = "twoframe_16";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 198, 306));
        arraylist1.add(a(198, 0, 108, 306));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_12.jpg";
        tphotocollagecomposeinfo.name = "twoframe_12";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 130));
        arraylist2.add(new Point(0, 176));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 176));
        arraylist2.add(new Point(306, 130));
        arraylist2.add(new Point(306, 306));
        arraylist2.add(new Point(0, 306));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_15.jpg";
        tphotocollagecomposeinfo.name = "twoframe_15";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 198));
        arraylist1.add(a(0, 198, 306, 108));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_13.jpg";
        tphotocollagecomposeinfo.name = "twoframe_13";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(178, 0));
        arraylist2.add(new Point(130, 306));
        arraylist2.add(new Point(0, 306));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(178, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 306));
        arraylist2.add(new Point(130, 306));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_25.jpg";
        tphotocollagecomposeinfo.name = "twoframe_25";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 181));
        arraylist1.add(a(0, 181, 125, 125));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_28.jpg";
        tphotocollagecomposeinfo.name = "twoframe_28";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 306));
        arraylist1.add(a(153, 153, 153, 153));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_27.jpg";
        tphotocollagecomposeinfo.name = "twoframe_27";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 93, 112, 120));
        arraylist1.add(a(112, 93, 194, 120));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_1.jpg";
        tphotocollagecomposeinfo.name = "twoframe_1";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 230));
        arraylist1.add(a(153, 0, 153, 230));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_3.jpg";
        tphotocollagecomposeinfo.name = "twoframe_3";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 245, 153));
        arraylist1.add(a(56, 153, 250, 153));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_31.jpg";
        tphotocollagecomposeinfo.name = "twoframe_31";
        arraylist1 = new ArrayList();
        arraylist1.add(a(181, 0, 125, 125));
        arraylist1.add(a(0, 125, 306, 181));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_24.jpg";
        tphotocollagecomposeinfo.name = "twoframe_24";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(136, 10));
        arraylist2.add(new Point(301, 10));
        arraylist2.add(new Point(301, 180));
        arraylist2.add(new Point(136, 180));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(5, 140));
        arraylist2.add(new Point(136, 140));
        arraylist2.add(new Point(136, 180));
        arraylist2.add(new Point(280, 180));
        arraylist2.add(new Point(280, 301));
        arraylist2.add(new Point(5, 301));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_30.jpg";
        tphotocollagecomposeinfo.name = "twoframe_30";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(100, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 148));
        arraylist2.add(new Point(70, 148));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 158));
        arraylist2.add(new Point(236, 158));
        arraylist2.add(new Point(206, 306));
        arraylist2.add(new Point(0, 306));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_17.jpg";
        tphotocollagecomposeinfo.name = "twoframe_17";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 198));
        arraylist1.add(a(0, 198, 306, 108));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_19.jpg";
        tphotocollagecomposeinfo.name = "twoframe_19";
        arraylist1 = new ArrayList();
        arraylist1.add(a(76, 0, 153, 153));
        arraylist1.add(a(76, 153, 153, 153));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_32.jpg";
        tphotocollagecomposeinfo.name = "twoframe_32";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 100));
        arraylist2.add(new Point(0, 306));
        arraylist2.add(new Point(153, 306));
        arraylist2.add(new Point(153, 70));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(153, 40));
        arraylist2.add(new Point(153, 266));
        arraylist2.add(new Point(306, 266));
        arraylist2.add(new Point(306, 10));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_33.jpg";
        tphotocollagecomposeinfo.name = "twoframe_33";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(140, 0));
        arraylist2.add(new Point(164, 180));
        arraylist2.add(new Point(0, 230));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(140, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 306));
        arraylist2.add(new Point(180, 306));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.6F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_34.jpg";
        tphotocollagecomposeinfo.name = "twoframe_34";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 80));
        arraylist2.add(new Point(30, 60));
        arraylist2.add(new Point(153, 60));
        arraylist2.add(new Point(153, 306));
        arraylist2.add(new Point(0, 306));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(153, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 226));
        arraylist2.add(new Point(276, 246));
        arraylist2.add(new Point(153, 246));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_35.jpg";
        tphotocollagecomposeinfo.name = "twoframe_35";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 153));
        arraylist2.add(new Point(120, 170));
        arraylist2.add(new Point(0, 153));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(120, 170));
        arraylist2.add(new Point(306, 153));
        arraylist2.add(new Point(306, 270));
        arraylist2.add(new Point(270, 306));
        arraylist2.add(new Point(140, 306));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.0F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }

    public static List b()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r1.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r1";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 204));
        arraylist1.add(a(0, 204, 306, 204));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r6.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r6";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 408));
        arraylist1.add(a(153, 0, 153, 408));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r2.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r2";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 306));
        arraylist1.add(a(0, 316, 306, 92));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r4.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r4";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(0, 204));
        arraylist2.add(new Point(39, 184));
        arraylist2.add(new Point(77, 204));
        arraylist2.add(new Point(115, 184));
        arraylist2.add(new Point(153, 204));
        arraylist2.add(new Point(191, 184));
        arraylist2.add(new Point(229, 204));
        arraylist2.add(new Point(267, 184));
        arraylist2.add(new Point(306, 204));
        arraylist2.add(new Point(306, 0));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 204));
        arraylist2.add(new Point(39, 184));
        arraylist2.add(new Point(77, 204));
        arraylist2.add(new Point(115, 184));
        arraylist2.add(new Point(153, 204));
        arraylist2.add(new Point(191, 184));
        arraylist2.add(new Point(229, 204));
        arraylist2.add(new Point(267, 184));
        arraylist2.add(new Point(306, 204));
        arraylist2.add(new Point(306, 408));
        arraylist2.add(new Point(0, 408));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist2.add(new PointF(0.75F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist2.add(new PointF(0.25F, 0.5F));
        arraylist2.add(new PointF(0.0F, 0.5F));
        arraylist2.add(new PointF(-0.25F, 0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(-0.75F, 0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(0.75F, -0.5F));
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(0.25F, -0.5F));
        arraylist2.add(new PointF(0.0F, -0.5F));
        arraylist2.add(new PointF(-0.25F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.75F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r5.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r5";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(0, 204));
        arraylist2.add(new Point(158, 164));
        arraylist2.add(new Point(306, 204));
        arraylist2.add(new Point(306, 0));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 204));
        arraylist2.add(new Point(158, 164));
        arraylist2.add(new Point(306, 204));
        arraylist2.add(new Point(306, 408));
        arraylist2.add(new Point(0, 408));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist2.add(new PointF(0.0F, 0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(0.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r8.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r8";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 208));
        arraylist2.add(new Point(0, 408));
        arraylist2.add(new Point(306, 408));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(180, 0));
        arraylist2.add(new Point(123, 153));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(0, 208));
        arraylist2.add(new Point(123, 153));
        arraylist2.add(new Point(180, 0));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist2.add(new PointF(-0.25F, 0.25F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r3.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r3";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 135));
        arraylist2.add(new Point(0, 204));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 204));
        arraylist2.add(new Point(306, 135));
        arraylist2.add(new Point(306, 408));
        arraylist2.add(new Point(0, 408));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r50.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r50";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 240));
        arraylist1.add(a(0, 250, 153, 158));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(10);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r51.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r51";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 153));
        arraylist1.add(a(153, 153, 153, 255));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(10);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r52.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r52";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 268, 135, 140));
        arraylist1.add(a(135, 0, 171, 268));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(10);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r53.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r53";
        arraylist1 = new ArrayList();
        arraylist1.add(a(83, 0, 140, 135));
        arraylist1.add(a(83, 145, 140, 263));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/twoframe_r54.jpg";
        tphotocollagecomposeinfo.name = "twoframe_r54";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 151, 153));
        arraylist1.add(a(156, 0, 150, 408));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_13.jpg";
        tphotocollagecomposeinfo.name = "twoframe_13";
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(0, 0));
        arraylist2.add(new Point(178, 0));
        arraylist2.add(new Point(130, 408));
        arraylist2.add(new Point(0, 408));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new Point(178, 0));
        arraylist2.add(new Point(306, 0));
        arraylist2.add(new Point(306, 408));
        arraylist2.add(new Point(130, 408));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setTrackPointsArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_2.jpg";
        tphotocollagecomposeinfo.name = "twoframe_2";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 153, 408));
        arraylist1.add(a(153, 0, 153, 408));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_16.jpg";
        tphotocollagecomposeinfo.name = "twoframe_16";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 198, 408));
        arraylist1.add(a(198, 0, 108, 408));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_17.jpg";
        tphotocollagecomposeinfo.name = "twoframe_17";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 268));
        arraylist1.add(a(0, 268, 306, 140));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_18.jpg";
        tphotocollagecomposeinfo.name = "twoframe_18";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 408));
        arraylist1.add(a(10, 252, 146, 146));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_19.jpg";
        tphotocollagecomposeinfo.name = "twoframe_19";
        arraylist1 = new ArrayList();
        arraylist1.add(a(76, 0, 153, 204));
        arraylist1.add(a(76, 204, 153, 204));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/twoframe_14.jpg";
        tphotocollagecomposeinfo.name = "twoframe_4";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 306, 140));
        arraylist1.add(a(0, 140, 306, 268));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }
}
