// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

import android.graphics.PointF;
import android.graphics.Rect;
import com.fotoable.photocollage.model.res.collage.TPhotoCollageComposeInfo;
import com.wantu.model.res.EResType;
import java.util.ArrayList;
import java.util.List;

public class lx
{

    public static Rect a(int i, int j, int k, int l)
    {
        return new Rect(i, j, i + k, j + l);
    }

    public static List a()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/nineframe_1.jpg";
        tphotocollagecomposeinfo.name = "nineframe_1";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 102, 102));
        arraylist1.add(a(102, 0, 102, 102));
        arraylist1.add(a(204, 0, 102, 102));
        arraylist1.add(a(0, 102, 102, 102));
        arraylist1.add(a(102, 102, 102, 102));
        arraylist1.add(a(204, 102, 102, 102));
        arraylist1.add(a(0, 204, 102, 102));
        arraylist1.add(a(102, 204, 102, 102));
        arraylist1.add(a(204, 204, 102, 102));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/nineframe_2.jpg";
        tphotocollagecomposeinfo.name = "nineframe_2";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 102, 153));
        arraylist1.add(a(0, 153, 102, 153));
        arraylist1.add(a(102, 0, 102, 102));
        arraylist1.add(a(102, 102, 102, 102));
        arraylist1.add(a(102, 204, 102, 102));
        arraylist1.add(a(204, 0, 102, 76));
        arraylist1.add(a(204, 76, 102, 77));
        arraylist1.add(a(204, 153, 102, 77));
        arraylist1.add(a(204, 230, 102, 76));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/W.jpg";
        tphotocollagecomposeinfo.name = "W";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 45, 72, 72));
        arraylist1.add(a(0, 117, 72, 72));
        arraylist1.add(a(0, 189, 72, 72));
        arraylist1.add(a(117, 45, 72, 72));
        arraylist1.add(a(117, 117, 72, 72));
        arraylist1.add(a(72, 189, 162, 72));
        arraylist1.add(a(234, 45, 72, 72));
        arraylist1.add(a(234, 117, 72, 72));
        arraylist1.add(a(234, 189, 72, 72));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle/X.jpg";
        tphotocollagecomposeinfo.name = "X";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 61, 61));
        arraylist1.add(a(61, 61, 61, 61));
        arraylist1.add(a(122, 122, 61, 61));
        arraylist1.add(a(183, 183, 61, 61));
        arraylist1.add(a(245, 245, 61, 61));
        arraylist1.add(a(245, 0, 61, 61));
        arraylist1.add(a(183, 61, 61, 61));
        arraylist1.add(a(61, 183, 61, 61));
        arraylist1.add(a(0, 245, 61, 61));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }

    public static List b()
    {
        ArrayList arraylist = new ArrayList();
        TPhotoCollageComposeInfo tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/nineframe_r1.jpg";
        tphotocollagecomposeinfo.name = "nineframe_r1";
        ArrayList arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 102, 136));
        arraylist1.add(a(102, 0, 102, 136));
        arraylist1.add(a(204, 0, 102, 136));
        arraylist1.add(a(0, 136, 102, 136));
        arraylist1.add(a(102, 136, 102, 136));
        arraylist1.add(a(204, 136, 102, 136));
        arraylist1.add(a(0, 272, 102, 136));
        arraylist1.add(a(102, 272, 102, 136));
        arraylist1.add(a(204, 272, 102, 136));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        ArrayList arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/nineframe_r2.jpg";
        tphotocollagecomposeinfo.name = "nineframe_r2";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 102, 204));
        arraylist1.add(a(0, 204, 102, 204));
        arraylist1.add(a(102, 0, 102, 136));
        arraylist1.add(a(102, 136, 102, 136));
        arraylist1.add(a(102, 272, 102, 136));
        arraylist1.add(a(204, 0, 102, 102));
        arraylist1.add(a(204, 102, 102, 102));
        arraylist1.add(a(204, 204, 102, 102));
        arraylist1.add(a(204, 306, 102, 102));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        tphotocollagecomposeinfo = new TPhotoCollageComposeInfo();
        tphotocollagecomposeinfo.setRoundRadius(10F);
        tphotocollagecomposeinfo.setAspectRatio(1.333F);
        tphotocollagecomposeinfo.setResType(EResType.ASSET);
        tphotocollagecomposeinfo.icon = "fixComposeStyle43/nineframe_r3.jpg";
        tphotocollagecomposeinfo.name = "nineframe_r3";
        arraylist1 = new ArrayList();
        arraylist1.add(a(0, 0, 172, 102));
        arraylist1.add(a(0, 102, 172, 102));
        arraylist1.add(a(0, 204, 172, 102));
        arraylist1.add(a(0, 306, 172, 102));
        arraylist1.add(a(172, 0, 134, 81));
        arraylist1.add(a(172, 81, 134, 81));
        arraylist1.add(a(172, 162, 134, 82));
        arraylist1.add(a(172, 244, 134, 82));
        arraylist1.add(a(172, 326, 134, 82));
        tphotocollagecomposeinfo.setPhotoFrameArray(arraylist1);
        arraylist1 = new ArrayList();
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -1F));
        arraylist2.add(new PointF(-0.5F, -1F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 0.5F));
        arraylist2.add(new PointF(1.0F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(1.0F, -0.5F));
        arraylist2.add(new PointF(-0.5F, -0.5F));
        arraylist2.add(new PointF(-0.5F, 1.0F));
        arraylist2.add(new PointF(1.0F, 1.0F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -1F));
        arraylist2.add(new PointF(-1F, -1F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 0.5F));
        arraylist2.add(new PointF(0.5F, 0.5F));
        arraylist1.add(arraylist2);
        arraylist2 = new ArrayList();
        arraylist2.add(new PointF(0.5F, -0.5F));
        arraylist2.add(new PointF(-1F, -0.5F));
        arraylist2.add(new PointF(-1F, 1.0F));
        arraylist2.add(new PointF(0.5F, 1.0F));
        arraylist1.add(arraylist2);
        tphotocollagecomposeinfo.setVectorPointsArray(arraylist1);
        tphotocollagecomposeinfo.setDefaultEdge(5);
        arraylist.add(tphotocollagecomposeinfo);
        return arraylist;
    }
}
