// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.amazon.searchapp.retailsearch.client;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

// Referenced classes of package com.amazon.searchapp.retailsearch.client:
//            SearchConfigurationSet

public class StaticSearchConfiguration
{

    public StaticSearchConfiguration()
    {
    }

    public static SearchConfigurationSet build()
    {
        Map map = Collections.synchronizedMap(new LinkedHashMap(5));
        Map map1 = Collections.synchronizedMap(new LinkedHashMap(14));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://www.amazon.com").setSecureSiteUrl("https://www.amazon.com").setSearchServiceUrl("http://www.amazon.com").setSecureSearchServiceUrl("https://www.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://www.amazon.com.br").setSecureSiteUrl("https://www.amazon.com.br").setSearchServiceUrl("http://www.amazon.com.br").setSecureSearchServiceUrl("https://www.amazon.com.br").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://www.amazon.ca").setSecureSiteUrl("https://www.amazon.ca").setSearchServiceUrl("http://www.amazon.ca").setSecureSearchServiceUrl("https://www.amazon.ca").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://www.amazon.ca").setSecureSiteUrl("https://www.amazon.ca").setSearchServiceUrl("http://www.amazon.ca").setSecureSearchServiceUrl("https://www.amazon.ca").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://www.amazon.cn").setSecureSiteUrl("https://www.amazon.cn").setSearchServiceUrl("http://www.amazon.cn").setSecureSearchServiceUrl("https://www.amazon.cn").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://www.amazon.de").setSecureSiteUrl("https://www.amazon.de").setSearchServiceUrl("http://www.amazon.de").setSecureSearchServiceUrl("https://www.amazon.de").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://www.amazon.es").setSecureSiteUrl("https://www.amazon.es").setSearchServiceUrl("http://www.amazon.es").setSecureSearchServiceUrl("https://www.amazon.es").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://www.amazon.fr").setSecureSiteUrl("https://www.amazon.fr").setSearchServiceUrl("http://www.amazon.fr").setSecureSearchServiceUrl("https://www.amazon.fr").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://www.amazon.in").setSecureSiteUrl("https://www.amazon.in").setSearchServiceUrl("http://www.amazon.in").setSecureSearchServiceUrl("https://www.amazon.in").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://www.amazon.it").setSecureSiteUrl("https://www.amazon.it").setSearchServiceUrl("http://www.amazon.it").setSecureSearchServiceUrl("https://www.amazon.it").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://www.amazon.jp").setSecureSiteUrl("https://www.amazon.jp").setSearchServiceUrl("http://www.amazon.co.jp").setSecureSearchServiceUrl("https://www.amazon.co.jp").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://www.amazon.co.uk").setSecureSiteUrl("https://www.amazon.co.uk").setSearchServiceUrl("http://www.amazon.co.uk").setSecureSearchServiceUrl("https://www.amazon.co.uk").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://www.amazon.com.au").setSecureSiteUrl("https://www.amazon.com.au").setSearchServiceUrl("http://www.amazon.com.au").setSecureSearchServiceUrl("https://www.amazon.com.au").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://www.amazon.com.mx").setSecureSiteUrl("https://www.amazon.com.mx").setSearchServiceUrl("http://www.amazon.com.mx").setSecureSearchServiceUrl("https://www.amazon.com.mx").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map.put("amazon", (new SearchConfiguration.Builder()).setId("amazon").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(14));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://sitenav-qa-gamma.amazon.com:9100").setSecureSiteUrl("http://sitenav-qa-gamma.amazon.com:9100").setSearchServiceUrl("http://sitenav-qa-gamma.amazon.com:9100").setSecureSearchServiceUrl("https://sitenav-qa-gamma.amazon.com:9100").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://sitenav-qa-gamma-br.amazon.com:17100").setSecureSiteUrl("http://sitenav-qa-gamma-br.amazon.com:17100").setSearchServiceUrl("http://sitenav-qa-gamma-br.amazon.com:17100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-br.amazon.com:17100").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8100").setSecureSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8100").setSearchServiceUrl("http://sitenav-qa-gamma-ca.amazon.com:8100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-ca.amazon.com:8100").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8100").setSecureSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8100").setSearchServiceUrl("http://sitenav-qa-gamma-ca.amazon.com:8100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-ca.amazon.com:8100").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://sitenav-qa-gamma-cn.amazon.com:6100").setSecureSiteUrl("http://sitenav-qa-gamma-cn.amazon.com:6100").setSearchServiceUrl("http://sitenav-qa-gamma-cn.amazon.com:6100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-cn.amazon.com:6100").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://sitenav-qa-gamma-de.amazon.com:12100").setSecureSiteUrl("http://sitenav-qa-gamma-de.amazon.com:12100").setSearchServiceUrl("http://sitenav-qa-gamma-de.amazon.com:12100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-de.amazon.com:12100").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://sitenav-qa-gamma-es.amazon.com:17100").setSecureSiteUrl("http://sitenav-qa-gamma-es.amazon.com:17100").setSearchServiceUrl("http://sitenav-qa-gamma-es.amazon.com:17100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-es.amazon.com:17100").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://sitenav-qa-gamma-fr.amazon.com:11100").setSecureSiteUrl("http://sitenav-qa-gamma-fr.amazon.com:11100").setSearchServiceUrl("http://sitenav-qa-gamma-fr.amazon.com:11100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-fr.amazon.com:11100").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://sitenav-qa-gamma-in.amazon.com:17100").setSecureSiteUrl("http://sitenav-qa-gamma-in.amazon.com:17100").setSearchServiceUrl("http://sitenav-qa-gamma-in.amazon.com:17100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-in.amazon.com:17100").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://sitenav-qa-gamma-it.amazon.com:17100").setSecureSiteUrl("http://sitenav-qa-gamma-it.amazon.com:17100").setSearchServiceUrl("http://sitenav-qa-gamma-it.amazon.com:17100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-it.amazon.com:17100").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://sitenav-qa-gamma-jp.amazon.com:7100").setSecureSiteUrl("http://sitenav-qa-gamma-jp.amazon.com:7100").setSearchServiceUrl("http://sitenav-qa-gamma-jp.amazon.com:7100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-jp.amazon.com:7100").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://sitenav-qa-gamma-uk.amazon.com:10100").setSecureSiteUrl("http://sitenav-qa-gamma-uk.amazon.com:10100").setSearchServiceUrl("http://sitenav-qa-gamma-uk.amazon.com:10100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-uk.amazon.com:10100").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://sitenav-qa-gamma-au.amazon.com:18100").setSecureSiteUrl("http://sitenav-qa-gamma-au.amazon.com:18100").setSearchServiceUrl("http://sitenav-qa-gamma-au.amazon.com:18100").setSecureSearchServiceUrl("http://sitenav-qa-gamma-au.amazon.com:18100").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://sitenav-qa-gamma-mx.amazon.com:19100").setSecureSiteUrl("http://sitenav-qa-gamma-mx.amazon.com:19100").setSearchServiceUrl("http://sitenav-qa-gamma-mx.amazon.com:19100").setSecureSearchServiceUrl("https://sitenav-qa-gamma-mx.amazon.com:19100").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map.put("test1", (new SearchConfiguration.Builder()).setId("test1").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(14));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://sitenav-qa-gamma.amazon.com:9200").setSecureSiteUrl("http://sitenav-qa-gamma.amazon.com:9200").setSearchServiceUrl("http://sitenav-qa-gamma.amazon.com:9200").setSecureSearchServiceUrl("https://sitenav-qa-gamma.amazon.com:9200").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://sitenav-qa-gamma-br.amazon.com:17200").setSecureSiteUrl("http://sitenav-qa-gamma-br.amazon.com:17200").setSearchServiceUrl("http://sitenav-qa-gamma-br.amazon.com:17200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-br.amazon.com:17200").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8200").setSecureSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8200").setSearchServiceUrl("http://sitenav-qa-gamma-ca.amazon.com:8200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-ca.amazon.com:8200").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8200").setSecureSiteUrl("http://sitenav-qa-gamma-ca.amazon.com:8200").setSearchServiceUrl("http://sitenav-qa-gamma-ca.amazon.com:8200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-ca.amazon.com:8200").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://sitenav-qa-gamma-cn.amazon.com:6200").setSecureSiteUrl("http://sitenav-qa-gamma-cn.amazon.com:6200").setSearchServiceUrl("http://sitenav-qa-gamma-cn.amazon.com:6200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-cn.amazon.com:6200").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://sitenav-qa-gamma-de.amazon.com:12200").setSecureSiteUrl("http://sitenav-qa-gamma-de.amazon.com:12200").setSearchServiceUrl("http://sitenav-qa-gamma-de.amazon.com:12200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-de.amazon.com:12200").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://sitenav-qa-gamma-es.amazon.com:17200").setSecureSiteUrl("http://sitenav-qa-gamma-es.amazon.com:17200").setSearchServiceUrl("http://sitenav-qa-gamma-es.amazon.com:17200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-es.amazon.com:17200").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://sitenav-qa-gamma-fr.amazon.com:11200").setSecureSiteUrl("http://sitenav-qa-gamma-fr.amazon.com:11200").setSearchServiceUrl("http://sitenav-qa-gamma-fr.amazon.com:11200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-fr.amazon.com:11200").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://sitenav-qa-gamma-in.amazon.com:17200").setSecureSiteUrl("http://sitenav-qa-gamma-in.amazon.com:17200").setSearchServiceUrl("http://sitenav-qa-gamma-in.amazon.com:17200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-in.amazon.com:17200").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://sitenav-qa-gamma-it.amazon.com:17200").setSecureSiteUrl("http://sitenav-qa-gamma-it.amazon.com:17200").setSearchServiceUrl("http://sitenav-qa-gamma-it.amazon.com:17200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-it.amazon.com:17200").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://sitenav-qa-gamma-jp.amazon.com:7200").setSecureSiteUrl("http://sitenav-qa-gamma-jp.amazon.com:7200").setSearchServiceUrl("http://sitenav-qa-gamma-jp.amazon.com:7200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-jp.amazon.com:7200").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://sitenav-qa-gamma-uk.amazon.com:10200").setSecureSiteUrl("http://sitenav-qa-gamma-uk.amazon.com:10200").setSearchServiceUrl("http://sitenav-qa-gamma-uk.amazon.com:10200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-uk.amazon.com:10200").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://sitenav-qa-gamma-au.amazon.com:18200").setSecureSiteUrl("http://sitenav-qa-gamma-au.amazon.com:18200").setSearchServiceUrl("http://sitenav-qa-gamma-au.amazon.com:18200").setSecureSearchServiceUrl("http://sitenav-qa-gamma-au.amazon.com:18200").setCompletionServiceUrl("http://completion.amazon.co.jpg").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://sitenav-qa-gamma-mx.amazon.com:19200").setSecureSiteUrl("http://sitenav-qa-gamma-mx.amazon.com:19200").setSearchServiceUrl("http://sitenav-qa-gamma-mx.amazon.com:19200").setSecureSearchServiceUrl("https://sitenav-qa-gamma-mx.amazon.com:19200").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map.put("test2", (new SearchConfiguration.Builder()).setId("test2").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(15));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://sx-mobile-us.integ.amazon.com").setSecureSiteUrl("https://sx-mobile-us.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-us.integ.amazon.com").setSecureSearchServiceUrl("https://sx-mobile-us.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://sx-mobile-br.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-br.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-br.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-br.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sx-mobile-ca.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-ca.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-ca.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-ca.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sx-mobile-ca.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-ca.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-ca.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-ca.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://sx-mobile-cn.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-cn.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-cn.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-cn.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://sx-mobile-de.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-de.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-de.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-de.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://sx-mobile-es.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-es.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-es.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-es.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://sx-mobile-fr.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-fr.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-fr.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-fr.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://sx-mobile-in.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-in.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-in.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-in.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://sx-mobile-it.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-it.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-it.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-it.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://sx-mobile-jp.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-jp.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-jp.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-jp.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://sx-mobile-uk.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-uk.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-uk.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-uk.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://sx-mobile-au.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-au.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-au.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-au.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://sx-mobile-mx.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-mx.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-mx.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-mx.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("ru", (new SearchRealm.Builder()).setId("ru").setLocale("ru_RU").setMarketplaceId(0x1b23a).setObfuscatedMarketplaceId("AD2EMQ3L3PG8S").setSiteUrl("http://sx-mobile-ru.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-ru.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-ru.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-ru.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map.put("test3", (new SearchConfiguration.Builder()).setId("test3").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(15));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://sx-mobile-us-gamma.integ.amazon.com").setSecureSiteUrl("https://sx-mobile-us-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-us-gamma.integ.amazon.com").setSecureSearchServiceUrl("https://sx-mobile-us-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://sx-mobile-br-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-br-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-br-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-br-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-ca-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://sx-mobile-cn-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-cn-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-cn-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-cn-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://sx-mobile-de-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-de-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-de-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-de-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://sx-mobile-es-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-es-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-es-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-es-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://sx-mobile-fr-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-fr-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-fr-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-fr-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://sx-mobile-in-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-in-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-in-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-in-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://sx-mobile-it-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-it-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-it-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-it-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://sx-mobile-jp-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-jp-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-jp-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-jp-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://sx-mobile-uk-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-uk-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-uk-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-uk-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://sx-mobile-au-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-au-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-au-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-au-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://sx-mobile-mx-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-mx-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-mx-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-mx-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("ru", (new SearchRealm.Builder()).setId("ru").setLocale("ru_RU").setMarketplaceId(0x1b23a).setObfuscatedMarketplaceId("AD2EMQ3L3PG8S").setSiteUrl("http://sx-mobile-ru-gamma.integ.amazon.com").setSecureSiteUrl("http://sx-mobile-ru-gamma.integ.amazon.com").setSearchServiceUrl("http://sx-mobile-ru-gamma.integ.amazon.com").setSecureSearchServiceUrl("http://sx-mobile-ru-gamma.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map.put("test4", (new SearchConfiguration.Builder()).setId("test4").setRealms(map1).build());
        return (new SearchConfigurationSet.Builder()).setConfigurations(map).build();
    }
}
