// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.ebay.nautilus.domain.net.api.shopcase.models;


// Referenced classes of package com.ebay.nautilus.domain.net.api.shopcase.models:
//            ShopCart

public static final class  extends Enum
{

    private static final UNFORESEEN_DOMAIN_ERROR $VALUES[];
    public static final UNFORESEEN_DOMAIN_ERROR AUCTION_ENDED_AS_BIN;
    public static final UNFORESEEN_DOMAIN_ERROR BLOCKED_ITEM_CATEGORY;
    public static final UNFORESEEN_DOMAIN_ERROR BML_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_AUTHENTIFY_VERIFICATION;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_CC_VERIFICATION;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_DOES_NOT_SHIP_TO_LOCATION;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_ITEM_COUNT_LIMIT_EXCEEDED;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_LOW_FEEDBACK_SCORE;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_LOW_UNPAID_ITEM_STRIKE;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_NO_LINKED_PAYPAL_ACCOUNT;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_SELLER_EXCLUDED_SHIP_TO_LOCATION;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_SMS_VERIFICATION;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_VERIFICATION_NO_REMEDY;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_VERIFIED_USER;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_BLOCKED_ZERO_FEEDBACK_SCORE;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_INFO_INVALID;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_IS_SELLER;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_MARKED_PAID;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_MESSAGE;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_NOT_CART_BUYER;
    public static final UNFORESEEN_DOMAIN_ERROR BUYER_WARNING_DOES_NOT_SHIP_TO_POBOX;
    public static final UNFORESEEN_DOMAIN_ERROR BUYING_SERVICE_CANCELLABLE;
    public static final UNFORESEEN_DOMAIN_ERROR BUYING_SERVICE_LOCKABLE;
    public static final UNFORESEEN_DOMAIN_ERROR BUYING_SERVICE_PURCHASE_FAILED;
    public static final UNFORESEEN_DOMAIN_ERROR BUYING_SERVICE_RETRYABLE;
    public static final UNFORESEEN_DOMAIN_ERROR CART_API_VERSION_FAILED_TO_UPDATE;
    public static final UNFORESEEN_DOMAIN_ERROR CART_IS_NOT_ENABLED_ON_THIS_SITE;
    public static final UNFORESEEN_DOMAIN_ERROR CART_SERVICE_INTERNAL_EXCEPTION;
    public static final UNFORESEEN_DOMAIN_ERROR CASH_BACK_ITEMS_NOT_CARTABLE;
    public static final UNFORESEEN_DOMAIN_ERROR CHECKOUT_COMPLETED;
    public static final UNFORESEEN_DOMAIN_ERROR CHECKOUT_EXPIRED;
    public static final UNFORESEEN_DOMAIN_ERROR DATASOURCE_DOWN_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR DOMAIN_INTERNAL_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR DOUBLE_BINNING;
    public static final UNFORESEEN_DOMAIN_ERROR EMPTY_ORDER;
    public static final UNFORESEEN_DOMAIN_ERROR IDENTICAL;
    public static final UNFORESEEN_DOMAIN_ERROR INCENTIVE_NOT_APPLIED;
    public static final UNFORESEEN_DOMAIN_ERROR INCENTIVE_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_BASE_IDENTIFIER;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_BUYER_STATE;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_CART_ITEM_REFERENCE_ID;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_CART_SERVICE_REQUEST;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_COUNTRY;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_DOMAIN;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_EXTENDED_IDENTIFIER;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_IDENTIFIER;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_INPUT;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_ITEMID;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_ITEM_PRICE;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_ITEM_REFERENCE_ID;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_ITEM_SELLER;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_ITEM_VERSION;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_ORDER_STATE;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_PAYMENT_METHOD;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_PICKUP_LOCATION;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_QUANTITY;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_SALE_TYPE;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_SFL_ITEM_REFERENCE_ID;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_SHIPPING;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_SHIPPING_ADDRESS;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_SHIPPING_TYPE;
    public static final UNFORESEEN_DOMAIN_ERROR INVALID_VARIATION_ID;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_ALREADY_EXIST;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_ALREADY_EXISTS_IN_CART;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_CANNOT_BE_ADDED_AS_COMMITTED;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_CANNOT_BE_ADDED_AS_UNCOMMITTED;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_COMPONENTS_MISSING;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_LISTING_SITE_UNSUPPORED;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_NOT_AVAILABLE;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_NOT_AVAILABLE_FOR_PURCHASE;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_NOT_FOUND;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_REVISED;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_TYPE_NOT_SUPPORTED;
    public static final UNFORESEEN_DOMAIN_ERROR ITEM_VALIDATION_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR LOCAL_INVENTORY_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR LOGISTICS_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR LOGISTIC_UPDATE_FAILED;
    public static final UNFORESEEN_DOMAIN_ERROR NOT_BIN_ITEM;
    public static final UNFORESEEN_DOMAIN_ERROR NOT_RELISTED;
    public static final UNFORESEEN_DOMAIN_ERROR NOT_SELLER_CREATED_ORDER;
    public static final UNFORESEEN_DOMAIN_ERROR OFFER_AMOUNT_LIMIT_EXCEEDED;
    public static final UNFORESEEN_DOMAIN_ERROR ORDER_BUYER_MISMATCH;
    public static final UNFORESEEN_DOMAIN_ERROR ORDER_NOT_FOUND;
    public static final UNFORESEEN_DOMAIN_ERROR PAYMENT_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR POSTPAY_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR POSTPAY_WARNING;
    public static final UNFORESEEN_DOMAIN_ERROR PROMOTION_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR REAL_ESTATE_ITEMS_NOT_CARTABLE;
    public static final UNFORESEEN_DOMAIN_ERROR RELISTED;
    public static final UNFORESEEN_DOMAIN_ERROR RELISTED_ADDED;
    public static final UNFORESEEN_DOMAIN_ERROR RELISTED_AVAILABLE;
    public static final UNFORESEEN_DOMAIN_ERROR REQUEST_DATA_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR REWARDS_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR SALE_ENDED;
    public static final UNFORESEEN_DOMAIN_ERROR SCO_CANNOT_BE_REMOVED;
    public static final UNFORESEEN_DOMAIN_ERROR SELECTED_SHIPPING_UPDATED;
    public static final UNFORESEEN_DOMAIN_ERROR SELLER_CREATED_ORDER_NOT_UPDATABLE;
    public static final UNFORESEEN_DOMAIN_ERROR SELLER_NOT_PERMITTED_TO_BUY_HISITEM;
    public static final UNFORESEEN_DOMAIN_ERROR SELLER_STATE_INVALID;
    public static final UNFORESEEN_DOMAIN_ERROR SHIPPING_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR SHIPPING_SERVICE_NOT_SUPPORTED;
    public static final UNFORESEEN_DOMAIN_ERROR STATUS_FLAG_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR STORE_OWNER_ON_VACATION;
    public static final UNFORESEEN_DOMAIN_ERROR TAX_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR TRACKING_SERVICE_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR TRANSACTION_ARCHIVED_REMOVED_FROM_CART;
    public static final UNFORESEEN_DOMAIN_ERROR TRANSACTION_BUYER_MISMATCH;
    public static final UNFORESEEN_DOMAIN_ERROR TRANSACTION_CANCELLED;
    public static final UNFORESEEN_DOMAIN_ERROR TRANSACTION_CANNOT_BE_REMOVED;
    public static final UNFORESEEN_DOMAIN_ERROR TRANSACTION_IS_PART_OF_ORDER;
    public static final UNFORESEEN_DOMAIN_ERROR TRANSACTION_NOT_FOUND;
    public static final UNFORESEEN_DOMAIN_ERROR UNFORESEEN_DOMAIN_ERROR;
    public static final UNFORESEEN_DOMAIN_ERROR UNFORSEEN_EXCEPTION;
    public static final UNFORESEEN_DOMAIN_ERROR UNPROCESSED;
    public static final UNFORESEEN_DOMAIN_ERROR UNSUPPORTED_CATEGORY;
    public static final UNFORESEEN_DOMAIN_ERROR UNSUPPORTED_SALE_TYPE;
    public static final UNFORESEEN_DOMAIN_ERROR UPI_CASE_CLOSED;
    public static final UNFORESEEN_DOMAIN_ERROR USER_NOT_PREAPPROVED;
    public static final UNFORESEEN_DOMAIN_ERROR USER_NOT_VALID;
    public static final UNFORESEEN_DOMAIN_ERROR USER_SUSPENDED;
    public static final UNFORESEEN_DOMAIN_ERROR VARIATION_NOT_FOUND;

    public static  valueOf(String s)
    {
        return ()Enum.valueOf(com/ebay/nautilus/domain/net/api/shopcase/models/ShopCart$NotificationCode, s);
    }

    public static [] values()
    {
        return ([])$VALUES.clone();
    }

    static 
    {
        TRANSACTION_NOT_FOUND = new <init>("TRANSACTION_NOT_FOUND", 0);
        UPI_CASE_CLOSED = new <init>("UPI_CASE_CLOSED", 1);
        CHECKOUT_EXPIRED = new <init>("CHECKOUT_EXPIRED", 2);
        CHECKOUT_COMPLETED = new <init>("CHECKOUT_COMPLETED", 3);
        TRANSACTION_BUYER_MISMATCH = new <init>("TRANSACTION_BUYER_MISMATCH", 4);
        TRANSACTION_CANCELLED = new <init>("TRANSACTION_CANCELLED", 5);
        TRANSACTION_IS_PART_OF_ORDER = new <init>("TRANSACTION_IS_PART_OF_ORDER", 6);
        BUYER_MARKED_PAID = new <init>("BUYER_MARKED_PAID", 7);
        TRANSACTION_ARCHIVED_REMOVED_FROM_CART = new <init>("TRANSACTION_ARCHIVED_REMOVED_FROM_CART", 8);
        RELISTED = new <init>("RELISTED", 9);
        NOT_RELISTED = new <init>("NOT_RELISTED", 10);
        IDENTICAL = new <init>("IDENTICAL", 11);
        RELISTED_AVAILABLE = new <init>("RELISTED_AVAILABLE", 12);
        RELISTED_ADDED = new <init>("RELISTED_ADDED", 13);
        VARIATION_NOT_FOUND = new <init>("VARIATION_NOT_FOUND", 14);
        INVALID_QUANTITY = new <init>("INVALID_QUANTITY", 15);
        UNSUPPORTED_CATEGORY = new <init>("UNSUPPORTED_CATEGORY", 16);
        NOT_BIN_ITEM = new <init>("NOT_BIN_ITEM", 17);
        SALE_ENDED = new <init>("SALE_ENDED", 18);
        SHIPPING_SERVICE_NOT_SUPPORTED = new <init>("SHIPPING_SERVICE_NOT_SUPPORTED", 19);
        ITEM_ERROR = new <init>("ITEM_ERROR", 20);
        ITEM_REVISED = new <init>("ITEM_REVISED", 21);
        BUYER_MESSAGE = new <init>("BUYER_MESSAGE", 22);
        ITEM_NOT_AVAILABLE = new <init>("ITEM_NOT_AVAILABLE", 23);
        OFFER_AMOUNT_LIMIT_EXCEEDED = new <init>("OFFER_AMOUNT_LIMIT_EXCEEDED", 24);
        INVALID_ITEM_PRICE = new <init>("INVALID_ITEM_PRICE", 25);
        INVALID_SHIPPING = new <init>("INVALID_SHIPPING", 26);
        INVALID_COUNTRY = new <init>("INVALID_COUNTRY", 27);
        SELLER_NOT_PERMITTED_TO_BUY_HISITEM = new <init>("SELLER_NOT_PERMITTED_TO_BUY_HISITEM", 28);
        DOUBLE_BINNING = new <init>("DOUBLE_BINNING", 29);
        UNSUPPORTED_SALE_TYPE = new <init>("UNSUPPORTED_SALE_TYPE", 30);
        AUCTION_ENDED_AS_BIN = new <init>("AUCTION_ENDED_AS_BIN", 31);
        ITEM_TYPE_NOT_SUPPORTED = new <init>("ITEM_TYPE_NOT_SUPPORTED", 32);
        USER_NOT_VALID = new <init>("USER_NOT_VALID", 33);
        UNPROCESSED = new <init>("UNPROCESSED", 34);
        REQUEST_DATA_ERROR = new <init>("REQUEST_DATA_ERROR", 35);
        DATASOURCE_DOWN_ERROR = new <init>("DATASOURCE_DOWN_ERROR", 36);
        INVALID_VARIATION_ID = new <init>("INVALID_VARIATION_ID", 37);
        SELECTED_SHIPPING_UPDATED = new <init>("SELECTED_SHIPPING_UPDATED", 38);
        BUYER_BLOCKED_ZERO_FEEDBACK_SCORE = new <init>("BUYER_BLOCKED_ZERO_FEEDBACK_SCORE", 39);
        BUYER_BLOCKED_LOW_FEEDBACK_SCORE = new <init>("BUYER_BLOCKED_LOW_FEEDBACK_SCORE", 40);
        BUYER_BLOCKED_LOW_UNPAID_ITEM_STRIKE = new <init>("BUYER_BLOCKED_LOW_UNPAID_ITEM_STRIKE", 41);
        BUYER_BLOCKED_DOES_NOT_SHIP_TO_LOCATION = new <init>("BUYER_BLOCKED_DOES_NOT_SHIP_TO_LOCATION", 42);
        BUYER_BLOCKED_NO_LINKED_PAYPAL_ACCOUNT = new <init>("BUYER_BLOCKED_NO_LINKED_PAYPAL_ACCOUNT", 43);
        BUYER_BLOCKED_CC_VERIFICATION = new <init>("BUYER_BLOCKED_CC_VERIFICATION", 44);
        BUYER_BLOCKED_SMS_VERIFICATION = new <init>("BUYER_BLOCKED_SMS_VERIFICATION", 45);
        BUYER_BLOCKED_AUTHENTIFY_VERIFICATION = new <init>("BUYER_BLOCKED_AUTHENTIFY_VERIFICATION", 46);
        BUYER_BLOCKED_VERIFICATION_NO_REMEDY = new <init>("BUYER_BLOCKED_VERIFICATION_NO_REMEDY", 47);
        BUYER_BLOCKED_VERIFIED_USER = new <init>("BUYER_BLOCKED_VERIFIED_USER", 48);
        BUYER_BLOCKED_ITEM_COUNT_LIMIT_EXCEEDED = new <init>("BUYER_BLOCKED_ITEM_COUNT_LIMIT_EXCEEDED", 49);
        BUYER_BLOCKED = new <init>("BUYER_BLOCKED", 50);
        BUYER_WARNING_DOES_NOT_SHIP_TO_POBOX = new <init>("BUYER_WARNING_DOES_NOT_SHIP_TO_POBOX", 51);
        USER_SUSPENDED = new <init>("USER_SUSPENDED", 52);
        USER_NOT_PREAPPROVED = new <init>("USER_NOT_PREAPPROVED", 53);
        TRANSACTION_CANNOT_BE_REMOVED = new <init>("TRANSACTION_CANNOT_BE_REMOVED", 54);
        SCO_CANNOT_BE_REMOVED = new <init>("SCO_CANNOT_BE_REMOVED", 55);
        ITEM_NOT_FOUND = new <init>("ITEM_NOT_FOUND", 56);
        ITEM_ALREADY_EXISTS_IN_CART = new <init>("ITEM_ALREADY_EXISTS_IN_CART", 57);
        INVALID_SHIPPING_ADDRESS = new <init>("INVALID_SHIPPING_ADDRESS", 58);
        INVALID_ORDER_STATE = new <init>("INVALID_ORDER_STATE", 59);
        NOT_SELLER_CREATED_ORDER = new <init>("NOT_SELLER_CREATED_ORDER", 60);
        EMPTY_ORDER = new <init>("EMPTY_ORDER", 61);
        ORDER_NOT_FOUND = new <init>("ORDER_NOT_FOUND", 62);
        ORDER_BUYER_MISMATCH = new <init>("ORDER_BUYER_MISMATCH", 63);
        INVALID_ITEM_REFERENCE_ID = new <init>("INVALID_ITEM_REFERENCE_ID", 64);
        INVALID_INPUT = new <init>("INVALID_INPUT", 65);
        LOGISTIC_UPDATE_FAILED = new <init>("LOGISTIC_UPDATE_FAILED", 66);
        LOCAL_INVENTORY_SERVICE_ERROR = new <init>("LOCAL_INVENTORY_SERVICE_ERROR", 67);
        INVALID_PICKUP_LOCATION = new <init>("INVALID_PICKUP_LOCATION", 68);
        CART_SERVICE_INTERNAL_EXCEPTION = new <init>("CART_SERVICE_INTERNAL_EXCEPTION", 69);
        CART_API_VERSION_FAILED_TO_UPDATE = new <init>("CART_API_VERSION_FAILED_TO_UPDATE", 70);
        INVALID_SFL_ITEM_REFERENCE_ID = new <init>("INVALID_SFL_ITEM_REFERENCE_ID", 71);
        INVALID_CART_ITEM_REFERENCE_ID = new <init>("INVALID_CART_ITEM_REFERENCE_ID", 72);
        SELLER_STATE_INVALID = new <init>("SELLER_STATE_INVALID", 73);
        BUYER_BLOCKED_SELLER_EXCLUDED_SHIP_TO_LOCATION = new <init>("BUYER_BLOCKED_SELLER_EXCLUDED_SHIP_TO_LOCATION", 74);
        STORE_OWNER_ON_VACATION = new <init>("STORE_OWNER_ON_VACATION", 75);
        INVALID_BUYER_STATE = new <init>("INVALID_BUYER_STATE", 76);
        INVALID_CART_SERVICE_REQUEST = new <init>("INVALID_CART_SERVICE_REQUEST", 77);
        INVALID_DOMAIN = new <init>("INVALID_DOMAIN", 78);
        INVALID_IDENTIFIER = new <init>("INVALID_IDENTIFIER", 79);
        INVALID_BASE_IDENTIFIER = new <init>("INVALID_BASE_IDENTIFIER", 80);
        INVALID_EXTENDED_IDENTIFIER = new <init>("INVALID_EXTENDED_IDENTIFIER", 81);
        ITEM_NOT_AVAILABLE_FOR_PURCHASE = new <init>("ITEM_NOT_AVAILABLE_FOR_PURCHASE", 82);
        ITEM_CANNOT_BE_ADDED_AS_COMMITTED = new <init>("ITEM_CANNOT_BE_ADDED_AS_COMMITTED", 83);
        ITEM_CANNOT_BE_ADDED_AS_UNCOMMITTED = new <init>("ITEM_CANNOT_BE_ADDED_AS_UNCOMMITTED", 84);
        INVALID_ITEM_SELLER = new <init>("INVALID_ITEM_SELLER", 85);
        BUYER_NOT_CART_BUYER = new <init>("BUYER_NOT_CART_BUYER", 86);
        BUYER_IS_SELLER = new <init>("BUYER_IS_SELLER", 87);
        BUYER_INFO_INVALID = new <init>("BUYER_INFO_INVALID", 88);
        INCENTIVE_NOT_APPLIED = new <init>("INCENTIVE_NOT_APPLIED", 89);
        ITEM_ALREADY_EXIST = new <init>("ITEM_ALREADY_EXIST", 90);
        INVALID_ITEM_VERSION = new <init>("INVALID_ITEM_VERSION", 91);
        ITEM_COMPONENTS_MISSING = new <init>("ITEM_COMPONENTS_MISSING", 92);
        ITEM_VALIDATION_ERROR = new <init>("ITEM_VALIDATION_ERROR", 93);
        DOMAIN_INTERNAL_ERROR = new <init>("DOMAIN_INTERNAL_ERROR", 94);
        TAX_SERVICE_ERROR = new <init>("TAX_SERVICE_ERROR", 95);
        PAYMENT_SERVICE_ERROR = new <init>("PAYMENT_SERVICE_ERROR", 96);
        INCENTIVE_SERVICE_ERROR = new <init>("INCENTIVE_SERVICE_ERROR", 97);
        STATUS_FLAG_ERROR = new <init>("STATUS_FLAG_ERROR", 98);
        BUYING_SERVICE_PURCHASE_FAILED = new <init>("BUYING_SERVICE_PURCHASE_FAILED", 99);
        BUYING_SERVICE_RETRYABLE = new <init>("BUYING_SERVICE_RETRYABLE", 100);
        BUYING_SERVICE_LOCKABLE = new <init>("BUYING_SERVICE_LOCKABLE", 101);
        BUYING_SERVICE_CANCELLABLE = new <init>("BUYING_SERVICE_CANCELLABLE", 102);
        POSTPAY_ERROR = new <init>("POSTPAY_ERROR", 103);
        POSTPAY_WARNING = new <init>("POSTPAY_WARNING", 104);
        SHIPPING_SERVICE_ERROR = new <init>("SHIPPING_SERVICE_ERROR", 105);
        UNFORSEEN_EXCEPTION = new <init>("UNFORSEEN_EXCEPTION", 106);
        PROMOTION_SERVICE_ERROR = new <init>("PROMOTION_SERVICE_ERROR", 107);
        REWARDS_SERVICE_ERROR = new <init>("REWARDS_SERVICE_ERROR", 108);
        BML_SERVICE_ERROR = new <init>("BML_SERVICE_ERROR", 109);
        TRACKING_SERVICE_ERROR = new <init>("TRACKING_SERVICE_ERROR", 110);
        LOGISTICS_SERVICE_ERROR = new <init>("LOGISTICS_SERVICE_ERROR", 111);
        INVALID_ITEMID = new <init>("INVALID_ITEMID", 112);
        CASH_BACK_ITEMS_NOT_CARTABLE = new <init>("CASH_BACK_ITEMS_NOT_CARTABLE", 113);
        REAL_ESTATE_ITEMS_NOT_CARTABLE = new <init>("REAL_ESTATE_ITEMS_NOT_CARTABLE", 114);
        CART_IS_NOT_ENABLED_ON_THIS_SITE = new <init>("CART_IS_NOT_ENABLED_ON_THIS_SITE", 115);
        ITEM_LISTING_SITE_UNSUPPORED = new <init>("ITEM_LISTING_SITE_UNSUPPORED", 116);
        BLOCKED_ITEM_CATEGORY = new <init>("BLOCKED_ITEM_CATEGORY", 117);
        INVALID_SHIPPING_TYPE = new <init>("INVALID_SHIPPING_TYPE", 118);
        INVALID_PAYMENT_METHOD = new <init>("INVALID_PAYMENT_METHOD", 119);
        INVALID_SALE_TYPE = new <init>("INVALID_SALE_TYPE", 120);
        SELLER_CREATED_ORDER_NOT_UPDATABLE = new <init>("SELLER_CREATED_ORDER_NOT_UPDATABLE", 121);
        UNFORESEEN_DOMAIN_ERROR = new <init>("UNFORESEEN_DOMAIN_ERROR", 122);
        $VALUES = (new .VALUES[] {
            TRANSACTION_NOT_FOUND, UPI_CASE_CLOSED, CHECKOUT_EXPIRED, CHECKOUT_COMPLETED, TRANSACTION_BUYER_MISMATCH, TRANSACTION_CANCELLED, TRANSACTION_IS_PART_OF_ORDER, BUYER_MARKED_PAID, TRANSACTION_ARCHIVED_REMOVED_FROM_CART, RELISTED, 
            NOT_RELISTED, IDENTICAL, RELISTED_AVAILABLE, RELISTED_ADDED, VARIATION_NOT_FOUND, INVALID_QUANTITY, UNSUPPORTED_CATEGORY, NOT_BIN_ITEM, SALE_ENDED, SHIPPING_SERVICE_NOT_SUPPORTED, 
            ITEM_ERROR, ITEM_REVISED, BUYER_MESSAGE, ITEM_NOT_AVAILABLE, OFFER_AMOUNT_LIMIT_EXCEEDED, INVALID_ITEM_PRICE, INVALID_SHIPPING, INVALID_COUNTRY, SELLER_NOT_PERMITTED_TO_BUY_HISITEM, DOUBLE_BINNING, 
            UNSUPPORTED_SALE_TYPE, AUCTION_ENDED_AS_BIN, ITEM_TYPE_NOT_SUPPORTED, USER_NOT_VALID, UNPROCESSED, REQUEST_DATA_ERROR, DATASOURCE_DOWN_ERROR, INVALID_VARIATION_ID, SELECTED_SHIPPING_UPDATED, BUYER_BLOCKED_ZERO_FEEDBACK_SCORE, 
            BUYER_BLOCKED_LOW_FEEDBACK_SCORE, BUYER_BLOCKED_LOW_UNPAID_ITEM_STRIKE, BUYER_BLOCKED_DOES_NOT_SHIP_TO_LOCATION, BUYER_BLOCKED_NO_LINKED_PAYPAL_ACCOUNT, BUYER_BLOCKED_CC_VERIFICATION, BUYER_BLOCKED_SMS_VERIFICATION, BUYER_BLOCKED_AUTHENTIFY_VERIFICATION, BUYER_BLOCKED_VERIFICATION_NO_REMEDY, BUYER_BLOCKED_VERIFIED_USER, BUYER_BLOCKED_ITEM_COUNT_LIMIT_EXCEEDED, 
            BUYER_BLOCKED, BUYER_WARNING_DOES_NOT_SHIP_TO_POBOX, USER_SUSPENDED, USER_NOT_PREAPPROVED, TRANSACTION_CANNOT_BE_REMOVED, SCO_CANNOT_BE_REMOVED, ITEM_NOT_FOUND, ITEM_ALREADY_EXISTS_IN_CART, INVALID_SHIPPING_ADDRESS, INVALID_ORDER_STATE, 
            NOT_SELLER_CREATED_ORDER, EMPTY_ORDER, ORDER_NOT_FOUND, ORDER_BUYER_MISMATCH, INVALID_ITEM_REFERENCE_ID, INVALID_INPUT, LOGISTIC_UPDATE_FAILED, LOCAL_INVENTORY_SERVICE_ERROR, INVALID_PICKUP_LOCATION, CART_SERVICE_INTERNAL_EXCEPTION, 
            CART_API_VERSION_FAILED_TO_UPDATE, INVALID_SFL_ITEM_REFERENCE_ID, INVALID_CART_ITEM_REFERENCE_ID, SELLER_STATE_INVALID, BUYER_BLOCKED_SELLER_EXCLUDED_SHIP_TO_LOCATION, STORE_OWNER_ON_VACATION, INVALID_BUYER_STATE, INVALID_CART_SERVICE_REQUEST, INVALID_DOMAIN, INVALID_IDENTIFIER, 
            INVALID_BASE_IDENTIFIER, INVALID_EXTENDED_IDENTIFIER, ITEM_NOT_AVAILABLE_FOR_PURCHASE, ITEM_CANNOT_BE_ADDED_AS_COMMITTED, ITEM_CANNOT_BE_ADDED_AS_UNCOMMITTED, INVALID_ITEM_SELLER, BUYER_NOT_CART_BUYER, BUYER_IS_SELLER, BUYER_INFO_INVALID, INCENTIVE_NOT_APPLIED, 
            ITEM_ALREADY_EXIST, INVALID_ITEM_VERSION, ITEM_COMPONENTS_MISSING, ITEM_VALIDATION_ERROR, DOMAIN_INTERNAL_ERROR, TAX_SERVICE_ERROR, PAYMENT_SERVICE_ERROR, INCENTIVE_SERVICE_ERROR, STATUS_FLAG_ERROR, BUYING_SERVICE_PURCHASE_FAILED, 
            BUYING_SERVICE_RETRYABLE, BUYING_SERVICE_LOCKABLE, BUYING_SERVICE_CANCELLABLE, POSTPAY_ERROR, POSTPAY_WARNING, SHIPPING_SERVICE_ERROR, UNFORSEEN_EXCEPTION, PROMOTION_SERVICE_ERROR, REWARDS_SERVICE_ERROR, BML_SERVICE_ERROR, 
            TRACKING_SERVICE_ERROR, LOGISTICS_SERVICE_ERROR, INVALID_ITEMID, CASH_BACK_ITEMS_NOT_CARTABLE, REAL_ESTATE_ITEMS_NOT_CARTABLE, CART_IS_NOT_ENABLED_ON_THIS_SITE, ITEM_LISTING_SITE_UNSUPPORED, BLOCKED_ITEM_CATEGORY, INVALID_SHIPPING_TYPE, INVALID_PAYMENT_METHOD, 
            INVALID_SALE_TYPE, SELLER_CREATED_ORDER_NOT_UPDATABLE, UNFORESEEN_DOMAIN_ERROR
        });
    }

    private (String s, int i)
    {
        super(s, i);
    }
}
