// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package jp.co.cyberagent.android.gpuimage.grafika;


public final class a extends Enum
{

    private static final BEAUTYCAM_FILTER_GAUSSIANBLUR $VALUES[];
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BBEAUTYCAM_FILTER_LUT_UNA;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ASSORTED_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ASSORTED_BeachBlue_dusk;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ASSORTED_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ASSORTED_Exposed;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ASSORTED_Lavender;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ASSORTED_Lomo;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ASSORTED_Softpink;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BLACKWHITE_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BLACKWHITE_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BLACKWHITE_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BLACKWHITE_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BLEND;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_10;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_11;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_5;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_6;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_7;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_8;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_9;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_BXXX_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_5;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_6;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_7;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_8;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_COLORLEAK_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_FIXSIZE_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_FIXSIZE_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GAUSSIANBLUR;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET1_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET1_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET1_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET2_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET2_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET2_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET3_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET3_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET3_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET4_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET4_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET4_4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_GROUPSET_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_1977;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Amaro;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Apollo;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Brannan;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Classic;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Earlybird;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Hefe;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Hudson;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Inkwell;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Lomofi;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_LordKelvin;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Mayfair;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Nashville;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Retro;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Rise;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_SOOC;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Sierra;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Sutro;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Toaster;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Valencia;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Walden;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_Willow;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_INSTAGRAM_XProII;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_10;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_11;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_12;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_13;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_5;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_6;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_7;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_8;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LIGHT_9;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LOMO;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LOOKUPTABLE;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_ABAO;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_ABAO_EARTH;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_ABAO_FAIR;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_ABAO_LIBRA;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_HEIBAI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_JINGMI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_LIANGBAI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_LIANGLI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_LUANFENG;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_MENGLONG;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_QINGSHUANG;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_QINGXIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_TEST_01;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_TEST_02;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_TEST_03;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_TEST_04;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_TEST_05;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_TEST_06;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_TIANMI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_XIAOQINGXIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_LUT_XIARI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF5;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF6;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF7;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF8;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF9;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_MF_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_OLDFILM;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_OLDFILM_BW;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_OLDTIME;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Blue;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Cyan;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_DeepBlue;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_DeepEmerald;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_DeepRed;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_DeepYellow;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Green;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Magenta;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Orange;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Red;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Sepia;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_UnderWater;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Violet;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PHOTOFILTER_Yellow;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP10;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP5;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP6;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP7;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP8;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIP9;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_PIPCAMERA_TEST;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_10;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_5;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_6;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_7;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_8;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_9;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SATURNRINGS_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_10;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_11;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_12;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_13;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_14;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_15;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_16;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_18;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_19;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_20;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_5;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_6;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_7;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_8;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SELECTIVECOLOR_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_SOFTEN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_TEMPLATE1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_TEMPLATE2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_TEMPLATE3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_TEMPLATE4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_VINTANGE_1;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_VINTANGE_2;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_VINTANGE_3;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_VINTANGE_4;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_VINTANGE_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_VINTANGE_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_BEGIN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_BIYE;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_CHUNVZUO;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_END;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_GUIMI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_LVXING;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_SHENGHUO;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_SHOUZI;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_WOMEN;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_XIAOQUEXING;
    public static final BEAUTYCAM_FILTER_GAUSSIANBLUR BEAUTYCAM_FILTER_ZZZ_ZHESHIWO;

    public static a valueOf(String s)
    {
        return (a)Enum.valueOf(jp/co/cyberagent/android/gpuimage/grafika/GPUImageBeautyFilterFactory$BEAUTYCAM_FILTER_TYPE, s);
    }

    public static a[] values()
    {
        return (a[])$VALUES.clone();
    }

    static 
    {
        BEAUTYCAM_FILTER_TEMPLATE1 = new <init>("BEAUTYCAM_FILTER_TEMPLATE1", 0);
        BEAUTYCAM_FILTER_TEMPLATE2 = new <init>("BEAUTYCAM_FILTER_TEMPLATE2", 1);
        BEAUTYCAM_FILTER_TEMPLATE3 = new <init>("BEAUTYCAM_FILTER_TEMPLATE3", 2);
        BEAUTYCAM_FILTER_TEMPLATE4 = new <init>("BEAUTYCAM_FILTER_TEMPLATE4", 3);
        BEAUTYCAM_FILTER_SOFTEN = new <init>("BEAUTYCAM_FILTER_SOFTEN", 4);
        BEAUTYCAM_FILTER_LOOKUPTABLE = new <init>("BEAUTYCAM_FILTER_LOOKUPTABLE", 5);
        BEAUTYCAM_FILTER_BLEND = new <init>("BEAUTYCAM_FILTER_BLEND", 6);
        BEAUTYCAM_FILTER_PIPCAMERA_TEST = new <init>("BEAUTYCAM_FILTER_PIPCAMERA_TEST", 7);
        BEAUTYCAM_FILTER_MF_BEGIN = new <init>("BEAUTYCAM_FILTER_MF_BEGIN", 8);
        BEAUTYCAM_FILTER_MF1 = new <init>("BEAUTYCAM_FILTER_MF1", 9);
        BEAUTYCAM_FILTER_MF2 = new <init>("BEAUTYCAM_FILTER_MF2", 10);
        BEAUTYCAM_FILTER_MF3 = new <init>("BEAUTYCAM_FILTER_MF3", 11);
        BEAUTYCAM_FILTER_MF4 = new <init>("BEAUTYCAM_FILTER_MF4", 12);
        BEAUTYCAM_FILTER_MF5 = new <init>("BEAUTYCAM_FILTER_MF5", 13);
        BEAUTYCAM_FILTER_MF6 = new <init>("BEAUTYCAM_FILTER_MF6", 14);
        BEAUTYCAM_FILTER_MF7 = new <init>("BEAUTYCAM_FILTER_MF7", 15);
        BEAUTYCAM_FILTER_MF8 = new <init>("BEAUTYCAM_FILTER_MF8", 16);
        BEAUTYCAM_FILTER_MF9 = new <init>("BEAUTYCAM_FILTER_MF9", 17);
        BEAUTYCAM_FILTER_MF_END = new <init>("BEAUTYCAM_FILTER_MF_END", 18);
        BEAUTYCAM_FILTER_FIXSIZE_BEGIN = new <init>("BEAUTYCAM_FILTER_FIXSIZE_BEGIN", 19);
        BEAUTYCAM_FILTER_PIP1 = new <init>("BEAUTYCAM_FILTER_PIP1", 20);
        BEAUTYCAM_FILTER_PIP2 = new <init>("BEAUTYCAM_FILTER_PIP2", 21);
        BEAUTYCAM_FILTER_PIP3 = new <init>("BEAUTYCAM_FILTER_PIP3", 22);
        BEAUTYCAM_FILTER_PIP4 = new <init>("BEAUTYCAM_FILTER_PIP4", 23);
        BEAUTYCAM_FILTER_PIP5 = new <init>("BEAUTYCAM_FILTER_PIP5", 24);
        BEAUTYCAM_FILTER_PIP6 = new <init>("BEAUTYCAM_FILTER_PIP6", 25);
        BEAUTYCAM_FILTER_PIP7 = new <init>("BEAUTYCAM_FILTER_PIP7", 26);
        BEAUTYCAM_FILTER_PIP8 = new <init>("BEAUTYCAM_FILTER_PIP8", 27);
        BEAUTYCAM_FILTER_PIP9 = new <init>("BEAUTYCAM_FILTER_PIP9", 28);
        BEAUTYCAM_FILTER_PIP10 = new <init>("BEAUTYCAM_FILTER_PIP10", 29);
        BEAUTYCAM_FILTER_FIXSIZE_END = new <init>("BEAUTYCAM_FILTER_FIXSIZE_END", 30);
        BEAUTYCAM_FILTER_INSTAGRAM_BEGIN = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_BEGIN", 31);
        BEAUTYCAM_FILTER_INSTAGRAM_Classic = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Classic", 32);
        BEAUTYCAM_FILTER_INSTAGRAM_SOOC = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_SOOC", 33);
        BEAUTYCAM_FILTER_INSTAGRAM_Rise = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Rise", 34);
        BEAUTYCAM_FILTER_INSTAGRAM_Valencia = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Valencia", 35);
        BEAUTYCAM_FILTER_INSTAGRAM_Retro = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Retro", 36);
        BEAUTYCAM_FILTER_INSTAGRAM_Sutro = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Sutro", 37);
        BEAUTYCAM_FILTER_INSTAGRAM_Sierra = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Sierra", 38);
        BEAUTYCAM_FILTER_INSTAGRAM_Willow = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Willow", 39);
        BEAUTYCAM_FILTER_INSTAGRAM_Walden = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Walden", 40);
        BEAUTYCAM_FILTER_INSTAGRAM_Apollo = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Apollo", 41);
        BEAUTYCAM_FILTER_INSTAGRAM_Amaro = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Amaro", 42);
        BEAUTYCAM_FILTER_INSTAGRAM_LordKelvin = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_LordKelvin", 43);
        BEAUTYCAM_FILTER_INSTAGRAM_Nashville = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Nashville", 44);
        BEAUTYCAM_FILTER_INSTAGRAM_Lomofi = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Lomofi", 45);
        BEAUTYCAM_FILTER_INSTAGRAM_Inkwell = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Inkwell", 46);
        BEAUTYCAM_FILTER_INSTAGRAM_1977 = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_1977", 47);
        BEAUTYCAM_FILTER_INSTAGRAM_Brannan = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Brannan", 48);
        BEAUTYCAM_FILTER_INSTAGRAM_Earlybird = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Earlybird", 49);
        BEAUTYCAM_FILTER_INSTAGRAM_Hudson = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Hudson", 50);
        BEAUTYCAM_FILTER_INSTAGRAM_Mayfair = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Mayfair", 51);
        BEAUTYCAM_FILTER_INSTAGRAM_XProII = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_XProII", 52);
        BEAUTYCAM_FILTER_INSTAGRAM_Toaster = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Toaster", 53);
        BEAUTYCAM_FILTER_INSTAGRAM_Hefe = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_Hefe", 54);
        BEAUTYCAM_FILTER_INSTAGRAM_END = new <init>("BEAUTYCAM_FILTER_INSTAGRAM_END", 55);
        BEAUTYCAM_FILTER_SATURNRINGS_BEGIN = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_BEGIN", 56);
        BEAUTYCAM_FILTER_SATURNRINGS_1 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_1", 57);
        BEAUTYCAM_FILTER_SATURNRINGS_2 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_2", 58);
        BEAUTYCAM_FILTER_SATURNRINGS_3 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_3", 59);
        BEAUTYCAM_FILTER_SATURNRINGS_4 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_4", 60);
        BEAUTYCAM_FILTER_SATURNRINGS_5 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_5", 61);
        BEAUTYCAM_FILTER_SATURNRINGS_6 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_6", 62);
        BEAUTYCAM_FILTER_SATURNRINGS_7 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_7", 63);
        BEAUTYCAM_FILTER_SATURNRINGS_8 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_8", 64);
        BEAUTYCAM_FILTER_SATURNRINGS_9 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_9", 65);
        BEAUTYCAM_FILTER_SATURNRINGS_10 = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_10", 66);
        BEAUTYCAM_FILTER_SATURNRINGS_END = new <init>("BEAUTYCAM_FILTER_SATURNRINGS_END", 67);
        BEAUTYCAM_FILTER_BXXX_BEGIN = new <init>("BEAUTYCAM_FILTER_BXXX_BEGIN", 68);
        BEAUTYCAM_FILTER_BXXX_3 = new <init>("BEAUTYCAM_FILTER_BXXX_3", 69);
        BEAUTYCAM_FILTER_BXXX_4 = new <init>("BEAUTYCAM_FILTER_BXXX_4", 70);
        BEAUTYCAM_FILTER_BXXX_5 = new <init>("BEAUTYCAM_FILTER_BXXX_5", 71);
        BEAUTYCAM_FILTER_BXXX_6 = new <init>("BEAUTYCAM_FILTER_BXXX_6", 72);
        BEAUTYCAM_FILTER_BXXX_7 = new <init>("BEAUTYCAM_FILTER_BXXX_7", 73);
        BEAUTYCAM_FILTER_BXXX_8 = new <init>("BEAUTYCAM_FILTER_BXXX_8", 74);
        BEAUTYCAM_FILTER_BXXX_9 = new <init>("BEAUTYCAM_FILTER_BXXX_9", 75);
        BEAUTYCAM_FILTER_BXXX_10 = new <init>("BEAUTYCAM_FILTER_BXXX_10", 76);
        BEAUTYCAM_FILTER_BXXX_11 = new <init>("BEAUTYCAM_FILTER_BXXX_11", 77);
        BEAUTYCAM_FILTER_BXXX_END = new <init>("BEAUTYCAM_FILTER_BXXX_END", 78);
        BEAUTYCAM_FILTER_GROUPSET_BEGIN = new <init>("BEAUTYCAM_FILTER_GROUPSET_BEGIN", 79);
        BEAUTYCAM_FILTER_GROUPSET1_1 = new <init>("BEAUTYCAM_FILTER_GROUPSET1_1", 80);
        BEAUTYCAM_FILTER_GROUPSET1_2 = new <init>("BEAUTYCAM_FILTER_GROUPSET1_2", 81);
        BEAUTYCAM_FILTER_GROUPSET1_3 = new <init>("BEAUTYCAM_FILTER_GROUPSET1_3", 82);
        BEAUTYCAM_FILTER_GROUPSET2_1 = new <init>("BEAUTYCAM_FILTER_GROUPSET2_1", 83);
        BEAUTYCAM_FILTER_GROUPSET2_2 = new <init>("BEAUTYCAM_FILTER_GROUPSET2_2", 84);
        BEAUTYCAM_FILTER_GROUPSET2_3 = new <init>("BEAUTYCAM_FILTER_GROUPSET2_3", 85);
        BEAUTYCAM_FILTER_GROUPSET3_1 = new <init>("BEAUTYCAM_FILTER_GROUPSET3_1", 86);
        BEAUTYCAM_FILTER_GROUPSET3_2 = new <init>("BEAUTYCAM_FILTER_GROUPSET3_2", 87);
        BEAUTYCAM_FILTER_GROUPSET3_3 = new <init>("BEAUTYCAM_FILTER_GROUPSET3_3", 88);
        BEAUTYCAM_FILTER_GROUPSET4_1 = new <init>("BEAUTYCAM_FILTER_GROUPSET4_1", 89);
        BEAUTYCAM_FILTER_GROUPSET4_2 = new <init>("BEAUTYCAM_FILTER_GROUPSET4_2", 90);
        BEAUTYCAM_FILTER_GROUPSET4_4 = new <init>("BEAUTYCAM_FILTER_GROUPSET4_4", 91);
        BEAUTYCAM_FILTER_GROUPSET_END = new <init>("BEAUTYCAM_FILTER_GROUPSET_END", 92);
        BEAUTYCAM_FILTER_ASSORTED_BEGIN = new <init>("BEAUTYCAM_FILTER_ASSORTED_BEGIN", 93);
        BEAUTYCAM_FILTER_ASSORTED_Lavender = new <init>("BEAUTYCAM_FILTER_ASSORTED_Lavender", 94);
        BEAUTYCAM_FILTER_ASSORTED_Lomo = new <init>("BEAUTYCAM_FILTER_ASSORTED_Lomo", 95);
        BEAUTYCAM_FILTER_ASSORTED_Softpink = new <init>("BEAUTYCAM_FILTER_ASSORTED_Softpink", 96);
        BEAUTYCAM_FILTER_ASSORTED_Exposed = new <init>("BEAUTYCAM_FILTER_ASSORTED_Exposed", 97);
        BEAUTYCAM_FILTER_ASSORTED_BeachBlue_dusk = new <init>("BEAUTYCAM_FILTER_ASSORTED_BeachBlue_dusk", 98);
        BEAUTYCAM_FILTER_ASSORTED_END = new <init>("BEAUTYCAM_FILTER_ASSORTED_END", 99);
        BEAUTYCAM_FILTER_VINTANGE_BEGIN = new <init>("BEAUTYCAM_FILTER_VINTANGE_BEGIN", 100);
        BEAUTYCAM_FILTER_VINTANGE_1 = new <init>("BEAUTYCAM_FILTER_VINTANGE_1", 101);
        BEAUTYCAM_FILTER_VINTANGE_2 = new <init>("BEAUTYCAM_FILTER_VINTANGE_2", 102);
        BEAUTYCAM_FILTER_VINTANGE_3 = new <init>("BEAUTYCAM_FILTER_VINTANGE_3", 103);
        BEAUTYCAM_FILTER_VINTANGE_4 = new <init>("BEAUTYCAM_FILTER_VINTANGE_4", 104);
        BEAUTYCAM_FILTER_VINTANGE_END = new <init>("BEAUTYCAM_FILTER_VINTANGE_END", 105);
        BEAUTYCAM_FILTER_COLORLEAK_BEGIN = new <init>("BEAUTYCAM_FILTER_COLORLEAK_BEGIN", 106);
        BEAUTYCAM_FILTER_COLORLEAK_1 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_1", 107);
        BEAUTYCAM_FILTER_COLORLEAK_2 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_2", 108);
        BEAUTYCAM_FILTER_COLORLEAK_3 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_3", 109);
        BEAUTYCAM_FILTER_COLORLEAK_4 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_4", 110);
        BEAUTYCAM_FILTER_COLORLEAK_5 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_5", 111);
        BEAUTYCAM_FILTER_COLORLEAK_6 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_6", 112);
        BEAUTYCAM_FILTER_COLORLEAK_7 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_7", 113);
        BEAUTYCAM_FILTER_COLORLEAK_8 = new <init>("BEAUTYCAM_FILTER_COLORLEAK_8", 114);
        BEAUTYCAM_FILTER_COLORLEAK_END = new <init>("BEAUTYCAM_FILTER_COLORLEAK_END", 115);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_BEGIN = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_BEGIN", 116);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_1 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_1", 117);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_2 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_2", 118);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_3 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_3", 119);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_5 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_5", 120);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_6 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_6", 121);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_7 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_7", 122);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_8 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_8", 123);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_10 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_10", 124);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_11 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_11", 125);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_12 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_12", 126);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_13 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_13", 127);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_14 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_14", 128);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_15 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_15", 129);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_16 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_16", 130);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_18 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_18", 131);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_19 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_19", 132);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_20 = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_20", 133);
        BEAUTYCAM_FILTER_SELECTIVECOLOR_END = new <init>("BEAUTYCAM_FILTER_SELECTIVECOLOR_END", 134);
        BEAUTYCAM_FILTER_BLACKWHITE_BEGIN = new <init>("BEAUTYCAM_FILTER_BLACKWHITE_BEGIN", 135);
        BEAUTYCAM_FILTER_BLACKWHITE_1 = new <init>("BEAUTYCAM_FILTER_BLACKWHITE_1", 136);
        BEAUTYCAM_FILTER_BLACKWHITE_2 = new <init>("BEAUTYCAM_FILTER_BLACKWHITE_2", 137);
        BEAUTYCAM_FILTER_BLACKWHITE_END = new <init>("BEAUTYCAM_FILTER_BLACKWHITE_END", 138);
        BEAUTYCAM_FILTER_PHOTOFILTER_BEGIN = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_BEGIN", 139);
        BEAUTYCAM_FILTER_PHOTOFILTER_Red = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Red", 140);
        BEAUTYCAM_FILTER_PHOTOFILTER_DeepRed = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_DeepRed", 141);
        BEAUTYCAM_FILTER_PHOTOFILTER_Green = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Green", 142);
        BEAUTYCAM_FILTER_PHOTOFILTER_Blue = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Blue", 143);
        BEAUTYCAM_FILTER_PHOTOFILTER_DeepBlue = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_DeepBlue", 144);
        BEAUTYCAM_FILTER_PHOTOFILTER_Yellow = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Yellow", 145);
        BEAUTYCAM_FILTER_PHOTOFILTER_DeepYellow = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_DeepYellow", 146);
        BEAUTYCAM_FILTER_PHOTOFILTER_Violet = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Violet", 147);
        BEAUTYCAM_FILTER_PHOTOFILTER_Magenta = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Magenta", 148);
        BEAUTYCAM_FILTER_PHOTOFILTER_Sepia = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Sepia", 149);
        BEAUTYCAM_FILTER_PHOTOFILTER_Cyan = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Cyan", 150);
        BEAUTYCAM_FILTER_PHOTOFILTER_Orange = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Orange", 151);
        BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter1 = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter1", 152);
        BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter2 = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter2", 153);
        BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter3 = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter3", 154);
        BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter1 = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter1", 155);
        BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter2 = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter2", 156);
        BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter3 = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter3", 157);
        BEAUTYCAM_FILTER_PHOTOFILTER_DeepEmerald = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_DeepEmerald", 158);
        BEAUTYCAM_FILTER_PHOTOFILTER_UnderWater = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_UnderWater", 159);
        BEAUTYCAM_FILTER_PHOTOFILTER_END = new <init>("BEAUTYCAM_FILTER_PHOTOFILTER_END", 160);
        BEAUTYCAM_FILTER_LUT_BEGIN = new <init>("BEAUTYCAM_FILTER_LUT_BEGIN", 161);
        BEAUTYCAM_FILTER_LUT_LIANGBAI = new <init>("BEAUTYCAM_FILTER_LUT_LIANGBAI", 162);
        BEAUTYCAM_FILTER_LUT_MENGLONG = new <init>("BEAUTYCAM_FILTER_LUT_MENGLONG", 163);
        BEAUTYCAM_FILTER_LUT_TIANMI = new <init>("BEAUTYCAM_FILTER_LUT_TIANMI", 164);
        BEAUTYCAM_FILTER_LUT_ABAO = new <init>("BEAUTYCAM_FILTER_LUT_ABAO", 165);
        BEAUTYCAM_FILTER_LUT_ABAO_EARTH = new <init>("BEAUTYCAM_FILTER_LUT_ABAO_EARTH", 166);
        BEAUTYCAM_FILTER_LUT_ABAO_FAIR = new <init>("BEAUTYCAM_FILTER_LUT_ABAO_FAIR", 167);
        BEAUTYCAM_FILTER_LUT_ABAO_LIBRA = new <init>("BEAUTYCAM_FILTER_LUT_ABAO_LIBRA", 168);
        BEAUTYCAM_FILTER_LUT_XIARI = new <init>("BEAUTYCAM_FILTER_LUT_XIARI", 169);
        BEAUTYCAM_FILTER_LUT_QINGXIN = new <init>("BEAUTYCAM_FILTER_LUT_QINGXIN", 170);
        BEAUTYCAM_FILTER_LUT_QINGSHUANG = new <init>("BEAUTYCAM_FILTER_LUT_QINGSHUANG", 171);
        BEAUTYCAM_FILTER_LUT_LIANGLI = new <init>("BEAUTYCAM_FILTER_LUT_LIANGLI", 172);
        BEAUTYCAM_FILTER_LUT_XIAOQINGXIN = new <init>("BEAUTYCAM_FILTER_LUT_XIAOQINGXIN", 173);
        BEAUTYCAM_FILTER_LUT_LUANFENG = new <init>("BEAUTYCAM_FILTER_LUT_LUANFENG", 174);
        BEAUTYCAM_FILTER_LUT_JINGMI = new <init>("BEAUTYCAM_FILTER_LUT_JINGMI", 175);
        BEAUTYCAM_FILTER_LUT_HEIBAI = new <init>("BEAUTYCAM_FILTER_LUT_HEIBAI", 176);
        BBEAUTYCAM_FILTER_LUT_UNA = new <init>("BBEAUTYCAM_FILTER_LUT_UNA", 177);
        BEAUTYCAM_FILTER_LUT_TEST_01 = new <init>("BEAUTYCAM_FILTER_LUT_TEST_01", 178);
        BEAUTYCAM_FILTER_LUT_TEST_02 = new <init>("BEAUTYCAM_FILTER_LUT_TEST_02", 179);
        BEAUTYCAM_FILTER_LUT_TEST_03 = new <init>("BEAUTYCAM_FILTER_LUT_TEST_03", 180);
        BEAUTYCAM_FILTER_LUT_TEST_04 = new <init>("BEAUTYCAM_FILTER_LUT_TEST_04", 181);
        BEAUTYCAM_FILTER_LUT_TEST_05 = new <init>("BEAUTYCAM_FILTER_LUT_TEST_05", 182);
        BEAUTYCAM_FILTER_LUT_TEST_06 = new <init>("BEAUTYCAM_FILTER_LUT_TEST_06", 183);
        BEAUTYCAM_FILTER_LUT_END = new <init>("BEAUTYCAM_FILTER_LUT_END", 184);
        BEAUTYCAM_FILTER_LOMO = new <init>("BEAUTYCAM_FILTER_LOMO", 185);
        BEAUTYCAM_FILTER_OLDTIME = new <init>("BEAUTYCAM_FILTER_OLDTIME", 186);
        BEAUTYCAM_FILTER_OLDFILM = new <init>("BEAUTYCAM_FILTER_OLDFILM", 187);
        BEAUTYCAM_FILTER_OLDFILM_BW = new <init>("BEAUTYCAM_FILTER_OLDFILM_BW", 188);
        BEAUTYCAM_FILTER_LIGHT_1 = new <init>("BEAUTYCAM_FILTER_LIGHT_1", 189);
        BEAUTYCAM_FILTER_LIGHT_2 = new <init>("BEAUTYCAM_FILTER_LIGHT_2", 190);
        BEAUTYCAM_FILTER_LIGHT_3 = new <init>("BEAUTYCAM_FILTER_LIGHT_3", 191);
        BEAUTYCAM_FILTER_LIGHT_4 = new <init>("BEAUTYCAM_FILTER_LIGHT_4", 192);
        BEAUTYCAM_FILTER_LIGHT_5 = new <init>("BEAUTYCAM_FILTER_LIGHT_5", 193);
        BEAUTYCAM_FILTER_LIGHT_6 = new <init>("BEAUTYCAM_FILTER_LIGHT_6", 194);
        BEAUTYCAM_FILTER_LIGHT_7 = new <init>("BEAUTYCAM_FILTER_LIGHT_7", 195);
        BEAUTYCAM_FILTER_LIGHT_8 = new <init>("BEAUTYCAM_FILTER_LIGHT_8", 196);
        BEAUTYCAM_FILTER_LIGHT_9 = new <init>("BEAUTYCAM_FILTER_LIGHT_9", 197);
        BEAUTYCAM_FILTER_LIGHT_10 = new <init>("BEAUTYCAM_FILTER_LIGHT_10", 198);
        BEAUTYCAM_FILTER_LIGHT_11 = new <init>("BEAUTYCAM_FILTER_LIGHT_11", 199);
        BEAUTYCAM_FILTER_LIGHT_12 = new <init>("BEAUTYCAM_FILTER_LIGHT_12", 200);
        BEAUTYCAM_FILTER_LIGHT_13 = new <init>("BEAUTYCAM_FILTER_LIGHT_13", 201);
        BEAUTYCAM_FILTER_ZZZ_BEGIN = new <init>("BEAUTYCAM_FILTER_ZZZ_BEGIN", 202);
        BEAUTYCAM_FILTER_ZZZ_SHENGHUO = new <init>("BEAUTYCAM_FILTER_ZZZ_SHENGHUO", 203);
        BEAUTYCAM_FILTER_ZZZ_SHOUZI = new <init>("BEAUTYCAM_FILTER_ZZZ_SHOUZI", 204);
        BEAUTYCAM_FILTER_ZZZ_ZHESHIWO = new <init>("BEAUTYCAM_FILTER_ZZZ_ZHESHIWO", 205);
        BEAUTYCAM_FILTER_ZZZ_LVXING = new <init>("BEAUTYCAM_FILTER_ZZZ_LVXING", 206);
        BEAUTYCAM_FILTER_ZZZ_XIAOQUEXING = new <init>("BEAUTYCAM_FILTER_ZZZ_XIAOQUEXING", 207);
        BEAUTYCAM_FILTER_ZZZ_CHUNVZUO = new <init>("BEAUTYCAM_FILTER_ZZZ_CHUNVZUO", 208);
        BEAUTYCAM_FILTER_ZZZ_WOMEN = new <init>("BEAUTYCAM_FILTER_ZZZ_WOMEN", 209);
        BEAUTYCAM_FILTER_ZZZ_GUIMI = new <init>("BEAUTYCAM_FILTER_ZZZ_GUIMI", 210);
        BEAUTYCAM_FILTER_ZZZ_BIYE = new <init>("BEAUTYCAM_FILTER_ZZZ_BIYE", 211);
        BEAUTYCAM_FILTER_ZZZ_END = new <init>("BEAUTYCAM_FILTER_ZZZ_END", 212);
        BEAUTYCAM_FILTER_GAUSSIANBLUR = new <init>("BEAUTYCAM_FILTER_GAUSSIANBLUR", 213);
        $VALUES = (new .VALUES[] {
            BEAUTYCAM_FILTER_TEMPLATE1, BEAUTYCAM_FILTER_TEMPLATE2, BEAUTYCAM_FILTER_TEMPLATE3, BEAUTYCAM_FILTER_TEMPLATE4, BEAUTYCAM_FILTER_SOFTEN, BEAUTYCAM_FILTER_LOOKUPTABLE, BEAUTYCAM_FILTER_BLEND, BEAUTYCAM_FILTER_PIPCAMERA_TEST, BEAUTYCAM_FILTER_MF_BEGIN, BEAUTYCAM_FILTER_MF1, 
            BEAUTYCAM_FILTER_MF2, BEAUTYCAM_FILTER_MF3, BEAUTYCAM_FILTER_MF4, BEAUTYCAM_FILTER_MF5, BEAUTYCAM_FILTER_MF6, BEAUTYCAM_FILTER_MF7, BEAUTYCAM_FILTER_MF8, BEAUTYCAM_FILTER_MF9, BEAUTYCAM_FILTER_MF_END, BEAUTYCAM_FILTER_FIXSIZE_BEGIN, 
            BEAUTYCAM_FILTER_PIP1, BEAUTYCAM_FILTER_PIP2, BEAUTYCAM_FILTER_PIP3, BEAUTYCAM_FILTER_PIP4, BEAUTYCAM_FILTER_PIP5, BEAUTYCAM_FILTER_PIP6, BEAUTYCAM_FILTER_PIP7, BEAUTYCAM_FILTER_PIP8, BEAUTYCAM_FILTER_PIP9, BEAUTYCAM_FILTER_PIP10, 
            BEAUTYCAM_FILTER_FIXSIZE_END, BEAUTYCAM_FILTER_INSTAGRAM_BEGIN, BEAUTYCAM_FILTER_INSTAGRAM_Classic, BEAUTYCAM_FILTER_INSTAGRAM_SOOC, BEAUTYCAM_FILTER_INSTAGRAM_Rise, BEAUTYCAM_FILTER_INSTAGRAM_Valencia, BEAUTYCAM_FILTER_INSTAGRAM_Retro, BEAUTYCAM_FILTER_INSTAGRAM_Sutro, BEAUTYCAM_FILTER_INSTAGRAM_Sierra, BEAUTYCAM_FILTER_INSTAGRAM_Willow, 
            BEAUTYCAM_FILTER_INSTAGRAM_Walden, BEAUTYCAM_FILTER_INSTAGRAM_Apollo, BEAUTYCAM_FILTER_INSTAGRAM_Amaro, BEAUTYCAM_FILTER_INSTAGRAM_LordKelvin, BEAUTYCAM_FILTER_INSTAGRAM_Nashville, BEAUTYCAM_FILTER_INSTAGRAM_Lomofi, BEAUTYCAM_FILTER_INSTAGRAM_Inkwell, BEAUTYCAM_FILTER_INSTAGRAM_1977, BEAUTYCAM_FILTER_INSTAGRAM_Brannan, BEAUTYCAM_FILTER_INSTAGRAM_Earlybird, 
            BEAUTYCAM_FILTER_INSTAGRAM_Hudson, BEAUTYCAM_FILTER_INSTAGRAM_Mayfair, BEAUTYCAM_FILTER_INSTAGRAM_XProII, BEAUTYCAM_FILTER_INSTAGRAM_Toaster, BEAUTYCAM_FILTER_INSTAGRAM_Hefe, BEAUTYCAM_FILTER_INSTAGRAM_END, BEAUTYCAM_FILTER_SATURNRINGS_BEGIN, BEAUTYCAM_FILTER_SATURNRINGS_1, BEAUTYCAM_FILTER_SATURNRINGS_2, BEAUTYCAM_FILTER_SATURNRINGS_3, 
            BEAUTYCAM_FILTER_SATURNRINGS_4, BEAUTYCAM_FILTER_SATURNRINGS_5, BEAUTYCAM_FILTER_SATURNRINGS_6, BEAUTYCAM_FILTER_SATURNRINGS_7, BEAUTYCAM_FILTER_SATURNRINGS_8, BEAUTYCAM_FILTER_SATURNRINGS_9, BEAUTYCAM_FILTER_SATURNRINGS_10, BEAUTYCAM_FILTER_SATURNRINGS_END, BEAUTYCAM_FILTER_BXXX_BEGIN, BEAUTYCAM_FILTER_BXXX_3, 
            BEAUTYCAM_FILTER_BXXX_4, BEAUTYCAM_FILTER_BXXX_5, BEAUTYCAM_FILTER_BXXX_6, BEAUTYCAM_FILTER_BXXX_7, BEAUTYCAM_FILTER_BXXX_8, BEAUTYCAM_FILTER_BXXX_9, BEAUTYCAM_FILTER_BXXX_10, BEAUTYCAM_FILTER_BXXX_11, BEAUTYCAM_FILTER_BXXX_END, BEAUTYCAM_FILTER_GROUPSET_BEGIN, 
            BEAUTYCAM_FILTER_GROUPSET1_1, BEAUTYCAM_FILTER_GROUPSET1_2, BEAUTYCAM_FILTER_GROUPSET1_3, BEAUTYCAM_FILTER_GROUPSET2_1, BEAUTYCAM_FILTER_GROUPSET2_2, BEAUTYCAM_FILTER_GROUPSET2_3, BEAUTYCAM_FILTER_GROUPSET3_1, BEAUTYCAM_FILTER_GROUPSET3_2, BEAUTYCAM_FILTER_GROUPSET3_3, BEAUTYCAM_FILTER_GROUPSET4_1, 
            BEAUTYCAM_FILTER_GROUPSET4_2, BEAUTYCAM_FILTER_GROUPSET4_4, BEAUTYCAM_FILTER_GROUPSET_END, BEAUTYCAM_FILTER_ASSORTED_BEGIN, BEAUTYCAM_FILTER_ASSORTED_Lavender, BEAUTYCAM_FILTER_ASSORTED_Lomo, BEAUTYCAM_FILTER_ASSORTED_Softpink, BEAUTYCAM_FILTER_ASSORTED_Exposed, BEAUTYCAM_FILTER_ASSORTED_BeachBlue_dusk, BEAUTYCAM_FILTER_ASSORTED_END, 
            BEAUTYCAM_FILTER_VINTANGE_BEGIN, BEAUTYCAM_FILTER_VINTANGE_1, BEAUTYCAM_FILTER_VINTANGE_2, BEAUTYCAM_FILTER_VINTANGE_3, BEAUTYCAM_FILTER_VINTANGE_4, BEAUTYCAM_FILTER_VINTANGE_END, BEAUTYCAM_FILTER_COLORLEAK_BEGIN, BEAUTYCAM_FILTER_COLORLEAK_1, BEAUTYCAM_FILTER_COLORLEAK_2, BEAUTYCAM_FILTER_COLORLEAK_3, 
            BEAUTYCAM_FILTER_COLORLEAK_4, BEAUTYCAM_FILTER_COLORLEAK_5, BEAUTYCAM_FILTER_COLORLEAK_6, BEAUTYCAM_FILTER_COLORLEAK_7, BEAUTYCAM_FILTER_COLORLEAK_8, BEAUTYCAM_FILTER_COLORLEAK_END, BEAUTYCAM_FILTER_SELECTIVECOLOR_BEGIN, BEAUTYCAM_FILTER_SELECTIVECOLOR_1, BEAUTYCAM_FILTER_SELECTIVECOLOR_2, BEAUTYCAM_FILTER_SELECTIVECOLOR_3, 
            BEAUTYCAM_FILTER_SELECTIVECOLOR_5, BEAUTYCAM_FILTER_SELECTIVECOLOR_6, BEAUTYCAM_FILTER_SELECTIVECOLOR_7, BEAUTYCAM_FILTER_SELECTIVECOLOR_8, BEAUTYCAM_FILTER_SELECTIVECOLOR_10, BEAUTYCAM_FILTER_SELECTIVECOLOR_11, BEAUTYCAM_FILTER_SELECTIVECOLOR_12, BEAUTYCAM_FILTER_SELECTIVECOLOR_13, BEAUTYCAM_FILTER_SELECTIVECOLOR_14, BEAUTYCAM_FILTER_SELECTIVECOLOR_15, 
            BEAUTYCAM_FILTER_SELECTIVECOLOR_16, BEAUTYCAM_FILTER_SELECTIVECOLOR_18, BEAUTYCAM_FILTER_SELECTIVECOLOR_19, BEAUTYCAM_FILTER_SELECTIVECOLOR_20, BEAUTYCAM_FILTER_SELECTIVECOLOR_END, BEAUTYCAM_FILTER_BLACKWHITE_BEGIN, BEAUTYCAM_FILTER_BLACKWHITE_1, BEAUTYCAM_FILTER_BLACKWHITE_2, BEAUTYCAM_FILTER_BLACKWHITE_END, BEAUTYCAM_FILTER_PHOTOFILTER_BEGIN, 
            BEAUTYCAM_FILTER_PHOTOFILTER_Red, BEAUTYCAM_FILTER_PHOTOFILTER_DeepRed, BEAUTYCAM_FILTER_PHOTOFILTER_Green, BEAUTYCAM_FILTER_PHOTOFILTER_Blue, BEAUTYCAM_FILTER_PHOTOFILTER_DeepBlue, BEAUTYCAM_FILTER_PHOTOFILTER_Yellow, BEAUTYCAM_FILTER_PHOTOFILTER_DeepYellow, BEAUTYCAM_FILTER_PHOTOFILTER_Violet, BEAUTYCAM_FILTER_PHOTOFILTER_Magenta, BEAUTYCAM_FILTER_PHOTOFILTER_Sepia, 
            BEAUTYCAM_FILTER_PHOTOFILTER_Cyan, BEAUTYCAM_FILTER_PHOTOFILTER_Orange, BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter1, BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter2, BEAUTYCAM_FILTER_PHOTOFILTER_Coolingfilter3, BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter1, BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter2, BEAUTYCAM_FILTER_PHOTOFILTER_Warmingfilter3, BEAUTYCAM_FILTER_PHOTOFILTER_DeepEmerald, BEAUTYCAM_FILTER_PHOTOFILTER_UnderWater, 
            BEAUTYCAM_FILTER_PHOTOFILTER_END, BEAUTYCAM_FILTER_LUT_BEGIN, BEAUTYCAM_FILTER_LUT_LIANGBAI, BEAUTYCAM_FILTER_LUT_MENGLONG, BEAUTYCAM_FILTER_LUT_TIANMI, BEAUTYCAM_FILTER_LUT_ABAO, BEAUTYCAM_FILTER_LUT_ABAO_EARTH, BEAUTYCAM_FILTER_LUT_ABAO_FAIR, BEAUTYCAM_FILTER_LUT_ABAO_LIBRA, BEAUTYCAM_FILTER_LUT_XIARI, 
            BEAUTYCAM_FILTER_LUT_QINGXIN, BEAUTYCAM_FILTER_LUT_QINGSHUANG, BEAUTYCAM_FILTER_LUT_LIANGLI, BEAUTYCAM_FILTER_LUT_XIAOQINGXIN, BEAUTYCAM_FILTER_LUT_LUANFENG, BEAUTYCAM_FILTER_LUT_JINGMI, BEAUTYCAM_FILTER_LUT_HEIBAI, BBEAUTYCAM_FILTER_LUT_UNA, BEAUTYCAM_FILTER_LUT_TEST_01, BEAUTYCAM_FILTER_LUT_TEST_02, 
            BEAUTYCAM_FILTER_LUT_TEST_03, BEAUTYCAM_FILTER_LUT_TEST_04, BEAUTYCAM_FILTER_LUT_TEST_05, BEAUTYCAM_FILTER_LUT_TEST_06, BEAUTYCAM_FILTER_LUT_END, BEAUTYCAM_FILTER_LOMO, BEAUTYCAM_FILTER_OLDTIME, BEAUTYCAM_FILTER_OLDFILM, BEAUTYCAM_FILTER_OLDFILM_BW, BEAUTYCAM_FILTER_LIGHT_1, 
            BEAUTYCAM_FILTER_LIGHT_2, BEAUTYCAM_FILTER_LIGHT_3, BEAUTYCAM_FILTER_LIGHT_4, BEAUTYCAM_FILTER_LIGHT_5, BEAUTYCAM_FILTER_LIGHT_6, BEAUTYCAM_FILTER_LIGHT_7, BEAUTYCAM_FILTER_LIGHT_8, BEAUTYCAM_FILTER_LIGHT_9, BEAUTYCAM_FILTER_LIGHT_10, BEAUTYCAM_FILTER_LIGHT_11, 
            BEAUTYCAM_FILTER_LIGHT_12, BEAUTYCAM_FILTER_LIGHT_13, BEAUTYCAM_FILTER_ZZZ_BEGIN, BEAUTYCAM_FILTER_ZZZ_SHENGHUO, BEAUTYCAM_FILTER_ZZZ_SHOUZI, BEAUTYCAM_FILTER_ZZZ_ZHESHIWO, BEAUTYCAM_FILTER_ZZZ_LVXING, BEAUTYCAM_FILTER_ZZZ_XIAOQUEXING, BEAUTYCAM_FILTER_ZZZ_CHUNVZUO, BEAUTYCAM_FILTER_ZZZ_WOMEN, 
            BEAUTYCAM_FILTER_ZZZ_GUIMI, BEAUTYCAM_FILTER_ZZZ_BIYE, BEAUTYCAM_FILTER_ZZZ_END, BEAUTYCAM_FILTER_GAUSSIANBLUR
        });
    }

    private a(String s, int i)
    {
        super(s, i);
    }
}
