// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.disney.datg.videoplatforms.sdk.models.api;


// Referenced classes of package com.disney.datg.videoplatforms.sdk.models.api:
//            ErrorType

public static final class  extends Enum
{

    private static final KALTURA_INVALID_PROXY $VALUES[];
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_INTERNAL_ERROR;
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_REQUESTOR_ID_INVALID;
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_REQUESTOR_ID_MISSING;
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_RESOURCE_ID_INVALID;
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_RESOURCE_ID_MISSING;
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_TOKEN_EXPIRED;
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_TOKEN_INVALID;
    public static final KALTURA_INVALID_PROXY ADOBE_PASS_TOKEN_MISSING;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_EMPTY_CHANNEL_RESPONSE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_EMPTY_GEO_RESPONSE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_EMPTY_VIDEO_RESPONSE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_ACCESS_LEVEL_INVALID;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_ACCESS_MISSING_ASSET;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_CHANNEL_SERVICE_UNAVAILABLE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_GEO_BLOCK;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_GEO_OUTSIDE_US;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_GEO_SERVICE_UNAVAILABLE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_GEO_UNAVAILABLE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_UNKNOWN_TOKEN;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_UNKNOWN_VP2_APIKEY;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ERROR_VIDEO_SERVICE_UNAVAILABLE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_FATAL_ERROR;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_GEO_INTERNAL_ERROR;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_ILLEGAL_STATE_EXCEPTION;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_INVALID_PARAMETER_FIELDS;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_IPADDRESS_INVALID;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_MISSING_REQUIRED_FIELDS;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_SAX_EXCEPTION;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_SERVICE_IO_EXCEPTION;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_UNKNOWN_BRAND;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_UNKNOWN_PROTOCOL_EXCEPTION;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_UNSUPPORTED_CHANNEL_SERVICE;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_XPATH_EXPRESSION_EXCEPTION;
    public static final KALTURA_INVALID_PROXY ENTITLEMENT_APP_XPATH_PARSER_CONFIGURATION_EXCEPTION;
    public static final KALTURA_INVALID_PROXY KALTURA_INTERNAL_ERROR;
    public static final KALTURA_INVALID_PROXY KALTURA_INVALID_PROXY;
    public static final KALTURA_INVALID_PROXY UPLYNK_ERROR_ACCOUNT_ID_INVALID;
    public static final KALTURA_INVALID_PROXY UPLYNK_ERROR_API_KEY_INVALID;
    public static final KALTURA_INVALID_PROXY UPLYNK_ERROR_APPLICATION_KEY_INVALID;
    public static final KALTURA_INVALID_PROXY UPLYNK_ERROR_DIGITAL_SIGNATURE_CREATION_FAILED;
    public static final KALTURA_INVALID_PROXY UPLYNK_ERROR_MISSING_ASSET;
    public static final KALTURA_INVALID_PROXY UPLYNK_INTERNAL_ERROR;
    public static final KALTURA_INVALID_PROXY UPLYNK_INVALID_CONTENT_TYPE;
    public static final KALTURA_INVALID_PROXY UPLYNK_INVALID_VIDEO_ID;
    public static final KALTURA_INVALID_PROXY UPLYNK_INVALID_VIDEO_ID_MISSING;
    public static final KALTURA_INVALID_PROXY UPLYNK_MISSING_CONTENT_TYPE;
    public static final KALTURA_INVALID_PROXY UPLYNK_WORKFLOW_ID_INVALID;
    public static final KALTURA_INVALID_PROXY UPLYNK_WORKFLOW_ID_MISSING;

    public static  valueOf(String s)
    {
        return ()Enum.valueOf(com/disney/datg/videoplatforms/sdk/models/api/ErrorType$ErrorDefinition, s);
    }

    public static [] values()
    {
        return ([])$VALUES.clone();
    }

    static 
    {
        ENTITLEMENT_APP_ERROR = new <init>("ENTITLEMENT_APP_ERROR", 0);
        ENTITLEMENT_APP_ERROR_GEO_UNAVAILABLE = new <init>("ENTITLEMENT_APP_ERROR_GEO_UNAVAILABLE", 1);
        ENTITLEMENT_APP_ERROR_GEO_OUTSIDE_US = new <init>("ENTITLEMENT_APP_ERROR_GEO_OUTSIDE_US", 2);
        ENTITLEMENT_APP_ERROR_VIDEO_SERVICE_UNAVAILABLE = new <init>("ENTITLEMENT_APP_ERROR_VIDEO_SERVICE_UNAVAILABLE", 3);
        ENTITLEMENT_APP_ERROR_ACCESS_LEVEL_INVALID = new <init>("ENTITLEMENT_APP_ERROR_ACCESS_LEVEL_INVALID", 4);
        ENTITLEMENT_APP_ERROR_ACCESS_MISSING_ASSET = new <init>("ENTITLEMENT_APP_ERROR_ACCESS_MISSING_ASSET", 5);
        ENTITLEMENT_APP_FATAL_ERROR = new <init>("ENTITLEMENT_APP_FATAL_ERROR", 6);
        ENTITLEMENT_APP_MISSING_REQUIRED_FIELDS = new <init>("ENTITLEMENT_APP_MISSING_REQUIRED_FIELDS", 7);
        ENTITLEMENT_APP_UNKNOWN_BRAND = new <init>("ENTITLEMENT_APP_UNKNOWN_BRAND", 8);
        ENTITLEMENT_APP_IPADDRESS_INVALID = new <init>("ENTITLEMENT_APP_IPADDRESS_INVALID", 9);
        ENTITLEMENT_APP_GEO_INTERNAL_ERROR = new <init>("ENTITLEMENT_APP_GEO_INTERNAL_ERROR", 10);
        ENTITLEMENT_APP_INVALID_PARAMETER_FIELDS = new <init>("ENTITLEMENT_APP_INVALID_PARAMETER_FIELDS", 11);
        ENTITLEMENT_APP_EMPTY_VIDEO_RESPONSE = new <init>("ENTITLEMENT_APP_EMPTY_VIDEO_RESPONSE", 12);
        ENTITLEMENT_APP_ERROR_CHANNEL_SERVICE_UNAVAILABLE = new <init>("ENTITLEMENT_APP_ERROR_CHANNEL_SERVICE_UNAVAILABLE", 13);
        ENTITLEMENT_APP_EMPTY_CHANNEL_RESPONSE = new <init>("ENTITLEMENT_APP_EMPTY_CHANNEL_RESPONSE", 14);
        ENTITLEMENT_APP_UNSUPPORTED_CHANNEL_SERVICE = new <init>("ENTITLEMENT_APP_UNSUPPORTED_CHANNEL_SERVICE", 15);
        ENTITLEMENT_APP_EMPTY_GEO_RESPONSE = new <init>("ENTITLEMENT_APP_EMPTY_GEO_RESPONSE", 16);
        ENTITLEMENT_APP_ERROR_GEO_SERVICE_UNAVAILABLE = new <init>("ENTITLEMENT_APP_ERROR_GEO_SERVICE_UNAVAILABLE", 17);
        ENTITLEMENT_APP_ERROR_GEO_BLOCK = new <init>("ENTITLEMENT_APP_ERROR_GEO_BLOCK", 18);
        ENTITLEMENT_APP_ERROR_UNKNOWN_VP2_APIKEY = new <init>("ENTITLEMENT_APP_ERROR_UNKNOWN_VP2_APIKEY", 19);
        ENTITLEMENT_APP_ERROR_UNKNOWN_TOKEN = new <init>("ENTITLEMENT_APP_ERROR_UNKNOWN_TOKEN", 20);
        ENTITLEMENT_APP_UNKNOWN_PROTOCOL_EXCEPTION = new <init>("ENTITLEMENT_APP_UNKNOWN_PROTOCOL_EXCEPTION", 21);
        ENTITLEMENT_APP_ILLEGAL_STATE_EXCEPTION = new <init>("ENTITLEMENT_APP_ILLEGAL_STATE_EXCEPTION", 22);
        ENTITLEMENT_APP_XPATH_EXPRESSION_EXCEPTION = new <init>("ENTITLEMENT_APP_XPATH_EXPRESSION_EXCEPTION", 23);
        ENTITLEMENT_APP_XPATH_PARSER_CONFIGURATION_EXCEPTION = new <init>("ENTITLEMENT_APP_XPATH_PARSER_CONFIGURATION_EXCEPTION", 24);
        ENTITLEMENT_APP_SAX_EXCEPTION = new <init>("ENTITLEMENT_APP_SAX_EXCEPTION", 25);
        ENTITLEMENT_APP_SERVICE_IO_EXCEPTION = new <init>("ENTITLEMENT_APP_SERVICE_IO_EXCEPTION", 26);
        UPLYNK_INTERNAL_ERROR = new <init>("UPLYNK_INTERNAL_ERROR", 27);
        UPLYNK_WORKFLOW_ID_INVALID = new <init>("UPLYNK_WORKFLOW_ID_INVALID", 28);
        UPLYNK_WORKFLOW_ID_MISSING = new <init>("UPLYNK_WORKFLOW_ID_MISSING", 29);
        UPLYNK_INVALID_VIDEO_ID = new <init>("UPLYNK_INVALID_VIDEO_ID", 30);
        UPLYNK_INVALID_VIDEO_ID_MISSING = new <init>("UPLYNK_INVALID_VIDEO_ID_MISSING", 31);
        UPLYNK_INVALID_CONTENT_TYPE = new <init>("UPLYNK_INVALID_CONTENT_TYPE", 32);
        UPLYNK_MISSING_CONTENT_TYPE = new <init>("UPLYNK_MISSING_CONTENT_TYPE", 33);
        UPLYNK_ERROR_MISSING_ASSET = new <init>("UPLYNK_ERROR_MISSING_ASSET", 34);
        UPLYNK_ERROR_DIGITAL_SIGNATURE_CREATION_FAILED = new <init>("UPLYNK_ERROR_DIGITAL_SIGNATURE_CREATION_FAILED", 35);
        UPLYNK_ERROR_API_KEY_INVALID = new <init>("UPLYNK_ERROR_API_KEY_INVALID", 36);
        UPLYNK_ERROR_ACCOUNT_ID_INVALID = new <init>("UPLYNK_ERROR_ACCOUNT_ID_INVALID", 37);
        UPLYNK_ERROR_APPLICATION_KEY_INVALID = new <init>("UPLYNK_ERROR_APPLICATION_KEY_INVALID", 38);
        ADOBE_PASS_INTERNAL_ERROR = new <init>("ADOBE_PASS_INTERNAL_ERROR", 39);
        ADOBE_PASS_REQUESTOR_ID_MISSING = new <init>("ADOBE_PASS_REQUESTOR_ID_MISSING", 40);
        ADOBE_PASS_REQUESTOR_ID_INVALID = new <init>("ADOBE_PASS_REQUESTOR_ID_INVALID", 41);
        ADOBE_PASS_RESOURCE_ID_MISSING = new <init>("ADOBE_PASS_RESOURCE_ID_MISSING", 42);
        ADOBE_PASS_RESOURCE_ID_INVALID = new <init>("ADOBE_PASS_RESOURCE_ID_INVALID", 43);
        ADOBE_PASS_TOKEN_MISSING = new <init>("ADOBE_PASS_TOKEN_MISSING", 44);
        ADOBE_PASS_TOKEN_INVALID = new <init>("ADOBE_PASS_TOKEN_INVALID", 45);
        ADOBE_PASS_TOKEN_EXPIRED = new <init>("ADOBE_PASS_TOKEN_EXPIRED", 46);
        KALTURA_INTERNAL_ERROR = new <init>("KALTURA_INTERNAL_ERROR", 47);
        KALTURA_INVALID_PROXY = new <init>("KALTURA_INVALID_PROXY", 48);
        $VALUES = (new .VALUES[] {
            ENTITLEMENT_APP_ERROR, ENTITLEMENT_APP_ERROR_GEO_UNAVAILABLE, ENTITLEMENT_APP_ERROR_GEO_OUTSIDE_US, ENTITLEMENT_APP_ERROR_VIDEO_SERVICE_UNAVAILABLE, ENTITLEMENT_APP_ERROR_ACCESS_LEVEL_INVALID, ENTITLEMENT_APP_ERROR_ACCESS_MISSING_ASSET, ENTITLEMENT_APP_FATAL_ERROR, ENTITLEMENT_APP_MISSING_REQUIRED_FIELDS, ENTITLEMENT_APP_UNKNOWN_BRAND, ENTITLEMENT_APP_IPADDRESS_INVALID, 
            ENTITLEMENT_APP_GEO_INTERNAL_ERROR, ENTITLEMENT_APP_INVALID_PARAMETER_FIELDS, ENTITLEMENT_APP_EMPTY_VIDEO_RESPONSE, ENTITLEMENT_APP_ERROR_CHANNEL_SERVICE_UNAVAILABLE, ENTITLEMENT_APP_EMPTY_CHANNEL_RESPONSE, ENTITLEMENT_APP_UNSUPPORTED_CHANNEL_SERVICE, ENTITLEMENT_APP_EMPTY_GEO_RESPONSE, ENTITLEMENT_APP_ERROR_GEO_SERVICE_UNAVAILABLE, ENTITLEMENT_APP_ERROR_GEO_BLOCK, ENTITLEMENT_APP_ERROR_UNKNOWN_VP2_APIKEY, 
            ENTITLEMENT_APP_ERROR_UNKNOWN_TOKEN, ENTITLEMENT_APP_UNKNOWN_PROTOCOL_EXCEPTION, ENTITLEMENT_APP_ILLEGAL_STATE_EXCEPTION, ENTITLEMENT_APP_XPATH_EXPRESSION_EXCEPTION, ENTITLEMENT_APP_XPATH_PARSER_CONFIGURATION_EXCEPTION, ENTITLEMENT_APP_SAX_EXCEPTION, ENTITLEMENT_APP_SERVICE_IO_EXCEPTION, UPLYNK_INTERNAL_ERROR, UPLYNK_WORKFLOW_ID_INVALID, UPLYNK_WORKFLOW_ID_MISSING, 
            UPLYNK_INVALID_VIDEO_ID, UPLYNK_INVALID_VIDEO_ID_MISSING, UPLYNK_INVALID_CONTENT_TYPE, UPLYNK_MISSING_CONTENT_TYPE, UPLYNK_ERROR_MISSING_ASSET, UPLYNK_ERROR_DIGITAL_SIGNATURE_CREATION_FAILED, UPLYNK_ERROR_API_KEY_INVALID, UPLYNK_ERROR_ACCOUNT_ID_INVALID, UPLYNK_ERROR_APPLICATION_KEY_INVALID, ADOBE_PASS_INTERNAL_ERROR, 
            ADOBE_PASS_REQUESTOR_ID_MISSING, ADOBE_PASS_REQUESTOR_ID_INVALID, ADOBE_PASS_RESOURCE_ID_MISSING, ADOBE_PASS_RESOURCE_ID_INVALID, ADOBE_PASS_TOKEN_MISSING, ADOBE_PASS_TOKEN_INVALID, ADOBE_PASS_TOKEN_EXPIRED, KALTURA_INTERNAL_ERROR, KALTURA_INVALID_PROXY
        });
    }

    private (String s, int i)
    {
        super(s, i);
    }
}
