// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.espn.androidplayersdk.datamanager;


class Omniture
{

    String ch;
    String eVar11;
    String eVar16;
    String eVar17;
    String eVar19;
    String eVar2;
    String eVar20;
    String eVar21;
    String eVar29;
    String eVar3;
    String eVar30;
    String eVar31;
    String eVar32;
    String eVar33;
    String eVar34;
    String eVar37;
    String eVar39;
    String eVar45;
    String eVar47;
    String eVar52;
    String eVar53;
    String eVar54;
    String eVar55;
    String eVar56;
    String eVar57;
    String eVar58;
    String eVar59;
    String eVar60;
    String eVar61;
    String eVar62;
    String eVar63;
    String eVar64;
    String eVar65;
    String eVar66;
    String eVar67;
    String eVar68;
    String eVar71;
    String eVar9;
    String events;
    String linkID;
    String pe;
    String pev2;
    String products;
    String prop1;
    String prop17;
    String prop2;
    String prop25;
    String prop26;
    String prop28;
    String prop3;
    String prop35;
    String prop4;
    String prop42;
    String prop43;
    String prop45;
    String prop47;
    String prop48;
    String prop5;
    String prop51;
    String prop52;
    String prop53;
    String prop54;
    String prop55;
    String prop56;
    String prop57;
    String prop58;
    String prop59;
    String prop60;
    String prop61;
    String prop62;
    String prop63;
    String prop64;
    String prop65;
    String prop66;
    String prop67;
    String prop68;
    String prop71;
    String prop72;
    String prop73;
    String prop74;
    String prop75;
    String prop9;

    Omniture()
    {
        pe = null;
        pev2 = null;
        linkID = null;
        ch = null;
        events = null;
        products = null;
        prop1 = null;
        prop2 = null;
        prop3 = null;
        prop4 = null;
        prop5 = null;
        prop9 = null;
        prop17 = null;
        prop25 = null;
        prop26 = null;
        prop28 = null;
        prop35 = null;
        prop42 = null;
        prop43 = null;
        prop45 = null;
        prop47 = null;
        prop48 = null;
        prop51 = null;
        prop52 = null;
        prop53 = null;
        prop54 = null;
        prop55 = null;
        prop56 = null;
        prop57 = null;
        prop58 = null;
        prop59 = null;
        prop60 = null;
        prop61 = null;
        prop62 = null;
        prop63 = null;
        prop64 = null;
        prop65 = null;
        prop66 = null;
        prop67 = null;
        prop68 = null;
        prop71 = null;
        prop72 = null;
        prop73 = null;
        prop74 = null;
        prop75 = null;
        eVar2 = null;
        eVar3 = null;
        eVar9 = null;
        eVar11 = null;
        eVar16 = null;
        eVar20 = null;
        eVar17 = null;
        eVar19 = null;
        eVar21 = null;
        eVar29 = null;
        eVar30 = null;
        eVar31 = null;
        eVar32 = null;
        eVar33 = null;
        eVar34 = null;
        eVar37 = null;
        eVar39 = null;
        eVar45 = null;
        eVar47 = null;
        eVar52 = null;
        eVar53 = null;
        eVar54 = null;
        eVar55 = null;
        eVar56 = null;
        eVar57 = null;
        eVar58 = null;
        eVar59 = null;
        eVar60 = null;
        eVar61 = null;
        eVar62 = null;
        eVar63 = null;
        eVar64 = null;
        eVar65 = null;
        eVar66 = null;
        eVar67 = null;
        eVar68 = null;
        eVar71 = null;
    }
}
