// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package android.support.v7;


public final class android.support.v7.a
{
    public static final class a
    {

        public static final int abc_fade_in = 0x7f050000;
        public static final int abc_fade_out = 0x7f050001;
        public static final int abc_grow_fade_in_from_bottom = 0x7f050002;
        public static final int abc_popup_enter = 0x7f050003;
        public static final int abc_popup_exit = 0x7f050004;
        public static final int abc_shrink_fade_out_from_bottom = 0x7f050005;
        public static final int abc_slide_in_bottom = 0x7f050006;
        public static final int abc_slide_in_top = 0x7f050007;
        public static final int abc_slide_out_bottom = 0x7f050008;
        public static final int abc_slide_out_top = 0x7f050009;
        public static final int fab_in = 0x7f05000a;
        public static final int fab_out = 0x7f05000b;
        public static final int snackbar_in = 0x7f05000c;
        public static final int snackbar_out = 0x7f05000d;
    }

    public static final class b
    {

        public static final int actionBarDivider = 0x7f0100bc;
        public static final int actionBarItemBackground = 0x7f0100bd;
        public static final int actionBarPopupTheme = 0x7f0100b6;
        public static final int actionBarSize = 0x7f0100bb;
        public static final int actionBarSplitStyle = 0x7f0100b8;
        public static final int actionBarStyle = 0x7f0100b7;
        public static final int actionBarTabBarStyle = 0x7f0100b2;
        public static final int actionBarTabStyle = 0x7f0100b1;
        public static final int actionBarTabTextStyle = 0x7f0100b3;
        public static final int actionBarTheme = 0x7f0100b9;
        public static final int actionBarWidgetTheme = 0x7f0100ba;
        public static final int actionButtonStyle = 0x7f0100d6;
        public static final int actionDropDownStyle = 0x7f0100d2;
        public static final int actionLayout = 0x7f01006a;
        public static final int actionMenuTextAppearance = 0x7f0100be;
        public static final int actionMenuTextColor = 0x7f0100bf;
        public static final int actionModeBackground = 0x7f0100c2;
        public static final int actionModeCloseButtonStyle = 0x7f0100c1;
        public static final int actionModeCloseDrawable = 0x7f0100c4;
        public static final int actionModeCopyDrawable = 0x7f0100c6;
        public static final int actionModeCutDrawable = 0x7f0100c5;
        public static final int actionModeFindDrawable = 0x7f0100ca;
        public static final int actionModePasteDrawable = 0x7f0100c7;
        public static final int actionModePopupWindowStyle = 0x7f0100cc;
        public static final int actionModeSelectAllDrawable = 0x7f0100c8;
        public static final int actionModeShareDrawable = 0x7f0100c9;
        public static final int actionModeSplitBackground = 0x7f0100c3;
        public static final int actionModeStyle = 0x7f0100c0;
        public static final int actionModeWebSearchDrawable = 0x7f0100cb;
        public static final int actionOverflowButtonStyle = 0x7f0100b4;
        public static final int actionOverflowMenuStyle = 0x7f0100b5;
        public static final int actionProviderClass = 0x7f01006c;
        public static final int actionViewClass = 0x7f01006b;
        public static final int activityChooserViewStyle = 0x7f0100de;
        public static final int alertDialogButtonGroupStyle = 0x7f0100ff;
        public static final int alertDialogCenterButtons = 0x7f010100;
        public static final int alertDialogStyle = 0x7f0100fe;
        public static final int alertDialogTheme = 0x7f010101;
        public static final int autoCompleteTextViewStyle = 0x7f010106;
        public static final int background = 0x7f01000c;
        public static final int backgroundSplit = 0x7f01000e;
        public static final int backgroundStacked = 0x7f01000d;
        public static final int backgroundTint = 0x7f01011f;
        public static final int backgroundTintMode = 0x7f010120;
        public static final int barSize = 0x7f01004d;
        public static final int behavior_overlapTop = 0x7f01007a;
        public static final int borderWidth = 0x7f010052;
        public static final int borderlessButtonStyle = 0x7f0100db;
        public static final int buttonBarButtonStyle = 0x7f0100d8;
        public static final int buttonBarNegativeButtonStyle = 0x7f010104;
        public static final int buttonBarNeutralButtonStyle = 0x7f010105;
        public static final int buttonBarPositiveButtonStyle = 0x7f010103;
        public static final int buttonBarStyle = 0x7f0100d7;
        public static final int buttonPanelSideLayout = 0x7f010022;
        public static final int buttonStyle = 0x7f010107;
        public static final int buttonStyleSmall = 0x7f010108;
        public static final int checkboxStyle = 0x7f010109;
        public static final int checkedTextViewStyle = 0x7f01010a;
        public static final int closeIcon = 0x7f01007f;
        public static final int closeItemLayout = 0x7f01001c;
        public static final int collapseContentDescription = 0x7f010119;
        public static final int collapseIcon = 0x7f010118;
        public static final int collapsedTitleTextAppearance = 0x7f01003d;
        public static final int color = 0x7f010047;
        public static final int colorAccent = 0x7f0100f8;
        public static final int colorButtonNormal = 0x7f0100fc;
        public static final int colorControlActivated = 0x7f0100fa;
        public static final int colorControlHighlight = 0x7f0100fb;
        public static final int colorControlNormal = 0x7f0100f9;
        public static final int colorPrimary = 0x7f0100f6;
        public static final int colorPrimaryDark = 0x7f0100f7;
        public static final int colorSwitchThumbNormal = 0x7f0100fd;
        public static final int commitIcon = 0x7f010084;
        public static final int contentInsetEnd = 0x7f010017;
        public static final int contentInsetLeft = 0x7f010018;
        public static final int contentInsetRight = 0x7f010019;
        public static final int contentInsetStart = 0x7f010016;
        public static final int contentScrim = 0x7f01003e;
        public static final int customNavigationLayout = 0x7f01000f;
        public static final int defaultQueryHint = 0x7f01007e;
        public static final int dialogPreferredPadding = 0x7f0100d0;
        public static final int dialogTheme = 0x7f0100cf;
        public static final int disableChildrenWhenDisabled = 0x7f01008c;
        public static final int displayOptions = 0x7f010005;
        public static final int divider = 0x7f01000b;
        public static final int dividerHorizontal = 0x7f0100dd;
        public static final int dividerPadding = 0x7f010055;
        public static final int dividerVertical = 0x7f0100dc;
        public static final int drawableSize = 0x7f010049;
        public static final int drawerArrowStyle = 0x7f010000;
        public static final int dropDownListViewStyle = 0x7f0100ee;
        public static final int dropdownListPreferredItemHeight = 0x7f0100d3;
        public static final int editTextBackground = 0x7f0100e4;
        public static final int editTextColor = 0x7f0100e3;
        public static final int editTextStyle = 0x7f01010b;
        public static final int elevation = 0x7f01001a;
        public static final int errorEnabled = 0x7f0100a5;
        public static final int errorTextAppearance = 0x7f0100a6;
        public static final int expandActivityOverflowButtonDrawable = 0x7f01001e;
        public static final int expandedTitleMargin = 0x7f010037;
        public static final int expandedTitleMarginBottom = 0x7f01003b;
        public static final int expandedTitleMarginEnd = 0x7f01003a;
        public static final int expandedTitleMarginStart = 0x7f010038;
        public static final int expandedTitleMarginTop = 0x7f010039;
        public static final int expandedTitleTextAppearance = 0x7f01003c;
        public static final int fabSize = 0x7f010050;
        public static final int gapBetweenBars = 0x7f01004a;
        public static final int goIcon = 0x7f010080;
        public static final int headerLayout = 0x7f010072;
        public static final int height = 0x7f010001;
        public static final int hideOnContentScroll = 0x7f010015;
        public static final int hintTextAppearance = 0x7f0100a4;
        public static final int homeAsUpIndicator = 0x7f0100d5;
        public static final int homeLayout = 0x7f010010;
        public static final int icon = 0x7f010009;
        public static final int iconifiedByDefault = 0x7f01007c;
        public static final int indeterminateProgressStyle = 0x7f010012;
        public static final int initialActivityCount = 0x7f01001d;
        public static final int insetForeground = 0x7f010079;
        public static final int isLightTheme = 0x7f010002;
        public static final int itemBackground = 0x7f010071;
        public static final int itemIconTint = 0x7f01006f;
        public static final int itemPadding = 0x7f010014;
        public static final int itemTextColor = 0x7f010070;
        public static final int keylines = 0x7f010041;
        public static final int layout = 0x7f01007b;
        public static final int layout_anchor = 0x7f010044;
        public static final int layout_anchorGravity = 0x7f010046;
        public static final int layout_behavior = 0x7f010043;
        public static final int layout_collapseMode = 0x7f010035;
        public static final int layout_collapseParallaxMultiplier = 0x7f010036;
        public static final int layout_keyline = 0x7f010045;
        public static final int layout_scrollFlags = 0x7f010027;
        public static final int layout_scrollInterpolator = 0x7f010028;
        public static final int listChoiceBackgroundIndicator = 0x7f0100f5;
        public static final int listDividerAlertDialog = 0x7f0100d1;
        public static final int listItemLayout = 0x7f010026;
        public static final int listLayout = 0x7f010023;
        public static final int listPopupWindowStyle = 0x7f0100ef;
        public static final int listPreferredItemHeight = 0x7f0100e9;
        public static final int listPreferredItemHeightLarge = 0x7f0100eb;
        public static final int listPreferredItemHeightSmall = 0x7f0100ea;
        public static final int listPreferredItemPaddingLeft = 0x7f0100ec;
        public static final int listPreferredItemPaddingRight = 0x7f0100ed;
        public static final int logo = 0x7f01000a;
        public static final int maxActionInlineWidth = 0x7f010088;
        public static final int maxButtonHeight = 0x7f010117;
        public static final int measureWithLargestChild = 0x7f010053;
        public static final int menu = 0x7f01006e;
        public static final int middleBarArrowSize = 0x7f01004c;
        public static final int multiChoiceItemLayout = 0x7f010024;
        public static final int navigationContentDescription = 0x7f01011b;
        public static final int navigationIcon = 0x7f01011a;
        public static final int navigationMode = 0x7f010004;
        public static final int overlapAnchor = 0x7f010073;
        public static final int paddingEnd = 0x7f01011d;
        public static final int paddingStart = 0x7f01011c;
        public static final int panelBackground = 0x7f0100f2;
        public static final int panelMenuListTheme = 0x7f0100f4;
        public static final int panelMenuListWidth = 0x7f0100f3;
        public static final int popupMenuStyle = 0x7f0100e1;
        public static final int popupPromptView = 0x7f01008b;
        public static final int popupTheme = 0x7f01001b;
        public static final int popupWindowStyle = 0x7f0100e2;
        public static final int preserveIconSpacing = 0x7f01006d;
        public static final int pressedTranslationZ = 0x7f010051;
        public static final int progressBarPadding = 0x7f010013;
        public static final int progressBarStyle = 0x7f010011;
        public static final int prompt = 0x7f010089;
        public static final int queryBackground = 0x7f010086;
        public static final int queryHint = 0x7f01007d;
        public static final int radioButtonStyle = 0x7f01010c;
        public static final int ratingBarStyle = 0x7f01010d;
        public static final int rippleColor = 0x7f01004f;
        public static final int searchHintIcon = 0x7f010082;
        public static final int searchIcon = 0x7f010081;
        public static final int searchViewStyle = 0x7f0100e8;
        public static final int selectableItemBackground = 0x7f0100d9;
        public static final int selectableItemBackgroundBorderless = 0x7f0100da;
        public static final int showAsAction = 0x7f010069;
        public static final int showDividers = 0x7f010054;
        public static final int showText = 0x7f010093;
        public static final int singleChoiceItemLayout = 0x7f010025;
        public static final int spinBars = 0x7f010048;
        public static final int spinnerDropDownItemStyle = 0x7f0100d4;
        public static final int spinnerMode = 0x7f01008a;
        public static final int spinnerStyle = 0x7f01010e;
        public static final int splitTrack = 0x7f010092;
        public static final int state_above_anchor = 0x7f010074;
        public static final int statusBarBackground = 0x7f010042;
        public static final int statusBarScrim = 0x7f01003f;
        public static final int submitBackground = 0x7f010087;
        public static final int subtitle = 0x7f010006;
        public static final int subtitleTextAppearance = 0x7f010111;
        public static final int subtitleTextStyle = 0x7f010008;
        public static final int suggestionRowLayout = 0x7f010085;
        public static final int switchMinWidth = 0x7f010090;
        public static final int switchPadding = 0x7f010091;
        public static final int switchStyle = 0x7f01010f;
        public static final int switchTextAppearance = 0x7f01008f;
        public static final int tabBackground = 0x7f010097;
        public static final int tabContentStart = 0x7f010096;
        public static final int tabGravity = 0x7f010099;
        public static final int tabIndicatorColor = 0x7f010094;
        public static final int tabIndicatorHeight = 0x7f010095;
        public static final int tabMaxWidth = 0x7f01009b;
        public static final int tabMinWidth = 0x7f01009a;
        public static final int tabMode = 0x7f010098;
        public static final int tabPadding = 0x7f0100a3;
        public static final int tabPaddingBottom = 0x7f0100a2;
        public static final int tabPaddingEnd = 0x7f0100a1;
        public static final int tabPaddingStart = 0x7f01009f;
        public static final int tabPaddingTop = 0x7f0100a0;
        public static final int tabSelectedTextColor = 0x7f01009e;
        public static final int tabTextAppearance = 0x7f01009c;
        public static final int tabTextColor = 0x7f01009d;
        public static final int textAllCaps = 0x7f010029;
        public static final int textAppearanceLargePopupMenu = 0x7f0100cd;
        public static final int textAppearanceListItem = 0x7f0100f0;
        public static final int textAppearanceListItemSmall = 0x7f0100f1;
        public static final int textAppearanceSearchResultSubtitle = 0x7f0100e6;
        public static final int textAppearanceSearchResultTitle = 0x7f0100e5;
        public static final int textAppearanceSmallPopupMenu = 0x7f0100ce;
        public static final int textColorAlertDialogListItem = 0x7f010102;
        public static final int textColorSearchUrl = 0x7f0100e7;
        public static final int theme = 0x7f01011e;
        public static final int thickness = 0x7f01004e;
        public static final int thumbTextPadding = 0x7f01008e;
        public static final int title = 0x7f010003;
        public static final int titleMarginBottom = 0x7f010116;
        public static final int titleMarginEnd = 0x7f010114;
        public static final int titleMarginStart = 0x7f010113;
        public static final int titleMarginTop = 0x7f010115;
        public static final int titleMargins = 0x7f010112;
        public static final int titleTextAppearance = 0x7f010110;
        public static final int titleTextStyle = 0x7f010007;
        public static final int toolbarId = 0x7f010040;
        public static final int toolbarNavigationButtonStyle = 0x7f0100e0;
        public static final int toolbarStyle = 0x7f0100df;
        public static final int topBottomBarArrowSize = 0x7f01004b;
        public static final int track = 0x7f01008d;
        public static final int voiceIcon = 0x7f010083;
        public static final int windowActionBar = 0x7f0100a7;
        public static final int windowActionBarOverlay = 0x7f0100a9;
        public static final int windowActionModeOverlay = 0x7f0100aa;
        public static final int windowFixedHeightMajor = 0x7f0100ae;
        public static final int windowFixedHeightMinor = 0x7f0100ac;
        public static final int windowFixedWidthMajor = 0x7f0100ab;
        public static final int windowFixedWidthMinor = 0x7f0100ad;
        public static final int windowMinWidthMajor = 0x7f0100af;
        public static final int windowMinWidthMinor = 0x7f0100b0;
        public static final int windowNoTitle = 0x7f0100a8;
    }

    public static final class c
    {

        public static final int abc_action_bar_content_inset_material = 0x7f0a000d;
        public static final int abc_action_bar_default_height_material = 0x7f0a0002;
        public static final int abc_action_bar_default_padding_material = 0x7f0a0003;
        public static final int abc_action_bar_icon_vertical_padding_material = 0x7f0a001c;
        public static final int abc_action_bar_navigation_padding_start_material = 0x7f0a000e;
        public static final int abc_action_bar_overflow_padding_end_material = 0x7f0a000f;
        public static final int abc_action_bar_overflow_padding_start_material = 0x7f0a001d;
        public static final int abc_action_bar_progress_bar_size = 0x7f0a0004;
        public static final int abc_action_bar_stacked_max_height = 0x7f0a001e;
        public static final int abc_action_bar_stacked_tab_max_width = 0x7f0a001f;
        public static final int abc_action_bar_subtitle_bottom_margin_material = 0x7f0a0020;
        public static final int abc_action_bar_subtitle_top_margin_material = 0x7f0a0021;
        public static final int abc_action_button_min_height_material = 0x7f0a0022;
        public static final int abc_action_button_min_width_material = 0x7f0a0023;
        public static final int abc_action_button_min_width_overflow_material = 0x7f0a0024;
        public static final int abc_alert_dialog_button_bar_height = 0x7f0a0000;
        public static final int abc_button_inset_horizontal_material = 0x7f0a0025;
        public static final int abc_button_inset_vertical_material = 0x7f0a0026;
        public static final int abc_button_padding_horizontal_material = 0x7f0a0027;
        public static final int abc_button_padding_vertical_material = 0x7f0a0028;
        public static final int abc_config_prefDialogWidth = 0x7f0a0007;
        public static final int abc_control_corner_material = 0x7f0a0029;
        public static final int abc_control_inset_material = 0x7f0a002a;
        public static final int abc_control_padding_material = 0x7f0a002b;
        public static final int abc_dialog_list_padding_vertical_material = 0x7f0a002c;
        public static final int abc_dialog_min_width_major = 0x7f0a002d;
        public static final int abc_dialog_min_width_minor = 0x7f0a002e;
        public static final int abc_dialog_padding_material = 0x7f0a002f;
        public static final int abc_dialog_padding_top_material = 0x7f0a0030;
        public static final int abc_disabled_alpha_material_dark = 0x7f0a0031;
        public static final int abc_disabled_alpha_material_light = 0x7f0a0032;
        public static final int abc_dropdownitem_icon_width = 0x7f0a0033;
        public static final int abc_dropdownitem_text_padding_left = 0x7f0a0034;
        public static final int abc_dropdownitem_text_padding_right = 0x7f0a0035;
        public static final int abc_edit_text_inset_bottom_material = 0x7f0a0036;
        public static final int abc_edit_text_inset_horizontal_material = 0x7f0a0037;
        public static final int abc_edit_text_inset_top_material = 0x7f0a0038;
        public static final int abc_floating_window_z = 0x7f0a0039;
        public static final int abc_list_item_padding_horizontal_material = 0x7f0a003a;
        public static final int abc_panel_menu_list_width = 0x7f0a003b;
        public static final int abc_search_view_preferred_width = 0x7f0a003c;
        public static final int abc_search_view_text_min_width = 0x7f0a0008;
        public static final int abc_switch_padding = 0x7f0a0017;
        public static final int abc_text_size_body_1_material = 0x7f0a003d;
        public static final int abc_text_size_body_2_material = 0x7f0a003e;
        public static final int abc_text_size_button_material = 0x7f0a003f;
        public static final int abc_text_size_caption_material = 0x7f0a0040;
        public static final int abc_text_size_display_1_material = 0x7f0a0041;
        public static final int abc_text_size_display_2_material = 0x7f0a0042;
        public static final int abc_text_size_display_3_material = 0x7f0a0043;
        public static final int abc_text_size_display_4_material = 0x7f0a0044;
        public static final int abc_text_size_headline_material = 0x7f0a0045;
        public static final int abc_text_size_large_material = 0x7f0a0046;
        public static final int abc_text_size_medium_material = 0x7f0a0047;
        public static final int abc_text_size_menu_material = 0x7f0a0048;
        public static final int abc_text_size_small_material = 0x7f0a0049;
        public static final int abc_text_size_subhead_material = 0x7f0a004a;
        public static final int abc_text_size_subtitle_material_toolbar = 0x7f0a0005;
        public static final int abc_text_size_title_material = 0x7f0a004b;
        public static final int abc_text_size_title_material_toolbar = 0x7f0a0006;
        public static final int appbar_elevation = 0x7f0a004d;
        public static final int dialog_fixed_height_major = 0x7f0a0009;
        public static final int dialog_fixed_height_minor = 0x7f0a000a;
        public static final int dialog_fixed_width_major = 0x7f0a000b;
        public static final int dialog_fixed_width_minor = 0x7f0a000c;
        public static final int disabled_alpha_material_dark = 0x7f0a006e;
        public static final int disabled_alpha_material_light = 0x7f0a006f;
        public static final int fab_border_width = 0x7f0a0070;
        public static final int fab_content_size = 0x7f0a0071;
        public static final int fab_elevation = 0x7f0a0072;
        public static final int fab_size_mini = 0x7f0a0073;
        public static final int fab_size_normal = 0x7f0a0074;
        public static final int fab_translation_z_pressed = 0x7f0a0075;
        public static final int navigation_elevation = 0x7f0a0087;
        public static final int navigation_icon_padding = 0x7f0a0088;
        public static final int navigation_icon_size = 0x7f0a0089;
        public static final int navigation_max_width = 0x7f0a008a;
        public static final int navigation_padding_bottom = 0x7f0a008b;
        public static final int navigation_padding_top_default = 0x7f0a0018;
        public static final int navigation_separator_vertical_padding = 0x7f0a008c;
        public static final int notification_large_icon_height = 0x7f0a0090;
        public static final int notification_large_icon_width = 0x7f0a0091;
        public static final int notification_subtext_size = 0x7f0a0092;
        public static final int snackbar_action_inline_max_width = 0x7f0a0010;
        public static final int snackbar_background_corner_radius = 0x7f0a0011;
        public static final int snackbar_elevation = 0x7f0a00a9;
        public static final int snackbar_extra_spacing_horizontal = 0x7f0a0012;
        public static final int snackbar_max_width = 0x7f0a0013;
        public static final int snackbar_min_width = 0x7f0a0014;
        public static final int snackbar_padding_horizontal = 0x7f0a00aa;
        public static final int snackbar_padding_vertical = 0x7f0a00ab;
        public static final int snackbar_padding_vertical_2lines = 0x7f0a0015;
        public static final int snackbar_text_size = 0x7f0a00ac;
        public static final int tab_max_width = 0x7f0a00b1;
        public static final int tab_min_width = 0x7f0a0016;
    }

    public static final class d
    {

        public static final int action0 = 0x7f100142;
        public static final int action_bar = 0x7f10006a;
        public static final int action_bar_activity_content = 0x7f100000;
        public static final int action_bar_container = 0x7f100069;
        public static final int action_bar_root = 0x7f100065;
        public static final int action_bar_spinner = 0x7f100001;
        public static final int action_bar_subtitle = 0x7f10004e;
        public static final int action_bar_title = 0x7f10004d;
        public static final int action_context_bar = 0x7f10006b;
        public static final int action_divider = 0x7f100146;
        public static final int action_menu_divider = 0x7f100002;
        public static final int action_menu_presenter = 0x7f100003;
        public static final int action_mode_bar = 0x7f100067;
        public static final int action_mode_bar_stub = 0x7f100066;
        public static final int action_mode_close_button = 0x7f10004f;
        public static final int activity_chooser_view_content = 0x7f100050;
        public static final int alertTitle = 0x7f10005a;
        public static final int always = 0x7f100032;
        public static final int beginning = 0x7f10002b;
        public static final int bottom = 0x7f10001c;
        public static final int buttonPanel = 0x7f100060;
        public static final int cancel_action = 0x7f100143;
        public static final int center = 0x7f10001d;
        public static final int center_horizontal = 0x7f10001e;
        public static final int center_vertical = 0x7f10001f;
        public static final int checkbox = 0x7f100062;
        public static final int chronometer = 0x7f100149;
        public static final int clip_horizontal = 0x7f100020;
        public static final int clip_vertical = 0x7f100021;
        public static final int collapseActionView = 0x7f100033;
        public static final int contentPanel = 0x7f10005b;
        public static final int custom = 0x7f10005f;
        public static final int customPanel = 0x7f10005e;
        public static final int decor_content_parent = 0x7f100068;
        public static final int default_activity_button = 0x7f100053;
        public static final int dialog = 0x7f100037;
        public static final int disableHome = 0x7f10000f;
        public static final int dropdown = 0x7f100038;
        public static final int edit_query = 0x7f10006c;
        public static final int end = 0x7f100022;
        public static final int end_padder = 0x7f10014d;
        public static final int enterAlways = 0x7f100016;
        public static final int enterAlwaysCollapsed = 0x7f100017;
        public static final int exitUntilCollapsed = 0x7f100018;
        public static final int expand_activities_button = 0x7f100051;
        public static final int expanded_menu = 0x7f100061;
        public static final int fill = 0x7f100023;
        public static final int fill_horizontal = 0x7f100024;
        public static final int fill_vertical = 0x7f100025;
        public static final int fixed = 0x7f100039;
        public static final int home = 0x7f100004;
        public static final int homeAsUp = 0x7f100010;
        public static final int icon = 0x7f100055;
        public static final int ifRoom = 0x7f100034;
        public static final int image = 0x7f100052;
        public static final int info = 0x7f10014c;
        public static final int left = 0x7f100026;
        public static final int line1 = 0x7f100147;
        public static final int line3 = 0x7f10014b;
        public static final int listMode = 0x7f10000c;
        public static final int list_item = 0x7f100054;
        public static final int media_actions = 0x7f100145;
        public static final int middle = 0x7f10002c;
        public static final int mini = 0x7f10002a;
        public static final int multiply = 0x7f10003c;
        public static final int never = 0x7f100035;
        public static final int none = 0x7f100011;
        public static final int normal = 0x7f10000d;
        public static final int parallax = 0x7f10001a;
        public static final int parentPanel = 0x7f100057;
        public static final int pin = 0x7f10001b;
        public static final int progress_circular = 0x7f100006;
        public static final int progress_horizontal = 0x7f100007;
        public static final int radio = 0x7f100064;
        public static final int right = 0x7f100027;
        public static final int screen = 0x7f10003d;
        public static final int scroll = 0x7f100019;
        public static final int scrollView = 0x7f10005c;
        public static final int scrollable = 0x7f10003a;
        public static final int search_badge = 0x7f10006e;
        public static final int search_bar = 0x7f10006d;
        public static final int search_button = 0x7f10006f;
        public static final int search_close_btn = 0x7f100074;
        public static final int search_edit_frame = 0x7f100070;
        public static final int search_go_btn = 0x7f100076;
        public static final int search_mag_icon = 0x7f100071;
        public static final int search_plate = 0x7f100072;
        public static final int search_src_text = 0x7f100073;
        public static final int search_voice_btn = 0x7f100077;
        public static final int select_dialog_listview = 0x7f100078;
        public static final int shortcut = 0x7f100063;
        public static final int showCustom = 0x7f100012;
        public static final int showHome = 0x7f100013;
        public static final int showTitle = 0x7f100014;
        public static final int snackbar_action = 0x7f100119;
        public static final int snackbar_text = 0x7f100118;
        public static final int split_action_bar = 0x7f100008;
        public static final int src_atop = 0x7f10003e;
        public static final int src_in = 0x7f10003f;
        public static final int src_over = 0x7f100040;
        public static final int start = 0x7f100028;
        public static final int status_bar_latest_event_content = 0x7f100144;
        public static final int submit_area = 0x7f100075;
        public static final int tabMode = 0x7f10000e;
        public static final int text = 0x7f100009;
        public static final int text2 = 0x7f10014a;
        public static final int textSpacerNoButtons = 0x7f10005d;
        public static final int time = 0x7f100148;
        public static final int title = 0x7f100056;
        public static final int title_template = 0x7f100059;
        public static final int top = 0x7f100029;
        public static final int topPanel = 0x7f100058;
        public static final int up = 0x7f10000a;
        public static final int useLogo = 0x7f100015;
        public static final int view_offset_helper = 0x7f10000b;
        public static final int withText = 0x7f100036;
        public static final int wrap_content = 0x7f10003b;
    }

    public static final class e
    {

        public static final int abc_action_bar_title_item = 0x7f040000;
        public static final int abc_action_bar_up_container = 0x7f040001;
        public static final int abc_action_bar_view_list_nav_layout = 0x7f040002;
        public static final int abc_action_menu_item_layout = 0x7f040003;
        public static final int abc_action_menu_layout = 0x7f040004;
        public static final int abc_action_mode_bar = 0x7f040005;
        public static final int abc_action_mode_close_item_material = 0x7f040006;
        public static final int abc_activity_chooser_view = 0x7f040007;
        public static final int abc_activity_chooser_view_list_item = 0x7f040008;
        public static final int abc_alert_dialog_material = 0x7f040009;
        public static final int abc_dialog_title_material = 0x7f04000a;
        public static final int abc_expanded_menu_layout = 0x7f04000b;
        public static final int abc_list_menu_item_checkbox = 0x7f04000c;
        public static final int abc_list_menu_item_icon = 0x7f04000d;
        public static final int abc_list_menu_item_layout = 0x7f04000e;
        public static final int abc_list_menu_item_radio = 0x7f04000f;
        public static final int abc_popup_menu_item_layout = 0x7f040010;
        public static final int abc_screen_content_include = 0x7f040011;
        public static final int abc_screen_simple = 0x7f040012;
        public static final int abc_screen_simple_overlay_action_mode = 0x7f040013;
        public static final int abc_screen_toolbar = 0x7f040014;
        public static final int abc_search_dropdown_item_icons_2line = 0x7f040015;
        public static final int abc_search_view = 0x7f040016;
        public static final int abc_select_dialog_material = 0x7f040017;
        public static final int abc_simple_dropdown_hint = 0x7f040018;
        public static final int design_navigation_item = 0x7f040032;
        public static final int design_navigation_item_header = 0x7f040033;
        public static final int design_navigation_item_separator = 0x7f040034;
        public static final int design_navigation_item_subheader = 0x7f040035;
        public static final int design_navigation_menu = 0x7f040036;
        public static final int layout_snackbar = 0x7f040044;
        public static final int layout_snackbar_include = 0x7f040045;
        public static final int notification_media_action = 0x7f04005a;
        public static final int notification_media_cancel_action = 0x7f04005b;
        public static final int notification_template_big_media = 0x7f04005c;
        public static final int notification_template_big_media_narrow = 0x7f04005d;
        public static final int notification_template_lines = 0x7f04005e;
        public static final int notification_template_media = 0x7f04005f;
        public static final int notification_template_part_chronometer = 0x7f040060;
        public static final int notification_template_part_time = 0x7f040061;
        public static final int select_dialog_item_material = 0x7f04006e;
        public static final int select_dialog_multichoice_material = 0x7f04006f;
        public static final int select_dialog_singlechoice_material = 0x7f040070;
        public static final int support_simple_spinner_dropdown_item = 0x7f040076;
    }

    public static final class f
    {

        public static final int AlertDialog_AppCompat = 0x7f0b0087;
        public static final int AlertDialog_AppCompat_Light = 0x7f0b0088;
        public static final int Animation_AppCompat_Dialog = 0x7f0b0089;
        public static final int Animation_AppCompat_DropDownUp = 0x7f0b008a;
        public static final int Base_AlertDialog_AppCompat = 0x7f0b008f;
        public static final int Base_AlertDialog_AppCompat_Light = 0x7f0b0090;
        public static final int Base_Animation_AppCompat_Dialog = 0x7f0b0091;
        public static final int Base_Animation_AppCompat_DropDownUp = 0x7f0b0092;
        public static final int Base_DialogWindowTitleBackground_AppCompat = 0x7f0b0094;
        public static final int Base_DialogWindowTitle_AppCompat = 0x7f0b0093;
        public static final int Base_TextAppearance_AppCompat = 0x7f0b003f;
        public static final int Base_TextAppearance_AppCompat_Body1 = 0x7f0b0040;
        public static final int Base_TextAppearance_AppCompat_Body2 = 0x7f0b0041;
        public static final int Base_TextAppearance_AppCompat_Button = 0x7f0b001a;
        public static final int Base_TextAppearance_AppCompat_Caption = 0x7f0b0042;
        public static final int Base_TextAppearance_AppCompat_Display1 = 0x7f0b0043;
        public static final int Base_TextAppearance_AppCompat_Display2 = 0x7f0b0044;
        public static final int Base_TextAppearance_AppCompat_Display3 = 0x7f0b0045;
        public static final int Base_TextAppearance_AppCompat_Display4 = 0x7f0b0046;
        public static final int Base_TextAppearance_AppCompat_Headline = 0x7f0b0047;
        public static final int Base_TextAppearance_AppCompat_Inverse = 0x7f0b0004;
        public static final int Base_TextAppearance_AppCompat_Large = 0x7f0b0048;
        public static final int Base_TextAppearance_AppCompat_Large_Inverse = 0x7f0b0005;
        public static final int Base_TextAppearance_AppCompat_Light_Widget_PopupMenu_Large = 0x7f0b0049;
        public static final int Base_TextAppearance_AppCompat_Light_Widget_PopupMenu_Small = 0x7f0b004a;
        public static final int Base_TextAppearance_AppCompat_Medium = 0x7f0b004b;
        public static final int Base_TextAppearance_AppCompat_Medium_Inverse = 0x7f0b0006;
        public static final int Base_TextAppearance_AppCompat_Menu = 0x7f0b004c;
        public static final int Base_TextAppearance_AppCompat_SearchResult = 0x7f0b0095;
        public static final int Base_TextAppearance_AppCompat_SearchResult_Subtitle = 0x7f0b004d;
        public static final int Base_TextAppearance_AppCompat_SearchResult_Title = 0x7f0b004e;
        public static final int Base_TextAppearance_AppCompat_Small = 0x7f0b004f;
        public static final int Base_TextAppearance_AppCompat_Small_Inverse = 0x7f0b0007;
        public static final int Base_TextAppearance_AppCompat_Subhead = 0x7f0b0050;
        public static final int Base_TextAppearance_AppCompat_Subhead_Inverse = 0x7f0b0008;
        public static final int Base_TextAppearance_AppCompat_Title = 0x7f0b0051;
        public static final int Base_TextAppearance_AppCompat_Title_Inverse = 0x7f0b0009;
        public static final int Base_TextAppearance_AppCompat_Widget_ActionBar_Menu = 0x7f0b0052;
        public static final int Base_TextAppearance_AppCompat_Widget_ActionBar_Subtitle = 0x7f0b0053;
        public static final int Base_TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse = 0x7f0b0054;
        public static final int Base_TextAppearance_AppCompat_Widget_ActionBar_Title = 0x7f0b0055;
        public static final int Base_TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse = 0x7f0b0056;
        public static final int Base_TextAppearance_AppCompat_Widget_ActionMode_Subtitle = 0x7f0b0057;
        public static final int Base_TextAppearance_AppCompat_Widget_ActionMode_Title = 0x7f0b0058;
        public static final int Base_TextAppearance_AppCompat_Widget_DropDownItem = 0x7f0b0096;
        public static final int Base_TextAppearance_AppCompat_Widget_PopupMenu_Large = 0x7f0b0059;
        public static final int Base_TextAppearance_AppCompat_Widget_PopupMenu_Small = 0x7f0b005a;
        public static final int Base_TextAppearance_AppCompat_Widget_Switch = 0x7f0b005b;
        public static final int Base_TextAppearance_AppCompat_Widget_TextView_SpinnerItem = 0x7f0b005c;
        public static final int Base_TextAppearance_Widget_AppCompat_ExpandedMenu_Item = 0x7f0b0097;
        public static final int Base_TextAppearance_Widget_AppCompat_Toolbar_Subtitle = 0x7f0b005d;
        public static final int Base_TextAppearance_Widget_AppCompat_Toolbar_Title = 0x7f0b005e;
        public static final int Base_ThemeOverlay_AppCompat = 0x7f0b00a0;
        public static final int Base_ThemeOverlay_AppCompat_ActionBar = 0x7f0b00a1;
        public static final int Base_ThemeOverlay_AppCompat_Dark = 0x7f0b00a2;
        public static final int Base_ThemeOverlay_AppCompat_Dark_ActionBar = 0x7f0b00a3;
        public static final int Base_ThemeOverlay_AppCompat_Light = 0x7f0b00a4;
        public static final int Base_Theme_AppCompat = 0x7f0b005f;
        public static final int Base_Theme_AppCompat_CompactMenu = 0x7f0b0098;
        public static final int Base_Theme_AppCompat_Dialog = 0x7f0b000a;
        public static final int Base_Theme_AppCompat_DialogWhenLarge = 0x7f0b0002;
        public static final int Base_Theme_AppCompat_Dialog_Alert = 0x7f0b0099;
        public static final int Base_Theme_AppCompat_Dialog_FixedSize = 0x7f0b009a;
        public static final int Base_Theme_AppCompat_Dialog_MinWidth = 0x7f0b009b;
        public static final int Base_Theme_AppCompat_Light = 0x7f0b0060;
        public static final int Base_Theme_AppCompat_Light_DarkActionBar = 0x7f0b009c;
        public static final int Base_Theme_AppCompat_Light_Dialog = 0x7f0b000b;
        public static final int Base_Theme_AppCompat_Light_DialogWhenLarge = 0x7f0b0003;
        public static final int Base_Theme_AppCompat_Light_Dialog_Alert = 0x7f0b009d;
        public static final int Base_Theme_AppCompat_Light_Dialog_FixedSize = 0x7f0b009e;
        public static final int Base_Theme_AppCompat_Light_Dialog_MinWidth = 0x7f0b009f;
        public static final int Base_V11_Theme_AppCompat_Dialog = 0x7f0b000c;
        public static final int Base_V11_Theme_AppCompat_Light_Dialog = 0x7f0b000d;
        public static final int Base_V12_Widget_AppCompat_AutoCompleteTextView = 0x7f0b0015;
        public static final int Base_V12_Widget_AppCompat_EditText = 0x7f0b0016;
        public static final int Base_V21_Theme_AppCompat = 0x7f0b0061;
        public static final int Base_V21_Theme_AppCompat_Dialog = 0x7f0b0062;
        public static final int Base_V21_Theme_AppCompat_Light = 0x7f0b0063;
        public static final int Base_V21_Theme_AppCompat_Light_Dialog = 0x7f0b0064;
        public static final int Base_V7_Theme_AppCompat = 0x7f0b00a5;
        public static final int Base_V7_Theme_AppCompat_Dialog = 0x7f0b00a6;
        public static final int Base_V7_Theme_AppCompat_Light = 0x7f0b00a7;
        public static final int Base_V7_Theme_AppCompat_Light_Dialog = 0x7f0b00a8;
        public static final int Base_V7_Widget_AppCompat_AutoCompleteTextView = 0x7f0b00a9;
        public static final int Base_V7_Widget_AppCompat_EditText = 0x7f0b00aa;
        public static final int Base_Widget_AppCompat_ActionBar = 0x7f0b00ab;
        public static final int Base_Widget_AppCompat_ActionBar_Solid = 0x7f0b00ac;
        public static final int Base_Widget_AppCompat_ActionBar_TabBar = 0x7f0b00ad;
        public static final int Base_Widget_AppCompat_ActionBar_TabText = 0x7f0b0065;
        public static final int Base_Widget_AppCompat_ActionBar_TabView = 0x7f0b0066;
        public static final int Base_Widget_AppCompat_ActionButton = 0x7f0b0067;
        public static final int Base_Widget_AppCompat_ActionButton_CloseMode = 0x7f0b0068;
        public static final int Base_Widget_AppCompat_ActionButton_Overflow = 0x7f0b0069;
        public static final int Base_Widget_AppCompat_ActionMode = 0x7f0b00ae;
        public static final int Base_Widget_AppCompat_ActivityChooserView = 0x7f0b00af;
        public static final int Base_Widget_AppCompat_AutoCompleteTextView = 0x7f0b0017;
        public static final int Base_Widget_AppCompat_Button = 0x7f0b006a;
        public static final int Base_Widget_AppCompat_ButtonBar = 0x7f0b006e;
        public static final int Base_Widget_AppCompat_ButtonBar_AlertDialog = 0x7f0b00b1;
        public static final int Base_Widget_AppCompat_Button_Borderless = 0x7f0b006b;
        public static final int Base_Widget_AppCompat_Button_Borderless_Colored = 0x7f0b006c;
        public static final int Base_Widget_AppCompat_Button_ButtonBar_AlertDialog = 0x7f0b00b0;
        public static final int Base_Widget_AppCompat_Button_Small = 0x7f0b006d;
        public static final int Base_Widget_AppCompat_CompoundButton_CheckBox = 0x7f0b006f;
        public static final int Base_Widget_AppCompat_CompoundButton_RadioButton = 0x7f0b0070;
        public static final int Base_Widget_AppCompat_CompoundButton_Switch = 0x7f0b00b2;
        public static final int Base_Widget_AppCompat_DrawerArrowToggle = 0x7f0b0000;
        public static final int Base_Widget_AppCompat_DrawerArrowToggle_Common = 0x7f0b00b3;
        public static final int Base_Widget_AppCompat_DropDownItem_Spinner = 0x7f0b0071;
        public static final int Base_Widget_AppCompat_EditText = 0x7f0b0018;
        public static final int Base_Widget_AppCompat_Light_ActionBar = 0x7f0b00b4;
        public static final int Base_Widget_AppCompat_Light_ActionBar_Solid = 0x7f0b00b5;
        public static final int Base_Widget_AppCompat_Light_ActionBar_TabBar = 0x7f0b00b6;
        public static final int Base_Widget_AppCompat_Light_ActionBar_TabText = 0x7f0b0072;
        public static final int Base_Widget_AppCompat_Light_ActionBar_TabText_Inverse = 0x7f0b0073;
        public static final int Base_Widget_AppCompat_Light_ActionBar_TabView = 0x7f0b0074;
        public static final int Base_Widget_AppCompat_Light_PopupMenu = 0x7f0b0075;
        public static final int Base_Widget_AppCompat_Light_PopupMenu_Overflow = 0x7f0b0076;
        public static final int Base_Widget_AppCompat_ListPopupWindow = 0x7f0b0077;
        public static final int Base_Widget_AppCompat_ListView = 0x7f0b0078;
        public static final int Base_Widget_AppCompat_ListView_DropDown = 0x7f0b0079;
        public static final int Base_Widget_AppCompat_ListView_Menu = 0x7f0b007a;
        public static final int Base_Widget_AppCompat_PopupMenu = 0x7f0b007b;
        public static final int Base_Widget_AppCompat_PopupMenu_Overflow = 0x7f0b007c;
        public static final int Base_Widget_AppCompat_PopupWindow = 0x7f0b00b7;
        public static final int Base_Widget_AppCompat_ProgressBar = 0x7f0b000e;
        public static final int Base_Widget_AppCompat_ProgressBar_Horizontal = 0x7f0b000f;
        public static final int Base_Widget_AppCompat_RatingBar = 0x7f0b007d;
        public static final int Base_Widget_AppCompat_SearchView = 0x7f0b00b8;
        public static final int Base_Widget_AppCompat_SearchView_ActionBar = 0x7f0b00b9;
        public static final int Base_Widget_AppCompat_Spinner = 0x7f0b0010;
        public static final int Base_Widget_AppCompat_Spinner_DropDown_ActionBar = 0x7f0b007e;
        public static final int Base_Widget_AppCompat_Spinner_Underlined = 0x7f0b007f;
        public static final int Base_Widget_AppCompat_TextView_SpinnerItem = 0x7f0b0080;
        public static final int Base_Widget_AppCompat_Toolbar = 0x7f0b00ba;
        public static final int Base_Widget_AppCompat_Toolbar_Button_Navigation = 0x7f0b0081;
        public static final int Base_Widget_Design_TabLayout = 0x7f0b00bb;
        public static final int Platform_AppCompat = 0x7f0b0011;
        public static final int Platform_AppCompat_Light = 0x7f0b0012;
        public static final int Platform_ThemeOverlay_AppCompat_Dark = 0x7f0b0082;
        public static final int Platform_ThemeOverlay_AppCompat_Light = 0x7f0b0083;
        public static final int Platform_V11_AppCompat = 0x7f0b0013;
        public static final int Platform_V11_AppCompat_Light = 0x7f0b0014;
        public static final int Platform_V14_AppCompat = 0x7f0b001e;
        public static final int Platform_V14_AppCompat_Light = 0x7f0b001f;
        public static final int RtlOverlay_DialogWindowTitle_AppCompat = 0x7f0b0030;
        public static final int RtlOverlay_Widget_AppCompat_ActionBar_TitleItem = 0x7f0b0031;
        public static final int RtlOverlay_Widget_AppCompat_ActionButton_Overflow = 0x7f0b0032;
        public static final int RtlOverlay_Widget_AppCompat_DialogTitle_Icon = 0x7f0b0033;
        public static final int RtlOverlay_Widget_AppCompat_PopupMenuItem = 0x7f0b0034;
        public static final int RtlOverlay_Widget_AppCompat_PopupMenuItem_InternalGroup = 0x7f0b0035;
        public static final int RtlOverlay_Widget_AppCompat_PopupMenuItem_Text = 0x7f0b0036;
        public static final int RtlOverlay_Widget_AppCompat_SearchView_MagIcon = 0x7f0b003c;
        public static final int RtlOverlay_Widget_AppCompat_Search_DropDown = 0x7f0b0037;
        public static final int RtlOverlay_Widget_AppCompat_Search_DropDown_Icon1 = 0x7f0b0038;
        public static final int RtlOverlay_Widget_AppCompat_Search_DropDown_Icon2 = 0x7f0b0039;
        public static final int RtlOverlay_Widget_AppCompat_Search_DropDown_Query = 0x7f0b003a;
        public static final int RtlOverlay_Widget_AppCompat_Search_DropDown_Text = 0x7f0b003b;
        public static final int RtlOverlay_Widget_AppCompat_Toolbar_Button_Navigation = 0x7f0b003d;
        public static final int TextAppearance_AppCompat = 0x7f0b00ec;
        public static final int TextAppearance_AppCompat_Body1 = 0x7f0b00ed;
        public static final int TextAppearance_AppCompat_Body2 = 0x7f0b00ee;
        public static final int TextAppearance_AppCompat_Button = 0x7f0b00ef;
        public static final int TextAppearance_AppCompat_Caption = 0x7f0b00f0;
        public static final int TextAppearance_AppCompat_Display1 = 0x7f0b00f1;
        public static final int TextAppearance_AppCompat_Display2 = 0x7f0b00f2;
        public static final int TextAppearance_AppCompat_Display3 = 0x7f0b00f3;
        public static final int TextAppearance_AppCompat_Display4 = 0x7f0b00f4;
        public static final int TextAppearance_AppCompat_Headline = 0x7f0b00f5;
        public static final int TextAppearance_AppCompat_Inverse = 0x7f0b00f6;
        public static final int TextAppearance_AppCompat_Large = 0x7f0b00f7;
        public static final int TextAppearance_AppCompat_Large_Inverse = 0x7f0b00f8;
        public static final int TextAppearance_AppCompat_Light_SearchResult_Subtitle = 0x7f0b00f9;
        public static final int TextAppearance_AppCompat_Light_SearchResult_Title = 0x7f0b00fa;
        public static final int TextAppearance_AppCompat_Light_Widget_PopupMenu_Large = 0x7f0b00fb;
        public static final int TextAppearance_AppCompat_Light_Widget_PopupMenu_Small = 0x7f0b00fc;
        public static final int TextAppearance_AppCompat_Medium = 0x7f0b00fd;
        public static final int TextAppearance_AppCompat_Medium_Inverse = 0x7f0b00fe;
        public static final int TextAppearance_AppCompat_Menu = 0x7f0b00ff;
        public static final int TextAppearance_AppCompat_SearchResult_Subtitle = 0x7f0b0100;
        public static final int TextAppearance_AppCompat_SearchResult_Title = 0x7f0b0101;
        public static final int TextAppearance_AppCompat_Small = 0x7f0b0102;
        public static final int TextAppearance_AppCompat_Small_Inverse = 0x7f0b0103;
        public static final int TextAppearance_AppCompat_Subhead = 0x7f0b0104;
        public static final int TextAppearance_AppCompat_Subhead_Inverse = 0x7f0b0105;
        public static final int TextAppearance_AppCompat_Title = 0x7f0b0106;
        public static final int TextAppearance_AppCompat_Title_Inverse = 0x7f0b0107;
        public static final int TextAppearance_AppCompat_Widget_ActionBar_Menu = 0x7f0b0108;
        public static final int TextAppearance_AppCompat_Widget_ActionBar_Subtitle = 0x7f0b0109;
        public static final int TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse = 0x7f0b010a;
        public static final int TextAppearance_AppCompat_Widget_ActionBar_Title = 0x7f0b010b;
        public static final int TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse = 0x7f0b010c;
        public static final int TextAppearance_AppCompat_Widget_ActionMode_Subtitle = 0x7f0b010d;
        public static final int TextAppearance_AppCompat_Widget_ActionMode_Subtitle_Inverse = 0x7f0b010e;
        public static final int TextAppearance_AppCompat_Widget_ActionMode_Title = 0x7f0b010f;
        public static final int TextAppearance_AppCompat_Widget_ActionMode_Title_Inverse = 0x7f0b0110;
        public static final int TextAppearance_AppCompat_Widget_DropDownItem = 0x7f0b0111;
        public static final int TextAppearance_AppCompat_Widget_PopupMenu_Large = 0x7f0b0112;
        public static final int TextAppearance_AppCompat_Widget_PopupMenu_Small = 0x7f0b0113;
        public static final int TextAppearance_AppCompat_Widget_Switch = 0x7f0b0114;
        public static final int TextAppearance_AppCompat_Widget_TextView_SpinnerItem = 0x7f0b0115;
        public static final int TextAppearance_Design_Error = 0x7f0b0116;
        public static final int TextAppearance_Design_Hint = 0x7f0b0117;
        public static final int TextAppearance_Design_Snackbar_Action = 0x7f0b0118;
        public static final int TextAppearance_Design_Snackbar_Message = 0x7f0b0119;
        public static final int TextAppearance_Design_Tab = 0x7f0b011a;
        public static final int TextAppearance_StatusBar_EventContent = 0x7f0b0021;
        public static final int TextAppearance_StatusBar_EventContent_Info = 0x7f0b0022;
        public static final int TextAppearance_StatusBar_EventContent_Line2 = 0x7f0b0023;
        public static final int TextAppearance_StatusBar_EventContent_Time = 0x7f0b0024;
        public static final int TextAppearance_StatusBar_EventContent_Title = 0x7f0b0025;
        public static final int TextAppearance_Widget_AppCompat_ExpandedMenu_Item = 0x7f0b011b;
        public static final int TextAppearance_Widget_AppCompat_Toolbar_Subtitle = 0x7f0b011c;
        public static final int TextAppearance_Widget_AppCompat_Toolbar_Title = 0x7f0b011d;
        public static final int ThemeOverlay_AppCompat = 0x7f0b012d;
        public static final int ThemeOverlay_AppCompat_ActionBar = 0x7f0b012e;
        public static final int ThemeOverlay_AppCompat_Dark = 0x7f0b012f;
        public static final int ThemeOverlay_AppCompat_Dark_ActionBar = 0x7f0b0130;
        public static final int ThemeOverlay_AppCompat_Light = 0x7f0b0131;
        public static final int Theme_AppCompat = 0x7f0b011e;
        public static final int Theme_AppCompat_CompactMenu = 0x7f0b011f;
        public static final int Theme_AppCompat_Dialog = 0x7f0b0120;
        public static final int Theme_AppCompat_DialogWhenLarge = 0x7f0b0123;
        public static final int Theme_AppCompat_Dialog_Alert = 0x7f0b0121;
        public static final int Theme_AppCompat_Dialog_MinWidth = 0x7f0b0122;
        public static final int Theme_AppCompat_Light = 0x7f0b0124;
        public static final int Theme_AppCompat_Light_DarkActionBar = 0x7f0b0125;
        public static final int Theme_AppCompat_Light_Dialog = 0x7f0b0126;
        public static final int Theme_AppCompat_Light_DialogWhenLarge = 0x7f0b0129;
        public static final int Theme_AppCompat_Light_Dialog_Alert = 0x7f0b0127;
        public static final int Theme_AppCompat_Light_Dialog_MinWidth = 0x7f0b0128;
        public static final int Theme_AppCompat_Light_NoActionBar = 0x7f0b012a;
        public static final int Theme_AppCompat_NoActionBar = 0x7f0b012b;
        public static final int Widget_AppCompat_ActionBar = 0x7f0b0137;
        public static final int Widget_AppCompat_ActionBar_Solid = 0x7f0b0138;
        public static final int Widget_AppCompat_ActionBar_TabBar = 0x7f0b0139;
        public static final int Widget_AppCompat_ActionBar_TabText = 0x7f0b013a;
        public static final int Widget_AppCompat_ActionBar_TabView = 0x7f0b013b;
        public static final int Widget_AppCompat_ActionButton = 0x7f0b013c;
        public static final int Widget_AppCompat_ActionButton_CloseMode = 0x7f0b013d;
        public static final int Widget_AppCompat_ActionButton_Overflow = 0x7f0b013e;
        public static final int Widget_AppCompat_ActionMode = 0x7f0b013f;
        public static final int Widget_AppCompat_ActivityChooserView = 0x7f0b0140;
        public static final int Widget_AppCompat_AutoCompleteTextView = 0x7f0b0141;
        public static final int Widget_AppCompat_Button = 0x7f0b0142;
        public static final int Widget_AppCompat_ButtonBar = 0x7f0b0147;
        public static final int Widget_AppCompat_ButtonBar_AlertDialog = 0x7f0b0148;
        public static final int Widget_AppCompat_Button_Borderless = 0x7f0b0143;
        public static final int Widget_AppCompat_Button_Borderless_Colored = 0x7f0b0144;
        public static final int Widget_AppCompat_Button_ButtonBar_AlertDialog = 0x7f0b0145;
        public static final int Widget_AppCompat_Button_Small = 0x7f0b0146;
        public static final int Widget_AppCompat_CompoundButton_CheckBox = 0x7f0b0149;
        public static final int Widget_AppCompat_CompoundButton_RadioButton = 0x7f0b014a;
        public static final int Widget_AppCompat_CompoundButton_Switch = 0x7f0b014b;
        public static final int Widget_AppCompat_DrawerArrowToggle = 0x7f0b014c;
        public static final int Widget_AppCompat_DropDownItem_Spinner = 0x7f0b014d;
        public static final int Widget_AppCompat_EditText = 0x7f0b014e;
        public static final int Widget_AppCompat_Light_ActionBar = 0x7f0b014f;
        public static final int Widget_AppCompat_Light_ActionBar_Solid = 0x7f0b0150;
        public static final int Widget_AppCompat_Light_ActionBar_Solid_Inverse = 0x7f0b0151;
        public static final int Widget_AppCompat_Light_ActionBar_TabBar = 0x7f0b0152;
        public static final int Widget_AppCompat_Light_ActionBar_TabBar_Inverse = 0x7f0b0153;
        public static final int Widget_AppCompat_Light_ActionBar_TabText = 0x7f0b0154;
        public static final int Widget_AppCompat_Light_ActionBar_TabText_Inverse = 0x7f0b0155;
        public static final int Widget_AppCompat_Light_ActionBar_TabView = 0x7f0b0156;
        public static final int Widget_AppCompat_Light_ActionBar_TabView_Inverse = 0x7f0b0157;
        public static final int Widget_AppCompat_Light_ActionButton = 0x7f0b0158;
        public static final int Widget_AppCompat_Light_ActionButton_CloseMode = 0x7f0b0159;
        public static final int Widget_AppCompat_Light_ActionButton_Overflow = 0x7f0b015a;
        public static final int Widget_AppCompat_Light_ActionMode_Inverse = 0x7f0b015b;
        public static final int Widget_AppCompat_Light_ActivityChooserView = 0x7f0b015c;
        public static final int Widget_AppCompat_Light_AutoCompleteTextView = 0x7f0b015d;
        public static final int Widget_AppCompat_Light_DropDownItem_Spinner = 0x7f0b015e;
        public static final int Widget_AppCompat_Light_ListPopupWindow = 0x7f0b015f;
        public static final int Widget_AppCompat_Light_ListView_DropDown = 0x7f0b0160;
        public static final int Widget_AppCompat_Light_PopupMenu = 0x7f0b0161;
        public static final int Widget_AppCompat_Light_PopupMenu_Overflow = 0x7f0b0162;
        public static final int Widget_AppCompat_Light_SearchView = 0x7f0b0163;
        public static final int Widget_AppCompat_Light_Spinner_DropDown_ActionBar = 0x7f0b0164;
        public static final int Widget_AppCompat_ListPopupWindow = 0x7f0b0165;
        public static final int Widget_AppCompat_ListView = 0x7f0b0166;
        public static final int Widget_AppCompat_ListView_DropDown = 0x7f0b0167;
        public static final int Widget_AppCompat_ListView_Menu = 0x7f0b0168;
        public static final int Widget_AppCompat_PopupMenu = 0x7f0b0169;
        public static final int Widget_AppCompat_PopupMenu_Overflow = 0x7f0b016a;
        public static final int Widget_AppCompat_PopupWindow = 0x7f0b016b;
        public static final int Widget_AppCompat_ProgressBar = 0x7f0b016c;
        public static final int Widget_AppCompat_ProgressBar_Horizontal = 0x7f0b016d;
        public static final int Widget_AppCompat_RatingBar = 0x7f0b016e;
        public static final int Widget_AppCompat_SearchView = 0x7f0b016f;
        public static final int Widget_AppCompat_SearchView_ActionBar = 0x7f0b0170;
        public static final int Widget_AppCompat_Spinner = 0x7f0b0171;
        public static final int Widget_AppCompat_Spinner_DropDown = 0x7f0b0172;
        public static final int Widget_AppCompat_Spinner_DropDown_ActionBar = 0x7f0b0173;
        public static final int Widget_AppCompat_Spinner_Underlined = 0x7f0b0174;
        public static final int Widget_AppCompat_TextView_SpinnerItem = 0x7f0b0175;
        public static final int Widget_AppCompat_Toolbar = 0x7f0b0176;
        public static final int Widget_AppCompat_Toolbar_Button_Navigation = 0x7f0b0177;
        public static final int Widget_Design_AppBarLayout = 0x7f0b0178;
        public static final int Widget_Design_CollapsingToolbar = 0x7f0b0179;
        public static final int Widget_Design_CoordinatorLayout = 0x7f0b017a;
        public static final int Widget_Design_FloatingActionButton = 0x7f0b017b;
        public static final int Widget_Design_NavigationView = 0x7f0b017c;
        public static final int Widget_Design_ScrimInsetsFrameLayout = 0x7f0b017d;
        public static final int Widget_Design_Snackbar = 0x7f0b017e;
        public static final int Widget_Design_TabLayout = 0x7f0b0001;
        public static final int Widget_Design_TextInputLayout = 0x7f0b017f;
    }

    public static final class g
    {

        public static final int ActionBar[] = {
            0x7f010001, 0x7f010003, 0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007, 0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b, 
            0x7f01000c, 0x7f01000d, 0x7f01000e, 0x7f01000f, 0x7f010010, 0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014, 0x7f010015, 
            0x7f010016, 0x7f010017, 0x7f010018, 0x7f010019, 0x7f01001a, 0x7f01001b, 0x7f0100d5
        };
        public static final int ActionBarLayout[] = {
            0x10100b3
        };
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_contentInsetEnd = 21;
        public static final int ActionBar_contentInsetLeft = 22;
        public static final int ActionBar_contentInsetRight = 23;
        public static final int ActionBar_contentInsetStart = 20;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_elevation = 24;
        public static final int ActionBar_height = 0;
        public static final int ActionBar_hideOnContentScroll = 19;
        public static final int ActionBar_homeAsUpIndicator = 26;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_popupTheme = 25;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 1;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int ActionMenuItemView[] = {
            0x101013f
        };
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int ActionMenuView[] = new int[0];
        public static final int ActionMode[] = {
            0x7f010001, 0x7f010007, 0x7f010008, 0x7f01000c, 0x7f01000e, 0x7f01001c
        };
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_closeItemLayout = 5;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int ActivityChooserView[] = {
            0x7f01001d, 0x7f01001e
        };
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int AlertDialog[] = {
            0x10100f2, 0x7f010022, 0x7f010023, 0x7f010024, 0x7f010025, 0x7f010026
        };
        public static final int AlertDialog_android_layout = 0;
        public static final int AlertDialog_buttonPanelSideLayout = 1;
        public static final int AlertDialog_listItemLayout = 5;
        public static final int AlertDialog_listLayout = 2;
        public static final int AlertDialog_multiChoiceItemLayout = 3;
        public static final int AlertDialog_singleChoiceItemLayout = 4;
        public static final int AppBarLayout[] = {
            0x10100d4, 0x7f01001a
        };
        public static final int AppBarLayout_LayoutParams[] = {
            0x7f010027, 0x7f010028
        };
        public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
        public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
        public static final int AppBarLayout_android_background = 0;
        public static final int AppBarLayout_elevation = 1;
        public static final int AppCompatTextView[] = {
            0x1010034, 0x7f010029
        };
        public static final int AppCompatTextView_android_textAppearance = 0;
        public static final int AppCompatTextView_textAllCaps = 1;
        public static final int CollapsingAppBarLayout_LayoutParams[] = {
            0x7f010035, 0x7f010036
        };
        public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
        public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseParallaxMultiplier = 1;
        public static final int CollapsingToolbarLayout[] = {
            0x7f010037, 0x7f010038, 0x7f010039, 0x7f01003a, 0x7f01003b, 0x7f01003c, 0x7f01003d, 0x7f01003e, 0x7f01003f, 0x7f010040
        };
        public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 6;
        public static final int CollapsingToolbarLayout_contentScrim = 7;
        public static final int CollapsingToolbarLayout_expandedTitleMargin = 0;
        public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 4;
        public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 3;
        public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 1;
        public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 2;
        public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 5;
        public static final int CollapsingToolbarLayout_statusBarScrim = 8;
        public static final int CollapsingToolbarLayout_toolbarId = 9;
        public static final int CoordinatorLayout[] = {
            0x7f010041, 0x7f010042
        };
        public static final int CoordinatorLayout_LayoutParams[] = {
            0x10100b3, 0x7f010043, 0x7f010044, 0x7f010045, 0x7f010046
        };
        public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
        public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
        public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
        public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
        public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
        public static final int CoordinatorLayout_keylines = 0;
        public static final int CoordinatorLayout_statusBarBackground = 1;
        public static final int DrawerArrowToggle[] = {
            0x7f010047, 0x7f010048, 0x7f010049, 0x7f01004a, 0x7f01004b, 0x7f01004c, 0x7f01004d, 0x7f01004e
        };
        public static final int DrawerArrowToggle_barSize = 6;
        public static final int DrawerArrowToggle_color = 0;
        public static final int DrawerArrowToggle_drawableSize = 2;
        public static final int DrawerArrowToggle_gapBetweenBars = 3;
        public static final int DrawerArrowToggle_middleBarArrowSize = 5;
        public static final int DrawerArrowToggle_spinBars = 1;
        public static final int DrawerArrowToggle_thickness = 7;
        public static final int DrawerArrowToggle_topBottomBarArrowSize = 4;
        public static final int FloatingActionButton[] = {
            0x10100d4, 0x7f01001a, 0x7f01004f, 0x7f010050, 0x7f010051, 0x7f010052, 0x7f01011f, 0x7f010120
        };
        public static final int FloatingActionButton_android_background = 0;
        public static final int FloatingActionButton_backgroundTint = 6;
        public static final int FloatingActionButton_backgroundTintMode = 7;
        public static final int FloatingActionButton_borderWidth = 5;
        public static final int FloatingActionButton_elevation = 1;
        public static final int FloatingActionButton_fabSize = 3;
        public static final int FloatingActionButton_pressedTranslationZ = 4;
        public static final int FloatingActionButton_rippleColor = 2;
        public static final int LinearLayoutCompat[] = {
            0x10100af, 0x10100c4, 0x1010126, 0x1010127, 0x1010128, 0x7f01000b, 0x7f010053, 0x7f010054, 0x7f010055
        };
        public static final int LinearLayoutCompat_Layout[] = {
            0x10100b3, 0x10100f4, 0x10100f5, 0x1010181
        };
        public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
        public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
        public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
        public static final int LinearLayoutCompat_android_baselineAligned = 2;
        public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
        public static final int LinearLayoutCompat_android_gravity = 0;
        public static final int LinearLayoutCompat_android_orientation = 1;
        public static final int LinearLayoutCompat_android_weightSum = 4;
        public static final int LinearLayoutCompat_divider = 5;
        public static final int LinearLayoutCompat_dividerPadding = 8;
        public static final int LinearLayoutCompat_measureWithLargestChild = 6;
        public static final int LinearLayoutCompat_showDividers = 7;
        public static final int ListPopupWindow[] = {
            0x10102ac, 0x10102ad
        };
        public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static final int MenuGroup[] = {
            0x101000e, 0x10100d0, 0x1010194, 0x10101de, 0x10101df, 0x10101e0
        };
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int MenuItem[] = {
            0x1010002, 0x101000e, 0x10100d0, 0x1010106, 0x1010194, 0x10101de, 0x10101df, 0x10101e1, 0x10101e2, 0x10101e3, 
            0x10101e4, 0x10101e5, 0x101026f, 0x7f010069, 0x7f01006a, 0x7f01006b, 0x7f01006c
        };
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int MenuView[] = {
            0x10100ae, 0x101012c, 0x101012d, 0x101012e, 0x101012f, 0x1010130, 0x1010131, 0x7f01006d
        };
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int MenuView_preserveIconSpacing = 7;
        public static final int NavigationView[] = {
            0x10100d4, 0x10100dd, 0x101011f, 0x7f01001a, 0x7f01006e, 0x7f01006f, 0x7f010070, 0x7f010071, 0x7f010072
        };
        public static final int NavigationView_android_background = 0;
        public static final int NavigationView_android_fitsSystemWindows = 1;
        public static final int NavigationView_android_maxWidth = 2;
        public static final int NavigationView_elevation = 3;
        public static final int NavigationView_headerLayout = 8;
        public static final int NavigationView_itemBackground = 7;
        public static final int NavigationView_itemIconTint = 5;
        public static final int NavigationView_itemTextColor = 6;
        public static final int NavigationView_menu = 4;
        public static final int PopupWindow[] = {
            0x1010176, 0x7f010073
        };
        public static final int PopupWindowBackgroundState[] = {
            0x7f010074
        };
        public static final int PopupWindowBackgroundState_state_above_anchor = 0;
        public static final int PopupWindow_android_popupBackground = 0;
        public static final int PopupWindow_overlapAnchor = 1;
        public static final int ScrimInsetsFrameLayout[] = {
            0x7f010079
        };
        public static final int ScrimInsetsFrameLayout_insetForeground = 0;
        public static final int ScrollingViewBehavior_Params[] = {
            0x7f01007a
        };
        public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
        public static final int SearchView[] = {
            0x10100da, 0x101011f, 0x1010220, 0x1010264, 0x7f01007b, 0x7f01007c, 0x7f01007d, 0x7f01007e, 0x7f01007f, 0x7f010080, 
            0x7f010081, 0x7f010082, 0x7f010083, 0x7f010084, 0x7f010085, 0x7f010086, 0x7f010087
        };
        public static final int SearchView_android_focusable = 0;
        public static final int SearchView_android_imeOptions = 3;
        public static final int SearchView_android_inputType = 2;
        public static final int SearchView_android_maxWidth = 1;
        public static final int SearchView_closeIcon = 8;
        public static final int SearchView_commitIcon = 13;
        public static final int SearchView_defaultQueryHint = 7;
        public static final int SearchView_goIcon = 9;
        public static final int SearchView_iconifiedByDefault = 5;
        public static final int SearchView_layout = 4;
        public static final int SearchView_queryBackground = 15;
        public static final int SearchView_queryHint = 6;
        public static final int SearchView_searchHintIcon = 11;
        public static final int SearchView_searchIcon = 10;
        public static final int SearchView_submitBackground = 16;
        public static final int SearchView_suggestionRowLayout = 14;
        public static final int SearchView_voiceIcon = 12;
        public static final int SnackbarLayout[] = {
            0x101011f, 0x7f01001a, 0x7f010088
        };
        public static final int SnackbarLayout_android_maxWidth = 0;
        public static final int SnackbarLayout_elevation = 1;
        public static final int SnackbarLayout_maxActionInlineWidth = 2;
        public static final int Spinner[] = {
            0x10100af, 0x10100d4, 0x1010175, 0x1010176, 0x1010262, 0x10102ac, 0x10102ad, 0x7f010089, 0x7f01008a, 0x7f01008b, 
            0x7f01008c
        };
        public static final int Spinner_android_background = 1;
        public static final int Spinner_android_dropDownHorizontalOffset = 5;
        public static final int Spinner_android_dropDownSelector = 2;
        public static final int Spinner_android_dropDownVerticalOffset = 6;
        public static final int Spinner_android_dropDownWidth = 4;
        public static final int Spinner_android_gravity = 0;
        public static final int Spinner_android_popupBackground = 3;
        public static final int Spinner_disableChildrenWhenDisabled = 10;
        public static final int Spinner_popupPromptView = 9;
        public static final int Spinner_prompt = 7;
        public static final int Spinner_spinnerMode = 8;
        public static final int SwitchCompat[] = {
            0x1010124, 0x1010125, 0x1010142, 0x7f01008d, 0x7f01008e, 0x7f01008f, 0x7f010090, 0x7f010091, 0x7f010092, 0x7f010093
        };
        public static final int SwitchCompat_android_textOff = 1;
        public static final int SwitchCompat_android_textOn = 0;
        public static final int SwitchCompat_android_thumb = 2;
        public static final int SwitchCompat_showText = 9;
        public static final int SwitchCompat_splitTrack = 8;
        public static final int SwitchCompat_switchMinWidth = 6;
        public static final int SwitchCompat_switchPadding = 7;
        public static final int SwitchCompat_switchTextAppearance = 5;
        public static final int SwitchCompat_thumbTextPadding = 4;
        public static final int SwitchCompat_track = 3;
        public static final int TabLayout[] = {
            0x7f010094, 0x7f010095, 0x7f010096, 0x7f010097, 0x7f010098, 0x7f010099, 0x7f01009a, 0x7f01009b, 0x7f01009c, 0x7f01009d, 
            0x7f01009e, 0x7f01009f, 0x7f0100a0, 0x7f0100a1, 0x7f0100a2, 0x7f0100a3
        };
        public static final int TabLayout_tabBackground = 3;
        public static final int TabLayout_tabContentStart = 2;
        public static final int TabLayout_tabGravity = 5;
        public static final int TabLayout_tabIndicatorColor = 0;
        public static final int TabLayout_tabIndicatorHeight = 1;
        public static final int TabLayout_tabMaxWidth = 7;
        public static final int TabLayout_tabMinWidth = 6;
        public static final int TabLayout_tabMode = 4;
        public static final int TabLayout_tabPadding = 15;
        public static final int TabLayout_tabPaddingBottom = 14;
        public static final int TabLayout_tabPaddingEnd = 13;
        public static final int TabLayout_tabPaddingStart = 11;
        public static final int TabLayout_tabPaddingTop = 12;
        public static final int TabLayout_tabSelectedTextColor = 10;
        public static final int TabLayout_tabTextAppearance = 8;
        public static final int TabLayout_tabTextColor = 9;
        public static final int TextAppearance[] = {
            0x1010095, 0x1010096, 0x1010097, 0x1010098, 0x7f010029
        };
        public static final int TextAppearance_android_textColor = 3;
        public static final int TextAppearance_android_textSize = 0;
        public static final int TextAppearance_android_textStyle = 2;
        public static final int TextAppearance_android_typeface = 1;
        public static final int TextAppearance_textAllCaps = 4;
        public static final int TextInputLayout[] = {
            0x1010150, 0x7f0100a4, 0x7f0100a5, 0x7f0100a6
        };
        public static final int TextInputLayout_android_hint = 0;
        public static final int TextInputLayout_errorEnabled = 2;
        public static final int TextInputLayout_errorTextAppearance = 3;
        public static final int TextInputLayout_hintTextAppearance = 1;
        public static final int Theme[] = {
            0x1010057, 0x10100ae, 0x7f0100a7, 0x7f0100a8, 0x7f0100a9, 0x7f0100aa, 0x7f0100ab, 0x7f0100ac, 0x7f0100ad, 0x7f0100ae, 
            0x7f0100af, 0x7f0100b0, 0x7f0100b1, 0x7f0100b2, 0x7f0100b3, 0x7f0100b4, 0x7f0100b5, 0x7f0100b6, 0x7f0100b7, 0x7f0100b8, 
            0x7f0100b9, 0x7f0100ba, 0x7f0100bb, 0x7f0100bc, 0x7f0100bd, 0x7f0100be, 0x7f0100bf, 0x7f0100c0, 0x7f0100c1, 0x7f0100c2, 
            0x7f0100c3, 0x7f0100c4, 0x7f0100c5, 0x7f0100c6, 0x7f0100c7, 0x7f0100c8, 0x7f0100c9, 0x7f0100ca, 0x7f0100cb, 0x7f0100cc, 
            0x7f0100cd, 0x7f0100ce, 0x7f0100cf, 0x7f0100d0, 0x7f0100d1, 0x7f0100d2, 0x7f0100d3, 0x7f0100d4, 0x7f0100d5, 0x7f0100d6, 
            0x7f0100d7, 0x7f0100d8, 0x7f0100d9, 0x7f0100da, 0x7f0100db, 0x7f0100dc, 0x7f0100dd, 0x7f0100de, 0x7f0100df, 0x7f0100e0, 
            0x7f0100e1, 0x7f0100e2, 0x7f0100e3, 0x7f0100e4, 0x7f0100e5, 0x7f0100e6, 0x7f0100e7, 0x7f0100e8, 0x7f0100e9, 0x7f0100ea, 
            0x7f0100eb, 0x7f0100ec, 0x7f0100ed, 0x7f0100ee, 0x7f0100ef, 0x7f0100f0, 0x7f0100f1, 0x7f0100f2, 0x7f0100f3, 0x7f0100f4, 
            0x7f0100f5, 0x7f0100f6, 0x7f0100f7, 0x7f0100f8, 0x7f0100f9, 0x7f0100fa, 0x7f0100fb, 0x7f0100fc, 0x7f0100fd, 0x7f0100fe, 
            0x7f0100ff, 0x7f010100, 0x7f010101, 0x7f010102, 0x7f010103, 0x7f010104, 0x7f010105, 0x7f010106, 0x7f010107, 0x7f010108, 
            0x7f010109, 0x7f01010a, 0x7f01010b, 0x7f01010c, 0x7f01010d, 0x7f01010e, 0x7f01010f
        };
        public static final int Theme_actionBarDivider = 23;
        public static final int Theme_actionBarItemBackground = 24;
        public static final int Theme_actionBarPopupTheme = 17;
        public static final int Theme_actionBarSize = 22;
        public static final int Theme_actionBarSplitStyle = 19;
        public static final int Theme_actionBarStyle = 18;
        public static final int Theme_actionBarTabBarStyle = 13;
        public static final int Theme_actionBarTabStyle = 12;
        public static final int Theme_actionBarTabTextStyle = 14;
        public static final int Theme_actionBarTheme = 20;
        public static final int Theme_actionBarWidgetTheme = 21;
        public static final int Theme_actionButtonStyle = 49;
        public static final int Theme_actionDropDownStyle = 45;
        public static final int Theme_actionMenuTextAppearance = 25;
        public static final int Theme_actionMenuTextColor = 26;
        public static final int Theme_actionModeBackground = 29;
        public static final int Theme_actionModeCloseButtonStyle = 28;
        public static final int Theme_actionModeCloseDrawable = 31;
        public static final int Theme_actionModeCopyDrawable = 33;
        public static final int Theme_actionModeCutDrawable = 32;
        public static final int Theme_actionModeFindDrawable = 37;
        public static final int Theme_actionModePasteDrawable = 34;
        public static final int Theme_actionModePopupWindowStyle = 39;
        public static final int Theme_actionModeSelectAllDrawable = 35;
        public static final int Theme_actionModeShareDrawable = 36;
        public static final int Theme_actionModeSplitBackground = 30;
        public static final int Theme_actionModeStyle = 27;
        public static final int Theme_actionModeWebSearchDrawable = 38;
        public static final int Theme_actionOverflowButtonStyle = 15;
        public static final int Theme_actionOverflowMenuStyle = 16;
        public static final int Theme_activityChooserViewStyle = 57;
        public static final int Theme_alertDialogButtonGroupStyle = 90;
        public static final int Theme_alertDialogCenterButtons = 91;
        public static final int Theme_alertDialogStyle = 89;
        public static final int Theme_alertDialogTheme = 92;
        public static final int Theme_android_windowAnimationStyle = 1;
        public static final int Theme_android_windowIsFloating = 0;
        public static final int Theme_autoCompleteTextViewStyle = 97;
        public static final int Theme_borderlessButtonStyle = 54;
        public static final int Theme_buttonBarButtonStyle = 51;
        public static final int Theme_buttonBarNegativeButtonStyle = 95;
        public static final int Theme_buttonBarNeutralButtonStyle = 96;
        public static final int Theme_buttonBarPositiveButtonStyle = 94;
        public static final int Theme_buttonBarStyle = 50;
        public static final int Theme_buttonStyle = 98;
        public static final int Theme_buttonStyleSmall = 99;
        public static final int Theme_checkboxStyle = 100;
        public static final int Theme_checkedTextViewStyle = 101;
        public static final int Theme_colorAccent = 83;
        public static final int Theme_colorButtonNormal = 87;
        public static final int Theme_colorControlActivated = 85;
        public static final int Theme_colorControlHighlight = 86;
        public static final int Theme_colorControlNormal = 84;
        public static final int Theme_colorPrimary = 81;
        public static final int Theme_colorPrimaryDark = 82;
        public static final int Theme_colorSwitchThumbNormal = 88;
        public static final int Theme_dialogPreferredPadding = 43;
        public static final int Theme_dialogTheme = 42;
        public static final int Theme_dividerHorizontal = 56;
        public static final int Theme_dividerVertical = 55;
        public static final int Theme_dropDownListViewStyle = 73;
        public static final int Theme_dropdownListPreferredItemHeight = 46;
        public static final int Theme_editTextBackground = 63;
        public static final int Theme_editTextColor = 62;
        public static final int Theme_editTextStyle = 102;
        public static final int Theme_homeAsUpIndicator = 48;
        public static final int Theme_listChoiceBackgroundIndicator = 80;
        public static final int Theme_listDividerAlertDialog = 44;
        public static final int Theme_listPopupWindowStyle = 74;
        public static final int Theme_listPreferredItemHeight = 68;
        public static final int Theme_listPreferredItemHeightLarge = 70;
        public static final int Theme_listPreferredItemHeightSmall = 69;
        public static final int Theme_listPreferredItemPaddingLeft = 71;
        public static final int Theme_listPreferredItemPaddingRight = 72;
        public static final int Theme_panelBackground = 77;
        public static final int Theme_panelMenuListTheme = 79;
        public static final int Theme_panelMenuListWidth = 78;
        public static final int Theme_popupMenuStyle = 60;
        public static final int Theme_popupWindowStyle = 61;
        public static final int Theme_radioButtonStyle = 103;
        public static final int Theme_ratingBarStyle = 104;
        public static final int Theme_searchViewStyle = 67;
        public static final int Theme_selectableItemBackground = 52;
        public static final int Theme_selectableItemBackgroundBorderless = 53;
        public static final int Theme_spinnerDropDownItemStyle = 47;
        public static final int Theme_spinnerStyle = 105;
        public static final int Theme_switchStyle = 106;
        public static final int Theme_textAppearanceLargePopupMenu = 40;
        public static final int Theme_textAppearanceListItem = 75;
        public static final int Theme_textAppearanceListItemSmall = 76;
        public static final int Theme_textAppearanceSearchResultSubtitle = 65;
        public static final int Theme_textAppearanceSearchResultTitle = 64;
        public static final int Theme_textAppearanceSmallPopupMenu = 41;
        public static final int Theme_textColorAlertDialogListItem = 93;
        public static final int Theme_textColorSearchUrl = 66;
        public static final int Theme_toolbarNavigationButtonStyle = 59;
        public static final int Theme_toolbarStyle = 58;
        public static final int Theme_windowActionBar = 2;
        public static final int Theme_windowActionBarOverlay = 4;
        public static final int Theme_windowActionModeOverlay = 5;
        public static final int Theme_windowFixedHeightMajor = 9;
        public static final int Theme_windowFixedHeightMinor = 7;
        public static final int Theme_windowFixedWidthMajor = 6;
        public static final int Theme_windowFixedWidthMinor = 8;
        public static final int Theme_windowMinWidthMajor = 10;
        public static final int Theme_windowMinWidthMinor = 11;
        public static final int Theme_windowNoTitle = 3;
        public static final int Toolbar[] = {
            0x10100af, 0x1010140, 0x7f010003, 0x7f010006, 0x7f010016, 0x7f010017, 0x7f010018, 0x7f010019, 0x7f01001b, 0x7f010110, 
            0x7f010111, 0x7f010112, 0x7f010113, 0x7f010114, 0x7f010115, 0x7f010116, 0x7f010117, 0x7f010118, 0x7f010119, 0x7f01011a, 
            0x7f01011b
        };
        public static final int Toolbar_android_gravity = 0;
        public static final int Toolbar_android_minHeight = 1;
        public static final int Toolbar_collapseContentDescription = 18;
        public static final int Toolbar_collapseIcon = 17;
        public static final int Toolbar_contentInsetEnd = 5;
        public static final int Toolbar_contentInsetLeft = 6;
        public static final int Toolbar_contentInsetRight = 7;
        public static final int Toolbar_contentInsetStart = 4;
        public static final int Toolbar_maxButtonHeight = 16;
        public static final int Toolbar_navigationContentDescription = 20;
        public static final int Toolbar_navigationIcon = 19;
        public static final int Toolbar_popupTheme = 8;
        public static final int Toolbar_subtitle = 3;
        public static final int Toolbar_subtitleTextAppearance = 10;
        public static final int Toolbar_title = 2;
        public static final int Toolbar_titleMarginBottom = 15;
        public static final int Toolbar_titleMarginEnd = 13;
        public static final int Toolbar_titleMarginStart = 12;
        public static final int Toolbar_titleMarginTop = 14;
        public static final int Toolbar_titleMargins = 11;
        public static final int Toolbar_titleTextAppearance = 9;
        public static final int View[] = {
            0x1010000, 0x10100da, 0x7f01011c, 0x7f01011d, 0x7f01011e, 0x7f01011f, 0x7f010120
        };
        public static final int ViewStubCompat[] = {
            0x10100d0, 0x10100f2, 0x10100f3
        };
        public static final int ViewStubCompat_android_id = 0;
        public static final int ViewStubCompat_android_inflatedId = 2;
        public static final int ViewStubCompat_android_layout = 1;
        public static final int View_android_focusable = 1;
        public static final int View_android_theme = 0;
        public static final int View_backgroundTint = 5;
        public static final int View_backgroundTintMode = 6;
        public static final int View_paddingEnd = 3;
        public static final int View_paddingStart = 2;
        public static final int View_theme = 4;

    }

}
