// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

// Referenced classes of package com.paypal.android.sdk:
//            ig, fa

public final class h
    implements ig
{

    private static final Map a = new HashMap();
    private static final Map b = new HashMap();
    private static final Map c = new HashMap();

    public h()
    {
        a.put(fa.a, "Godk\344nn och betala");
        a.put(fa.b, "och annan");
        a.put(fa.c, "Autentisering utf\366rs");
        a.put(fa.d, "Tillbaka");
        a.put(fa.e, "Reservmetod");
        a.put(fa.f, "Avbryt");
        a.put(fa.g, "American Express");
        a.put(fa.h, "Carta Aura");
        a.put(fa.i, "Carte Aurore");
        a.put(fa.j, "Carta Prepagata PayPal");
        a.put(fa.k, "Carte Bancaire");
        a.put(fa.l, "Cofinoga");
        a.put(fa.m, "Delta");
        a.put(fa.n, "Discover");
        a.put(fa.o, "Electron");
        a.put(fa.p, "JCB");
        a.put(fa.q, "Maestro");
        a.put(fa.r, "MasterCard");
        a.put(fa.s, "Postepay");
        a.put(fa.t, "4 \351toiles");
        a.put(fa.u, "Tarjeta Aurora");
        a.put(fa.v, "Visa");
        a.put(fa.w, "\304ndra betalningsmetod");
        a.put(fa.x, "L\366nekonto");
        a.put(fa.y, "Enheten kontrolleras \u2026");
        a.put(fa.z, "Ta bort kortuppgifter");
        a.put(fa.A, "Bekr\344fta");
        a.put(fa.B, "Vill du ta bort kortuppgifterna?");
        a.put(fa.C, "Debitera kort");
        a.put(fa.D, "Vill du logga ut fr\345n PayPal?");
        a.put(fa.E, "Betala");
        a.put(fa.F, "Godk\344nn");
        a.put(fa.G, "Datum d\345 kontot skapades");
        a.put(fa.H, "Kontostatus");
        a.put(fa.I, "Kontotyp");
        a.put(fa.J, "Adress");
        a.put(fa.K, "\305ldersintervall");
        a.put(fa.L, "F\366delsedatum");
        a.put(fa.M, "E-postadress");
        a.put(fa.N, "Fullst\344ndigt namn");
        a.put(fa.O, "K\366n");
        a.put(fa.P, "Spr\345k");
        a.put(fa.Q, "Spr\345kinst\344llning");
        a.put(fa.R, "Telefon");
        a.put(fa.S, "Tidszon");
        a.put(fa.T, "Dela det h\344r: %s.");
        a.put(fa.U, "Betala smidigt.");
        a.put(fa.V, "%s ber dig att:");
        a.put(fa.W, "Dela <a href='%1$s'>betalningsmetoderna</a> som \344r kopplade till ditt PayPal-konto.");
        a.put(fa.X, "Aktivera visning av dina betalningsalternativ s\345 att du kan v\344lja mellan dem.");
        a.put(fa.Y, "<a href='%1$s'>Godk\344nna avgifter</a> f\366r framtida k\366p hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som beg\344rs av %3$s.");
        a.put(fa.Z, "Till\345t att de l\344gger till och hanterar sina lojalitetskort i din PayPal-e-pl\345nbok.");
        a.put(fa.aa, "godk\344nna <a href='%2$s'>sekretesspolicyn</a> och <a href='%3$s'>anv\344ndaravtalet</a> f\366r %1$s.");
        a.put(fa.ab, "Till\345t dem att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        a.put(fa.ac, "Till\345t dem att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        a.put(fa.ad, "Medgivande");
        a.put(fa.ae, "E-post");
        a.put(fa.af, "Exempeldata");
        a.put(fa.ag, "Sandbox");
        a.put(fa.ah, "G\345r ut");
        a.put(fa.ai, "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilken av dina betalningsmetoder som ska anv\344ndas.</p>");
        a.put(fa.aj, "Har du gl\366mt l\366senordet?");
        a.put(fa.ak, "Fr\345n");
        a.put(fa.al, "P\345 vilket s\344tt vill du g\366ra framtida betalningar till %1$s?");
        a.put(fa.am, "<h1><strong>Avtal f\366r framtida betalningar</strong></h1><p>Dina framtida PayPal-betalningar betalas med det betalningsalternativ du angett f\366r den h\344r handlaren.</p><p>Om du vill upph\344va avtalet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina inst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p><p>Avsnittet \305terkommande betalningar i <a href='%s'>PayPals anv\344ndaravtal</a> g\344ller.</p><p>Appen simulerar eventuellt en liten testtransaktion f\366r att se till att du kan g\366ra betalningar fr\345n ditt PayPal-konto, men inga pengar \366verf\366rs.</p>");
        a.put(fa.an, "Internt fel");
        a.put(fa.ao, "<p>Genom att klicka p\345 knappen godtar jag villkoren i <a href='%1$s'>PayPals anv\344ndaravtal</a> och intygar att jag f\366ljer japanska lagar och regleringar, inklusive sanktionerna mot betalningar till Nordkorea och Iran enligt <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> f\366r att slutf\366ra transaktionen.</p>");
        a.put(fa.ap, "Logga in");
        a.put(fa.aq, "Logga in med PayPal");
        a.put(fa.ar, "Logga ut");
        a.put(fa.as, "Logga ut");
        a.put(fa.at, "OK");
        a.put(fa.au, "L\366senord");
        a.put(fa.av, "Betala efter leverans");
        a.put(fa.aw, "Betala med");
        a.put(fa.ax, "Betala med kort");
        a.put(fa.ay, "PayPal-saldo");
        a.put(fa.az, "PayPal Credit");
        a.put(fa.aA, "Telefon");
        a.put(fa.aB, "Pinkod");
        a.put(fa.aC, "Favoritbetalningsmetod");
        a.put(fa.aD, "PayPal skyddar dina <a href='%s'>personliga uppgifter</a> och dina betalningsuppgifter.");
        a.put(fa.aE, "Behandling");
        a.put(fa.aF, "Kom ih\345g kort");
        a.put(fa.aG, "Be om betalning");
        a.put(fa.aH, "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n partnerns sida.</p>");
        a.put(fa.aI, "Sparkonto");
        a.put(fa.aJ, "\326verf\366ra pengar");
        a.put(fa.aK, "Det gick inte att kommunicera med PayPal-servrarna. F\366rs\366k igen.");
        a.put(fa.aL, "Logga in p\345 PayPal igen.");
        a.put(fa.aM, "Sessionen har upph\366rt att g\344lla");
        a.put(fa.aN, "Leveransadress");
        a.put(fa.aO, "Har du inte anv\344nt PayPal f\366rut? Skapa konto");
        a.put(fa.aP, "Forts\344tt att vara inloggad");
        a.put(fa.aQ, "Systemfel (%s). F\366rs\366k igen senare.");
        a.put(fa.aR, "F\366rs\366k igen");
        a.put(fa.aS, "Det gick inte att logga in eftersom tv\345faktorautentisering har aktiverats f\366r ditt konto.");
        a.put(fa.aT, "S\344kerhetskod");
        a.put(fa.aU, "Skicka ett sms till din mobiltelefon. Den sexsiffriga koden du f\345r \344r giltig i 5 minuter.");
        a.put(fa.aV, "Skicka sms");
        a.put(fa.aW, "Ange den sexsiffriga s\344kerhetskoden");
        a.put(fa.aX, "Ditt mobilnummer");
        a.put(fa.aY, "Skicka sms");
        a.put(fa.aZ, "Skicka sms igen");
        a.put(fa.ba, "Det gick inte att logga in eftersom tv\345faktorautentisering har aktiverats f\366r ditt konto. G\345 till PayPals webbplats f\366r att aktivera s\344kerhetsnyckeln.");
        a.put(fa.bb, "Betalningar fr\345n den h\344r enheten \344r inte till\345tna.");
        a.put(fa.bc, "Obeh\366rig enhet");
        a.put(fa.bd, "Betalningar till den h\344r handlaren medges inte (ogiltigt klient-id).");
        a.put(fa.be, "Ogiltig handlare");
        a.put(fa.bf, "Det gick inte att behandla din betalning. F\366rs\366k igen.");
        a.put(fa.bg, "Ok\344nd betalningsmetod");
        a.put(fa.bh, "Tyv\344rr");
        a.put(fa.bi, "Din order");
        a.put(fa.bj, "Vill du ta bort kortet?");
        a.put(fa.bk, "Samtycke misslyckades");
        a.put(fa.bl, "Anslutningen misslyckades");
        a.put(fa.bm, "Inloggningen misslyckades");
        a.put(fa.bn, "Logga in med ditt l\366senord");
        a.put(fa.bo, "Logga in med din pinkod");
        a.put(fa.bp, "Ett \366gonblick \u2026");
        a.put(fa.bq, "Betalningen misslyckades");
        a.put(fa.br, "Skanna");
        a.put(fa.bs, "Felaktig s\344kerhetskod. F\366rs\366k igen.");
        a.put(fa.bt, "Via");
        a.put(fa.bu, "Systemfel. F\366rs\366k igen senare.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Dela information om de <a href='%1$s'>betalningsalternativ</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Dela informationen om de <a href='%1$s'>betalningsalternativ</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Dela information om de <a href='%1$s'>betalningsalternativ</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Dela information om de <a href='%1$s'>betalningsalternativ</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Dela information om de <a href='%1$s'>betalningsmetoder</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Dela information med dem om de <a href='%1$s'>betalningsalternativ</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Dela <a href='%1$s'>betalningsalternativen</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Dela <a href='%1$s'>betalningsalternativen</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Dela informationen om de <a href='%1$s'>betalningsalternativ</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Dela information om de <a href='%1$s'>betalningsmetoder</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Dela informationen om de <a href='%1$s'>betalningsalternativ</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Dela information om de <a href='%1$s'>betalningsmetoder</a> som \344r kopplade till ditt PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Dela <a href='%1$s'>betalningsalternativen</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godk\344nna avgifter</a> f\366r framtida k\366p hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som beg\344rs av %3$s.</p><p>Mer information finns i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtal om \345terkommande betalningar och fakturering</a>.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godk\344nna avgifter</a> f\366r framtida k\366p hos %2$s som betalas med PayPal. Du ger PayPal i uppdrag att betala alla belopp som beg\344rs av %3$s.</p><p>Mer information finns i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtal om \345terkommande betalningar och fakturering</a>.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Godk\344nn att pengar dras</a> f\366r framtida k\366p som betalas med PayPal. Du ber PayPal betala alla belopp och godk\344nner detta.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Godk\344nn att pengar dras</a> f\366r framtida k\366p som betalas med PayPal. Du ber PayPal betala alla belopp och godk\344nner detta.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Godk\344nn att pengar dras</a> f\366r framtida k\366p som betalas med PayPal. Du ber PayPal betala alla belopp och godk\344nner detta.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Godk\344nn p\345 f\366rhand framtida betalningar fr\345n ditt PayPal-konto utan att logga in p\345 PayPal varje g\345ng. <a href='%1$s'>Se fler villkor</a>, inklusive betalningsmetoder och information om hur du avbryter framtida betalningar.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Till\345t %2$s att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Till\345t %2$s att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Till\345t %2$s att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Till\345t %2$s att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Till\345t %2$s att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Till\345t %2$s att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Till\345t %2$s att <a href='%1$s'>be om betalning</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Till\345t %2$s att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Till\345t %2$s att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Till\345t %2$s att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Till\345t %2$s att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Till\345t %2$s att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Till\345t %2$s att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Till\345t %2$s att <a href='%1$s'>\366verf\366ra pengar</a> f\366r din r\344kning tills du drar tillbaka ditt medgivande.");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Betalningsmetoder</strong></h1><p>PayPal delar bara information om vilka av dina betalningsalternativ som kan anv\344ndas.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Avtal f\366r framtida betalningar</strong></h1><p>Med appen simuleras eventuellt en liten testtransaktion f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med den betalningsmetod du har angett som standard (PayPal-saldo, kopplat bankkonto eller betalkort, i den ordningen). T\344nk p\345 att banken eller kortutf\344rdaren kan ta ut en avgift om det inte finns tillr\344ckligt med pengar f\366r att t\344cka k\366pet.</p><p>Om du vill upph\344va avtalet loggar du in p\345 ditt PayPal-konto och g\345r till <strong>Min profil</strong>. Klicka sedan p\345 <strong>Mina inst\344llningar</strong> och <strong>\304ndra</strong> bredvid \u201DLogga in med PayPal\u201D.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Avtal f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med ditt PayPal-saldo eller ditt prim\344ra betalkort.</p><p>Om du vill upph\344va avtalet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina inst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Avtal f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill upph\344va avtalet loggar du in p\345 ditt PayPal-konto och g\345r till <strong>Min profil</strong> &gt; <strong>Inst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Avtal f\366r framtida betalningar</strong></h1><p>Dina framtida PayPal-betalningar betalas med det betalningsalternativ du angett f\366r den h\344r handlaren.</p><p>Om du vill upph\344va avtalet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina inst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p><p>Avsnittet \305terkommande betalningar i <a href='%s'>PayPals anv\344ndaravtal</a> g\344ller.</p><p>Appen simulerar eventuellt en liten testtransaktion f\366r att se till att du kan g\366ra betalningar fr\345n ditt PayPal-konto, men inga pengar \366verf\366rs.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godk\344nnande f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godk\344nnandet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina kontoinst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p><p>Mer information finns i avsnittet \u201DF\366rgodk\344nda betalningar\u201D i <a href='%s'>PayPals anv\344ndaravtal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godk\344nnande f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godk\344nnandet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina kontoinst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p><p>Mer information finns i avsnittet \u201DF\366rgodk\344nda betalningar\u201D i <a href='%s'>PayPals anv\344ndaravtal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Avtal f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med ditt PayPal-saldo eller ditt prim\344ra betalkort.</p><p>Om du vill upph\344va avtalet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina inst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Godk\344nnande f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godk\344nnandet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina kontoinst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p><p>Mer information finns i avsnittet \u201DF\366rgodk\344nda betalningar\u201D i <a href='%s'>PayPals anv\344ndaravtal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Godk\344nnande f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godk\344nnandet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina kontoinst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p><p>Mer information finns i avsnittet \u201DF\366rgodk\344nda betalningar\u201D i <a href='%s'>PayPals anv\344ndaravtal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godk\344nnande f\366r framtida betalningar</strong></h1><p>En liten testtransaktion simuleras eventuellt med appen f\366r att se till att ditt PayPal-konto kan debiteras senare, men inga pengar \366verf\366rs.</p><p>PayPal-k\366pen betalas med den betalningsmetod du har angett som standard.</p><p>Om du vill avbryta godk\344nnandet loggar du in p\345 PayPal-kontot och g\345r till <strong>Min profil</strong> &gt; <strong>Mina kontoinst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och tar bort handlaren fr\345n listan.</p><p>Mer information finns i avsnittet \u201DF\366rgodk\344nda betalningar\u201D i <a href='%s'>PayPals anv\344ndaravtal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Avtal f\366r framtida betalningar</strong></h1><p>Vid k\366p dras pengar f\366rst fr\345n ditt PayPal-saldo. Om det inte t\344cker summan dras resterande summa fr\345n ditt bankkonto, PayPal Credit, betalkort, och/eller eCheck, i den ordningen.</p><p>G\345 till www.paypal.com <strong>Min profil</strong> &gt; <strong>Mina inst\344llningar</strong> &gt; <strong>Logga in med PayPal</strong> och ta bort handlaren fr\345n listan om du vill upph\344va avtalet.</p><p>Det kan h\344nda att en mindre betalning m\345ste godk\344nnas f\366r att ditt PayPal-konto ska kunna debiteras i framtiden. Godk\344nnandet annulleras sedan och du debiteras inte.</p>");
        b.put("LOG_IN_TO_PAYPAL|AU", "Logga in med PayPal");
        b.put("LOG_IN_TO_PAYPAL|GB", "Logga in med PayPal");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och klickar p\345 kugghjulssymbolen. G\345 till <strong>S\344kerhet</strong>, v\344lj <strong>Logga in med PayPal</strong> och ta bort den h\344r partnern.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n partnerns sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n partnerns sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och klickar p\345 kugghjulssymbolen. G\345 till <strong>S\344kerhet</strong>, v\344lj <strong>Logga in med PayPal</strong> och ta bort den h\344r partnern.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n partnerns sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och klickar p\345 kugghjulssymbolen. G\345 till <strong>S\344kerhet</strong>, v\344lj <strong>Logga in med PayPal</strong> och ta bort den h\344r partnern.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n partnerns sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och klickar p\345 kugghjulssymbolen l\344ngst upp till h\366ger. V\344lj sedan <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och tar bort handlaren. Om du fortfarande anv\344nder den gamla vyn ska du g\345 till <strong>Min profil</strong>, v\344lja <strong>Mina kontoinst\344llningar</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och g\345r till <strong>Min profil</strong> och tar sedan bort partnern under <strong>Logga in med PayPal</strong>.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n partnerns sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.it och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med partnern.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.ru och klickar p\345 kugghjulssymbolen l\344ngst upp till h\366ger. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r partnern.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n partnerns sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 ditt PayPal-konto och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com.tr och klickar p\345 kugghjulssymbolen l\344ngst upp till h\366ger. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r partnern.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till avsnittet <strong>Logga in med PayPal</strong> under inst\344llningarna f\366r <strong>Min profil</strong> och tar bort handlaren.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alla relevanta transaktionsuppgifter delas med handlaren.</p><p>Om du vill dra tillbaka ditt medgivande loggar du in p\345 paypal.com och g\345r till <strong>Min profil</strong>. V\344lj sedan fliken <strong>S\344kerhet</strong>, g\345 till avsnittet <strong>Logga in med PayPal</strong> och ta bort den h\344r handlaren.</p><p>PayPal ansvarar inte f\366r \345tg\344rder eller fel fr\345n handlarens sida.</p>");
        c.put("AMOUNT_MISMATCH", "Totalbeloppet f\366r objekten i kundvagnen matchar inte f\366rs\344ljningsbeloppet.");
        c.put("AUTHORIZATION_ALREADY_COMPLETED", "Godk\344nnandet har redan slutf\366rts.");
        c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godk\344nnandets nuvarande status g\366r att det inte kan annulleras.");
        c.put("AUTHORIZATION_EXPIRED", "Godk\344nnandet har g\345tt ut.");
        c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Det id f\366r godk\344nnande som har beg\344rts finns inte.");
        c.put("AUTHORIZATION_VOIDED", "Ditt godk\344nnande har annullerats.");
        c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Det g\345r endast att omgodk\344nna det ursprungliga godk\344nnandet, inte ett omgodk\344nnande.");
        c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Det \344r inte till\345tet att omgodk\344nna inom garantiperioden.");
        c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Beloppet \366verskrider den till\345tna gr\344nsen.");
        c.put("CARD_TOKEN_PAYER_MISMATCH", "Det gick inte att komma \345t de sparade kortuppgifterna.");
        c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortuppgifterna \344r ogiltiga. Korrigera och skicka igen.");
        c.put("CREDIT_CARD_REFUSED", "Kortet nekades.");
        c.put("CURRENCY_MISMATCH", "Inkasseringsvalutan m\345ste vara samma som valutan f\366r godk\344nnandet.");
        c.put("CURRENCY_NOT_ALLOWED", "Den h\344r valutan st\366ds inte f\366r n\344rvarande av PayPal.");
        c.put("DATA_RETRIEVAL", "Systemfel. F\366rs\366k igen senare.");
        c.put("DUPLICATE_REQUEST_ID", "Systemfel. F\366rs\366k igen senare.");
        c.put("EXPIRED_CREDIT_CARD", "Kortet har upph\366rt att g\344lla");
        c.put("EXPIRED_CREDIT_CARD_TOKEN", "Informationen f\366r det h\344r kortet finns inte l\344ngre sparad.\nSkicka igen.");
        c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funktionen st\366ds inte f\366r betalningsmottagaren.");
        c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Transaktionen har delvis \345terbetalats.");
        c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Direktbetalning st\366ds inte f\366r det h\344r.");
        c.put("INSTRUMENT_DECLINED", "Den betalningsmetod du valde godk\344ndes inte. V\344lj en annan betalningsmetod.");
        c.put("INSUFFICIENT_FUNDS", "K\366paren kan inte betala \u2013 pengar saknas.");
        c.put("INTERNAL_SERVICE_ERROR", "Systemfel. F\366rs\366k igen senare.");
        c.put("INVALID_ACCOUNT_NUMBER", "Kontonumret finns inte.");
        c.put("INVALID_ARGUMENT", "Transaktionen nekades p\345 grund av ett ogiltigt argument");
        c.put("INVALID_CITY_STATE_ZIP", "Ogiltig kombination av ort/delstat/postnummer.");
        c.put("INVALID_FACILITATOR_CONFIGURATION", "Den h\344r transaktionen kan inte behandlas p\345 grund av ogiltig konfiguration hos partnern.");
        c.put("INVALID_PAYER_ID", "Systemfel (betalarens id \344r ogiltigt). F\366rs\366k igen senare.");
        c.put("INVALID_RESOURCE_ID", "Systemfel. F\366rs\366k igen senare.");
        c.put("PAYEE_ACCOUNT_INVALID", "Det finns ingen bekr\344ftad e-postadress f\366r betalningsmottagarens konto.");
        c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Den h\344r s\344ljaren kan inte ta emot betalningar just nu.");
        c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Det finns ingen bekr\344ftad e-postadress f\366r betalningsmottagarens konto.");
        c.put("PAYEE_ACCOUNT_RESTRICTED", "Den h\344r s\344ljaren kan inte ta emot betalningar just nu.");
        c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Ditt konto \344r sp\344rrat eller st\344ngt.");
        c.put("PAYER_ACCOUNT_RESTRICTED", "Ditt konto \344r begr\344nsat.");
        c.put("PAYER_CANNOT_PAY", "Du kan inte betala den h\344r transaktionen med PayPal.");
        c.put("PAYER_EMPTY_BILLING_ADDRESS", "Faktureringsadress kr\344vs f\366r korttransaktioner som inte g\366rs med PayPal.");
        c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Det gick inte att komma \345t de sparade kortuppgifterna.");
        c.put("PAYMENT_APPROVAL_EXPIRED", "Godk\344nnandet av betalningen har upph\366rt att g\344lla.");
        c.put("PAYMENT_EXPIRED", "Betalningen har upph\366rt att g\344lla.");
        c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betalaren inte har godk\344nt betalningen.");
        c.put("PAYMENT_REQUEST_ID_INVALID", "PayPals id f\366r beg\344ran \344r ogiltigt. F\366rs\366k igen senare.");
        c.put("PAYMENT_STATE_INVALID", "Denna beg\344ran \344r ogiltig p\345 grund av betalningens nuvarande status.");
        c.put("PERMISSION_DENIED", "Det finns inget tillst\345nd f\366r den beg\344rda \345tg\344rden.");
        c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den beg\344rda \345terbetalningen \366verskrider beloppet f\366r den ursprungliga transaktionen.");
        c.put("REFUND_TIME_LIMIT_EXCEEDED", "Transaktionen \344r f\366r gammal f\366r att \345terbetalas.");
        c.put("REQUIRED_SCOPE_MISSING", "Systemfel. F\366rs\366k igen senare.");
        c.put("TOO_MANY_REAUTHORIZATIONS", "Inga fler omgodk\344nnanden \344r till\345tna f\366r det h\344r godk\344nnandet.");
        c.put("TRANSACTION_ALREADY_REFUNDED", "Transaktionen har redan \345terbetalats.");
        c.put("TRANSACTION_LIMIT_EXCEEDED", "Beloppet \366verskrider den till\345tna gr\344nsen.");
        c.put("TRANSACTION_REFUSED", "Transaktionen nekades.");
        c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaktionen nekades.");
        c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Handlarens profil \344r inst\344lld p\345 att automatiskt neka vissa transaktioner.");
        c.put("UNKNOWN_ERROR", "Systemfel. F\366rs\366k igen senare.");
        c.put("UNSUPPORTED_PAYEE_COUNTRY", "Landet st\366ds inte.");
        c.put("VALIDATION_ERROR", "Betalningsuppgifterna \344r ogiltiga. Korrigera och skicka igen.");
        c.put("ORDER_ALREADY_COMPLETED", "Best\344llningen har redan annullerats, g\345tt ut eller slutf\366rts.");
        c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "H\366gsta antal till\345tna tillst\345nd f\366r best\344llningen har uppn\345tts.");
        c.put("ORDER_VOIDED", "Din order har annullerats.");
        c.put("ORDER_CANNOT_BE_VOIDED", "Best\344llningen \344r i ett skede som inte medger annullering.");
        c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfel. F\366rs\366k igen senare.");
        c.put("UNAUTHORIZED_PAYMENT", "Handlaren tar inte emot den h\344r betalningstypen.");
        c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valutan st\366ds inte f\366r korttypen.");
        c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen st\366ds inte.");
        c.put("ADDRESS_ADDITION_ERROR", "Fel p\345tr\344ffades n\344r en leveransadress skulle l\344ggas till PayPal-kontot.");
        c.put("DUPLICATE_TRANSACTION", "Dubblettransaktion.");
        c.put("INVALID_SHIPPING_ADDRESS", "Den angivna leveransadressen \344r ogiltig.");
        c.put("PAYMENT_CREATION_ERROR", "Det uppstod ett problem n\344r betalningen skulle registreras. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Det uppstod ett problem n\344r betalningen skulle registreras \u2013 kortet har upph\366rt att g\344lla. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Det uppstod ett problem n\344r betalningen skulle registreras \u2013 direktbetalning kr\344vs, t.ex. med ett betalkort. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Det uppstod ett problem n\344r betalningen skulle registreras \u2013 kortet m\345ste bekr\344ftas. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Det uppstod ett problem n\344r betalningen skulle registreras \u2013 kontot m\345ste inneh\345lla ett telefonnummer enligt villkoren f\366r appen. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Det uppstod ett problem n\344r betalningen skulle registreras \u2013 kontot beh\366ver en giltig betalningsmetod, t.ex. ett bankkonto eller betalkort. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Det uppstod ett problem n\344r betalningen skulle registreras \u2013 saldot \344r \366vertrasserat. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Det uppstod ett problem n\344r betalningen skulle registreras \u2013 du har kommit upp till \366verf\366ringsgr\344nsen. Kontrollera ditt konto p\345 PayPals webbplats.");
        c.put("AUTH_RC_RISK_FAILURE", "Nekad p\345 grund av risk.");
        c.put("AUTH_RC_OFAC_BLOCKED_IP", "Obeh\366rig klient.");
        c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Obeh\366rig klient.");
        c.put("invalid_user", "Fel anv\344ndarnamn/l\366senord. F\366rs\366k igen.");
        c.put("locked_user", "Ditt PayPal-konto har tillf\344lligt l\345sts. F\366rs\366k igen senare eller g\345 till www.paypal.com f\366r att l\345sa upp ditt PayPal-konto direkt.");
        c.put("max_attempts_exceeded", "F\366r m\345nga misslyckade inloggningsf\366rs\366k. F\366rs\366k igen senare.");
        c.put("invalid_request", "Ett fel har intr\344ffat.");
        c.put("unauthorized_client", "Beg\344ran medges ej.");
        c.put("access_denied", "Beg\344ran medges ej.");
        c.put("unsupported_response_type", "Ett fel har intr\344ffat.");
        c.put("invalid_scope", "Beg\344ran medges ej.");
        c.put("server_error", "Systemfel. F\366rs\366k igen senare.");
        c.put("temporarily_unavailable", "Systemfel. F\366rs\366k igen senare.");
        c.put("stepup_required", "Det g\345r inte att slutf\366ra din inloggning just nu. F\366rs\366k igen senare eller g\345 till www.paypal.com om du har n\345gra s\344kerhetsfr\345gor om ditt PayPal-konto.");
    }

    public final String a()
    {
        return "sv";
    }

    public final String a(Enum enum, String s)
    {
        enum = (fa)enum;
        s = (new StringBuilder()).append(enum.toString()).append("|").append(s).toString();
        if (b.containsKey(s))
        {
            return (String)b.get(s);
        } else
        {
            return (String)a.get(enum);
        }
    }

    public final String a(String s)
    {
        return (String)c.get(s);
    }

}
