// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

// Referenced classes of package com.paypal.android.sdk:
//            ig, fa

public final class kh
    implements ig
{

    private static final Map a = new HashMap();
    private static final Map b = new HashMap();
    private static final Map c = new HashMap();

    public kh()
    {
        a.put(fa.a, "Accepter og betal");
        a.put(fa.b, "og andre");
        a.put(fa.c, "Godkender");
        a.put(fa.d, "Tilbage");
        a.put(fa.e, "Alternativ");
        a.put(fa.f, "Annuller");
        a.put(fa.g, "American Express");
        a.put(fa.h, "Carta Aura");
        a.put(fa.i, "Carte Aurore");
        a.put(fa.j, "Carta Prepagata PayPal");
        a.put(fa.k, "Carte Bancaire");
        a.put(fa.l, "Cofinoga");
        a.put(fa.m, "Delta");
        a.put(fa.n, "Discover");
        a.put(fa.o, "Electron");
        a.put(fa.p, "JCB");
        a.put(fa.q, "Maestro");
        a.put(fa.r, "MasterCard");
        a.put(fa.s, "Postepay");
        a.put(fa.t, "4 \351toiles");
        a.put(fa.u, "Tarjeta Aurora");
        a.put(fa.v, "Visa");
        a.put(fa.w, "Skift betalingsmetode");
        a.put(fa.x, "Checkkonto");
        a.put(fa.y, "Kontrollerer enheden \u2026");
        a.put(fa.z, "Slet kortoplysninger");
        a.put(fa.A, "Bekr\346ft");
        a.put(fa.B, "Er du sikker p\345, at du vil slette kortoplysningerne?");
        a.put(fa.C, "Tr\346k p\345 kort");
        a.put(fa.D, "Vil du logge af PayPal?");
        a.put(fa.E, "Betal");
        a.put(fa.F, "Accepter");
        a.put(fa.G, "Dato for oprettelse af konto");
        a.put(fa.H, "Kontostatus");
        a.put(fa.I, "Kontotype");
        a.put(fa.J, "Adresse");
        a.put(fa.K, "Aldersgruppe");
        a.put(fa.L, "F\370dselsdato");
        a.put(fa.M, "E-mailadresse");
        a.put(fa.N, "Fulde navn");
        a.put(fa.O, "K\370n");
        a.put(fa.P, "Sprog");
        a.put(fa.Q, "Landestandard");
        a.put(fa.R, "Telefon");
        a.put(fa.S, "Tidszone");
        a.put(fa.T, "Del f\370lgende: %s.");
        a.put(fa.U, "Brug nem betaling.");
        a.put(fa.V, "%s beder dig om at:");
        a.put(fa.W, "Del de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        a.put(fa.X, "Aktiver visning af dine betalingsm\345der, s\345 du kan v\346lge.");
        a.put(fa.Y, "<a href='%1$s'>Godkende, at der tr\346kkes penge</a> for fremtidige k\370b hos %2$s, der betales via PayPal. Du beder os om at betale alle de bel\370b, som %3$s anmoder om.");
        a.put(fa.Z, "Give dem tilladelse til at tilf\370je og administrere deres loyalitetskort i din PayPal-pung.");
        a.put(fa.aa, "Acceptere <a href='%2$s'>politikken om beskyttelse af personlige oplysninger</a> og <a href='%3$s'>brugeraftalen</a> for %1$s.");
        a.put(fa.ab, "Giv dem tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        a.put(fa.ac, "Giv dem tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        a.put(fa.ad, "Samtykke");
        a.put(fa.ae, "E-mail");
        a.put(fa.af, "Simulerede data");
        a.put(fa.ag, "Sandbox");
        a.put(fa.ah, "Udl\370ber");
        a.put(fa.ai, "<h1><strong>Betalingsm\345der</strong></h1><p>PayPal deler kun oplysninger om, hvilke af dine betalingsmetoder der kan bruges.</p>");
        a.put(fa.aj, "Glemt adgangskoden?");
        a.put(fa.ak, "Fra");
        a.put(fa.al, "Hvordan vil du gerne betale %1$s i fremtiden?");
        a.put(fa.am, "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Din foretrukne betalingsm\345de bruges til at betale for fremtidige PayPal-betalinger til denne webbutik.</p><p>Hvis du vil annullere denne aftale, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Afsnittet Fast betaling i <a href='%s'>PayPals brugeraftale</a> finder anvendelse.</p><p>Appen kan simulere en lille pr\370vetransaktion for at sikre, at du kan betale med din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p>");
        a.put(fa.an, "Intern fejl");
        a.put(fa.ao, "<p>Ved at klikke p\345 knappen nedenfor accepterer jeg vilk\345rene i <a href='%1$s'>PayPals brugeraftale</a>, og jeg erkl\346rer mig i overensstemmelse med japanske love og regler, herunder sanktioner mod betalinger til Nordkorea og Iran i henhold til <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> for at gennemf\370re transaktionen.</p>");
        a.put(fa.ap, "Log p\345");
        a.put(fa.aq, "Log p\345 med PayPal");
        a.put(fa.ar, "Log af");
        a.put(fa.as, "Log af");
        a.put(fa.at, "OK");
        a.put(fa.au, "Adgangskode");
        a.put(fa.av, "Betal efter levering");
        a.put(fa.aw, "Betal med");
        a.put(fa.ax, "Betal med kort");
        a.put(fa.ay, "PayPal-saldo");
        a.put(fa.az, "PayPal Credit");
        a.put(fa.aA, "Telefon");
        a.put(fa.aB, "Pinkode");
        a.put(fa.aC, "Foretrukken betalingsmetode");
        a.put(fa.aD, "Vi beskytter dine <a href='%s'>personlige oplysninger</a> og betalingsoplysninger.");
        a.put(fa.aE, "Behandler");
        a.put(fa.aF, "Husk kort");
        a.put(fa.aG, "Anmod om penge");
        a.put(fa.aH, "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke tilladelsen tilbage, skal du logge p\345 paypal.com, g\345 til sektionen <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>Vi er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        a.put(fa.aI, "Opsparingskonto");
        a.put(fa.aJ, "Overf\370r penge");
        a.put(fa.aK, "Der kunne ikke oprettes forbindelse til vores servere. Pr\370v igen.");
        a.put(fa.aL, "Log p\345 PayPal igen.");
        a.put(fa.aM, "Sessionen er udl\370bet");
        a.put(fa.aN, "Forsendelsesadresse");
        a.put(fa.aO, "Har du ikke en PayPal-konto? Opret konto");
        a.put(fa.aP, "Forbliv logget p\345");
        a.put(fa.aQ, "Systemfejl (%s). Pr\370v igen senere.");
        a.put(fa.aR, "Pr\370v igen");
        a.put(fa.aS, "Der kunne ikke logges p\345, da to-faktor-godkendelse er aktiveret for din konto.");
        a.put(fa.aT, "Sikkerhedskode");
        a.put(fa.aU, "Send en sms til din telefon. Den 6-cifrede kode, som du modtager, er gyldig i 5 minutter.");
        a.put(fa.aV, "Afsende sms");
        a.put(fa.aW, "Angiv den 6-cifrede sikkerhedskode");
        a.put(fa.aX, "Dit mobilnummer");
        a.put(fa.aY, "Send sms");
        a.put(fa.aZ, "Send sms igen");
        a.put(fa.ba, "Der kunne ikke logges p\345, da to-faktor-godkendelse er aktiveret for din konto. G\345 til vores websted for at aktivere din sikkerhedsn\370gle.");
        a.put(fa.bb, "Du kan ikke betale med denne enhed.");
        a.put(fa.bc, "Uautoriseret enhed");
        a.put(fa.bd, "Du kan ikke betale denne webbutik (ugyldigt klient-id).");
        a.put(fa.be, "Ugyldig webbutik");
        a.put(fa.bf, "Betalingen blev ikke behandlet. Pr\370v igen.");
        a.put(fa.bg, "Ukendt betalingsmetode");
        a.put(fa.bh, "Vi beklager");
        a.put(fa.bi, "Din bestilling");
        a.put(fa.bj, "Vil du slette kortet?");
        a.put(fa.bk, "Samtykke mislykkedes");
        a.put(fa.bl, "Der blev ikke oprettet forbindelse");
        a.put(fa.bm, "Du blev ikke logget p\345");
        a.put(fa.bn, "Log p\345 med adgangskode");
        a.put(fa.bo, "Log p\345 med pinkode");
        a.put(fa.bp, "Et \370jeblik \u2026");
        a.put(fa.bq, "Betalingen blev ikke gennemf\370rt.");
        a.put(fa.br, "Skan");
        a.put(fa.bs, "Forkert sikkerhedskode. Pr\370v igen.");
        a.put(fa.bt, "Via");
        a.put(fa.bu, "Systemfejl. Pr\370v igen senere.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Del oplysninger om de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Del oplysningerne om de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Del oplysninger om de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Del oplysninger om de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Del oplysninger om de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Del oplysninger med vedkommende om de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Del de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Del de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Del oplysningerne om de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Del oplysninger om de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Del oplysningerne om de <a href='%1$s'>betalingsm\345der</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Del oplysninger om de <a href='%1$s'>betalingsmetoder</a>, der er tilknyttet din PayPal-konto.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Del dine <a href='%1$s'>betalingsm\345der</a> med andre, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkende, at der tr\346kkes penge</a> for fremtidige k\370b hos %2$s, der betales via PayPal. Du beder os om at betale alle de bel\370b, som %3$s anmoder om.</p><p>L\346s <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>vores aftale om faste betalinger og fakturering</a> for at f\345 flere oplysninger.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkende, at der tr\346kkes penge</a> for fremtidige k\370b hos %2$s, der betales via PayPal. Du beder os om at betale alle de bel\370b, som %3$s anmoder om.</p><p>L\346s <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>vores aftale om faste betalinger og fakturering</a> for at f\345 flere oplysninger.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Godkend, at der tr\346kkes penge</a> for fremtidige k\370b, der betales via PayPal. Du beder PayPal om at betale alle bel\370b og godkender dette.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Godkend, at der tr\346kkes penge</a> for fremtidige k\370b, der betales via PayPal. Du beder PayPal om at betale alle bel\370b og godkender dette.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Godkend, at der tr\346kkes penge</a> for fremtidige k\370b, der betales via PayPal. Du beder PayPal om at betale alle bel\370b og godkender dette.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Godkend p\345 forh\345nd fremtidige betalinger fra din PayPal-konto uden at logge p\345 PayPal hver gang. <a href='%1$s'>Se flere vilk\345r</a>, blandt andet betalingsmetoder, og hvordan du annullerer fremtidige betalinger.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Give %2$s tilladelse til at <a href='%1$s'>anmode om penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Give %2$s tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Give %2$s tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Give %2$s tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Give %2$s tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Give %2$s tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Give %2$s tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Give %2$s tilladelse til at <a href='%1$s'>overf\370re penge</a> p\345 dine vegne, indtil du tr\346kker din tilladelse tilbage.");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Betalingsmetoder</strong></h1><p>Vi deler kun oplysninger om, hvilke af dine betalingsm\345der, der kan bruges.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\370vetransaktion for at sikre, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode (din PayPal-saldo, din tilknyttede bankkonto eller dit betalingskort i denne r\346kkef\370lge) vil blive brugt, n\345r du betaler med PayPal. Bem\346rk, at din bank eller kortudsteder muligvis opkr\346ver et gebyr, hvis der ikke er nok penge til at d\346kke k\370bet med din foretrukne betalingsmetode.</p><p>Hvis du vil annullere denne aftale, skal du logge p\345 din PayPal-konto og g\345 til <strong>Min profil</strong>. Klik derefter p\345 <strong>Mine indstillinger</strong> og <strong>Skift</strong> ud for \u201CLog p\345 med PayPal\u201D.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\370vetransaktion for at kontrollere, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din PayPal-saldo eller det prim\346re betalingskort vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\370vetransaktion for at sikre, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge p\345 din PayPal-konto og g\345 til <strong>Min profil</strong> &gt; <strong>Indstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Din foretrukne betalingsm\345de vil blive brugt, n\345r du betaler med PayPal igen i denne webbutik.</p><p>Hvis du vil annullere aftalen, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Afsnittet Faste betalinger i <a href='%s'>PayPals brugeraftale</a> g\346lder.</p><p>Appen kan simulere en lille pr\370vebetaling for at kontrollere, at du kan betale med din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\370vebetaling for at kontrollere, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201CForh\345ndsgodkendte betalinger\u201D i vores <a href='%s'>brugeraftale</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\370vetransaktion for at sikre, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201CForh\345ndsgodkendte betalinger\u201D i <a href='%s'>vores brugeraftale</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Appen kan simulere en lille pr\370vetransaktion for at kontrollere, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din PayPal-saldo eller det prim\346re betalingskort vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere denne aftale, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne denne webbutik fra listen.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\370vebetaling for at kontrollere, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201CForh\345ndsgodkendte betalinger\u201D i vores <a href='%s'>brugeraftale</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\370vebetaling for at kontrollere, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201CForh\345ndsgodkendte betalinger\u201D i vores <a href='%s'>brugeraftale</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkendelse af fremtidig betaling</strong></h1><p>Appen kan simulere en lille pr\370vebetaling for at kontrollere, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden, men der vil ikke blive trukket nogen penge.</p><p>Din foretrukne betalingsmetode vil blive brugt, n\345r du betaler med PayPal.</p><p>Hvis du vil annullere autorisationen, skal du logge p\345 din PayPal-konto, g\345 til <strong>Min profil</strong> &gt; <strong>Mine kontoindstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne webbutikken fra listen.</p><p>Du kan finde flere oplysninger i afsnittet \u201CForh\345ndsgodkendte betalinger\u201D i vores <a href='%s'>brugeraftale</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsaftale</strong></h1><p>Vi tr\346kker f\370rst penge p\345 din PayPal-saldo for at betale for dit k\370b. Hvis der ikke er penge nok p\345 saldoen, tr\346kker vi pengene via din bankkonto, PayPal Credit, dit betalingskort og/eller eCheck i denne r\346kkef\370lge.</p><p>Hvis du vil annullere denne aftale, skal du g\345 til www.paypal.com, v\346lge <strong>Min profil</strong> &gt; <strong>Mine indstillinger</strong> &gt; <strong>Log p\345 med PayPal</strong> og fjerne denne webbutik fra listen.</p><p>Det kan v\346re n\370dvendigt, at du autoriserer en lille betaling for at kontrollere, at der kan tr\346kkes penge p\345 din PayPal-konto i fremtiden. Betalingen vil blive annulleret, og der vil ikke blive trukket nogen penge.</p>");
        b.put("LOG_IN_TO_PAYPAL|AU", "Log p\345 med PayPal");
        b.put("LOG_IN_TO_PAYPAL|GB", "Log p\345 med PayPal");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto og klikke p\345 tandhjulsikonet. G\345 til <strong>Sikkerhed</strong>, v\346lg <strong>Log p\345 med PayPal</strong>, og fjern partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke tilladelsen tilbage, skal du logge p\345 paypal.com, g\345 til sektionen <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne forhandleren.</p><p>Vi er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto, g\345 til <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto og klikke p\345 tandhjulsikonet. G\345 til <strong>Sikkerhed</strong>, v\346lg <strong>Log p\345 med PayPal</strong>, og fjern partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto og klikke p\345 tandhjulsikonet. G\345 til <strong>Sikkerhed</strong>, v\346lg <strong>Log p\345 med PayPal</strong>, og fjern partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto, g\345 til <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal p\345 logge p\345 din PayPal-konto, klikke p\345 tandhjulsikonet \370verst til h\370jre, v\346lge <strong>Sikkerhedscentret</strong>, v\346lge <strong>Log p\345 med PayPal</strong> og fjerne webbutikken. Hvis du stadig bruger det tidligere kontolayout, skal du g\345 til <strong>Min profil</strong>, v\346lge <strong>Mine kontoindstillinger</strong>, v\346lge <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>Vi er ikke ansvarlig for nogen af webbutikkens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal p\345 logge p\345 din PayPal-konto, g\345 til <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.it, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, finde sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto, g\345 til <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto, g\345 til <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto, g\345 til <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med partneren.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.ru, klikke p\345 tandhjulsikonet \370verst til h\370jre, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong>og fjerne partneren.</p><p>PayPal er ikke ansvarlig for nogen af partnerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 din PayPal-konto, g\345 til <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.tr, klikke p\345 tandhjulsikonet \370verst til h\370jre, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong>og fjerne partneren.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke tilladelsen tilbage, skal du logge p\345 paypal.com, g\345 til sektionen <strong>Log p\345 med PayPal</strong> under <strong>Min profil</strong> og fjerne webbutikken.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevante oplysninger om betalingen deles med webbutikken.</p><p>Hvis du vil tr\346kke din tilladelse tilbage, skal du logge p\345 paypal.com, g\345 til <strong>Min profil</strong>, v\346lge fanen <strong>Sikkerhed</strong>, g\345 til sektionen <strong>Log p\345 med PayPal</strong> og fjerne webbutikken.</p><p>PayPal er ikke ansvarlig for nogen af forhandlerens handlinger eller fejl.</p>");
        c.put("AMOUNT_MISMATCH", "Bel\370bet i indk\370bskurv stemmer ikke overens med salgsbel\370b.");
        c.put("AUTHORIZATION_ALREADY_COMPLETED", "Autorisationen er allerede blevet gennemf\370rt.");
        c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autorisationen er i en tilstand, der ikke kan annulleres.");
        c.put("AUTHORIZATION_EXPIRED", "Autorisationen er udl\370bet.");
        c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Det anmodede autorisations-id findes ikke.");
        c.put("AUTHORIZATION_VOIDED", "Din autorisation er blevet ugyldiggjort.");
        c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Du kan kun gentage den oprindelige autorisation igen og ikke en allerede gentaget autorisation.");
        c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Du m\345 ikke gentage en autorisation igen inden for garantiperioden.");
        c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Bel\370bet overstiger den tilladte gr\346nse.");
        c.put("CARD_TOKEN_PAYER_MISMATCH", "Kan ikke f\345 adgang til de gemte kortoplysninger.");
        c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortoplysningerne er ugyldige. Ret oplysningerne, og send dem igen.");
        c.put("CREDIT_CARD_REFUSED", "Kortet blev afvist.");
        c.put("CURRENCY_MISMATCH", "Valuta for hentning skal v\346re den samme som valutaen for tilladelsen.");
        c.put("CURRENCY_NOT_ALLOWED", "Denne valuta er i \370jeblikket ikke underst\370ttet af PayPal.");
        c.put("DATA_RETRIEVAL", "Systemfejl. Pr\370v igen senere.");
        c.put("DUPLICATE_REQUEST_ID", "Systemfejl. Pr\370v igen senere.");
        c.put("EXPIRED_CREDIT_CARD", "Kortet er udl\370bet");
        c.put("EXPIRED_CREDIT_CARD_TOKEN", "Oplysningerne for dette kort er ikke l\346ngere gemt.\nSend igen.");
        c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Butikken underst\370tter ikke denne funktion i \370jeblikket.");
        c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne betaling er allerede blevet delvist tilbagebetalt.");
        c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Den overf\370rte hensigt underst\370tter ikke \370jeblikkelig betaling.");
        c.put("INSTRUMENT_DECLINED", "Den valgte betalingsmetode blev ikke godkendt. V\346lg en anden betalingsmetode.");
        c.put("INSUFFICIENT_FUNDS", "Kunden kan ikke betale \u2013 der er ikke penge nok.");
        c.put("INTERNAL_SERVICE_ERROR", "Systemfejl. Pr\370v igen senere.");
        c.put("INVALID_ACCOUNT_NUMBER", "Kontonummeret findes ikke.");
        c.put("INVALID_ARGUMENT", "Betalingen blev afvist p\345 grund af et ugyldigt argument");
        c.put("INVALID_CITY_STATE_ZIP", "Ugyldig kombination af by, omr\345de og/eller postnummer.");
        c.put("INVALID_FACILITATOR_CONFIGURATION", "Denne betaling kan ikke behandles p\345 grund af en ugyldig formidlerkonfiguration.");
        c.put("INVALID_PAYER_ID", "Systemfejl (ugyldigt betaler-id). Pr\370v igen senere.");
        c.put("INVALID_RESOURCE_ID", "Systemfejl. Pr\370v igen senere.");
        c.put("PAYEE_ACCOUNT_INVALID", "S\346lgerkontoen har ikke en en bekr\346ftet e-mailadresse.");
        c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Denne s\346lger kan ikke tage imod betalinger i \370jeblikket.");
        c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "S\346lgerkontoen har ikke en en bekr\346ftet e-mailadresse.");
        c.put("PAYEE_ACCOUNT_RESTRICTED", "Denne s\346lger kan ikke tage imod betalinger i \370jeblikket.");
        c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Din konto er l\345st eller lukket.");
        c.put("PAYER_ACCOUNT_RESTRICTED", "Din konto er begr\346nset.");
        c.put("PAYER_CANNOT_PAY", "Du kan ikke bruge PayPal til denne betaling.");
        c.put("PAYER_EMPTY_BILLING_ADDRESS", "Der skal angives en faktureringsadresse ved de kortbetalinger, der ikke foretages via PayPal.");
        c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Kan ikke f\345 adgang til gemte kortoplysninger.");
        c.put("PAYMENT_APPROVAL_EXPIRED", "Godkendelsen af betalingen er udl\370bet.");
        c.put("PAYMENT_EXPIRED", "Betalingen er udl\370bet.");
        c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godkendt betalingen.");
        c.put("PAYMENT_REQUEST_ID_INVALID", "Id\u2019et for PayPal-anmodningen er ugyldigt. Pr\370v igen senere.");
        c.put("PAYMENT_STATE_INVALID", "Denne anmodning er ugyldig p\345 grund af den aktuelle tilstand for betaling.");
        c.put("PERMISSION_DENIED", "Du har ikke tilladelse til at udf\370re handlingen.");
        c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den anmodede tilbagebetaling overstiger det oprindelige bel\370b.");
        c.put("REFUND_TIME_LIMIT_EXCEEDED", "Du kan ikke l\346ngere f\345 tilbagebetalt denne betaling.");
        c.put("REQUIRED_SCOPE_MISSING", "Systemfejl. Pr\370v igen senere.");
        c.put("TOO_MANY_REAUTHORIZATIONS", "Du m\345 ikke gentage denne autorisation flere gange.");
        c.put("TRANSACTION_ALREADY_REFUNDED", "Betalingen er allerede blevet tilbagebetalt.");
        c.put("TRANSACTION_LIMIT_EXCEEDED", "Bel\370bet overstiger den tilladte gr\346nse.");
        c.put("TRANSACTION_REFUSED", "Betalingen blev afvist.");
        c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Betalingen blev afvist.");
        c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Indstillingen for webbutikken er angivet til automatisk at afvise bestemte betalinger.");
        c.put("UNKNOWN_ERROR", "Systemfejl. Pr\370v igen senere.");
        c.put("UNSUPPORTED_PAYEE_COUNTRY", "Dit land underst\370ttes ikke.");
        c.put("VALIDATION_ERROR", "Betalingsoplysningerne er ugyldige. Ret oplysningerne, og send dem igen.");
        c.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede blevet annulleret, er udl\370bet eller er blevet sendt.");
        c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Det maksimale antal autorisationer for bestillingen er n\345et.");
        c.put("ORDER_VOIDED", "Bestillingen er blevet annulleret.");
        c.put("ORDER_CANNOT_BE_VOIDED", "Bestillingen kan ikke annulleres.");
        c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfejl. Pr\370v igen senere.");
        c.put("UNAUTHORIZED_PAYMENT", "Du kan ikke bruge denne betalingsmetode i denne webbutik.");
        c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Du kan ikke betale med kortet i denne valuta.");
        c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen underst\370ttes ikke.");
        c.put("ADDRESS_ADDITION_ERROR", "Der opstod fejl, da leveringsadressen blev f\370jet til din PayPal-konto.");
        c.put("DUPLICATE_TRANSACTION", "Duplikeret betaling.");
        c.put("INVALID_SHIPPING_ADDRESS", "Det angivne leveringsadresse er ugyldig.");
        c.put("PAYMENT_CREATION_ERROR", "Betalingen blev ikke oprettet. G\345 til vores websted for at kontrollere din konto.");
        c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Betalingen blev ikke oprettet. Dit kort er udl\370bet. G\345 til vores websted for at kontrollere din konto.");
        c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Betalingen blev ikke oprettet. Du skal betale med det samme, f.eks. med et betalingskort. G\345 til vores websted for at kontrollere din konto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Betalingen blev ikke oprettet. Du skal bekr\346fte dit kort. G\345 til vores websted for at kontrollere din konto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Betalingen blev ikke oprettet. Du skal tilknytte et telefonnummer for at bruge denne app. G\345 til vores websted for at kontrollere din konto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Betalingen blev ikke oprettet. Du skal knytte en gyldig betalingsm\345de til kontoen, f.eks. et betalingskort. G\345 til vores websted for at kontrollere din konto.");
        c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Betalingen blev ikke oprettet. Der er et underskud p\345 din konto. G\345 til vores websted for at kontrollere din konto.");
        c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Betalingen blev ikke oprettet. Dit loft for overf\370rsel af penge er n\345et. G\345 til vores websted for at kontrollere din konto.");
        c.put("AUTH_RC_RISK_FAILURE", "Afvist p\345 grund af risiko.");
        c.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkendt.");
        c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkendt.");
        c.put("invalid_user", "Forkert brugernavn/adgangskode. Pr\370v igen.");
        c.put("locked_user", "Din PayPal-konto er blevet midlertidigt l\345st. Pr\370v igen senere, eller g\345 til www.paypal.com for straks at l\345se din PayPal-konto op.");
        c.put("max_attempts_exceeded", "Du har fors\370gt at logge p\345 din konto for mange gange. Pr\370v igen senere.");
        c.put("invalid_request", "Der opstod en fejl.");
        c.put("unauthorized_client", "Anmodningen blev ikke godkendt.");
        c.put("access_denied", "Anmodningen blev ikke godkendt.");
        c.put("unsupported_response_type", "Der opstod en fejl.");
        c.put("invalid_scope", "Anmodningen blev ikke godkendt.");
        c.put("server_error", "Systemfejl. Pr\370v igen senere.");
        c.put("temporarily_unavailable", "Systemfejl. Pr\370v igen senere.");
        c.put("stepup_required", "Du kan ikke logge p\345 i \370jeblikket. Pr\370v igen senere, eller g\345 til www.paypal.dk for at l\370se eventuelle sikkerhedsproblemer med din PayPal-konto.");
    }

    public final String a()
    {
        return "da";
    }

    public final String a(Enum enum, String s)
    {
        enum = (fa)enum;
        s = (new StringBuilder()).append(enum.toString()).append("|").append(s).toString();
        if (b.containsKey(s))
        {
            return (String)b.get(s);
        } else
        {
            return (String)a.get(enum);
        }
    }

    public final String a(String s)
    {
        return (String)c.get(s);
    }

}
