// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

// Referenced classes of package com.paypal.android.sdk:
//            ig, fa

public final class li
    implements ig
{

    private static final Map a = new HashMap();
    private static final Map b = new HashMap();
    private static final Map c = new HashMap();

    public li()
    {
        a.put(fa.a, "Zustimmen und zahlen");
        a.put(fa.b, "und andere");
        a.put(fa.c, "Authentifizierung");
        a.put(fa.d, "Zur\374ck");
        a.put(fa.e, "Alternative");
        a.put(fa.f, "Abbrechen");
        a.put(fa.g, "American Express");
        a.put(fa.h, "Carta Aura");
        a.put(fa.i, "Carte Aurore");
        a.put(fa.j, "Carta Prepagata PayPal");
        a.put(fa.k, "Carte Bancaire");
        a.put(fa.l, "Cofinoga");
        a.put(fa.m, "Delta");
        a.put(fa.n, "Discover");
        a.put(fa.o, "Electron");
        a.put(fa.p, "JCB");
        a.put(fa.q, "Maestro");
        a.put(fa.r, "MasterCard");
        a.put(fa.s, "Postepay");
        a.put(fa.t, "4 \351toiles");
        a.put(fa.u, "Tarjeta Aurora");
        a.put(fa.v, "Visa");
        a.put(fa.w, "Zahlungsmethode \344ndern");
        a.put(fa.x, "Girokonto");
        a.put(fa.y, "Ger\344t wird \374berpr\374ft\u2026");
        a.put(fa.z, "Kreditkartendaten l\366schen");
        a.put(fa.A, "Best\344tigen");
        a.put(fa.B, "M\366chten Sie Ihre Kreditkartendaten wirklich l\366schen?");
        a.put(fa.C, "Kreditkarte belasten");
        a.put(fa.D, "M\366chten Sie sich wirklich ausloggen?");
        a.put(fa.E, "Zahlen");
        a.put(fa.F, "Zustimmen");
        a.put(fa.G, "Konto er\366ffnet am");
        a.put(fa.H, "Kontostatus");
        a.put(fa.I, "Kontotyp");
        a.put(fa.J, "Adresse");
        a.put(fa.K, "Altersgruppe");
        a.put(fa.L, "Geburtsdatum");
        a.put(fa.M, "E-Mail-Adresse");
        a.put(fa.N, "Vollst\344ndiger Name");
        a.put(fa.O, "Geschlecht");
        a.put(fa.P, "Sprache");
        a.put(fa.Q, "L\344ndereinstellung");
        a.put(fa.R, "Telefon");
        a.put(fa.S, "Zeitzone");
        a.put(fa.T, "Folgende Informationen weitergeben: %s.");
        a.put(fa.U, "PayPal Express verwenden.");
        a.put(fa.V, "%s bittet um folgende Zustimmung:");
        a.put(fa.W, "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        a.put(fa.X, "Zahlungsquellen anzeigen, damit Sie bei der Zahlung w\344hlen k\366nnen.");
        a.put(fa.Y, "Sie <a href='%1$s'>autorisieren Abbuchungen f\374r zuk\374nftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Betr\344ge zu zahlen.");
        a.put(fa.Z, "Sie stimmen zu, dass der H\344ndler seine Kundenkarte Ihrer E-B\366rse hinzuf\374gt und sie dort verwaltet.");
        a.put(fa.aa, "Sie stimmen den <a href='%2$s'>Datenschutzgrunds\344tzen</a> und den <a href='%3$s'>Nutzungsbedingungen</a> von %1$s zu.");
        a.put(fa.ab, "Sie gestatten dem H\344ndler, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        a.put(fa.ac, "Sie gestatten dem H\344ndler, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        a.put(fa.ad, "Zustimmen");
        a.put(fa.ae, "E-Mail-Adresse");
        a.put(fa.af, "Beispieldaten");
        a.put(fa.ag, "Sandbox");
        a.put(fa.ah, "G\374ltig bis");
        a.put(fa.ai, "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsmethoden verf\374gbar sind.</p>");
        a.put(fa.aj, "Passwort vergessen?");
        a.put(fa.ak, "Von");
        a.put(fa.al, "Wie m\366chten Sie Ihre weiteren Zahlungen an %1$s finanzieren?");
        a.put(fa.am, "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>F\374r zuk\374nftige PayPal-Zahlungen bei diesem H\344ndler wird Ihre Standardzahlungsquelle verwendet. </p><p>Um diese Vereinbarung zu k\374ndigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diesen H\344ndler von der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> f\374r Zahlungen im Einzugsverfahren.</p><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p>");
        a.put(fa.an, "Interner Fehler");
        a.put(fa.ao, "<p>Durch Klicken auf den Button unten stimme ich den <a href='%1$s'>PayPal-Nutzungsbedingungen</a> zu und best\344tige, dass ich bei dieser Transaktion die japanischen Gesetze und Vorschriften einhalte, einschlie\337lich Sanktionen hinsichtlich Zahlungen nach Nordkorea oder in den Iran gem\344\337 dem <a href='%2$s'>Gesetz \374ber Devisen und internationalen Handel</a>.</p>");
        a.put(fa.ap, "Einloggen");
        a.put(fa.aq, "Login mit PayPal");
        a.put(fa.ar, "Ausloggen");
        a.put(fa.as, "Ausloggen");
        a.put(fa.at, "OK");
        a.put(fa.au, "Passwort");
        a.put(fa.av, "Abbuchung nach Warenerhalt");
        a.put(fa.aw, "Zahlen mit");
        a.put(fa.ax, "Mit Kreditkarte zahlen");
        a.put(fa.ay, "PayPal-Guthaben");
        a.put(fa.az, "PayPal Credit");
        a.put(fa.aA, "Handynr.");
        a.put(fa.aB, "PIN");
        a.put(fa.aC, "Bevorzugte Zahlungsmethode");
        a.put(fa.aD, "PayPal sch\374tzt Ihre <a href='%s'>Privatsph\344re</a> und Ihre Finanzinformationen.");
        a.put(fa.aE, "In Verarbeitung");
        a.put(fa.aF, "Kreditkarte speichern");
        a.put(fa.aG, "Geld anfordern");
        a.put(fa.aH, "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des Partners.</p>");
        a.put(fa.aI, "Sparkonto");
        a.put(fa.aJ, "Geld senden");
        a.put(fa.aK, "Beim Datenaustausch mit den PayPal-Servern ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.");
        a.put(fa.aL, "Loggen Sie sich erneut bei PayPal ein.");
        a.put(fa.aM, "Sitzung abgelaufen");
        a.put(fa.aN, "Lieferadresse");
        a.put(fa.aO, "Neu bei PayPal? Neu anmelden");
        a.put(fa.aP, "Eingeloggt bleiben");
        a.put(fa.aQ, "Systemfehler (%s). Bitte versuchen Sie es sp\344ter noch einmal.");
        a.put(fa.aR, "Erneut versuchen");
        a.put(fa.aS, "Einloggen nicht m\366glich, da in Ihrem Konto die Zwei-Faktor-Authentifizierung aktiviert ist.");
        a.put(fa.aT, "Sicherheitscode");
        a.put(fa.aU, "Wir senden Ihnen eine SMS auf Ihr Handy. Diese enth\344lt einen 6-stelligen Code, der f\374nf Minuten lang g\374ltig ist.");
        a.put(fa.aV, "SMS senden");
        a.put(fa.aW, "6-stelligen Sicherheitscode eingeben");
        a.put(fa.aX, "Ihre Handynummer");
        a.put(fa.aY, "SMS senden");
        a.put(fa.aZ, "SMS erneut senden");
        a.put(fa.ba, "Einloggen nicht m\366glich, da in Ihrem Konto die Zwei-Faktor-Authentifizierung aktiviert ist. Aktivieren Sie \374ber die PayPal-Website Ihren Sicherheitsschl\374ssel.");
        a.put(fa.bb, "Mit diesem Ger\344t sind keine Zahlungen m\366glich.");
        a.put(fa.bc, "Nicht autorisiertes Ger\344t");
        a.put(fa.bd, "Zahlungen an diesen H\344ndler sind nicht m\366glich (ung\374ltige Client-ID).");
        a.put(fa.be, "Ung\374ltiger H\344ndler");
        a.put(fa.bf, "Bei der Verarbeitung Ihrer Zahlung ist ein Problem aufgetreten. Bitte versuchen Sie es erneut.");
        a.put(fa.bg, "Nicht erkannte Zahlungsquelle");
        a.put(fa.bh, "Fehler");
        a.put(fa.bi, "Ihre Bestellung");
        a.put(fa.bj, "Kreditkarte l\366schen?");
        a.put(fa.bk, "Zustimmung fehlgeschlagen");
        a.put(fa.bl, "Keine Verbindung");
        a.put(fa.bm, "Login nicht erfolgreich");
        a.put(fa.bn, "Mit Passwort einloggen");
        a.put(fa.bo, "Mit PIN einloggen");
        a.put(fa.bp, "Einen Moment\u2026");
        a.put(fa.bq, "Zahlung fehlgeschlagen.");
        a.put(fa.br, "Fotografieren");
        a.put(fa.bs, "Sicherheitscode falsch. Bitte versuchen Sie es erneut.");
        a.put(fa.bt, "\374ber");
        a.put(fa.bu, "Systemfehler. Bitte versuchen Sie es sp\344ter noch einmal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a> an den H\344ndler.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Sie genehmigen die Weitergabe von Informationen \374ber die in Ihrem PayPal-Konto hinterlegten <a href='%1$s'>Zahlungsmethoden</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Sie genehmigen bis auf Widerruf die Weitergabe von Informationen \374ber Ihre <a href='%1$s'>Zahlungsquellen</a>.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p>Sie <a href='%1$s'>autorisieren Abbuchungen f\374r zuk\374nftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Betr\344ge zu zahlen.</p><p>Weitere Informationen finden Sie im <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPal-Vertrag \374ber Abonnementzahlungen</a>.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p>Sie <a href='%1$s'>autorisieren Abbuchungen f\374r zuk\374nftige PayPal-Zahlungen</a> bei %2$s. Sie weisen PayPal an, die von %3$s geforderten Betr\344ge zu zahlen.</p><p>Weitere Informationen finden Sie im <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPal-Vertrag \374ber Abonnementzahlungen</a>.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "Sie <a href='%1$s'>autorisieren Abbuchungen</a> f\374r zuk\374nftige PayPal-Zahlungen. Sie stimmen zu und beauftragen PayPal, alle Betr\344ge zu zahlen.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "Sie <a href='%1$s'>autorisieren Abbuchungen</a> f\374r zuk\374nftige PayPal-Zahlungen. Sie stimmen zu und beauftragen PayPal, alle Betr\344ge zu zahlen.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "Sie <a href='%1$s'>autorisieren Abbuchungen</a> f\374r zuk\374nftige PayPal-Zahlungen. Sie stimmen zu und beauftragen PayPal, alle Betr\344ge zu zahlen.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Sie genehmigen Zahlungen aus Abbuchungsauftr\344gen, die auch dann gesendet werden, wenn Sie nicht bei PayPal eingeloggt sind. <a href='%1$s'>Weitere Bedingungen</a>, einschlie\337lich Informationen zu Zahlungsmethoden und Hinweise zur Stornierung von Abbuchungsauftr\344gen.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld anzufordern</a>.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Sie gestatten %2$s, bis auf Widerruf in Ihrem Namen <a href='%1$s'>Geld zu senden</a>.");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen in Ihrem PayPal-Konto verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen in Ihrem PayPal-Konto verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen in Ihrem PayPal-Konto verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Zahlungsmethoden</strong></h1><p>PayPal gibt nur weiter, welche Zahlungsquellen verf\374gbar sind.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihre Standardzahlungsquelle (PayPal-Guthaben, hinzugef\374gtes Bankkonto, Debit Card oder Kreditkarte, in dieser Reihenfolge). Wenn Ihre Standardzahlungsquelle nicht ausreichend gedeckt ist, kann Ihre Bank oder Ihr Kreditkartenanbieter eine Geb\374hr berechnen.</p><p>Wenn Sie diese Vereinbarung k\374ndigen m\366chten, klicken Sie in Ihrem PayPal-Konto unter <strong>Mein Profil</strong> auf <strong>Einstellungen</strong> und anschlie\337end neben \u201CLogin mit PayPal\u201D auf <strong>\304ndern</strong>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihr PayPal-Guthaben oder Ihre Standard-Kreditkarte oder -Debit Card.</p><p>Um diese Vereinbarung zu k\374ndigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihre Standardzahlungsquelle.</p><p>Um diese Vereinbarung zu k\374ndigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>F\374r zuk\374nftige PayPal-Zahlungen bei diesem H\344ndler wird Ihre Standardzahlungsquelle verwendet. </p><p>Um diese Vereinbarung zu k\374ndigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen Sie diesen H\344ndler von der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> f\374r Zahlungen im Einzugsverfahren.</p><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und l\366schen Sie diesen H\344ndler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> f\374r Zahlungen im Einzugsverfahren.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorisierung f\374r zuk\374nftige Zahlungen</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihre Standardzahlungsquelle.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und l\366schen Sie diesen H\344ndler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> f\374r Zahlungen im Einzugsverfahren.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihr PayPal-Guthaben oder Ihre Standard-Kreditkarte oder -Debit Card.</p><p>Um diese Vereinbarung zu k\374ndigen, loggen Sie sich in Ihr PayPal-Konto ein, rufen Sie <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> auf und entfernen diese Website oder App von der Liste.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und l\366schen Sie diesen H\344ndler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> f\374r Zahlungen im Einzugsverfahren.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und l\366schen Sie diesen H\344ndler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> f\374r Zahlungen im Einzugsverfahren.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>Damit wir k\374nftig Zahlungen von Ihrem PayPal-Konto abbuchen k\366nnen, f\374hrt diese App eventuell eine kleine Testtransaktion durch. Hierbei wird aber kein Geld abgebucht.</p><p>F\374r Eink\344ufe mit PayPal verwenden wir Ihre Standardzahlungsmethode.</p><p>Um diese Autorisierung zu stornieren, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong>, und l\366schen Sie diesen H\344ndler aus der Liste.</p><p>Es gelten die <a href='%s'>PayPal-Nutzungsbedingungen</a> f\374r Zahlungen im Einzugsverfahren.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Abbuchungsvereinbarung</strong></h1><p>PayPal verwendet zuerst Ihr PayPal-Guthaben, um Eink\344ufe zu bezahlen. Wenn Ihr Guthaben nicht f\374r den gesamten Betrag ausreicht, werden die folgenden Zahlungsquellen in der angegebenen Reihenfolge verwendet: Bankkonto, PayPal Credit, Debit Card, Kreditkarte und/oder Lastschrift mit Sicherheitspr\374fung.</p><p>Um diese Vereinbarung zu k\374ndigen, klicken Sie in Ihrem PayPal-Konto auf <strong>Mein Profil</strong> &gt; <strong>Einstellungen</strong> &gt; <strong>Login mit PayPal</strong> und l\366schen Sie diesen H\344ndler aus der Liste.</p><p>Eventuell ist eine Zahlungsautorisierung erforderlich, damit Zahlungen k\374nftig von Ihrem PayPal-Konto abgebucht werden k\366nnen. Die Autorisierung wird storniert und es wird nichts abgebucht.</p>");
        b.put("LOG_IN_TO_PAYPAL|AU", "Login mit PayPal");
        b.put("LOG_IN_TO_PAYPAL|GB", "Login mit PayPal");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie auf das Zahnrad. Klicken Sie dann unter <strong>Sicherheit</strong> auf <strong>Login mit PayPal</strong> und l\366schen Sie diesen Partner.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des Partners.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des Partners.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie auf das Zahnrad. Klicken Sie dann unter <strong>Sicherheit</strong> auf <strong>Login mit PayPal</strong> und l\366schen Sie diesen Partner.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des Partners.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie auf das Zahnrad. Klicken Sie dann unter <strong>Sicherheit</strong> auf <strong>Login mit PayPal</strong> und l\366schen Sie diesen Partner.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des Partners.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheits-Center</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler. Im klassischen Design klicken Sie unter <strong>Mein Profil</strong> auf <strong>Kontoeinstellungen</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des Partners.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.it ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den Partner weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.ru ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des Partners.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich in Ihr PayPal-Konto ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com.tr ein, klicken Sie rechts oben auf das Zahnrad und danach auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen Partner.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf \u201CEinstellungen\u201D. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevanten Transaktionsdetails werden an den H\344ndler weitergegeben.</p><p>Wenn Sie Ihre Zustimmung widerrufen m\366chten, loggen Sie sich auf PayPal.com ein und klicken Sie unter <strong>Mein Profil</strong> auf <strong>Sicherheit</strong>. Anschlie\337end klicken Sie auf <strong>Login mit PayPal</strong> und entfernen diesen H\344ndler.</p><p>PayPal \374bernimmt keine Verantwortung f\374r die Handlungen oder Fehler des H\344ndlers.</p>");
        c.put("AMOUNT_MISMATCH", "Warenkorbsumme stimmt nicht mit Gesamtbetrag \374berein.");
        c.put("AUTHORIZATION_ALREADY_COMPLETED", "Diese Autorisierung ist bereits abgeschlossen.");
        c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autorisierung hat einen Status, der nicht storniert werden kann.");
        c.put("AUTHORIZATION_EXPIRED", "Autorisierung ist abgelaufen.");
        c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Der angeforderte Autorisierungscode existiert nicht.");
        c.put("AUTHORIZATION_VOIDED", "Autorisierung wurde storniert.");
        c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Nur die urspr\374ngliche Autorisierung kann erneut autorisiert werden. Bereits erneut autorisierte Zahlungen k\366nnen nicht nochmals autorisiert werden.");
        c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Erneute Autorisierungen w\344hrend des Anerkennungszeitraums sind nicht m\366glich.");
        c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Der Betrag \374bersteigt Ihr Limit.");
        c.put("CARD_TOKEN_PAYER_MISMATCH", "Zugriff auf gespeicherte Kreditkartendaten nicht m\366glich.");
        c.put("CREDIT_CARD_CVV_CHECK_FAILED", "Die Kreditkartendaten sind ung\374ltig. Bitte korrigieren Sie Ihre Eingabe und versuchen Sie es erneut.");
        c.put("CREDIT_CARD_REFUSED", "Kreditkarte abgelehnt.");
        c.put("CURRENCY_MISMATCH", "Die W\344hrung beim Einzug muss mit der W\344hrung der Autorisierung \374bereinstimmen.");
        c.put("CURRENCY_NOT_ALLOWED", "Diese W\344hrung wird von PayPal derzeit nicht unterst\374tzt.");
        c.put("DATA_RETRIEVAL", "Systemfehler. Bitte versuchen Sie es sp\344ter noch einmal.");
        c.put("DUPLICATE_REQUEST_ID", "Systemfehler. Versuchen Sie es sp\344ter noch einmal.");
        c.put("EXPIRED_CREDIT_CARD", "Kreditkarte abgelaufen");
        c.put("EXPIRED_CREDIT_CARD_TOKEN", "Diese Kreditkarte ist nicht mehr gespeichert.\nBitte erneut senden.");
        c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funktion wird f\374r diesen Anbieter nicht unterst\374tzt.");
        c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "F\374r diese Transaktion wurde bereits eine Teilr\374ckzahlung geleistet.");
        c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Sofortzahlung wird f\374r diesen Intent nicht unterst\374tzt.");
        c.put("INSTRUMENT_DECLINED", "Ihre ausgew\344hlte Zahlungsquelle wurde nicht akzeptiert. W\344hlen Sie eine andere Zahlungsquelle.");
        c.put("INSUFFICIENT_FUNDS", "K\344ufer kann nicht zahlen \u2013 Guthaben nicht ausreichend.");
        c.put("INTERNAL_SERVICE_ERROR", "Systemfehler. Versuchen Sie es sp\344ter noch einmal.");
        c.put("INVALID_ACCOUNT_NUMBER", "Diese Kontonummer existiert nicht.");
        c.put("INVALID_ARGUMENT", "Transaktion wegen eines ung\374ltigen Arguments abgelehnt");
        c.put("INVALID_CITY_STATE_ZIP", "Ung\374ltige Kombination aus Ort/Bundesstaat/PLZ.");
        c.put("INVALID_FACILITATOR_CONFIGURATION", "Diese Transaktion kann aufgrund einer ung\374ltigen Facilitator-Konfiguration nicht verarbeitet werden.");
        c.put("INVALID_PAYER_ID", "Systemfehler (ung\374ltige Absender-ID). Bitte versuchen Sie es sp\344ter noch einmal.");
        c.put("INVALID_RESOURCE_ID", "Systemfehler. Versuchen Sie es sp\344ter noch einmal.");
        c.put("PAYEE_ACCOUNT_INVALID", "Die E-Mail-Adresse des Anbieters ist nicht best\344tigt.");
        c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Dieser Anbieter kann zurzeit keine Zahlungen empfangen.");
        c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Die E-Mail-Adresse des Anbieters ist nicht best\344tigt.");
        c.put("PAYEE_ACCOUNT_RESTRICTED", "Dieser Anbieter kann zurzeit keine Zahlungen empfangen.");
        c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Ihr Konto ist gesperrt oder geschlossen.");
        c.put("PAYER_ACCOUNT_RESTRICTED", "Der Zugriff auf Ihr Konto ist eingeschr\344nkt.");
        c.put("PAYER_CANNOT_PAY", "Sie k\366nnen diese Transaktion nicht mit PayPal bezahlen.");
        c.put("PAYER_EMPTY_BILLING_ADDRESS", "Rechnungsadresse ist f\374r Transaktionen mit Nicht-PayPal-Kreditkarten erforderlich.");
        c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Zugriff auf gespeicherte Kreditkartendaten nicht m\366glich.");
        c.put("PAYMENT_APPROVAL_EXPIRED", "Die Zahlungsgenehmigung ist abgelaufen.");
        c.put("PAYMENT_EXPIRED", "Die Zahlung ist abgelaufen.");
        c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Der Absender hat die Zahlung nicht genehmigt.");
        c.put("PAYMENT_REQUEST_ID_INVALID", "PayPal-Anforderungs-ID ist ung\374ltig. Versuchen Sie es sp\344ter noch einmal.");
        c.put("PAYMENT_STATE_INVALID", "Diese Anforderung ist aufgrund des aktuellen Zahlungsstatus ung\374ltig.");
        c.put("PERMISSION_DENIED", "Keine Genehmigung f\374r die angeforderte Aktion.");
        c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Die angeforderte R\374ckzahlung \374bersteigt den Betrag der urspr\374nglichen Transaktion.");
        c.put("REFUND_TIME_LIMIT_EXCEEDED", "Diese Transaktion ist zu alt f\374r eine R\374ckzahlung.");
        c.put("REQUIRED_SCOPE_MISSING", "Systemfehler. Versuchen Sie es sp\344ter noch einmal.");
        c.put("TOO_MANY_REAUTHORIZATIONS", "F\374r diese Autorisierung sind keine weiteren Autorisierungen m\366glich.");
        c.put("TRANSACTION_ALREADY_REFUNDED", "F\374r diese Transaktion wurde bereits eine R\374ckzahlung geleistet.");
        c.put("TRANSACTION_LIMIT_EXCEEDED", "Der Betrag \374bersteigt Ihr Limit.");
        c.put("TRANSACTION_REFUSED", "Die Transaktion wurde abgelehnt.");
        c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Die Transaktion wurde abgelehnt.");
        c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Einstellung im H\344ndlerprofil: Bestimmte Transaktionen werden automatisch abgelehnt.");
        c.put("UNKNOWN_ERROR", "Systemfehler. Versuchen Sie es sp\344ter noch einmal.");
        c.put("UNSUPPORTED_PAYEE_COUNTRY", "Ihr Land wird nicht unterst\374tzt.");
        c.put("VALIDATION_ERROR", "Die Zahlungsdaten sind ung\374ltig. Bitte korrigieren und Eingabe wiederholen.");
        c.put("ORDER_ALREADY_COMPLETED", "Bestellung ist bereits storniert, abgelaufen oder abgeschlossen.");
        c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Die maximal zul\344ssige Anzahl an Autorisierungen f\374r die Bestellung wurde erreicht.");
        c.put("ORDER_VOIDED", "Bestellung wurde storniert.");
        c.put("ORDER_CANNOT_BE_VOIDED", "Bestellung kann in diesem Status nicht storniert werden.");
        c.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfehler. Versuchen Sie es sp\344ter noch einmal.");
        c.put("UNAUTHORIZED_PAYMENT", "Der H\344ndler akzeptiert diesen Zahlungstyp nicht.");
        c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "W\344hrung wird bei Kartentyp nicht unterst\374tzt.");
        c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Kreditkartentyp wird nicht unterst\374tzt.");
        c.put("ADDRESS_ADDITION_ERROR", "Fehler beim Hinzuf\374gen der Lieferadresse zum PayPal-Konto.");
        c.put("DUPLICATE_TRANSACTION", "Doppelte Transaktion.");
        c.put("INVALID_SHIPPING_ADDRESS", "Die angegebene Lieferadresse ist nicht g\374ltig.");
        c.put("PAYMENT_CREATION_ERROR", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten. Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten \u2013 Ihre Kreditkarte ist abgelaufen. Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten \u2013 Sofortzahlung erforderlich, z.B. mit Kreditkarte. Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten \u2013 best\344tigte Kreditkarte erforderlich. Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten \u2013 f\374r diese App muss in Ihrem Konto eine Telefonnummer hinterlegt sein. Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten \u2013 Sie brauchen ein Konto mit einer g\374ltigen Zahlungsquelle (Bankkonto oder Zahlungskarte). Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten \u2013 Ihr Konto ist im Minus. Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten \u2013 Sie haben Ihr Sendelimit erreicht. Loggen Sie sich \374ber die PayPal-Website ein und \374berpr\374fen Sie Ihr Konto.");
        c.put("AUTH_RC_RISK_FAILURE", "Aufgrund von Risikomodellen abgelehnt");
        c.put("AUTH_RC_OFAC_BLOCKED_IP", "Nicht autorisierter Client");
        c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Nicht autorisierter Client");
        c.put("invalid_user", "Benutzername/Passwort nicht korrekt. Bitte versuchen Sie es erneut.");
        c.put("locked_user", "Ihr PayPal-Konto wurde vor\374bergehend gesperrt. Versuchen Sie es sp\344ter noch einmal oder entsperren Sie Ihr Konto \374ber www.paypal.com.");
        c.put("max_attempts_exceeded", "Zu viele fehlgeschlagene Logins. Versuchen Sie es sp\344ter noch einmal.");
        c.put("invalid_request", "Es ist ein Fehler aufgetreten.");
        c.put("unauthorized_client", "Anforderung nicht autorisiert.");
        c.put("access_denied", "Anforderung nicht autorisiert.");
        c.put("unsupported_response_type", "Es ist ein Fehler aufgetreten.");
        c.put("invalid_scope", "Anforderung nicht autorisiert.");
        c.put("server_error", "Systemfehler. Bitte versuchen Sie es sp\344ter noch einmal.");
        c.put("temporarily_unavailable", "Systemfehler. Versuchen Sie es sp\344ter noch einmal.");
        c.put("stepup_required", "Wir k\366nnen Sie zurzeit nicht einloggen. Versuchen Sie es sp\344ter noch einmal, oder loggen Sie sich aus Sicherheitsgr\374nden \374ber die PayPal-Website ein.");
    }

    public final String a()
    {
        return "de";
    }

    public final String a(Enum enum, String s)
    {
        enum = (fa)enum;
        s = (new StringBuilder()).append(enum.toString()).append("|").append(s).toString();
        if (b.containsKey(s))
        {
            return (String)b.get(s);
        } else
        {
            return (String)a.get(enum);
        }
    }

    public final String a(String s)
    {
        return (String)c.get(s);
    }

}
