// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

// Referenced classes of package com.paypal.android.sdk:
//            ig, fa

public final class lq
    implements ig
{

    private static final Map a = new HashMap();
    private static final Map b = new HashMap();
    private static final Map c = new HashMap();

    public lq()
    {
        a.put(fa.a, "Aceptar y pagar");
        a.put(fa.b, "y otras");
        a.put(fa.c, "Autenticando");
        a.put(fa.d, "Atr\341s");
        a.put(fa.e, "Garant\355a");
        a.put(fa.f, "Cancelar");
        a.put(fa.g, "American Express");
        a.put(fa.h, "Carta Aura");
        a.put(fa.i, "Tarjeta Aurora");
        a.put(fa.j, "Carta Prepagata PayPal");
        a.put(fa.k, "Carte Bancaire");
        a.put(fa.l, "Cofinoga");
        a.put(fa.m, "Delta");
        a.put(fa.n, "Discover");
        a.put(fa.o, "Electron");
        a.put(fa.p, "JCB");
        a.put(fa.q, "Maestro");
        a.put(fa.r, "MasterCard");
        a.put(fa.s, "Postepay");
        a.put(fa.t, "4 \351toiles");
        a.put(fa.u, "Tarjeta Aurora");
        a.put(fa.v, "Visa");
        a.put(fa.w, "Cambiar forma de pago");
        a.put(fa.x, "Corriente");
        a.put(fa.y, "Comprobando este dispositivo\u2026");
        a.put(fa.z, "Borrar informaci\363n de tarjeta");
        a.put(fa.A, "Confirmar");
        a.put(fa.B, "\277Seguro de que deseas borrar la informaci\363n de la tarjeta?");
        a.put(fa.C, "Cargar en tarjeta");
        a.put(fa.D, "\277Seguro que deseas cerrar la sesi\363n de PayPal?");
        a.put(fa.E, "Pagar");
        a.put(fa.F, "Aceptar");
        a.put(fa.G, "Fecha de creaci\363n de la cuenta");
        a.put(fa.H, "Estado de cuenta");
        a.put(fa.I, "Tipo de cuenta");
        a.put(fa.J, "Direcci\363n");
        a.put(fa.K, "Intervalo de edad");
        a.put(fa.L, "Fecha de nacimiento");
        a.put(fa.M, "Direcci\363n de correo");
        a.put(fa.N, "Nombre completo");
        a.put(fa.O, "Sexo");
        a.put(fa.P, "Idioma");
        a.put(fa.Q, "Regi\363n");
        a.put(fa.R, "Tel\351fono");
        a.put(fa.S, "Zona horaria");
        a.put(fa.T, "Compartir lo siguiente: %s.");
        a.put(fa.U, "Utilizar el pago totalmente integrado.");
        a.put(fa.V, "%s te pide que:");
        a.put(fa.W, "Compartir las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
        a.put(fa.X, "Activa la visualizaci\363n de las opciones de pago para poder elegir.");
        a.put(fa.Y, "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indica a PayPal que pague todos los importes solicitados por %3$s.");
        a.put(fa.Z, "Le permitas a\361adir y administrar su tarjeta de fidelizaci\363n en tu cartera de PayPal.");
        a.put(fa.aa, "Aceptes la <a href='%2$s'>pol\355tica de privacidad</a> y las <a href='%3$s'>condiciones de uso</a> de %1$s.");
        a.put(fa.ab, "Le permitas <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        a.put(fa.ac, "Le permitas <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        a.put(fa.ad, "Consentimiento");
        a.put(fa.ae, "Correo");
        a.put(fa.af, "Datos simulados");
        a.put(fa.ag, "Entorno de pruebas");
        a.put(fa.ah, "Caduca");
        a.put(fa.ai, "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que est\341n disponibles para su uso.</p>");
        a.put(fa.aj, "\277Has olvidado la contrase\361a?");
        a.put(fa.ak, "De");
        a.put(fa.al, "\277C\363mo te gustar\355a realizar los pagos futuros a %1$s?");
        a.put(fa.am, "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Se utilizar\341 la fuente de fondos predeterminada para realizar futuros pagos con PayPal desde este vendedor.</p><p>Para cancelar este acuerdo, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Se aplicar\341 la secci\363n Pagos peri\363dicos de las <a href='%s'>Condiciones de uso de PayPal</a>.</p><p>Para asegurarte de que los pagos con tu cuenta PayPal funcionen correctamente, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero.</p>");
        a.put(fa.an, "Error interno");
        a.put(fa.ao, "<p>Al hacer clic en el bot\363n siguiente, por el presente documento acepto las condiciones que figuran en las <a href='%1$s'>Condiciones de uso de PayPal</a> y declaro que cumplo las leyes y normas japonesas, incluidas las sanciones contra pagos a Corea del Norte e Ir\341n que se establecen en la <a href='%2$s'>ley de divisas y comercio exterior</a> para completar la transacci\363n.</p>");
        a.put(fa.ap, "Iniciar sesi\363n");
        a.put(fa.aq, "Iniciar sesi\363n con PayPal");
        a.put(fa.ar, "Cerrar sesi\363n");
        a.put(fa.as, "Cerrar sesi\363n");
        a.put(fa.at, "Aceptar");
        a.put(fa.au, "Contrase\361a");
        a.put(fa.av, "Pago tras la entrega");
        a.put(fa.aw, "Pagar con");
        a.put(fa.ax, "Pagar con tarjeta");
        a.put(fa.ay, "Saldo de PayPal");
        a.put(fa.az, "PayPal Credit");
        a.put(fa.aA, "Tel\351fono");
        a.put(fa.aB, "PIN");
        a.put(fa.aC, "Forma de pago preferida");
        a.put(fa.aD, "PayPal protege tu <a href='%s'>privacidad</a> y tu informaci\363n financiera.");
        a.put(fa.aE, "Proceso en curso");
        a.put(fa.aF, "Recordar tarjeta");
        a.put(fa.aG, "Solicitar dinero");
        a.put(fa.aH, "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
        a.put(fa.aI, "De ahorro");
        a.put(fa.aJ, "Enviar dinero");
        a.put(fa.aK, "Se ha producido un problema de comunicaci\363n con los servidores de PayPal. Int\351ntalo de nuevo.");
        a.put(fa.aL, "Vuelve a iniciar sesi\363n en PayPal.");
        a.put(fa.aM, "La sesi\363n ha caducado");
        a.put(fa.aN, "Direcci\363n de env\355o");
        a.put(fa.aO, "\277No tienes una cuenta PayPal? Registrarse");
        a.put(fa.aP, "Mantener sesi\363n abierta");
        a.put(fa.aQ, "Error del sistema (%s). Int\351ntalo de nuevo m\341s tarde.");
        a.put(fa.aR, "Int\351ntalo de nuevo");
        a.put(fa.aS, "No es posible iniciar sesi\363n porque se ha activado la autenticaci\363n de dos factores para la cuenta.");
        a.put(fa.aT, "C\363digo de seguridad");
        a.put(fa.aU, "Env\355a un mensaje de texto a tu tel\351fono. El c\363digo de 6 d\355gitos que recibas ser\341 v\341lido durante 5 minutos.");
        a.put(fa.aV, "Env\355o de mensaje de texto");
        a.put(fa.aW, "Introduce el c\363digo de seguridad de 6 d\355gitos");
        a.put(fa.aX, "Tu n\372mero de tel\351fono m\363vil");
        a.put(fa.aY, "Enviar mensaje de texto");
        a.put(fa.aZ, "Enviar mensaje de texto de nuevo");
        a.put(fa.ba, "No es posible iniciar sesi\363n porque se ha activado la autenticaci\363n de dos factores para la cuenta. Para activar tu clave de seguridad, visita el sitio web de PayPal.");
        a.put(fa.bb, "No se admiten pagos desde este dispositivo.");
        a.put(fa.bc, "Dispositivo no autorizado");
        a.put(fa.bd, "No se permiten los pagos a este vendedor (Id. de cliente no v\341lido).");
        a.put(fa.be, "Vendedor no v\341lido");
        a.put(fa.bf, "Ha habido un problema al procesar el pago. Int\351ntalo de nuevo.");
        a.put(fa.bg, "Fuente no identificada");
        a.put(fa.bh, "Lo sentimos");
        a.put(fa.bi, "Tu pedido");
        a.put(fa.bj, "\277Borrar tarjeta?");
        a.put(fa.bk, "Error en el consentimiento");
        a.put(fa.bl, "Error de conexi\363n");
        a.put(fa.bm, "Error de inicio de sesi\363n");
        a.put(fa.bn, "Iniciar sesi\363n con contrase\361a");
        a.put(fa.bo, "Iniciar sesi\363n con PIN");
        a.put(fa.bp, "Un momento\u2026");
        a.put(fa.bq, "Error en el pago");
        a.put(fa.br, "Escanear");
        a.put(fa.bs, "C\363digo de seguridad incorrecto. Int\351ntalo de nuevo.");
        a.put(fa.bt, "Mediante");
        a.put(fa.bu, "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Compartir informaci\363n sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Compartir la informaci\363n sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Compartir informaci\363n sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Compartir informaci\363n sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Compartir informaci\363n sobre las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Compartir informaci\363n con ellos sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Compartir las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Compartir las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Compartir la informaci\363n sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Compartir informaci\363n sobre las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Compartir la informaci\363n sobre las <a href='%1$s'>fuentes de fondos</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Compartir informaci\363n sobre las <a href='%1$s'>formas de pago</a> vinculadas a tu cuenta PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Compartir tus <a href='%1$s'>fuentes de fondos</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indica a PayPal que pague todos los importes solicitados por %3$s.</p><p>Consulta el <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Acuerdo de pagos peri\363dicos y facturaci\363n de PayPal</a> para obtener m\341s informaci\363n.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indica a PayPal que pague todos los importes solicitados por %3$s.</p><p>Consulta el <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Acuerdo de pagos peri\363dicos y facturaci\363n de PayPal</a> para obtener m\341s informaci\363n.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras pagadas con PayPal. Autoriza y solicita a PayPal que pague todos los importes.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras pagadas con PayPal. Autoriza y solicita a PayPal que pague todos los importes.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Autoriza los cargos</a> correspondientes a futuras compras pagadas con PayPal. Autoriza y solicita a PayPal que pague todos los importes.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preaprueba pagos futuros realizados desde tu cuenta PayPal sin iniciar sesi\363n en PayPal cada vez. <a href='%1$s'>Consulta las condiciones adicionales</a>, incluidas las formas de pago y c\363mo se cancelan los pagos futuros.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Permitas a %2$s <a href='%1$s'>solicitar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Permitas a %2$s <a href='%1$s'>enviar dinero</a> en tu nombre hasta que retires el consentimiento.");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte informaci\363n sobre las fuentes de fondos disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte informaci\363n sobre las fuentes de fondos disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte informaci\363n sobre las fuentes de fondos disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las fuentes de fondos que est\341n disponibles para su uso.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero.</p><p>Se utilizar\341 la forma de pago predeterminada (el saldo de PayPal, cuenta bancaria, tarjeta de d\351bito o una tarjeta de cr\351dito vinculada, por este orden) para pagar las compras con PayPal. Ten en cuenta que si no hay fondos suficientes en la forma de pago predeterminada para cubrir la compra, el banco o la entidad emisora de la tarjeta pueden cargarte una comisi\363n.</p><p>Para cancelar este acuerdo, inicia sesi\363n en tu cuenta PayPal y ve a <strong>Perfil</strong>, a continuaci\363n haz clic en <strong>Opciones de cuenta</strong> y en el v\355nculo <strong>Cambiar</strong> situado junto a la opci\363n \u201CIniciar sesi\363n con PayPal\u201D.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 el saldo de PayPal o la tarjeta de d\351bito o cr\351dito principal para pagar las compras con PayPal.</p><p>Para cancelar este acuerdo, inicia sesi\363n en tu cuenta PayPal y ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar este acuerdo, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Se utilizar\341 la fuente de fondos predeterminada para realizar futuros pagos con PayPal desde este vendedor.</p><p>Para cancelar este acuerdo, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Se aplicar\341 la secci\363n Pagos peri\363dicos de las <a href='%s'>Condiciones de uso de PayPal</a>.</p><p>Para asegurarte de que los pagos con tu cuenta PayPal funcionen correctamente, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se transferir\341 dinero.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorizaci\363n de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorizaci\363n, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener m\341s informaci\363n, consulta la secci\363n \u201CPagos con aprobaci\363n previa\u201D de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorizaci\363n de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorizaci\363n, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener m\341s informaci\363n, consulta la secci\363n \u201CPagos con aprobaci\363n previa\u201D de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 el saldo de PayPal o la tarjeta de d\351bito o cr\351dito principal para pagar las compras con PayPal.</p><p>Para cancelar este acuerdo, inicia sesi\363n en tu cuenta PayPal y ve a <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Autorizaci\363n de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorizaci\363n, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener m\341s informaci\363n, consulta la secci\363n \u201CPagos con aprobaci\363n previa\u201D de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Autorizaci\363n de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorizaci\363n, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener m\341s informaci\363n, consulta la secci\363n \u201CPagos con aprobaci\363n previa\u201D de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorizaci\363n de pagos futuros</strong></h1><p>Para asegurarte de que se puedan realizar cargos en tu cuenta PayPal en el futuro, esta aplicaci\363n puede simular una peque\361a transacci\363n de prueba, pero no se realizar\341 ning\372n pago.</p><p>Se utilizar\341 la forma de pago predeterminada para pagar las compras con PayPal.</p><p>Para cancelar esta autorizaci\363n, inicia sesi\363n en tu cuenta PayPal, ve a <strong>Perfil</strong> &gt; <strong>Configuraci\363n de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Para obtener m\341s informaci\363n, consulta la secci\363n \u201CPagos con aprobaci\363n previa\u201D de las <a href='%s'>Condiciones de uso de PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Acuerdo de pagos futuros</strong></h1><p>PayPal usar\341 primero el saldo de la cuenta PayPal para pagar las compras. Si este no cubre el total de la compra, para realizar el pago se utilizar\341n tu cuenta bancaria, PayPal Credit, la tarjeta de d\351bito, de cr\351dito o el cargo en cuenta bancaria, en este orden.</p><p>Para cancelar este acuerdo, ve a www.paypal.com <strong>Perfil</strong> &gt; <strong>Opciones de cuenta</strong> &gt; <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor de la lista.</p><p>Es posible que tengas que autorizar un peque\361o pago para asegurarte de que se pueden realizar cargos en tu cuenta PayPal en el futuro. La autorizaci\363n se anular\341 y no se realizar\341 cargo alguno.</p>");
        b.put("LOG_IN_TO_PAYPAL|AU", "Iniciar sesi\363n con PayPal");
        b.put("LOG_IN_TO_PAYPAL|GB", "Iniciar sesi\363n con PayPal");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal y haz clic en el icono de la rueda dentada. Ve a <strong>Seguridad</strong>, selecciona <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal, ve a opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal y haz clic en el icono de la rueda dentada. Ve a <strong>Seguridad</strong>, selecciona <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal y haz clic en el icono de la rueda dentada. Ve a <strong>Seguridad</strong>, selecciona <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal, ve a las opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal, haz clic en el icono de rueda dentada en la esquina superior derecha, selecciona <strong>Centro de seguridad</strong>, selecciona <strong>Iniciar sesi\363n con PayPal</strong> y elimina al vendedor. Si a\372n utilizas el sitio web cl\341sico, ve a <strong>Mi perfil</strong>, selecciona <strong>Configuraci\363n de cuenta</strong>, selecciona <strong>Iniciar sesi\363n con PayPal</strong> y elimina al vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal y, a continuaci\363n, en la configuraci\363n de <strong>Perfil</strong>, ve a <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este partner.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.it, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal, ve a opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal, ve a las opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal, ve a opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el partner.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.ru, haz clic en el icono de la rueda dentada en la esquina superior derecha, selecciona la pesta\361a <strong>Seguridad</strong> y elimina a este partner en la opci\363n <strong>Iniciar sesi\363n con PayPal</strong>.</p><p>PayPal no es responsable las acciones o errores por parte del partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en tu cuenta PayPal, ve a las opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com.tr, haz clic en el icono de rueda dentada de la esquina superior derecha, selecciona la pesta\361a <strong>Seguridad</strong> y elimina a este partner en la opci\363n <strong>Iniciar sesi\363n con PayPal</strong>.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a opciones de <strong>Iniciar sesi\363n con PayPal</strong> en la configuraci\363n del <strong>Perfil</strong> y elimina a este vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Los detalles pertinentes de la transacci\363n se compartir\341n con el vendedor.</p><p>Para retirar el consentimiento, inicia sesi\363n en paypal.com, ve a <strong>Perfil</strong>, <strong>Seguridad</strong>, busca <strong>Iniciar sesi\363n con PayPal</strong> y elimina a este vendedor.</p><p>PayPal no es responsable las acciones o errores por parte del vendedor.</p>");
        c.put("AMOUNT_MISMATCH", "El importe total de los art\355culos del carro de la compra no coincide con el importe de la venta.");
        c.put("AUTHORIZATION_ALREADY_COMPLETED", "Esta autorizaci\363n ya se ha completado.");
        c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "El estado de la autorizaci\363n no se puede anular.");
        c.put("AUTHORIZATION_EXPIRED", "La autorizaci\363n ha caducado.");
        c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "El Id. de autorizaci\363n solicitado no existe.");
        c.put("AUTHORIZATION_VOIDED", "La autorizaci\363n se ha anulado.");
        c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Solo puedes volver a validar la autorizaci\363n original, no una nueva autorizaci\363n.");
        c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "No se permite realizar una nueva autorizaci\363n durante el per\355odo de tramitaci\363n.");
        c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "El importe supera el l\355mite permitido.");
        c.put("CARD_TOKEN_PAYER_MISMATCH", "No es posible acceder a la informaci\363n de la tarjeta guardada.");
        c.put("CREDIT_CARD_CVV_CHECK_FAILED", "La informaci\363n de la tarjeta no es v\341lida. Corr\355gela y vuelve a enviarla.");
        c.put("CREDIT_CARD_REFUSED", "Tarjeta rechazada.");
        c.put("CURRENCY_MISMATCH", "La divisa de la captura debe ser igual que la divisa de la autorizaci\363n.");
        c.put("CURRENCY_NOT_ALLOWED", "Actualmente, PayPal no admite esta divisa.");
        c.put("DATA_RETRIEVAL", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("DUPLICATE_REQUEST_ID", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("EXPIRED_CREDIT_CARD", "La tarjeta ha caducado");
        c.put("EXPIRED_CREDIT_CARD_TOKEN", "La informaci\363n de esta tarjeta ya no figura en nuestros registros.\nVuelve a enviarla.");
        c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funci\363n no admitida para este proveedor.");
        c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Parte del importe de esta transacci\363n ya se ha reembolsado.");
        c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Pago inmediato no compatible con la finalidad pasada.");
        c.put("INSTRUMENT_DECLINED", "No se ha aceptado la forma de pago seleccionada. Elige otra forma de pago.");
        c.put("INSUFFICIENT_FUNDS", "El comprador no puede pagar: saldo insuficiente.");
        c.put("INTERNAL_SERVICE_ERROR", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("INVALID_ACCOUNT_NUMBER", "Ese n\372mero de cuenta no existe.");
        c.put("INVALID_ARGUMENT", "Transacci\363n rechazada debido a un argumento no v\341lido");
        c.put("INVALID_CITY_STATE_ZIP", "Combinaci\363n de ciudad/estado/c\363digo postal no v\341lida.");
        c.put("INVALID_FACILITATOR_CONFIGURATION", "Esta transacci\363n no se puede procesar debido a una configuraci\363n del facilitador no v\341lida.");
        c.put("INVALID_PAYER_ID", "Error del sistema (Id. de pagador no v\341lido). Int\351ntalo de nuevo m\341s tarde.");
        c.put("INVALID_RESOURCE_ID", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("PAYEE_ACCOUNT_INVALID", "El correo electr\363nico de la cuenta del proveedor no est\341 confirmado.");
        c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Este proveedor no puede recibir pagos en este momento.");
        c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "El correo electr\363nico de la cuenta del proveedor no est\341 confirmado.");
        c.put("PAYEE_ACCOUNT_RESTRICTED", "Este proveedor no puede recibir pagos en este momento.");
        c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "La cuenta est\341 bloqueada o cerrada.");
        c.put("PAYER_ACCOUNT_RESTRICTED", "Tu cuenta est\341 restringida.");
        c.put("PAYER_CANNOT_PAY", "No puedes ingresar fondos para esta transacci\363n con PayPal.");
        c.put("PAYER_EMPTY_BILLING_ADDRESS", "La direcci\363n de facturaci\363n es obligatoria para transacciones con tarjetas de cr\351dito que no sean de PayPal.");
        c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "No es posible acceder a la informaci\363n de la tarjeta guardada.");
        c.put("PAYMENT_APPROVAL_EXPIRED", "La aprobaci\363n del pago ha caducado.");
        c.put("PAYMENT_EXPIRED", "El pago ha caducado.");
        c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "El pagador no ha aprobado el pago.");
        c.put("PAYMENT_REQUEST_ID_INVALID", "El Id. de la solicitud de PayPal no es v\341lido. Int\351ntalo de nuevo m\341s tarde.");
        c.put("PAYMENT_STATE_INVALID", "Esta solicitud no es v\341lida debido al estado actual del pago.");
        c.put("PERMISSION_DENIED", "No se permite la operaci\363n solicitada.");
        c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "El reembolso solicitado supera el importe de la transacci\363n original.");
        c.put("REFUND_TIME_LIMIT_EXCEEDED", "Esta transacci\363n se considera demasiado antigua para ser objeto de reembolso.");
        c.put("REQUIRED_SCOPE_MISSING", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("TOO_MANY_REAUTHORIZATIONS", "No se permiten m\341s autorizaciones nuevas para esta autorizaci\363n.");
        c.put("TRANSACTION_ALREADY_REFUNDED", "El importe de esta transacci\363n ya se ha reembolsado.");
        c.put("TRANSACTION_LIMIT_EXCEEDED", "El importe supera el l\355mite permitido.");
        c.put("TRANSACTION_REFUSED", "Esta transacci\363n se ha rechazado.");
        c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Esta transacci\363n se ha rechazado.");
        c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "La preferencia del perfil del vendedor est\341 configurada para rechazar autom\341ticamente ciertas transacciones.");
        c.put("UNKNOWN_ERROR", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("UNSUPPORTED_PAYEE_COUNTRY", "Pa\355s no admitido.");
        c.put("VALIDATION_ERROR", "La informaci\363n de pago no es v\341lida. Corr\355gela y vuelve a enviarla.");
        c.put("ORDER_ALREADY_COMPLETED", "El pedido ya se ha anulado, ha caducado o se ha completado.");
        c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Se ha alcanzado el n\372mero m\341ximo de autorizaciones permitidas para el pedido.");
        c.put("ORDER_VOIDED", "Se ha anulado el pedido.");
        c.put("ORDER_CANNOT_BE_VOIDED", "El estado del pedido hace que no sea posible su cancelaci\363n.");
        c.put("INVALID_EXPERIENCE_PROFILE_ID", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("UNAUTHORIZED_PAYMENT", "El vendedor no acepta pagos de este tipo.");
        c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Divisa no admitida para el tipo de tarjeta.");
        c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo de tarjeta no admitido.");
        c.put("ADDRESS_ADDITION_ERROR", "Error detectado al a\361adir la direcci\363n de env\355o a la cuenta PayPal.");
        c.put("DUPLICATE_TRANSACTION", "Transacci\363n duplicada.");
        c.put("INVALID_SHIPPING_ADDRESS", "La direcci\363n de env\355o proporcionada no es v\341lida.");
        c.put("PAYMENT_CREATION_ERROR", "Ha surgido un problema al configurar el pago. Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Ha surgido un problema al configurar el pago: la tarjeta ha caducado. Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Ha surgido un problema al configurar el pago: se requiere un m\351todo de pago instant\341neo (por ejemplo, una tarjeta de cr\351dito). Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Ha surgido un problema al configurar el pago: se debe confirmar la tarjeta. Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Ha surgido un problema al configurar el pago: la aplicaci\363n requiere que la cuenta incluya un n\372mero de tel\351fono. Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Ha surgido un problema al configurar el pago: la cuenta precisa una fuente de fondos v\341lida (por ejemplo, un banco o una tarjeta de pago). Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Ha surgido un problema al configurar el pago: el saldo es negativo. Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Ha surgido un problema al configurar el pago: se ha alcanzado el l\355mite de env\355o. Visita el sitio web de PayPal para consultar la cuenta.");
        c.put("AUTH_RC_RISK_FAILURE", "Rechazada debido al riesgo.");
        c.put("AUTH_RC_OFAC_BLOCKED_IP", "Cliente no autorizado.");
        c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Cliente no autorizado.");
        c.put("invalid_user", "Nombre de usuario o contrase\361a incorrectos. Int\351ntalo de nuevo.");
        c.put("locked_user", "Tu cuenta PayPal est\341 bloqueada temporalmente. Int\351ntalo de nuevo m\341s tarde o ve a www.paypal.com para desbloquear tu cuenta PayPal de inmediato.");
        c.put("max_attempts_exceeded", "Demasiados intentos fallidos de inicio de sesi\363n. Int\351ntalo de nuevo m\341s tarde.");
        c.put("invalid_request", "Ha habido un error.");
        c.put("unauthorized_client", "Solicitud no autorizada.");
        c.put("access_denied", "Solicitud no autorizada.");
        c.put("unsupported_response_type", "Ha habido un error.");
        c.put("invalid_scope", "Solicitud no autorizada.");
        c.put("server_error", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("temporarily_unavailable", "Error del sistema. Int\351ntalo de nuevo m\341s tarde.");
        c.put("stepup_required", "El inicio de sesi\363n no se puede completar en este momento. Int\351ntalo de nuevo m\341s tarde o ve a www.paypal.com para tratar cualquier problema de seguridad con tu cuenta PayPal.");
    }

    public final String a()
    {
        return "es";
    }

    public final String a(Enum enum, String s)
    {
        enum = (fa)enum;
        s = (new StringBuilder()).append(enum.toString()).append("|").append(s).toString();
        if (b.containsKey(s))
        {
            return (String)b.get(s);
        } else
        {
            return (String)a.get(enum);
        }
    }

    public final String a(String s)
    {
        return (String)c.get(s);
    }

}
