// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;

// Referenced classes of package com.paypal.android.sdk:
//            ig, fa

public final class lu
    implements ig
{

    private static final Map a = new HashMap();
    private static final Map b = new HashMap();
    private static final Map c = new HashMap();

    public lu()
    {
        a.put(fa.a, "Accetta e paga");
        a.put(fa.b, "e altri");
        a.put(fa.c, "Autenticazione\u2026");
        a.put(fa.d, "Prec.");
        a.put(fa.e, "Di riserva");
        a.put(fa.f, "Annulla");
        a.put(fa.g, "American Express");
        a.put(fa.h, "Carta Aura");
        a.put(fa.i, "Carta Aurore");
        a.put(fa.j, "Carta Prepagata PayPal");
        a.put(fa.k, "Carte Bancaire");
        a.put(fa.l, "Cofinoga");
        a.put(fa.m, "Delta");
        a.put(fa.n, "Discover");
        a.put(fa.o, "Electron");
        a.put(fa.p, "JCB");
        a.put(fa.q, "Maestro");
        a.put(fa.r, "MasterCard");
        a.put(fa.s, "Postepay");
        a.put(fa.t, "4 \351toiles");
        a.put(fa.u, "Tarjeta Aurora");
        a.put(fa.v, "Visa");
        a.put(fa.w, "Modifica metodo di pagamento");
        a.put(fa.x, "Conto corrente");
        a.put(fa.y, "Controllo dispositivo\u2026");
        a.put(fa.z, "Rimuovi dati della carta");
        a.put(fa.A, "Conferma");
        a.put(fa.B, "Rimuovere i dati della carta?");
        a.put(fa.C, "Addebita importo sulla carta");
        a.put(fa.D, "Vuoi uscire da PayPal?");
        a.put(fa.E, "Paga");
        a.put(fa.F, "Accetta");
        a.put(fa.G, "Data creazione conto");
        a.put(fa.H, "Stato del conto");
        a.put(fa.I, "Tipo di conto");
        a.put(fa.J, "Indirizzo");
        a.put(fa.K, "Fascia di et\340");
        a.put(fa.L, "Data di nascita");
        a.put(fa.M, "Indirizzo email");
        a.put(fa.N, "Nome e cognome");
        a.put(fa.O, "Sesso");
        a.put(fa.P, "Lingua");
        a.put(fa.Q, "Locale");
        a.put(fa.R, "Telefono");
        a.put(fa.S, "Fuso orario");
        a.put(fa.T, "Condividi il seguente: %s.");
        a.put(fa.U, "Usa Pagamento express.");
        a.put(fa.V, "%s ti chiede di:");
        a.put(fa.W, "Condividi i <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        a.put(fa.X, "Per effettuare una scelta, attiva la visualizzazione dei metodi di pagamento.");
        a.put(fa.Y, "<a href='%1$s'>Autorizza l\u2019addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.");
        a.put(fa.Z, "consentirgli di aggiungere e gestire la propria carta fedelt\340 nel tuo portafoglio PayPal.");
        a.put(fa.aa, "Accettare l\u2019<a href='%2$s'></a> Informativa sulla privacy<a href='%3$s'> e le</a> Condizioni d\u2019uso di %1$s.");
        a.put(fa.ab, "Consentirgli di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        a.put(fa.ac, "Consentirgli di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        a.put(fa.ad, "Consenso");
        a.put(fa.ae, "Email");
        a.put(fa.af, "Dati di esempio");
        a.put(fa.ag, "Sandbox");
        a.put(fa.ah, "Scadenza");
        a.put(fa.ai, "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal condivide solo i tuoi metodi di pagamento disponibili per l\u2019utilizzo.</p>");
        a.put(fa.aj, "Password dimenticata?");
        a.put(fa.ak, "Da");
        a.put(fa.al, "Come vuoi pagare i prossimi acquisti su %1$s?");
        a.put(fa.am, "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>Si applica la sezione Pagamenti automatici delle <a href='%s'>Condizioni d\u2019uso PayPal</a>.</p><p>Per verificare il funzionamento dell\u2019addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
        a.put(fa.an, "Errore interno");
        a.put(fa.ao, "<p>Cliccando il pulsante di seguito, accetto le <a href='%1$s'>Condizioni d\u2019uso PayPal</a> e dichiaro di rispettare le leggi e normative del Giappone, tra cui le sanzioni previste per i pagamenti alla Corea del Nord e all\u2019Iran in base al <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> (Legge sugli scambi e sul commercio estero), per completare la transazione.</p>");
        a.put(fa.ap, "Accedi");
        a.put(fa.aq, "Log in con PayPal");
        a.put(fa.ar, "Esci");
        a.put(fa.as, "Esci");
        a.put(fa.at, "OK");
        a.put(fa.au, "Password");
        a.put(fa.av, "Paga dopo la consegna");
        a.put(fa.aw, "Paga con");
        a.put(fa.ax, "Paga con una carta");
        a.put(fa.ay, "Saldo PayPal");
        a.put(fa.az, "PayPal Credit");
        a.put(fa.aA, "Telefono");
        a.put(fa.aB, "PIN");
        a.put(fa.aC, "Metodo di pagamento preferito");
        a.put(fa.aD, "PayPal protegge la tua <a href='%s'>privacy</a> e i tuoi dati.");
        a.put(fa.aE, "Elaborazione in corso");
        a.put(fa.aF, "Ricorda dati carta");
        a.put(fa.aG, "Richiedi denaro");
        a.put(fa.aH, "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non \350 responsabile di azioni o errori da parte del Partner.</p>");
        a.put(fa.aI, "Conto corrente");
        a.put(fa.aJ, "Invia denaro");
        a.put(fa.aK, "Si \350 verificato un problema con i nostri server. Riprova.");
        a.put(fa.aL, "Ripeti l\u2019accesso a PayPal.");
        a.put(fa.aM, "Sessione scaduta");
        a.put(fa.aN, "Indirizzo di spedizione");
        a.put(fa.aO, "Non hai un conto PayPal? Registrati");
        a.put(fa.aP, "Rimani collegato");
        a.put(fa.aQ, "Errore di sistema (%s). Riprova pi\371 tardi.");
        a.put(fa.aR, "Riprova");
        a.put(fa.aS, "Impossibile effettuare l\u2019accesso perch\351 sul tuo conto \350 attiva la doppia autenticazione.");
        a.put(fa.aT, "Codice di sicurezza");
        a.put(fa.aU, "Ricevi un SMS sul tuo telefono. Il codice a 6 cifre sar\340 valido per 5 minuti.");
        a.put(fa.aV, "Invio SMS in corso");
        a.put(fa.aW, "Immetti il codice di sicurezza a 6 cifre");
        a.put(fa.aX, "Numero di cellulare");
        a.put(fa.aY, "Ricevi SMS");
        a.put(fa.aZ, "Ricevi un altro SMS");
        a.put(fa.ba, "Impossibile effettuare l\u2019accesso perch\351 sul tuo conto \350 attiva la doppia autenticazione. Visita il sito PayPal per attivare la chiave di accesso.");
        a.put(fa.bb, "Pagamenti da questo dispositivo non consentiti.");
        a.put(fa.bc, "Dispositivo non autorizzato");
        a.put(fa.bd, "I pagamenti a questo venditore non sono consentiti (clientId non valido).");
        a.put(fa.be, "Sito non valido");
        a.put(fa.bf, "Si \350 verificato un problema durante l\u2019elaborazione del pagamento. Riprova.");
        a.put(fa.bg, "Metodo non riconosciuto");
        a.put(fa.bh, "Spiacenti");
        a.put(fa.bi, "Il tuo ordine");
        a.put(fa.bj, "Rimuovere la carta?");
        a.put(fa.bk, "Consenso non riuscito");
        a.put(fa.bl, "Connessione non riuscita");
        a.put(fa.bm, "Accesso non riuscito");
        a.put(fa.bn, "Accedi con la password");
        a.put(fa.bo, "Accedi con il PIN");
        a.put(fa.bp, "Attendi\u2026");
        a.put(fa.bq, "Pagamento non riuscito");
        a.put(fa.br, "Scansione");
        a.put(fa.bs, "Codice di sicurezza errato. Riprova.");
        a.put(fa.bt, "tramite");
        a.put(fa.bu, "Errore di sistema. Riprova pi\371 tardi.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Condividi con loro i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizza l\u2019addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizza l\u2019addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Autorizza l\u2019addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Autorizza l\u2019addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Autorizza l\u2019addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
        b.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preautorizza i prossimi pagamenti dal tuo conto PayPal senza effettuare ogni volta l\u2019accesso al conto. <a href='%1$s'>Vedi le condizioni aggiuntive</a>, tra cui i metodi di pagamento e le modalit\340 di annullamento dei pagamenti preautorizzati.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito (il saldo PayPal, il conto bancario, la carta di credito o di debito, in quest\u2019ordine) verr\340 usato per pagare gli acquisti con PayPal. Se sul tuo metodo di pagamento preferito non \350 presente denaro sufficiente per l\u2019acquisto, la banca o la societ\340 emittente della carta potrebbe addebitarti una tariffa.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Modifica</strong> accanto a \u201CLog in con PayPal\u201D.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verr\340 usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\340 usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Si applica la sezione \u201CPagamenti automatici\u201D delle <a href='%s'>Condizioni d\u2019uso PayPal</a>.</p><p>Per verificare il funzionamento dell\u2019addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\340 usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Per maggiori informazioni, vedi la sezione \u201CPagamenti automatici\u201D delle <a href='%s'>Condizioni d\u2019uso PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\340 usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Vedi la sezione \u201CPagamenti automatici\u201D delle <a href='%s'>Condizioni d\u2019uso PayPal</a> per maggiori informazioni.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verr\340 usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\340 usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Per maggiori informazioni, vedi la sezione \u201CPagamenti automatici\u201D delle <a href='%s'>Condizioni d\u2019uso PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\340 usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Per maggiori informazioni, vedi la sezione \u201CPagamenti automatici\u201D delle <a href='%s'>Condizioni d\u2019uso PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verr\340 usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall\u2019elenco.</p><p>Per maggiori informazioni, vedi la sezione \u201CPagamenti automatici\u201D delle <a href='%s'>Condizioni d\u2019uso PayPal</a>.</p>");
        b.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Come prima opzione per pagare i tuoi acquisti, verr\340 usato il tuo saldo PayPal. Se non \350 sufficiente, verranno usati, nell\u2019ordine, il conto bancario, PayPal Credit, la carta di debito (bancomat), la carta di credito e/o gli eCheck.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante dall\u2019elenco.</p><p>Potrebbe essere richiesta l\u2019autorizzazione di un piccolo pagamento per verificare la possibilit\340 di addebitare i pagamenti preautorizzati sul tuo conto PayPal. L\u2019autorizzazione verr\340 annullata e non ti verr\340 addebitato alcun importo.</p>");
        b.put("LOG_IN_TO_PAYPAL|AU", "Log in con PayPal");
        b.put("LOG_IN_TO_PAYPAL|GB", "Log in con PayPal");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l\u2019icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del Partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non \350 responsabile di azioni o errori da parte del Partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l\u2019icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del Partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l\u2019icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del Partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco. Se usi ancora la versione classica del sito, vai al tuo <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del Partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del Partner.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l\u2019icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l\u2019icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        b.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l\u2019icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall\u2019elenco.</p><p>PayPal non \350 responsabile di azioni o errori da parte del commerciante.</p>");
        c.put("AMOUNT_MISMATCH", "Il totale del carrello non corrisponde all\u2019importo delle vendite.");
        c.put("AUTHORIZATION_ALREADY_COMPLETED", "L\u2019autorizzazione \350 gi\340 stata completata.");
        c.put("AUTHORIZATION_CANNOT_BE_VOIDED", "L\u2019autorizzazione \350 in una provincia in cui non pu\362 essere annullata.");
        c.put("AUTHORIZATION_EXPIRED", "L\u2019autorizzazione \350 scaduta.");
        c.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "L\u2019ID autorizzazione richiesto non esiste.");
        c.put("AUTHORIZATION_VOIDED", "L\u2019autorizzazione \350 stata annullata.");
        c.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "\310 possibile riautorizzare solo le autorizzazioni originali.");
        c.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "La riautorizzazione non \350 consentita nel periodo di validit\340.");
        c.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "L\u2019importo supera il limite consentito.");
        c.put("CARD_TOKEN_PAYER_MISMATCH", "Impossibile accedere ai dati della carta in archivio.");
        c.put("CREDIT_CARD_CVV_CHECK_FAILED", "I dati della carta non sono validi. Correggi i tuoi dati e riprova.");
        c.put("CREDIT_CARD_REFUSED", "Carta rifiutata.");
        c.put("CURRENCY_MISMATCH", "La valuta di riscossione deve essere uguale a quella di autorizzazione.");
        c.put("CURRENCY_NOT_ALLOWED", "Valuta non supportata da PayPal.");
        c.put("DATA_RETRIEVAL", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("DUPLICATE_REQUEST_ID", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("EXPIRED_CREDIT_CARD", "La carta \350 scaduta");
        c.put("EXPIRED_CREDIT_CARD_TOKEN", "I dati di questa carta non sono pi\371 in archivio.\nInoltrali di nuovo.");
        c.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "La funzione non \350 supportata per questo beneficiario.");
        c.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "La transazione \350 stata gi\340 rimborsata parzialmente.");
        c.put("IMMEDIATE_PAY_NOT_SUPPORTED", "L\u2019opzione di pagamento immediato non \350 supportata per la finalit\340 impostata.");
        c.put("INSTRUMENT_DECLINED", "Il metodo di pagamento selezionato non \350 stato accettato. Scegli un altro metodo di pagamento.");
        c.put("INSUFFICIENT_FUNDS", "L\u2019acquirente non pu\362 pagare per denaro insufficiente.");
        c.put("INTERNAL_SERVICE_ERROR", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("INVALID_ACCOUNT_NUMBER", "Il numero di conto non esiste.");
        c.put("INVALID_ARGUMENT", "Transazione rifiutata per problemi tecnici");
        c.put("INVALID_CITY_STATE_ZIP", "Combinazione Citt\340/Provincia/CAP non valida.");
        c.put("INVALID_FACILITATOR_CONFIGURATION", "Impossibile elaborare la transazione per configurazione non valida.");
        c.put("INVALID_PAYER_ID", "Errore di sistema (ID acquirente non valido). Riprova pi\371 tardi.");
        c.put("INVALID_RESOURCE_ID", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("PAYEE_ACCOUNT_INVALID", "Il conto del beneficiario non ha un\u2019email confermata.");
        c.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Questo venditore non pu\362 ricevere pagamenti al momento.");
        c.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Il conto del beneficiario non ha un\u2019email confermata.");
        c.put("PAYEE_ACCOUNT_RESTRICTED", "Questo venditore non pu\362 ricevere pagamenti al momento.");
        c.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Il tuo conto \350 bloccato o chiuso.");
        c.put("PAYER_ACCOUNT_RESTRICTED", "Il tuo conto \350 stato limitato.");
        c.put("PAYER_CANNOT_PAY", "Impossibile inviare questo pagamento con PayPal.");
        c.put("PAYER_EMPTY_BILLING_ADDRESS", "L\u2019indirizzo di fatturazione \350 obbligatorio per le transazioni con carta non effettuate con PayPal.");
        c.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Impossibile accedere ai dati della carta in archivio.");
        c.put("PAYMENT_APPROVAL_EXPIRED", "L\u2019approvazione del pagamento \350 scaduta.");
        c.put("PAYMENT_EXPIRED", "Il pagamento \350 scaduto.");
        c.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "L\u2019acquirente non ha approvato il pagamento.");
        c.put("PAYMENT_REQUEST_ID_INVALID", "Il codice (ID) di richiesta PayPal non \350 valido. Riprova pi\371 tardi.");
        c.put("PAYMENT_STATE_INVALID", "Richiesta non valida nella provincia di pagamento.");
        c.put("PERMISSION_DENIED", "L\u2019operazione richiesta non \350 autorizzata.");
        c.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Il rimborso richiesto supera l\u2019importo della transazione originale.");
        c.put("REFUND_TIME_LIMIT_EXCEEDED", "Questa transazione \350 troppo datata per essere rimborsata.");
        c.put("REQUIRED_SCOPE_MISSING", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("TOO_MANY_REAUTHORIZATIONS", "Per questa autorizzazione non sono pi\371 consentite riautorizzazioni.");
        c.put("TRANSACTION_ALREADY_REFUNDED", "La transazione \350 stata gi\340 rimborsata.");
        c.put("TRANSACTION_LIMIT_EXCEEDED", "L\u2019importo supera il limite consentito.");
        c.put("TRANSACTION_REFUSED", "La transazione \350 stata rifiutata.");
        c.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "La transazione \350 stata rifiutata.");
        c.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Le preferenze del commerciante sono impostate per rifiutare automaticamente determinate transazioni.");
        c.put("UNKNOWN_ERROR", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("UNSUPPORTED_PAYEE_COUNTRY", "Il tuo Paese non \350 supportato.");
        c.put("VALIDATION_ERROR", "I dati di pagamento non sono validi. Correggi i tuoi dati e riprova.");
        c.put("ORDER_ALREADY_COMPLETED", "L\u2019ordine \350 stato gi\340 annullato, \350 scaduto o completato.");
        c.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Il numero massimo di autorizzazioni consentite per l\u2019ordine \350 stato raggiunto.");
        c.put("ORDER_VOIDED", "L\u2019ordine \350 stato annullato.");
        c.put("ORDER_CANNOT_BE_VOIDED", "L\u2019ordine \350 in uno stato che impedisce l\u2019annullamento.");
        c.put("INVALID_EXPERIENCE_PROFILE_ID", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("UNAUTHORIZED_PAYMENT", "Il commerciante non accetta questo tipo di pagamenti.");
        c.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta non supportata per il tipo di carta.");
        c.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo di carta non supportato.");
        c.put("ADDRESS_ADDITION_ERROR", "Si \350 verificato un errore durante l\u2019aggiunta dell\u2019indirizzo di spedizione al conto PayPal.");
        c.put("DUPLICATE_TRANSACTION", "Transazione doppia");
        c.put("INVALID_SHIPPING_ADDRESS", "L\u2019indirizzo di spedizione non \350 valido.");
        c.put("PAYMENT_CREATION_ERROR", "Si \350 verificato un problema nella disposizione del pagamento. Vai su paypal.it e controlla il tuo conto.");
        c.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Si \350 verificato un problema nella disposizione del pagamento: la tua carta \350 scaduta. Vai su paypal.it e controlla il tuo conto.");
        c.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Si \350 verificato un problema nella disposizione del pagamento: \350 richiesto un pagamento immediato, ad esempio una carta di credito. Vai su paypal.it e controlla il tuo conto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Si \350 verificato un problema nella disposizione del pagamento: la carta deve essere confermata. Vai su paypal.it e controlla il tuo conto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Si \350 verificato un problema nella disposizione del pagamento: questa applicazione richiede che sul tuo conto sia registrato un numero di telefono. Vai su paypal.it e controlla il tuo conto.");
        c.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Si \350 verificato un problema nella disposizione del pagamento: il conto necessita di un metodo di pagamento valido, ad esempio un conto bancario o una carta di pagamento. Vai su paypal.it e controlla il tuo conto.");
        c.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Si \350 verificato un problema nella disposizione del pagamento: il tuo saldo \350 negativo. Vai su paypal.it e controlla il tuo conto.");
        c.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Si \350 verificato un problema nella disposizione del pagamento: hai raggiunto il tuo limite di invio. Vai su paypal.it e controlla il tuo conto.");
        c.put("AUTH_RC_RISK_FAILURE", "Rifiutata per motivi di rischio.");
        c.put("AUTH_RC_OFAC_BLOCKED_IP", "Client non autorizzato.");
        c.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client non autorizzato.");
        c.put("invalid_user", "Email o password non corretta. Riprova.");
        c.put("locked_user", "Il tuo conto PayPal \350 stato temporaneamente bloccato. Riprova pi\371 tardi o accedi a www.paypal.com per sbloccare immediatamente il tuo conto PayPal.");
        c.put("max_attempts_exceeded", "Troppi tentativi di accesso non riusciti. Riprova pi\371 tardi.");
        c.put("invalid_request", "Si \350 verificato un errore.");
        c.put("unauthorized_client", "Richiesta non autorizzata.");
        c.put("access_denied", "Richiesta non autorizzata.");
        c.put("unsupported_response_type", "Si \350 verificato un errore.");
        c.put("invalid_scope", "Richiesta non autorizzata.");
        c.put("server_error", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("temporarily_unavailable", "Errore di sistema. Riprova pi\371 tardi.");
        c.put("stepup_required", "Non \350 possibile completare l\u2019accesso. Riprova pi\371 tardi o accedi a www.paypal.it per risolvere eventuali problema di sicurezza del tuo conto PayPal.");
    }

    public final String a()
    {
        return "it";
    }

    public final String a(Enum enum, String s)
    {
        enum = (fa)enum;
        s = (new StringBuilder()).append(enum.toString()).append("|").append(s).toString();
        if (b.containsKey(s))
        {
            return (String)b.get(s);
        } else
        {
            return (String)a.get(enum);
        }
    }

    public final String a(String s)
    {
        return (String)c.get(s);
    }

}
