// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.ebay.nautilus.domain.net.api.ecas.models;


// Referenced classes of package com.ebay.nautilus.domain.net.api.ecas.models:
//            EcasShoppingCart

public static final class  extends Enum
{

    private static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT $VALUES[];
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT_RANGE;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUNDLE_EPID_WITH_DISCOUNTS;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUNDLE_EPID_WITH_DISCOUNTS_PERCENT;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUNDLE_WITHOUT_DISCOUNTS;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUNDLE_WITHOUT_DISCOUNTS_NO_FREE_SHIPPING;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUNDLE_WITH_DISCOUNTS;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUY_1_ITEMS_GET_Y_PCT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUY_N_ITEMS_GET_M_ITEMS_FREE;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT BUY_N_ITEMS_GET_Y_PCT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT FOR_EVERY_BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT FOR_EVERY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT FOR_EVERY_N_ITEMS_GET_M_ITEMS_FREE;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT FOR_EVERY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT FOR_EVERY_X_AMT_SPENT_GET_Y_AMT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT MARK_DOWN_SALE;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT PROMOTIONAL_SHIPPING;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT PROMO_FREE_SHIPPING_ON_ITEM_X;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT PROMO_FREE_SHIPPING_SPEND_X;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT PROMO_FREE_SHIPPING_SPEND_X_ON_ITEM_Y;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT PROMO_SHIPPING_COST_ON_ITEM_X;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT PROMO_SHIPPING_COST_SPEND_X;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT PROMO_SHIPPING_COST_SPEND_X_ON_ITEMS_Y;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT REBATE_OFFER;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT SALE_AND_CLEARANCE;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT SALE_EVENT;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT SPEND_X_AMT_GET_Y_AMT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT SPEND_X_AMT_GET_Y_PCT_OFF_SUBTOTAL;
    public static final BUNDLE_EPID_WITH_DISCOUNTS_PERCENT VERTICAL_OFFER;

    public static  valueOf(String s)
    {
        return ()Enum.valueOf(com/ebay/nautilus/domain/net/api/ecas/models/EcasShoppingCart$PromotionalRuleTemplate, s);
    }

    public static [] values()
    {
        return ([])$VALUES.clone();
    }

    static 
    {
        SPEND_X_AMT_GET_Y_AMT_OFF_SUBTOTAL = new <init>("SPEND_X_AMT_GET_Y_AMT_OFF_SUBTOTAL", 0);
        SPEND_X_AMT_GET_Y_PCT_OFF_SUBTOTAL = new <init>("SPEND_X_AMT_GET_Y_PCT_OFF_SUBTOTAL", 1);
        BUY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL = new <init>("BUY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL", 2);
        BUY_N_ITEMS_GET_Y_PCT_OFF_SUBTOTAL = new <init>("BUY_N_ITEMS_GET_Y_PCT_OFF_SUBTOTAL", 3);
        BUY_N_ITEMS_GET_M_ITEMS_FREE = new <init>("BUY_N_ITEMS_GET_M_ITEMS_FREE", 4);
        BUY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF = new <init>("BUY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF", 5);
        BUNDLE_WITH_DISCOUNTS = new <init>("BUNDLE_WITH_DISCOUNTS", 6);
        BUNDLE_WITHOUT_DISCOUNTS = new <init>("BUNDLE_WITHOUT_DISCOUNTS", 7);
        SALE_EVENT = new <init>("SALE_EVENT", 8);
        SALE_AND_CLEARANCE = new <init>("SALE_AND_CLEARANCE", 9);
        PROMOTIONAL_SHIPPING = new <init>("PROMOTIONAL_SHIPPING", 10);
        PROMO_FREE_SHIPPING_SPEND_X = new <init>("PROMO_FREE_SHIPPING_SPEND_X", 11);
        PROMO_SHIPPING_COST_SPEND_X = new <init>("PROMO_SHIPPING_COST_SPEND_X", 12);
        PROMO_FREE_SHIPPING_SPEND_X_ON_ITEM_Y = new <init>("PROMO_FREE_SHIPPING_SPEND_X_ON_ITEM_Y", 13);
        PROMO_SHIPPING_COST_SPEND_X_ON_ITEMS_Y = new <init>("PROMO_SHIPPING_COST_SPEND_X_ON_ITEMS_Y", 14);
        PROMO_FREE_SHIPPING_ON_ITEM_X = new <init>("PROMO_FREE_SHIPPING_ON_ITEM_X", 15);
        PROMO_SHIPPING_COST_ON_ITEM_X = new <init>("PROMO_SHIPPING_COST_ON_ITEM_X", 16);
        BUNDLE_WITHOUT_DISCOUNTS_NO_FREE_SHIPPING = new <init>("BUNDLE_WITHOUT_DISCOUNTS_NO_FREE_SHIPPING", 17);
        VERTICAL_OFFER = new <init>("VERTICAL_OFFER", 18);
        REBATE_OFFER = new <init>("REBATE_OFFER", 19);
        FOR_EVERY_X_AMT_SPENT_GET_Y_AMT_OFF_SUBTOTAL = new <init>("FOR_EVERY_X_AMT_SPENT_GET_Y_AMT_OFF_SUBTOTAL", 20);
        FOR_EVERY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL = new <init>("FOR_EVERY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL", 21);
        FOR_EVERY_N_ITEMS_GET_M_ITEMS_FREE = new <init>("FOR_EVERY_N_ITEMS_GET_M_ITEMS_FREE", 22);
        FOR_EVERY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF = new <init>("FOR_EVERY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF", 23);
        BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL = new <init>("BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL", 24);
        BUY_1_ITEMS_GET_Y_PCT_OFF_SUBTOTAL = new <init>("BUY_1_ITEMS_GET_Y_PCT_OFF_SUBTOTAL", 25);
        FOR_EVERY_BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL = new <init>("FOR_EVERY_BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL", 26);
        AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT = new <init>("AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT", 27);
        AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT_RANGE = new <init>("AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT_RANGE", 28);
        MARK_DOWN_SALE = new <init>("MARK_DOWN_SALE", 29);
        BUNDLE_EPID_WITH_DISCOUNTS = new <init>("BUNDLE_EPID_WITH_DISCOUNTS", 30);
        BUNDLE_EPID_WITH_DISCOUNTS_PERCENT = new <init>("BUNDLE_EPID_WITH_DISCOUNTS_PERCENT", 31);
        $VALUES = (new .VALUES[] {
            SPEND_X_AMT_GET_Y_AMT_OFF_SUBTOTAL, SPEND_X_AMT_GET_Y_PCT_OFF_SUBTOTAL, BUY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL, BUY_N_ITEMS_GET_Y_PCT_OFF_SUBTOTAL, BUY_N_ITEMS_GET_M_ITEMS_FREE, BUY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF, BUNDLE_WITH_DISCOUNTS, BUNDLE_WITHOUT_DISCOUNTS, SALE_EVENT, SALE_AND_CLEARANCE, 
            PROMOTIONAL_SHIPPING, PROMO_FREE_SHIPPING_SPEND_X, PROMO_SHIPPING_COST_SPEND_X, PROMO_FREE_SHIPPING_SPEND_X_ON_ITEM_Y, PROMO_SHIPPING_COST_SPEND_X_ON_ITEMS_Y, PROMO_FREE_SHIPPING_ON_ITEM_X, PROMO_SHIPPING_COST_ON_ITEM_X, BUNDLE_WITHOUT_DISCOUNTS_NO_FREE_SHIPPING, VERTICAL_OFFER, REBATE_OFFER, 
            FOR_EVERY_X_AMT_SPENT_GET_Y_AMT_OFF_SUBTOTAL, FOR_EVERY_N_ITEMS_GET_Y_AMT_OFF_SUBTOTAL, FOR_EVERY_N_ITEMS_GET_M_ITEMS_FREE, FOR_EVERY_N_ITEMS_GET_M_ITEMS_AT_Y_PCT_OFF, BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL, BUY_1_ITEMS_GET_Y_PCT_OFF_SUBTOTAL, FOR_EVERY_BUY_1_ITEMS_GET_Y_AMT_OFF_SUBTOTAL, AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT, AUTO_SALE_CLEARANCE_WITH_DISCOUNT_PERCENT_RANGE, MARK_DOWN_SALE, 
            BUNDLE_EPID_WITH_DISCOUNTS, BUNDLE_EPID_WITH_DISCOUNTS_PERCENT
        });
    }

    private (String s, int i)
    {
        super(s, i);
    }
}
