// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.amazon.searchapp.retailsearch.client;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

// Referenced classes of package com.amazon.searchapp.retailsearch.client:
//            SearchConfigurationSet

public class StaticSearchConfiguration
{

    public StaticSearchConfiguration()
    {
    }

    public static SearchConfigurationSet build()
    {
        Map map = Collections.synchronizedMap(new LinkedHashMap(6));
        Map map1 = Collections.synchronizedMap(new LinkedHashMap(14));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://www.amazon.com").setSecureSiteUrl("https://www.amazon.com").setSearchServiceUrl("http://www.amazon.com").setSecureSearchServiceUrl("https://www.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://www.amazon.com.br").setSecureSiteUrl("https://www.amazon.com.br").setSearchServiceUrl("http://www.amazon.com.br").setSecureSearchServiceUrl("https://www.amazon.com.br").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://www.amazon.ca").setSecureSiteUrl("https://www.amazon.ca").setSearchServiceUrl("http://www.amazon.ca").setSecureSearchServiceUrl("https://www.amazon.ca").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://www.amazon.ca").setSecureSiteUrl("https://www.amazon.ca").setSearchServiceUrl("http://www.amazon.ca").setSecureSearchServiceUrl("https://www.amazon.ca").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://www.amazon.cn").setSecureSiteUrl("https://www.amazon.cn").setSearchServiceUrl("http://www.amazon.cn").setSecureSearchServiceUrl("https://www.amazon.cn").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://www.amazon.de").setSecureSiteUrl("https://www.amazon.de").setSearchServiceUrl("http://www.amazon.de").setSecureSearchServiceUrl("https://www.amazon.de").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://www.amazon.es").setSecureSiteUrl("https://www.amazon.es").setSearchServiceUrl("http://www.amazon.es").setSecureSearchServiceUrl("https://www.amazon.es").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://www.amazon.fr").setSecureSiteUrl("https://www.amazon.fr").setSearchServiceUrl("http://www.amazon.fr").setSecureSearchServiceUrl("https://www.amazon.fr").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://www.amazon.in").setSecureSiteUrl("https://www.amazon.in").setSearchServiceUrl("http://www.amazon.in").setSecureSearchServiceUrl("https://www.amazon.in").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://www.amazon.it").setSecureSiteUrl("https://www.amazon.it").setSearchServiceUrl("http://www.amazon.it").setSecureSearchServiceUrl("https://www.amazon.it").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://www.amazon.jp").setSecureSiteUrl("https://www.amazon.jp").setSearchServiceUrl("http://www.amazon.co.jp").setSecureSearchServiceUrl("https://www.amazon.co.jp").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://www.amazon.co.uk").setSecureSiteUrl("https://www.amazon.co.uk").setSearchServiceUrl("http://www.amazon.co.uk").setSecureSearchServiceUrl("https://www.amazon.co.uk").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://www.amazon.com.au").setSecureSiteUrl("https://www.amazon.com.au").setSearchServiceUrl("http://www.amazon.com.au").setSecureSearchServiceUrl("https://www.amazon.com.au").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://www.amazon.com.mx").setSecureSiteUrl("https://www.amazon.com.mx").setSearchServiceUrl("http://www.amazon.com.mx").setSecureSearchServiceUrl("https://www.amazon.com.mx").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map.put("amazon", (new SearchConfiguration.Builder()).setId("amazon").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(10));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(0x146e64).setObfuscatedMarketplaceId("A1IXFGJ6ITL7J4").setSiteUrl("http://primenow-us.amazon.com").setSecureSiteUrl("https://primenow-us.amazon.com").setSearchServiceUrl("http://primenow-us.amazon.com").setSecureSearchServiceUrl("https://primenow-us.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("nyc", (new SearchRealm.Builder()).setId("nyc").setLocale("en_US").setMarketplaceId(0x1359ca).setObfuscatedMarketplaceId("A1FI6AJ872SLSY").setSiteUrl("http://primenow.amazon.com").setSecureSiteUrl("https://primenow.amazon.com").setSearchServiceUrl("http://primenow.amazon.com").setSecureSearchServiceUrl("https://primenow.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("miami", (new SearchRealm.Builder()).setId("miami").setLocale("en_US").setMarketplaceId(0x1483ae).setObfuscatedMarketplaceId("ABFCYI119Q7RV").setSiteUrl("http://urmp-2-prod.amazon.com").setSecureSiteUrl("https://urmp-2-prod.amazon.com").setSearchServiceUrl("http://urmp-2-prod.amazon.com").setSecureSearchServiceUrl("https://urmp-2-prod.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("baltimore", (new SearchRealm.Builder()).setId("baltimore").setLocale("en_US").setMarketplaceId(0x148534).setObfuscatedMarketplaceId("AKYDKPSGVMMUD").setSiteUrl("http://urmp-3-prod.amazon.com").setSecureSiteUrl("https://urmp-3-prod.amazon.com").setSearchServiceUrl("http://urmp-3-prod.amazon.com").setSecureSearchServiceUrl("https://urmp-3-prod.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("dallas", (new SearchRealm.Builder()).setId("dallas").setLocale("en_US").setMarketplaceId(0x14853e).setObfuscatedMarketplaceId("A3IN3V5ELTHSS1").setSiteUrl("http://urmp-4-prod.amazon.com").setSecureSiteUrl("https://urmp-4-prod.amazon.com").setSearchServiceUrl("http://urmp-4-prod.amazon.com").setSecureSearchServiceUrl("https://urmp-4-prod.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("atlanta", (new SearchRealm.Builder()).setId("atlanta").setLocale("en_US").setMarketplaceId(0x148548).setObfuscatedMarketplaceId("A1UI7O2AITRR2Q").setSiteUrl("http://urmp-5-prod.amazon.com").setSecureSiteUrl("https://urmp-5-prod.amazon.com").setSearchServiceUrl("http://urmp-5-prod.amazon.com").setSecureSearchServiceUrl("https://urmp-5-prod.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("austin", (new SearchRealm.Builder()).setId("austin").setLocale("en_US").setMarketplaceId(0x14855c).setObfuscatedMarketplaceId("AH4LQL64AIXN4").setSiteUrl("http://urmp-7-prod.amazon.com").setSecureSiteUrl("https://urmp-7-prod.amazon.com").setSearchServiceUrl("http://urmp-7-prod.amazon.com").setSecureSearchServiceUrl("https://urmp-7-prod.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(0x50b37).setObfuscatedMarketplaceId("AM7DNVYQULIQ5").setSiteUrl("http://primenow.amazon.co.uk").setSecureSiteUrl("https://primenow.amazon.co.uk").setSearchServiceUrl("http://primenow.amazon.co.uk").setSecureSearchServiceUrl("https://primenow.amazon.co.uk").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(0x50bd7).setObfuscatedMarketplaceId("A1TERGVA4U2MLK").setSiteUrl("http://primenow.amazon.it").setSecureSiteUrl("https://primenow.amazon.it").setSearchServiceUrl("http://primenow.amazon.it").setSecureSearchServiceUrl("https://primenow.amazon.it").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(0x1d9ea).setObfuscatedMarketplaceId("A2MKBGGTHABQEV").setSiteUrl("http://primenow.amazon.co.jp").setSecureSiteUrl("https://primenow.amazon.co.jp").setSearchServiceUrl("http://primenow.amazon.co.jp").setSecureSearchServiceUrl("https://primenow.amazon.co.jp").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map.put("houdini", (new SearchConfiguration.Builder()).setId("houdini").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(1));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(0x1359ca).setObfuscatedMarketplaceId("A1FI6AJ872SLSY").setSiteUrl("http://primenow-preprod.amazon.com").setSecureSiteUrl("http://primenow-preprod.amazon.com").setSearchServiceUrl("http://primenow-preprod.amazon.com").setSecureSearchServiceUrl("http://primenow-preprod.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map.put("houdini-test1", (new SearchConfiguration.Builder()).setId("houdini-test1").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(1));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(0x1359ca).setObfuscatedMarketplaceId("A1FI6AJ872SLSY").setSiteUrl("http://primenow.integ.amazon.com").setSecureSiteUrl("http://primenow.integ.amazon.com").setSearchServiceUrl("http://primenow.integ.amazon.com").setSecureSearchServiceUrl("http://primenow.integ.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map.put("houdini-test2", (new SearchConfiguration.Builder()).setId("houdini-test2").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(14));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://sxqa-beta-us.amazon.com").setSecureSiteUrl("https://sxqa-beta-us.amazon.com").setSearchServiceUrl("http://sxqa-beta-us.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-us.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://sxqa-beta-br.amazon.com").setSecureSiteUrl("https://sxqa-beta-br.amazon.com").setSearchServiceUrl("http://sxqa-beta-br.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-br.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sxqa-beta-ca.amazon.com").setSecureSiteUrl("https://sxqa-beta-ca.amazon.com").setSearchServiceUrl("http://sxqa-beta-ca.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-ca.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sxqa-beta-ca.amazon.com").setSecureSiteUrl("https://sxqa-beta-ca.amazon.com").setSearchServiceUrl("http://sxqa-beta-ca.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-ca.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://sxqa-beta-cn.amazon.com").setSecureSiteUrl("https://sxqa-beta-cn.amazon.com").setSearchServiceUrl("http://sxqa-beta-cn.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-cn.amazon.com").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://sxqa-beta-de.amazon.com").setSecureSiteUrl("https://sxqa-beta-de.amazon.com").setSearchServiceUrl("http://sxqa-beta-de.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-de.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://sxqa-beta-es.amazon.com").setSecureSiteUrl("https://sxqa-beta-es.amazon.com").setSearchServiceUrl("http://sxqa-beta-es.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-es.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://sxqa-beta-fr.amazon.com").setSecureSiteUrl("https://sxqa-beta-fr.amazon.com").setSearchServiceUrl("http://sxqa-beta-fr.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-fr.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://sxqa-beta-in.amazon.com").setSecureSiteUrl("https://sxqa-beta-in.amazon.com").setSearchServiceUrl("http://sxqa-beta-in.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-in.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://sxqa-beta-it.amazon.com").setSecureSiteUrl("https://sxqa-beta-it.amazon.com").setSearchServiceUrl("http://sxqa-beta-it.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-it.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://sxqa-beta-jp.amazon.com").setSecureSiteUrl("https://sxqa-beta-jp.amazon.com").setSearchServiceUrl("http://sxqa-beta-jp.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-jp.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://sxqa-beta-uk.amazon.com").setSecureSiteUrl("https://sxqa-beta-uk.amazon.com").setSearchServiceUrl("http://sxqa-beta-uk.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-uk.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://sxqa-beta-au.amazon.com").setSecureSiteUrl("https://sxqa-beta-au.amazon.com").setSearchServiceUrl("http://sxqa-beta-au.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-au.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://sxqa-beta-mx.amazon.com").setSecureSiteUrl("https://sxqa-beta-mx.amazon.com").setSearchServiceUrl("http://sxqa-beta-mx.amazon.com").setSecureSearchServiceUrl("https://sxqa-beta-mx.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map.put("rsp-beta", (new SearchConfiguration.Builder()).setId("rsp-beta").setRealms(map1).build());
        map1 = Collections.synchronizedMap(new LinkedHashMap(14));
        map1.put("us", (new SearchRealm.Builder()).setId("us").setLocale("en_US").setMarketplaceId(1).setObfuscatedMarketplaceId("ATVPDKIKX0DER").setSiteUrl("http://sxqa-gamma-us.amazon.com").setSecureSiteUrl("https://sxqa-gamma-us.amazon.com").setSearchServiceUrl("http://sxqa-gamma-us.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-us.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("br", (new SearchRealm.Builder()).setId("br").setLocale("pt_BR").setMarketplaceId(0x80a7a).setObfuscatedMarketplaceId("A2Q3Y263D00KWC").setSiteUrl("http://sxqa-gamma-br.amazon.com").setSecureSiteUrl("https://sxqa-gamma-br.amazon.com").setSearchServiceUrl("http://sxqa-gamma-br.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-br.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_pt_BR").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("ca", (new SearchRealm.Builder()).setId("ca").setLocale("en_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sxqa-gamma-ca.amazon.com").setSecureSiteUrl("https://sxqa-gamma-ca.amazon.com").setSearchServiceUrl("http://sxqa-gamma-ca.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-ca.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setInputEncoding("UTF-8").build());
        map1.put("ca_fr", (new SearchRealm.Builder()).setId("ca_fr").setLocale("fr_CA").setMarketplaceId(7).setObfuscatedMarketplaceId("A2EUQ1WTGCTBG2").setSiteUrl("http://sxqa-gamma-ca.amazon.com").setSecureSiteUrl("https://sxqa-gamma-ca.amazon.com").setSearchServiceUrl("http://sxqa-gamma-ca.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-ca.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_fr_CA").setEncodingValue("\305M\305\u017D\325\321").build());
        map1.put("cn", (new SearchRealm.Builder()).setId("cn").setLocale("zh_CN").setMarketplaceId(3240).setObfuscatedMarketplaceId("AAHKV2X7AFYLW").setSiteUrl("http://sxqa-gamma-cn.amazon.com").setSecureSiteUrl("https://sxqa-gamma-cn.amazon.com").setSearchServiceUrl("http://sxqa-gamma-cn.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-cn.amazon.com").setCompletionServiceUrl("http://completion.amazon.cn").setSecureCompletionServiceUrl("https://completion.amazon.cn").setEncodingParam("__mk_zh_CN").setEncodingValue("\u4E9A\u9A6C\u900A\u7F51\u7AD9").build());
        map1.put("de", (new SearchRealm.Builder()).setId("de").setLocale("de_DE").setMarketplaceId(4).setObfuscatedMarketplaceId("A1PA6795UKMFR9").setSiteUrl("http://sxqa-gamma-de.amazon.com").setSecureSiteUrl("https://sxqa-gamma-de.amazon.com").setSearchServiceUrl("http://sxqa-gamma-de.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-de.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_de_DE").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("es", (new SearchRealm.Builder()).setId("es").setLocale("es_ES").setMarketplaceId(44551).setObfuscatedMarketplaceId("A1RKKUPIHCS9HS").setSiteUrl("http://sxqa-gamma-es.amazon.com").setSecureSiteUrl("https://sxqa-gamma-es.amazon.com").setSearchServiceUrl("http://sxqa-gamma-es.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-es.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_es_ES").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("fr", (new SearchRealm.Builder()).setId("fr").setLocale("fr_FR").setMarketplaceId(5).setObfuscatedMarketplaceId("A13V1IB3VIYZZH").setSiteUrl("http://sxqa-gamma-fr.amazon.com").setSecureSiteUrl("https://sxqa-gamma-fr.amazon.com").setSearchServiceUrl("http://sxqa-gamma-fr.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-fr.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_fr_FR").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("in", (new SearchRealm.Builder()).setId("in").setLocale("en_IN").setMarketplaceId(44571).setObfuscatedMarketplaceId("A21TJRUUN4KGV").setSiteUrl("http://sxqa-gamma-in.amazon.com").setSecureSiteUrl("https://sxqa-gamma-in.amazon.com").setSearchServiceUrl("http://sxqa-gamma-in.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-in.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setInputEncoding("UTF-8").build());
        map1.put("it", (new SearchRealm.Builder()).setId("it").setLocale("it_IT").setMarketplaceId(35691).setObfuscatedMarketplaceId("APJ6JRA9NG5V4").setSiteUrl("http://sxqa-gamma-it.amazon.com").setSecureSiteUrl("https://sxqa-gamma-it.amazon.com").setSearchServiceUrl("http://sxqa-gamma-it.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-it.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_it_IT").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("jp", (new SearchRealm.Builder()).setId("jp").setLocale("ja_JP").setMarketplaceId(6).setObfuscatedMarketplaceId("A1VC38T7YXB528").setSiteUrl("http://sxqa-gamma-jp.amazon.com").setSecureSiteUrl("https://sxqa-gamma-jp.amazon.com").setSearchServiceUrl("http://sxqa-gamma-jp.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-jp.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setEncodingParam("__mk_ja_JP").setEncodingValue("\u30AB\u30BF\u30AB\u30CA").build());
        map1.put("uk", (new SearchRealm.Builder()).setId("uk").setLocale("en_GB").setMarketplaceId(3).setObfuscatedMarketplaceId("A1F83G8C2ARO7P").setSiteUrl("http://sxqa-gamma-uk.amazon.com").setSecureSiteUrl("https://sxqa-gamma-uk.amazon.com").setSearchServiceUrl("http://sxqa-gamma-uk.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-uk.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.uk").setSecureCompletionServiceUrl("https://completion.amazon.co.uk").setEncodingParam("__mk_en_GB").setEncodingValue("\305M\305Z\325\321").build());
        map1.put("au", (new SearchRealm.Builder()).setId("au").setLocale("en_AU").setMarketplaceId(0x1b244).setObfuscatedMarketplaceId("A39IBJ37TRP1C6").setSiteUrl("http://sxqa-gamma-au.amazon.com").setSecureSiteUrl("https://sxqa-gamma-au.amazon.com").setSearchServiceUrl("http://sxqa-gamma-au.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-au.amazon.com").setCompletionServiceUrl("http://completion.amazon.co.jp").setSecureCompletionServiceUrl("https://completion.amazon.co.jp").setInputEncoding("UTF-8").build());
        map1.put("mx", (new SearchRealm.Builder()).setId("mx").setLocale("es_MX").setMarketplaceId(0xbc6ba).setObfuscatedMarketplaceId("A1AM78C64UM0Y8").setSiteUrl("http://sxqa-gamma-mx.amazon.com").setSecureSiteUrl("https://sxqa-gamma-mx.amazon.com").setSearchServiceUrl("http://sxqa-gamma-mx.amazon.com").setSecureSearchServiceUrl("https://sxqa-gamma-mx.amazon.com").setCompletionServiceUrl("http://completion.amazon.com").setSecureCompletionServiceUrl("https://completion.amazon.com").setEncodingParam("__mk_es_MX").setEncodingValue("\305M\305Z\325\321").build());
        map.put("rsp-gamma", (new SearchConfiguration.Builder()).setId("rsp-gamma").setRealms(map1).build());
        return (new SearchConfigurationSet.Builder()).setConfigurations(map).build();
    }
}
