// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.ebay.mobile;

import java.util.HashMap;
import java.util.Map;

public class ItemViewShipping
{
    public static class ShippingDisplayOrder
    {

        public int colorId;
        public boolean costShowEachAdditional;
        public boolean eddIncludeDayOfWeek;
        public boolean eddReturnJustDates;
        public ShippingDisplayOrderEnum type;

        public ShippingDisplayOrder(ShippingDisplayOrderEnum shippingdisplayorderenum, int i)
        {
            this(shippingdisplayorderenum, i, false, false);
        }

        public ShippingDisplayOrder(ShippingDisplayOrderEnum shippingdisplayorderenum, int i, boolean flag)
        {
            this(shippingdisplayorderenum, i, false, false);
            costShowEachAdditional = flag;
        }

        public ShippingDisplayOrder(ShippingDisplayOrderEnum shippingdisplayorderenum, int i, boolean flag, boolean flag1)
        {
            colorId = i;
            type = shippingdisplayorderenum;
            eddReturnJustDates = flag;
            eddIncludeDayOfWeek = flag1;
        }
    }

    public static final class ShippingDisplayOrderEnum extends Enum
    {

        private static final ShippingDisplayOrderEnum $VALUES[];
        public static final ShippingDisplayOrderEnum COST;
        public static final ShippingDisplayOrderEnum EDD;
        public static final ShippingDisplayOrderEnum LOCATION;
        public static final ShippingDisplayOrderEnum SERVICE_NAME;

        public static ShippingDisplayOrderEnum valueOf(String s)
        {
            return (ShippingDisplayOrderEnum)Enum.valueOf(com/ebay/mobile/ItemViewShipping$ShippingDisplayOrderEnum, s);
        }

        public static ShippingDisplayOrderEnum[] values()
        {
            return (ShippingDisplayOrderEnum[])$VALUES.clone();
        }

        static 
        {
            EDD = new ShippingDisplayOrderEnum("EDD", 0);
            COST = new ShippingDisplayOrderEnum("COST", 1);
            LOCATION = new ShippingDisplayOrderEnum("LOCATION", 2);
            SERVICE_NAME = new ShippingDisplayOrderEnum("SERVICE_NAME", 3);
            $VALUES = (new ShippingDisplayOrderEnum[] {
                EDD, COST, LOCATION, SERVICE_NAME
            });
        }

        private ShippingDisplayOrderEnum(String s, int i)
        {
            super(s, i);
        }
    }


    public static final HashMap shippingNameMap = setupShippingNameMap();
    public static final HashMap siteSpecificShippingNamesMap = new HashMap();

    public ItemViewShipping()
    {
    }

    public static void addShippingNamesSiteMap(String s, Map map)
    {
        if (s != null)
        {
            siteSpecificShippingNamesMap.put(s, map);
        }
    }

    public static boolean isSitePopulated(String s)
    {
        return siteSpecificShippingNamesMap.get(s) != null;
    }

    private static HashMap setupShippingNameMap()
    {
        HashMap hashmap = new HashMap();
        hashmap.put("77_DE_eBayDHLPaket24x7", "eBay DHL Paket 24/7 (Abgabe und Lieferung an Packstation)");
        hashmap.put("77_DE_IloxxWorldWideInternational", "iloxx World Wide");
        hashmap.put("77_DE_DHLPackchen", "DHL P\344ckchen");
        hashmap.put("77_PromotionalShippingMethod", "Versand zum Sonderpreis");
        hashmap.put("77_DE_NachnahmeVersandInklNachnahmegebuhr", "Nachnahme (Versand inkl. Nachnahmegeb\374hr)");
        hashmap.put("77_DE_eBayDHLPaeckchen", "eBay DHL Paeckchen");
        hashmap.put("77_DE_InsuredExpressOrCourierInternational", "Versicherter Express- oder Kurierversand");
        hashmap.put("77_DE_SparversandAusDemAusland", "Sparversand aus dem Ausland");
        hashmap.put("77_DE_InsuredDispatch", "Versicherter Versand");
        hashmap.put("77_DE_StandardversandAusDemAusland", "Standardversand aus dem Ausland");
        hashmap.put("77_DE_ExpeditedInternational", "Expresspauschale f\374r internationalen Versand");
        hashmap.put("77_DE_ExpressOrCourierInternational", "Express- oder Kurierversand");
        hashmap.put("77_DE_ExpressOrCourier", "Express- oder Kurierversand");
        hashmap.put("77_DE_GLSPaket", "GLS Paket");
        hashmap.put("77_DE_SonstigeInternational", "Economy Int'l Versand");
        hashmap.put("77_DE_IloxxTransportXXL", "iloxx Transport XXL");
        hashmap.put("77_DE_DeutschePostBriefLuftInternational", "Deutsche Post Brief (Luft)");
        hashmap.put("77_DE_DHLPaketInternational", "DHL Paket International");
        hashmap.put("77_DE_StandardInternational", "Standardpauschale f\374r internationalen Versand");
        hashmap.put("77_DE_EbayHermesPaketShop2Shop", "eBay Hermes Paket Shop2Shop");
        hashmap.put("77_DE_ExpressInternational", "Express Int'l Versand");
        hashmap.put("77_DE_HermesPaketShop2Shop", "Hermes Paket Shop2Shop");
        hashmap.put("77_DE_DeutschePostByendung", "Deutsche Post B\375endung");
        hashmap.put("77_DE_SpecialDelivery", "Sonderversand");
        hashmap.put("77_DE_InsuredExpressOrCourier", "Versicherter Express- oder Kurierversand");
        hashmap.put("77_DE_DeutschePostBrief", "Deutsche Post Brief");
        hashmap.put("77_DE_DHL2KGPaket", "DHL 2kg Paket (nur f\374r kurze Zeit)");
        hashmap.put("77_DE_DeutschePostWarensendungInternational", "Deutsche Post Warensendung");
        hashmap.put("77_DE_SonstigeDomestic", "Sonstige 1-2 Werktage");
        hashmap.put("77_DE_VersicherterSonderversandZBMobelKFZ", "Versicherter Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("77_DE_Einschreiben", "Einschreiben");
        hashmap.put("77_DE_HermesPaket", "Hermes Paket");
        hashmap.put("77_DE_DeutschePostBuchersendung", "Deutsche Post B\374chersendung");
        hashmap.put("77_DE_Express", "Sonstige 1 Werktag");
        hashmap.put("77_DE_Pickup", "Abholung");
        hashmap.put("77_DE_eBayHermesPaketShop2ShopKaeufer", "eBay Hermes Paket Shop2Shop (Abgabe und Zustellung im PaketShop)");
        hashmap.put("77_DE_DHLPostpaket", "DHL Postpaket");
        hashmap.put("77_DE_UPSStandard", "UPS Standard");
        hashmap.put("77_DE_DeutschePostBriefLandInternational", "Deutsche Post Brief (Land)");
        hashmap.put("77_DE_DHLStarPaeckchen", "DHL Star-Paeckchen");
        hashmap.put("77_DE_HermesPaketVersichert", "Hermes Paket (versichert)");
        hashmap.put("77_DE_Paket", "Paketversand");
        hashmap.put("77_DE_UnversicherterExpressVersandInternational", "Unversicherter Express - Versand");
        hashmap.put("77_DE_iLoxxTransportXXLInternational", "iloxx Transport XXL");
        hashmap.put("77_DE_UnversicherterVersandInternational", "Unversicherter Versand");
        hashmap.put("77_DE_DeutschePostBriefInternational", "Deutsche Post Brief");
        hashmap.put("77_DE_DPBuecherWarensendung", "Deutsche Post B\374cher-/Warensendung");
        hashmap.put("77_DE_HermesPaketShop2ShopKaeufer", "Hermes Paket Shop2Shop (Kaeufer erhaelt E-Mail von Hermes bei Zustellung)");
        hashmap.put("77_DE_IloxxTransport", "iloxx Transport");
        hashmap.put("77_DE_HermesPaketInternational", "Hermes Paket International");
        hashmap.put("77_DE_HermesPaketUnversichertInternational", "Hermes Paket (unversichert)");
        hashmap.put("77_DE_BitteTreffenSieEineAuswahl", "DE_BITTE_TREFFEN_SIE_EINE_AUSWAHL");
        hashmap.put("77_DE_HermesPaketSperrgut", "Hermes Paket Sperrgut");
        hashmap.put("77_DE_SonstigerVersandInternational", "Sonstiger Versand (Siehe Artikelbeschreibung)");
        hashmap.put("77_DE_DPDClassic", "DPD Classic");
        hashmap.put("77_DE_Sonstige", "Sonstige (Siehe Artikelbeschreibung)");
        hashmap.put("77_DE_DHLPaket", "DHL Paket");
        hashmap.put("77_DE_eBayHermesPaketSperrgutShop2Shop", "eBay Hermes Paket Sperrgut Shop2Shop (Abgabe und Zustellung im Paketshop)");
        hashmap.put("77_DE_SonderversandZBMobelKFZ", "Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("77_DE_Writing", "Einschreiben (Versand inkl. Einschreibengeb\374hr)");
        hashmap.put("77_DE_IloxxStandard", "iloxx Standard");
        hashmap.put("77_DE_HermesPaketUnversichert", "Hermes Paket (unversichert)");
        hashmap.put("77_DE_DPDExpress", "DPD Express");
        hashmap.put("77_DE_Nachname", "Nachnahme");
        hashmap.put("77_DE_DHLPaeckchenPackstation", "DHL Paeckchen Packstation");
        hashmap.put("77_DE_DHLPaketPackstation", "DHL Paket Packstation");
        hashmap.put("77_DE_EinschreibenVersandInklEinschreibengebuhr", "Einschreiben (Versand inkl. Einschreibengeb\374hr)");
        hashmap.put("77_DE_DHLPostpaketInternational", "DHL Postpaket International");
        hashmap.put("77_DE_StandardDispatch", "Unversicherter Versand");
        hashmap.put("77_DE_UnversicherterVersand", "Unversicherter Versand");
        hashmap.put("77_DE_iLoxxUbernachtExpressInternational", "iloxx \334bernacht Express");
        hashmap.put("77_DE_iLoxxStandardInternational", "iloxx Standard");
        hashmap.put("77_DE_ExpressversandAusDemAusland", "Expressversand aus dem Ausland");
        hashmap.put("77_DE_PaketInternational", "Standard Int'l Versand");
        hashmap.put("77_DE_COD", "Nachnahme (Versand inkl. Nachnahmegeb\374hr)");
        hashmap.put("77_DE_SpecialDispatch", "Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("77_DE_UPSExpress", "UPS Express");
        hashmap.put("77_DE_IloxxTransportInternational", "iloxx Transport International");
        hashmap.put("77_DE_DeutschePostWarensendung", "Deutsche Post Warensendung");
        hashmap.put("77_DE_InsuredSpecialDispatch", "Versicherter Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("77_DE_VersicherterExpressVersandInternational", "Versicherter Express - Versand");
        hashmap.put("77_DE_VersicherterVersandInternational", "Versicherter Versand");
        hashmap.put("77_DE_IloxxUbernachtExpress", "iloxx \334bernacht Express");
        hashmap.put("77_DE_DHLPackchenInternational", "DHL P\344ckchen International");
        hashmap.put("77_DE_IloxxEuropaInternational", "iloxx Europa");
        hashmap.put("77_DE_HermesPaketVersichertInternational", "Hermes Paket (versichert)");
        hashmap.put("186_ES_CartasNacionalesHasta20", "Cartas nacionales hasta 20 gr");
        hashmap.put("186_ES_EconomyPacketInternational", "Paquete internacional economico");
        hashmap.put("186_ES_PaqueteAzulHasta2kg", "Paquete Azul (nacional) hasta 2 kg");
        hashmap.put("186_ES_CartasNacionalesDeMas20", "Cartas nacionales de m\341s de 20 gr");
        hashmap.put("186_ES_OtherInternational", "Otros env\355os internacionales (ver descripci\363n)");
        hashmap.put("186_ES_EmsPostalExpressInternational", "Ems postal expres internacional");
        hashmap.put("186_ES_CartasInternacionalesHasta20", "Cartas internacionales hasta 20 gr");
        hashmap.put("186_ES_ExpeditedInternational", "Env\355os internacionales urgentes est\341ndar");
        hashmap.put("186_ES_PaqueteAzulDeMas2kg", "Paquete Azul (nacional) de m\341s de 2 kg");
        hashmap.put("186_ES_Urgente", "Urgente (ver descripci\363n)");
        hashmap.put("186_ES_CartasPostalInternational", "Cartas y tarjetas postales internacionales");
        hashmap.put("186_PromotionalShippingMethod", "Promoci\363n en servicio de env\355o");
        hashmap.put("186_ES_Otros", "Otros (ver descripci\363n)");
        hashmap.put("186_ES_PickUp", "Recogida local");
        hashmap.put("186_ES_StandardInternational", "Env\355os internacionales est\341ndar");
        hashmap.put("186_ES_CartasInternacionalesDeMas20", "Cartas internacionales de mas de 20 gr");
        hashmap.put("186_ES_PaqueteInternacionalEconomico", "Paquete Internacional Econ\363mico");
        hashmap.put("205_IE_OtherCourierInternational", "Other courier or delivery service");
        hashmap.put("205_IE_StandardInternationalFlatRatePostage", "Standard Int'l Flat Rate Postage");
        hashmap.put("205_PromotionalShippingMethod", "Promotional Postage Service");
        hashmap.put("205_IE_OtherInternationalPostage", "Other Int'l Postage (see description)");
        hashmap.put("205_IE_EconomySDSCourier", "Economy SDS Courier");
        hashmap.put("205_IE_SwiftPostExpressInternational", "SwiftPost Express");
        hashmap.put("205_IE_EconomySDSCourierInternational", "Economy SDS Courier");
        hashmap.put("205_IE_InternationalEconomyService", "International Economy Service");
        hashmap.put("205_IE_SellersStandardRate", "Seller's Standard Rate");
        hashmap.put("205_IE_EMSSDSCourierInternational", "EMS SDS Courier");
        hashmap.put("205_IE_EMSSDSCourier", "EMS SDS Courier");
        hashmap.put("205_IE_RegisteredPost", "Registered Post");
        hashmap.put("205_IE_ExpeditedInternationalFlatRatePostage", "Expedited Int'l Flat Rate Postage");
        hashmap.put("205_IE_SellersStandardRateInternational", "Sellers Standard International Rate");
        hashmap.put("205_IE_SwiftPostNational", "SwiftPost National");
        hashmap.put("205_IE_OtherCourier", "Other Courier");
        hashmap.put("205_IE_CollectionInPerson", "Collection in person");
        hashmap.put("205_IE_SwiftPostInternational", "SwiftPost International");
        hashmap.put("205_IE_CollectionInPersonInternational", "Collect in person");
        hashmap.put("205_IE_InternationalPriorityService", "International Priority Service");
        hashmap.put("205_IE_FirstClassLetterService", "First Class Letter Service");
        hashmap.put("71_FR_Autre", "Autre mode d'envoi de courrier");
        hashmap.put("71_FR_LaPosteLetterMax", "Lettre Max");
        hashmap.put("71_FR_StandardInternational", "Frais de livraison internationale fixes");
        hashmap.put("71_FR_UPSStandardInternational", "UPS Standard");
        hashmap.put("71_FR_Chrono10", "Chrono 10");
        hashmap.put("71_FR_AuteModeDenvoiDeColis", "Autre mode d'envoi de colis");
        hashmap.put("71_FR_UPSStandard", "UPS - Standard");
        hashmap.put("71_FR_LaPosteColissimoInternational", "La Poste - Colissimo International");
        hashmap.put("71_FR_PostOfficeLetterRecommended", "Lettre recommand\351e");
        hashmap.put("71_FR_ExpeditedInternational", "Frais fixes pour livraison internationale express");
        hashmap.put("71_FR_LaPosteColisEconomiqueInternational", "La Poste - Colis Economique International");
        hashmap.put("71_FR_Chronopost", "Chronopost");
        hashmap.put("71_FR_DHLExpressEuropack", "DHL - Express Europack");
        hashmap.put("71_FR_Colieco", "Coli\351co");
        hashmap.put("71_FR_OtherInternational", "Autres livraisons internationales (voir description)");
        hashmap.put("71_PromotionalShippingMethod", "Promotion sur les frais de livraison");
        hashmap.put("71_FR_DHLInternational", "DHL");
        hashmap.put("71_FR_LaPosteColissimoEmballageInternational", "La Poste - Colissimo Emballage International");
        hashmap.put("71_FR_ChronopostExpressInternational", "Chronopost Express International");
        hashmap.put("71_FR_Ecopli", "Ecopli");
        hashmap.put("71_FR_LaPosteInternationalEconomyCourier", "La Poste - Courrier International Economique");
        hashmap.put("71_FR_ColiposteColissimoRecommended", "Colissimo Recommand\351");
        hashmap.put("71_FR_ColiposteColissimo", "Colissimo");
        hashmap.put("71_FR_RemiseEnMainPropre", "Remise en mains propres");
        hashmap.put("71_FR_PostOfficeLetter", "Lettre");
        hashmap.put("71_FR_ChronopostPremiumInternational", "Chronopost Premium International");
        hashmap.put("71_FR_Chrono13", "Chrono 13");
        hashmap.put("71_FR_ChronopostClassicInternational", "Chronopost Classic International");
        hashmap.put("71_FR_ColiposteColissimoDirect", "Coliposte - Colissimo Direct");
        hashmap.put("71_FR_LaPosteInternationalPriorityCourier", "La Poste - Courrier International Prioritaire");
        hashmap.put("71_FR_ChronopostChronoRelais", "Chronopost - Chrono Relais");
        hashmap.put("71_FR_PostOfficeLetterFollowed", "Lettre avec suivi");
        hashmap.put("71_FR_UPSExpressInternational", "UPS Express");
        hashmap.put("71_FR_UPSStandardAgainstRefund", "Contre remboursement");
        hashmap.put("71_FR_Chrono18", "Chrono 18");
        hashmap.put("71_FR_ChronoposteInternationalClassic", "Chronoposte - Chrono Classic International");
        hashmap.put("0_EconomyShippingFromOutsideUS", "Economy Shipping from outside US");
        hashmap.put("0_FedExHomeDelivery", "FedEx Ground or FedEx Home Delivery");
        hashmap.put("0_USPSGlobalPriorityLargeEnvelope", "USPS Global Priority Mail Flat Rate Large Envelope");
        hashmap.put("0_USPSGlobalExpressGuaranteed", "USPS Global Express Guaranteed");
        hashmap.put("0_PromotionalShippingMethod", "Promotional Shipping Service");
        hashmap.put("0_OtherInternational", "Economy Int'l Shipping");
        hashmap.put("0_Other", "Economy Shipping");
        hashmap.put("0_Pickup", "Local Pickup");
        hashmap.put("0_USPSPriorityFlatRateBox", "USPS Priority Mail Medium Flat Rate Box");
        hashmap.put("0_USPSFirstClassLetter", "USPS First Class Letter ");
        hashmap.put("0_ShippingMethodStandard", "Standard Shipping");
        hashmap.put("0_ExpeditedInternational", "Expedited Int'l Shipping");
        hashmap.put("0_UPSWorldWideExpedited", "UPS Worldwide Expedited");
        hashmap.put("0_USPSFirstClass", "USPS First Class Mail");
        hashmap.put("0_FreightShippingInternational", "Freight Shipping");
        hashmap.put("0_USPSPriorityMailInternationalFlatRateEnvelope", "USPS Priority Mail International Flat Rate Envelope");
        hashmap.put("0_USPSPriorityMailInternationalLegalFlatRateEnvelope", "USPS Priority Mail International Legal Flat Rate Envelope");
        hashmap.put("0_FedExExpressSaver", "FedEx Express Saver");
        hashmap.put("0_FedExGroundInternationalToCanada", "FedEx Ground International for Canada");
        hashmap.put("0_FreightShipping", "Freight Shipping");
        hashmap.put("0_USPSExpressMailInternationalLegalFlatRateEnvelope", "USPS Express Mail International Legal Flat Rate Envelope");
        hashmap.put("0_UPSNextDay", "UPS Next Day Air Saver");
        hashmap.put("0_USPSPriorityMailRegionalBoxA", "USPS Priority Mail Regional Box A");
        hashmap.put("0_USPSPriorityMailRegionalBoxB", "USPS Priority Mail Regional Box B");
        hashmap.put("0_UPSWorldWideExpressPlusBox25kg", "UPS Worldwide Express Plus Box 25Kg");
        hashmap.put("0_UPSWorldWideExpressPlus", "UPS Worldwide Express Plus");
        hashmap.put("0_USPSPriorityMailPaddedFlatRateEnvelope", "USPS Priority Mail Padded Flat Rate Envelope");
        hashmap.put("0_UPSNextDayAir", "UPS Next Day Air");
        hashmap.put("0_USPSEconomyLetter", "USPS Economy Letter Post");
        hashmap.put("0_USPSFirstClassLargeEnvelop", "USPS First Class Large Envelop");
        hashmap.put("0_Freight", "Freight");
        hashmap.put("0_USPSMedia", "USPS Media Mail");
        hashmap.put("0_FedExStandardOvernight", "FedEx Standard Overnight");
        hashmap.put("0_UPSWorldwideSaver", "UPS Worldwide Saver");
        hashmap.put("0_USPSPriorityFlatRateEnvelope", "USPS Priority Mail Flat Rate Envelope");
        hashmap.put("0_USPSExpressMailInternationalFlatRateEnvelope", "USPS Express Mail International Flat Rate Envelope");
        hashmap.put("0_USPSFirstClassMailInternationalParcel", "USPS First Class Mail International Parcel");
        hashmap.put("0_UPSStandardToCanada", "UPS Standard To Canada");
        hashmap.put("0_Delivery", "Local Delivery");
        hashmap.put("0_USPSPriorityMailInternationalPaddedFlatRateEnvelope", "USPS Priority Mail International Padded Flat Rate Envelope");
        hashmap.put("0_USPSExpressMailInternational", "USPS Express Mail International");
        hashmap.put("0_USPSAirmailLetter", "USPS Airmail Letter Post");
        hashmap.put("0_USPSExpressFlatRateEnvelope", "USPS Express Mail Flat Rate Envelope");
        hashmap.put("0_USPSFirstClassMailInternational", "USPS First Class Mail International");
        hashmap.put("0_USPSFirstClassMailInternationalLetter", "USPS First Class Mail International Letter");
        hashmap.put("0_UPS3rdDay", "UPS 3 Day Select");
        hashmap.put("0_UPSWorldWideExpressBox10kg", "UPS Worldwide Express Box 10Kg");
        hashmap.put("0_UPS2DayAirAM", "UPS Next Day Air AM");
        hashmap.put("0_USPSFirstClassMailInternationalLargeEnvelope", "USPS First Class Mail International Large Envelope");
        hashmap.put("0_USPSParcel", "USPS Parcel Post");
        hashmap.put("0_USPSGlobalPriority", "USPS Global Priority Mail");
        hashmap.put("0_USPSPriorityMailInternationalFlatRateBox", "USPS Priority Mail International Medium Flat Rate Box");
        hashmap.put("0_USPSExpressMailLegalFlatRateEnvelope", "USPS Express Mail Legal Flat Rate Envelope");
        hashmap.put("0_FedEx2Day", "FedEx 2Day");
        hashmap.put("0_UPSWorldWideExpressBox25kg", "UPS Worldwide Express Box 25Kg");
        hashmap.put("0_UPSWorldWideExpress", "UPS Worldwide Express");
        hashmap.put("0_USPSPriorityMailLegalFlatRateEnvelope", "USPS Priority Mail Legal Flat Rate Envelope");
        hashmap.put("0_USPSExpressMail", "USPS Express Mail");
        hashmap.put("0_USPSPriorityMailSmallFlatRateBox", "USPS Priority Mail Small Flat Rate Box");
        hashmap.put("0_UPS2ndDay", "UPS 2nd Day Air");
        hashmap.put("0_FedExInternationalEconomy", "FedEx International Economy");
        hashmap.put("0_USPSPriorityMailLargeFlatRateBox", "USPS Priority Mail Large Flat Rate Box");
        hashmap.put("0_StandardInternational", "Standard Int'l Shipping");
        hashmap.put("0_StandardShippingFromOutsideUS", "Standard Shipping from outside US");
        hashmap.put("0_USPSEconomyParcel", "USPS Economy Parcel Post");
        hashmap.put("0_USPSPriority", "USPS Priority Mail");
        hashmap.put("0_USPSAirmailParcel", "USPS Airmail Parcel Post");
        hashmap.put("0_USPSGlobalPrioritySmallEnvelope", "USPS Global Priority Mail Flat Rate Small Envelope");
        hashmap.put("0_UPSWorldWideExpressPlusBox10kg", "UPS Worldwide Express Plus Box 10Kg");
        hashmap.put("0_LocalDelivery", "Local Delivery/Pickup");
        hashmap.put("0_ShippingMethodExpress", "Expedited Shipping");
        hashmap.put("0_FedExInternationalPriority", "FedEx International Priority");
        hashmap.put("0_ExpeditedShippingFromOutsideUS", "Expedited Shipping from outside US");
        hashmap.put("0_USPSPriorityMailInternational", "USPS Priority Mail International");
        hashmap.put("0_USPSGround", "US Postal Service Ground");
        hashmap.put("0_USPSFirstClassParcel", "USPS First Class Parcel");
        hashmap.put("0_UPSGround", "UPS Ground");
        hashmap.put("0_USPSPriorityMailInternationalSmallFlatRateBox", "US Postal Service Priority Mail International Small Flat Rate Box");
        hashmap.put("0_USPSPriorityMailInternationalLargeFlatRateBox", "USPS Priority Mail International Large Flat Rate Box");
        hashmap.put("0_FedExPriorityOvernight", "FedEx Priority Overnight");
        hashmap.put("0_ShippingMethodOvernight", "One-day Shipping");
        hashmap.put("0_USPSGlobalExpress", "USPS Global Express Mail");
        hashmap.put("0_eBayNowImmediateDelivery", "eBay Now Immediate Delivery");
        hashmap.put("146_NL_StandardDelivery", "Standaardverzending");
        hashmap.put("146_NL_TPGPostTNTInternational", "TPG Post / TNT");
        hashmap.put("146_NL_GLSBusinessInternational", "GLS (Alleen zakelijke verkopers)");
        hashmap.put("146_NL_RegisteredMail", "Verzending met ontvangstbevestiging");
        hashmap.put("146_NL_Other", "Andere verzendservice");
        hashmap.put("146_NL_OtherInternational", "Andere internationale verzending (zie beschrijving)");
        hashmap.put("146_PromotionalShippingMethod", " Verzendservice voor speciale acties ");
        hashmap.put("146_NL_DPDGBRInternational", "DPD (Duitsland)");
        hashmap.put("146_NL_StandardInternational", "Vaste kosten standaard internationale verzending");
        hashmap.put("146_NL_ParcelPost", "Pakketpost");
        hashmap.put("146_NL_UPSInternational", "UPS");
        hashmap.put("146_NL_FedExInternational", "Fedex");
        hashmap.put("146_NL_DHLInternational", "DHL");
        hashmap.put("146_NL_ExpeditedInternational", "Vaste kosten versnelde internationale verzending");
        hashmap.put("146_NL_PickUp", "Ophalen bij de verkoper");
        hashmap.put("2_CA_SmallPacketsInternational", "Small Packets - International");
        hashmap.put("2_CA_PostRegularParcel", "Canada Post Regular Parcel");
        hashmap.put("2_CA_StandardInternational", "Standard Int'l Flat Rate Shipping");
        hashmap.put("2_CA_EconomyToUS", "Economy Shipping to United States");
        hashmap.put("2_CA_PostXpresspost", "Canada Post Xpresspost");
        hashmap.put("2_CA_UPSStandardCanada", "UPS Standard Canada");
        hashmap.put("2_CA_PostUSALetterPost", "Canada Post USA Letter-post");
        hashmap.put("2_CA_StandardToUS", "Standard Shipping to United States");
        hashmap.put("2_CA_SmallPacketsInternationalAir", "Small Packets - International - Air");
        hashmap.put("2_CA_PurolatorInternational", "Purolator International");
        hashmap.put("2_CA_PostInternationalLetterPost", "Canada Post International Letter-post");
        hashmap.put("2_CA_PostLightPacketInternational", "Canada Post Light Packet International");
        hashmap.put("2_CanadaPostExpeditedFlatRateBoxUSA", "Canada Post Expedited Flat Rate Box USA");
        hashmap.put("2_CA_UPSExpeditedCanada", "UPS Expedited Canada");
        hashmap.put("2_CA_PostPriorityCourier", "Canada Post Priority Courier");
        hashmap.put("2_CA_UPSExpressUnitedStates", "UPS Express United States");
        hashmap.put("2_CA_ExpeditedInternational", "Expedited Int'l Flat Rate Shipping");
        hashmap.put("2_PromotionalShippingMethod", "Promotional Shipping Service");
        hashmap.put("2_CA_SmallPacketsInternationalGround", "Small Packets - International - Ground");
        hashmap.put("2_CA_OtherInternational", "Other Int'l Shipping (see description)");
        hashmap.put("2_CA_PostExpeditedParcel", "Canada Post Expedited Parcel");
        hashmap.put("2_CA_UPSWorldWideExpedited", "UPS Worldwide Expedited");
        hashmap.put("2_CA_ExpeditedToUS", "Expedited Shipping to United States");
        hashmap.put("2_CA_UPSExpressSaverCanada", "UPS Express Saver Canada");
        hashmap.put("2_CA_UPSStandardUnitedStates", "UPS Standard United States");
        hashmap.put("2_CA_UPS3DaySelectUnitedStates", "UPS 3 Day Select United States");
        hashmap.put("2_CA_PostXpresspostInternational", "Canada Post Xpresspost - International");
        hashmap.put("2_CA_PostSmallPacketsUSAAir", "Canada Post Small Packets - USA - Air");
        hashmap.put("2_CA_PostXpresspostUSA", "Canada Post Xpresspost - USA");
        hashmap.put("2_CA_PostLightPacketUSA", "Canada Post Light Packet USA");
        hashmap.put("2_CA_PostExpeditedParcelUSA", "Canada Post Expedited Parcel - USA");
        hashmap.put("2_CA_PostSmallPacketsUSA", "Canada Post Small Packets - USA");
        hashmap.put("2_CA_PriorityWorldwide", "Canada Post Priority Worldwide");
        hashmap.put("2_CA_PostSmallPacketsUSAGround", "Canada Post Small Packets - USA - Ground");
        hashmap.put("2_CA_PostLettermail", "Canada Post Lettermail");
        hashmap.put("2_CanadaPostExpeditedFlatRateBox", "Canada Post Expedited Flat Rate Box");
        hashmap.put("2_CA_PostInternationalParcelAir", "Canada Post International Parcel - Air");
        hashmap.put("2_CA_StandardDelivery", "Standard Delivery");
        hashmap.put("2_CA_UPSExpeditedUnitedStates", "UPS Expedited United States");
        hashmap.put("2_CA_UPSWorldWideExpress", "UPS Worldwide Express");
        hashmap.put("2_CA_PostInternationalParcelSurface", "Canada Post International Parcel - Surface");
        hashmap.put("2_CA_UPSExpressCanada", "UPS Express Canada");
        hashmap.put("2_CA_ExpeditedDelivery", "Expedited Delivery");
        hashmap.put("2_CA_Pickup", "Local Pickup");
        hashmap.put("2_CA_EconomyShipping", "Economy Shipping");
        hashmap.put("210_CA_SmallPacketsInternational", "Petits paquets - International");
        hashmap.put("210_CA_PostRegularParcel", "Postes Canada, Colis standard (2-10 jours ouvrables)");
        hashmap.put("210_CA_StandardInternational", "Standard Int'l Flat Rate Shipping");
        hashmap.put("210_CA_EconomyToUS", "Exp\351dition \351conomie aux \311tats-Unis");
        hashmap.put("210_CA_PostXpresspost", "Postes Canada, Xpresspost (1-3 jours ouvrables)");
        hashmap.put("210_CA_UPSStandardCanada", "UPS Standard au Canada (1-3 jours ouvrables)");
        hashmap.put("210_CA_PostUSALetterPost", "Postes Canada, Poste aux lettres - \311.-U.");
        hashmap.put("210_CA_StandardToUS", "Exp\351dition standard aux \311tats-Unis");
        hashmap.put("210_CA_SmallPacketsInternationalAir", "Petits paquets - International,courrier-avion");
        hashmap.put("210_CA_PurolatorInternational", "Purolator International");
        hashmap.put("210_CA_PostInternationalLetterPost", "Postes Canada, Poste aux lettres - International");
        hashmap.put("210_CA_PostLightPacketInternational", "Paquets l\351gers - International");
        hashmap.put("210_CanadaPostExpeditedFlatRateBoxUSA", "Bo\356te \340 tarif fixe du service Colis acc\351l\351r\351s \311.-U. de Postes Canada");
        hashmap.put("210_CA_UPSExpeditedCanada", "UPS Expedited Canada (2 jours ouvrables)");
        hashmap.put("210_CA_PostPriorityCourier", "Postes Canada, Messageries prioritaires");
        hashmap.put("210_CA_UPSExpressUnitedStates", "UPS Express \311tats-Unis");
        hashmap.put("210_CA_ExpeditedInternational", "Expedited Int'l Flat Rate Shipping");
        hashmap.put("210_PromotionalShippingMethod", "Promotional Shipping Service");
        hashmap.put("210_CA_SmallPacketsInternationalGround", "Petits paquets - International, courrier-surface");
        hashmap.put("210_CA_OtherInternational", "Autres services d'exp\351dition internationale (voir description)");
        hashmap.put("210_CA_PostExpeditedParcel", "Postes Canada, Colis acc\351l\351r\351s (1-7 jours ouvrables)");
        hashmap.put("210_CA_UPSWorldWideExpedited", "UPS Worlwide Expedited");
        hashmap.put("210_CA_ExpeditedToUS", "Exp\351dition acc\351l\351r\351e aux \311tats-Unis");
        hashmap.put("210_CA_UPSExpressSaverCanada", "UPS Express Saver Canada (1 jour ouvrable)");
        hashmap.put("210_CA_UPSStandardUnitedStates", "UPS Standard aux \311tats-Unis");
        hashmap.put("210_CA_UPS3DaySelectUnitedStates", "3Day Select aux \311tats-Unis");
        hashmap.put("210_CA_PostXpresspostInternational", "Postes Canada, Xpresspost - International");
        hashmap.put("210_CA_PostSmallPacketsUSAAir", "Postes Canada, Petits paquets - \311.-U. par avion");
        hashmap.put("210_CA_PostXpresspostUSA", "Canada Post Xpresspost - USA");
        hashmap.put("210_CA_PostLightPacketUSA", "Paquets l\351gers - \311.-U.");
        hashmap.put("210_CA_PostExpeditedParcelUSA", "Canada Post Expedited Parcel - USA");
        hashmap.put("210_CA_PostSmallPacketsUSA", "Postes Canada, Petits paquets - \311.-U.");
        hashmap.put("210_CA_PriorityWorldwide", "Priorit\351 Mondial");
        hashmap.put("210_CA_PostSmallPacketsUSAGround", "Postes Canada, Petits paquets - \311.-U. service de surface");
        hashmap.put("210_CA_PostLettermail", "Postes Canada, Poste-lettres (2-6 jours ouvrables)");
        hashmap.put("210_CanadaPostExpeditedFlatRateBox", "Bo\356te \340 tarif fixe du service Colis acc\351l\351r\351s de Postes Canada (1-7 jours ouvrables)");
        hashmap.put("210_CA_PostInternationalParcelAir", "Postes Canada, Colis-avion - International");
        hashmap.put("210_CA_StandardDelivery", "Normes de livraison postale");
        hashmap.put("210_CA_UPSExpeditedUnitedStates", "UPS Expedited \311tats-Unis");
        hashmap.put("210_CA_UPSWorldWideExpress", "UPS Worldwide Express");
        hashmap.put("210_CA_PostInternationalParcelSurface", "Postes Canada, Colis international de surface");
        hashmap.put("210_CA_UPSExpressCanada", "UPS Express Canada (1 jour ouvrable)");
        hashmap.put("210_CA_ExpeditedDelivery", "Exp\351dition acc\351l\351r\351e (1-5 jours ouvrables)");
        hashmap.put("210_CA_Pickup", "L'acheteur vient chercher l'objet");
        hashmap.put("3_UK_RoyalMailHMForcesMailInternational", "Royal Mail HM Forces Mail");
        hashmap.put("3_UK_Parcelforce24", "Parcelforce 24");
        hashmap.put("3_UK_OtherCourier24", "Other 24 Hour Courier");
        hashmap.put("3_UK_CollectDropAtStoreDeliveryToDoor", "Collect+ : drop at store-delivery to door");
        hashmap.put("3_UK_RoyalMailSpecialDeliveryNextDay", "Royal Mail Special Delivery (TM) Next Day");
        hashmap.put("3_UK_ParcelForceInternationalScheduled", "Parcelforce Global Priority");
        hashmap.put("3_UK_RoyalMailSurfaceMailInternational", "Royal Mail Surface Mail");
        hashmap.put("3_UK_RoyalMailInternationalSignedFor", "Royal Mail International Signed-for");
        hashmap.put("3_UK_OtherCourier48", "Other 48 Hour Courier");
        hashmap.put("3_UK_OtherCourier5Days", "Other Courier 5 days");
        hashmap.put("3_UK_CollectInPersonInternational", "Express Int'l Postage");
        hashmap.put("3_UK_OtherInternationalPostage", "Other Int'l Postage (see description)");
        hashmap.put("3_UK_ParcelForceEuro48International", "Parcelforce Euro 48");
        hashmap.put("3_UK_RoyalMailStandardParcel", "Royal Mail Standard Parcels");
        hashmap.put("3_UK_Parcelforce48", "Parcelforce 48");
        hashmap.put("3_Courier", "Freight");
        hashmap.put("3_UK_StandardShippingFromOutside", "Standard Delivery from outside UK");
        hashmap.put("3_UK_SellersStandardInternationalRate", "Standard Int'l Postage");
        hashmap.put("3_UK_RoyalMailSpecialDelivery9am", "Royal Mail Special Delivery (TM) 9:00 am");
        hashmap.put("3_UK_OtherCourierOrDeliveryInternational", "Economy Int'l Postage");
        hashmap.put("3_UK_ExpeditedShippingFromOutside", "Express Delivery from outside UK");
        hashmap.put("3_UK_OtherCourier3Days", "Other Courier 3 days");
        hashmap.put("3_UK_RoyalMailSecondClassRecorded", "Royal Mail 2nd Class Recorded");
        hashmap.put("3_UK_RoyalMailAirmailInternational", "Royal Mail Airmail (Small Packets)");
        hashmap.put("3_UK_RoyalMailSpecialDelivery", "Royal Mail Special Delivery");
        hashmap.put("3_PromotionalShippingMethod", "Promotional Postage Service");
        hashmap.put("3_UK_CollectInPerson", "Collection in Person");
        hashmap.put("3_UK_ParcelForceIreland24International", "Parcelforce Ireland 24");
        hashmap.put("3_UK_SellersStandardRate", "Other Courier 3-5 days");
        hashmap.put("3_UK_RoyalMailFirstClassRecorded", "Royal Mail 1st Class Recorded");
        hashmap.put("3_UK_RoyalMailAirsureInternational", "Royal Mail Airsure");
        hashmap.put("3_UK_ParcelForceInternationalDatapost", "Parcelforce International Datapost");
        hashmap.put("3_UK_OtherCourier", "Other Courier");
        hashmap.put("3_UK_RoyalMailFirstClassStandard", "Royal Mail 1st Class Standard");
        hashmap.put("3_UK_myHermesDoorToDoorService", "myHermes - door to door service");
        hashmap.put("3_UK_RoyalMailSecondClassStandard", "Royal Mail 2nd Class Standard");
        hashmap.put("3_UK_EconomyShippingFromOutside", "Economy Delivery from outside UK");
        hashmap.put("3_UK_StandardInternationalFlatRatePostage", "Standard Int'l Flat Rate Postage");
        hashmap.put("3_UK_ExpeditedInternationalFlatRatePostage", "Expedited Int'l Flat Rate Postage");
        hashmap.put("3_UK_ParcelForceIntlValue", "Parcelforce Global Value");
        hashmap.put("207_MY_LocalCourier", "Local courier");
        hashmap.put("207_MY_LocalPickUpOnly", "Local pick up only");
        hashmap.put("207_MY_DomesticStandardMail", "Domestic standard mail");
        hashmap.put("207_MY_DomesticNonStandardMail", "Domestic non standard mail");
        hashmap.put("207_PromotionalShippingMethod", "Promotional Shipping Service");
        hashmap.put("211_PH_DomesticNonStandardMail", "Domestic non standard mail");
        hashmap.put("211_PromotionalShippingMethod", "Promotional Shipping Service");
        hashmap.put("211_PH_DomesticStandardMail", "Domestic standard mail");
        hashmap.put("211_PH_LocalPickUpOnly", "Local pick up only");
        hashmap.put("211_PH_LocalCourier", "Local courier");
        hashmap.put("101_IT_Pickup", "Ritiro in zona");
        hashmap.put("101_IT_ExpeditedInternational", "Spedizione internazionale celere a prezzo fisso");
        hashmap.put("101_IT_StandardInternational", "Spedizione internazionale standard a prezzo fisso");
        hashmap.put("101_IT_MailRegisteredLetterWithMark", "Posta raccomandata con contrassegno");
        hashmap.put("101_IT_InsuredMail", "Posta assicurata");
        hashmap.put("101_IT_ExpressPackageMaxi", "Paccocelere Maxi");
        hashmap.put("101_IT_MailRegisteredLetter", "Posta raccomandata");
        hashmap.put("101_IT_RegularMail", "Posta ordinaria");
        hashmap.put("101_IT_QuickPackage3", "Pacco celere 3");
        hashmap.put("101_IT_QuickPackage1", "Pacco celere 1");
        hashmap.put("101_IT_QuickMail", "Posta celere");
        hashmap.put("101_IT_ExpressCourier", "Corriere espresso");
        hashmap.put("101_PromotionalShippingMethod", "Servizio di spedizione promozionale");
        hashmap.put("101_IT_OtherInternational", "Altre spedizioni internazionali (vedi descrizione)");
        hashmap.put("101_IT_PriorityMail", "Posta prioritaria");
        hashmap.put("101_IT_RegularPackage", "Pacco ordinario");
        hashmap.put("203_IN_BuyerPicksUpAndPays", "Buyer Picks Up And Pays");
        hashmap.put("203_IN_ExpeditedInternational", "International - Expedited");
        hashmap.put("203_IN_StandardInternational", "International - Standard");
        hashmap.put("203_IN_LocalCOD", "Local COD - Delivery within seller's city");
        hashmap.put("203_IN_Courier", "Local Courier - Delivery within seller's city");
        hashmap.put("203_IN_NationalCOD", "National COD - Delivery outside seller's city");
        hashmap.put("203_IN_Express", "Flat Rate Courier - Delivery anywhere in India");
        hashmap.put("203_IN_Regular", "National Courier - Delivery outside seller's city");
        hashmap.put("203_PromotionalShippingMethod", "Promotional Shipping Service");
        hashmap.put("203_IN_FlatRateCOD", "Cash On Delivery");
        hashmap.put("203_IN_OtherInternational", "International - Other");
        hashmap.put("15_AU_SeaMailInternational", "AusPost Sea Mail Parcel");
        hashmap.put("15_AU_ExpressCourierInternational", "AusPost Express Courier International");
        hashmap.put("15_AU_PrePaidExpressPostInternationalEnvelopeB4", "AusPost PrePaid Express Post International Envelope B4");
        hashmap.put("15_PromotionalShippingMethod", "Promotional Postage Service");
        hashmap.put("15_AU_ExpressPostInternational", "AusPost Express Post International Parcel");
        hashmap.put("15_AU_PrePaidExpressPostInternationalEnvelopeC5", "AusPost PrePaid Express Post International Envelope C5");
        hashmap.put("15_AU_SmallParcelWithTracking", "Small Parcel With Tracking");
        hashmap.put("15_AU_AusPostRegisteredPostInternationalParcel", "AusPost Registered Post International Parcel");
        hashmap.put("15_AU_RegularwithInsurance", "Regular with Insurance");
        hashmap.put("15_AU_SmallParcels", "Small Parcels");
        hashmap.put("15_AU_ExpeditedInternational", "Express International Flat Rate Postage");
        hashmap.put("15_AU_Express", "AusPost Express Post Parcel");
        hashmap.put("15_AU_AusPostRegisteredPostInternationalPaddedBag500g", "AusPost Registered Post International Padded Bag 500g");
        hashmap.put("15_AU_Freight", "Freight");
        hashmap.put("15_AU_AustralianAirExpressFlatRate5kg", "Australian air Express Flat Rate 5kg");
        hashmap.put("15_AU_RegularParcelWithTrackingAndSignature", "AusPost Parcel with tracking and signature");
        hashmap.put("15_AU_PrePaidParcelPostSatchels3kg", "AusPost PrePaid Parcel Post Satchels 3kg");
        hashmap.put("15_AU_Pickup", "Local Pickup");
        hashmap.put("15_AU_SmallParcelWithTrackingAndSignature", "Small Parcel With Tracking And Signature");
        hashmap.put("15_AU_PrePaidExpressPostPlatinum3kg", "AusPost PrePaid Express Post Platinum 3kg");
        hashmap.put("15_AU_PrePaidExpressPostInternationalBox5kg", "AusPost PrePaid Express Post International Box 5Kg");
        hashmap.put("15_AU_StandardDeliveryFromOutsideAU", "Standard delivery from outside AU");
        hashmap.put("15_AU_eBayAusPost3kgFlatRateSatchel", "eBay AusPost 3kg Flat Rate Satchel");
        hashmap.put("15_AU_RegisteredParcelPostPrepaidSatchel3kg", "AusPost Registered Parcel Post Prepaid 3kg Satchel");
        hashmap.put("15_AU_RegisteredSmallParcel", "Registered Small Parcel");
        hashmap.put("15_AU_OtherInternational", "Other Int'l Postage (see description)");
        hashmap.put("15_AU_RegisteredParcelPost", "AusPost Registered Parcel Post");
        hashmap.put("15_AU_AustralianAirExpressFlatRate3kg", "Australian air Express Flat Rate 3kg");
        hashmap.put("15_AU_Other", "Other");
        hashmap.put("15_AU_PrePaidExpressPostSatchel500g", "AusPost PrePaid Express Post Satchel 500g");
        hashmap.put("15_AU_ExpeditedDeliveryFromOutsideAU", "Expedited delivery from outside AU");
        hashmap.put("15_AU_PrePaidExpressPostInternationalSatchels3kg", "AusPost PrePaid Express Post International Satchel 3Kg");
        hashmap.put("15_AU_PrePaidExpressPostInternationalBox20kg", "AusPost PrePaid Express Post International Box 20Kg");
        hashmap.put("15_AU_RegularParcelWithTracking", "AusPost Parcel with tracking");
        hashmap.put("15_AU_Registered", "AusPost Registered");
        hashmap.put("15_AU_StandardDelivery", "Standard delivery");
        hashmap.put("15_AU_Regular", "AusPost Regular Parcel");
        hashmap.put("15_AU_EMSInternationalCourierDocuments", "EMS International Courier - Documents");
        hashmap.put("15_AU_ExpressDelivery", "Express delivery");
        hashmap.put("15_AU_ExpressPostInternationalDocuments", "Express Post International - Documents");
        hashmap.put("15_AU_PrePaidExpressPostPlatinum500g", "AusPost PrePaid Express Post Platinum 500g");
        hashmap.put("15_AU_EconomyAirInternational", "Economy Air");
        hashmap.put("15_AU_PrePaidParcelPostSatchels500g", "AusPost PrePaid Parcel Post Satchels 500g");
        hashmap.put("15_AU_RegisteredParcelPostPrepaidSatchel500g", "AusPost Registered Parcel Post Prepaid 500g Satchel");
        hashmap.put("15_AU_PrePaidExpressPostSatchel3kg", "AusPost PrePaid Express Post Satchel 3kg");
        hashmap.put("15_AU_PrePaidExpressPostInternationalBox10kg", "AusPost PrePaid Express Post International Box 10Kg");
        hashmap.put("15_AU_EMSInternationalCourierParcels", "EMS International Courier - Parcels");
        hashmap.put("15_AU_Courier", "Courier");
        hashmap.put("15_AU_AusPostRegisteredPostInternationalPaddedBag1kg", "AusPost Registered Post International Padded Bag 1kg");
        hashmap.put("15_AU_AustralianAirExpressFlatRate1kg", "Australian air Express Flat Rate 1kg");
        hashmap.put("15_AU_StandardInternational", "Standard International Flat Rate Postage");
        hashmap.put("15_AU_ExpresswithInsurance", "Express with Insurance");
        hashmap.put("15_AU_PrePaidExpressPostSatchel5kg", "AusPost PrePaid Express Post Satchel 5kg");
        hashmap.put("15_AU_AustralianAirExpressMetro15kg", "Australian air Express Metro 15kg");
        hashmap.put("15_AU_EconomyDeliveryFromOutsideAU", "Economy delivery from outside AU");
        hashmap.put("15_AU_PrePaidExpressPostInternationalSatchels2kg", "AusPost PrePaid Express Post International Satchel 2Kg");
        hashmap.put("15_AU_eBayAusPost500gFlatRateSatchel", "eBay AusPost 500g Flat Rate Satchel");
        hashmap.put("15_AU_AirMailInternational", "AusPost Air Mail Parcel");
        hashmap.put("216_PromotionalShippingMethod", "Promotional Postage Service");
        hashmap.put("216_SG_InternationalStandardMail", "International standard mail");
        hashmap.put("216_SG_LocalCourier", "Local courier");
        hashmap.put("216_SG_LocalPickUpOnly", "Local pick up only");
        hashmap.put("216_SG_InternationalCourier", "International courier (DHL, FedEx, UPS)");
        hashmap.put("216_SG_DomesticSpeedpostIslandwide", "Domestic Speedpost Islandwide");
        hashmap.put("216_SG_InternationalExpressMailService", "International Express Mail Service (EMS)");
        hashmap.put("216_SG_DomesticNonStandardMail", "Domestic non standard mail");
        hashmap.put("216_SG_DomesticStandardMail", "Domestic standard mail");
        hashmap.put("216_SG_Delivery", "Local Delivery");
        hashmap.put("23_BEFR_RegisteredMail", "Courrier en recommand\351");
        hashmap.put("23_BEFR_StandardDelivery", "Livraison standard");
        hashmap.put("23_BEFR_TNTInternational", "TNT");
        hashmap.put("23_BEFR_LaPosteTaxipostLLS", "La Poste - Taxipost LLS (2 jours ouvrables)");
        hashmap.put("23_BEFR_TPGPostTNTInternational", "TPG Post/TNT (Pays-Bas)");
        hashmap.put("23_BEFR_ExpeditedInternational", "Frais fixes pour livraison internationale express");
        hashmap.put("23_BEFR_OtherShippingMethods", "Autres livraisons");
        hashmap.put("23_BEFR_ParcelPost", "Colis");
        hashmap.put("23_BEFR_LaPoste:envoieRecommande", "La Poste: envoie recommande");
        hashmap.put("23_BEFR_Express:Taxipost", "Express : Taxipost");
        hashmap.put("23_BEFR_LivraisonSecurise", "Livraison securise");
        hashmap.put("23_BEFR_PostInternationalRegistered", "La Poste - envoi recommand\351");
        hashmap.put("23_BEFR_LivraisonExpressPrixforFaitaire", "Livraison express - prix forfaitaire");
        hashmap.put("23_BEFR_LaPosteEnvoiNONPRIOR", "La Poste envoi NON PRIOR (2 jours ouvrables)");
        hashmap.put("23_BEFR_PostInternationalStandard", "La Poste - livraison standard");
        hashmap.put("23_BEFR_LaPosteStandardShipping", "La Poste - livraison standard (1 \340 2 jours ouvrables)");
        hashmap.put("23_BEFR_FedExInternational", "Fedex");
        hashmap.put("23_BEFR_Pickup", "L'acheteur vient chercher l'objet");
        hashmap.put("23_PromotionalShippingMethod", "Promotion sur les frais de livraison");
        hashmap.put("23_BEFR_OtherInternational", "Autres livraisons internationales (voir description)");
        hashmap.put("23_BEFR_PaquetKilopost", "Paquet Kilopost (2 jours ouvrables)");
        hashmap.put("23_BEFR_LaPosteCetifiedShipping", "La Poste - envoi recommand\351 (1 jour ouvrable)");
        hashmap.put("23_BEFR_DePostInternational", "De Post");
        hashmap.put("23_BEFR_DHLInternational", "DHL");
        hashmap.put("23_BEFR_StandardInternational", "Frais de livraison internationale fixes");
        hashmap.put("23_BEFR_Taxipost", "Taxipost (express)");
        hashmap.put("23_BEFR_LaPosteInternational", "La Poste (France)");
        hashmap.put("23_BEFR_LaPosteEnvoiRecommande", "La Poste envoi recommande (1 jour ouvrable)");
        hashmap.put("23_BEFR_LivraisonStandardPrixforFaitaire", "Livraison standard - prix forfaitaire");
        hashmap.put("23_BEFR_LaPosteTaxipostSecur", "La Poste - Taxipost Secur (1 jour ouvrable)");
        hashmap.put("23_BEFR_Other", "Autre service de livraison");
        hashmap.put("23_BEFR_LaPosteTaxipost24h", "La Poste - Taxipost 24h (1 jour ouvrable)");
        hashmap.put("23_BEFR_PriorityDelivery", "Livraison express");
        hashmap.put("23_BEFR_UPSInternational", "UPS");
        hashmap.put("23_BEFR_Paquet:KilopostInternationale", "Paquet : Kilopost Internationale");
        hashmap.put("23_BEFR_LaPoste:envoiePRIOR", "La Poste: envoie PRIOR");
        hashmap.put("23_BEFR_LivraisonStandardInternationalePrixforFaitaire", "Livraison standard internationale - prix forfaitaire");
        hashmap.put("23_BEFR_LaPoste:envoieNONPRIOR", "La Poste: envoie NON PRIOR");
        hashmap.put("23_BEFR_LivraisonExpressInternationalePrixforFaitaire", "Livraison express internationale - prix forfaitaire");
        hashmap.put("23_BEFR_LaPosteEnvoiPRIOR", "La Poste envoi PRIOR (1 jour ouvrable)");
        hashmap.put("23_BEFR_PointRetraitKiala", "Point retrait Kiala (1 a 4 jours ouvrables)");
        hashmap.put("16_AT_BitteTreffenSieEineAuswahl", "AT_BITTE_TREFFEN_SIE_EINE_AUSWAHL");
        hashmap.put("16_PromotionalShippingMethod", "Versand zum Sonderpreis");
        hashmap.put("16_AT_InsuredExpressOrCourier", "Versicherter Express- oder Kurierversand");
        hashmap.put("16_AT_InsuredDispatch", "Versicherter Versand");
        hashmap.put("16_AT_ExpeditedInternational", "Expresspauschale f\374r internationalen Versand");
        hashmap.put("16_AT_UnversicherterExpressVersandInternational", "Unversicherter Express - Versand");
        hashmap.put("16_AT_ExpressOrCourier", "Express- oder Kurierversand");
        hashmap.put("16_AT_COD", "Nachnahme (Versand inkl. Nachnahmegeb\374hr)");
        hashmap.put("16_AT_SpecialDispatch", "Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("16_AT_InsuredSpecialDispatch", "Versicherter Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("16_AT_OtherInternationalShipping", "Sonstiger Versand (Siehe Artikelbeschreibung)");
        hashmap.put("16_AT_ExpressOrCourierInternational", "Express- oder Kurierversand");
        hashmap.put("16_AT_Writing", "Einschreiben (Versand inkl. Einschreibengeb\374hr)");
        hashmap.put("16_AT_InsuredSpecialDispatchInternational", "Versicherter Sonderversand (z.B. Sperrgut, KFZ)");
        hashmap.put("16_AT_SpecialDispatchInternational", "Sonderversand (z.B. Sperrgut, KFZ)");
        hashmap.put("16_AT_InsuredExpressOrCourierInternational", "Versicherter Express- oder Kurierversand");
        hashmap.put("16_AT_VersicherterVersandInternational", "Versicherter Versand");
        hashmap.put("16_AT_Sonstige", "Sonstige (Siehe Artikelbeschreibung)");
        hashmap.put("16_AT_VersicherterExpressVersandInternational", "Versicherter Express - Versand");
        hashmap.put("16_AT_StandardInternational", "Standardpauschale f\374r internationalen Versand");
        hashmap.put("16_AT_StandardDispatch", "Standardversand (unversichert)");
        hashmap.put("16_AT_SonstigerVersandInternational", "Sonstiger Versand (Siehe Artikelbeschreibung)");
        hashmap.put("16_AT_EinschreibenVersandInklEinschreibengebuhr", "Einschreiben (Versand inkl. Einschreibengeb\374hr)");
        hashmap.put("16_AT_UnversicherterVersandInternational", "Unversicherter Versand");
        hashmap.put("16_AT_NachnahmeVersandInklNachnahmegebuhr", "Nachnahme (Versand inkl. Nachnahmegeb\374hr)");
        hashmap.put("16_AT_Pickup", "Abholung");
        hashmap.put("193_PromotionalShippingMethod", "Versand zum Sonderpreis");
        hashmap.put("193_CH_SonstigerVersandInternational", "Sonstiger Versand (Siehe Artikelbeschreibung)");
        hashmap.put("193_CH_Pickup", "Abholung");
        hashmap.put("193_CH_UnversicherterVersand", "Unversicherter Versand");
        hashmap.put("193_CH_Writing", "Einschreiben (Versand inkl. Einschreibengeb\374hr)");
        hashmap.put("193_CH_StandardDispatchBPost", "Standardversand (B-Post/Economy)");
        hashmap.put("193_CH_COD", "Nachnahme (Versand inkl. Nachnahmegeb\374hr)");
        hashmap.put("193_CH_VersicherterVersand", "Versicherter Versand");
        hashmap.put("193_CH_EconomySendungenInternational", "ECONOMY Sendungen");
        hashmap.put("193_CH_PrioritySendungenInternational", "PRIORITY Sendungen");
        hashmap.put("193_CH_BitteTreffenSieEineAuswahl", "CH_BITTE_TREFFEN_SIE_EINE_AUSWAHL");
        hashmap.put("193_CH_StandardversandBPostEconomy", "Standardversand (B-Post/Economy)");
        hashmap.put("193_CH_StandardInternational", "Standardpauschale f\374r internationalen Versand");
        hashmap.put("193_CH_InsuredDispatch", "Versicherter Versand (z.B. Assurance/Fragile)");
        hashmap.put("193_CH_InsuredExpressOrCourierInternational", "Versicherter Express- oder Kurierversand");
        hashmap.put("193_CH_NachnahmeVersandInklNachnahmegebuhr", "Nachnahme (Versand inkl. Nachnahmegeb\374hr)");
        hashmap.put("193_CH_SpecialDispatch", "Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("193_CH_StandardDispatchAPost", "Standardversand (A-Post/Priority)");
        hashmap.put("193_CH_Sonstige", "Sonstige (Siehe Artikelbeschreibung)");
        hashmap.put("193_CH_EinschreibenVersandInklEinschreibengebuhr", "Einschreiben (Versand inkl. Einschreibengeb\374hr)");
        hashmap.put("193_CH_StandardversandAPostPriority", "Standardversand (A-Post/Priority)");
        hashmap.put("193_CH_ExpressOrCourierInternational", "Express- oder Kurierversand");
        hashmap.put("193_CH_SonstigerVersandSieheArtikelbeschreibung", "Sonstiger Versand (Siehe Artikelbeschreibung)");
        hashmap.put("193_CH_ExpressOrCourier", "Express- oder Kurierversand");
        hashmap.put("193_CH_ExpeditedInternational", "Expresspauschale f\374r internationalen Versand");
        hashmap.put("193_CH_InsuredExpressOrCourier", "Versicherter Express- oder Kurierversand");
        hashmap.put("193_CH_InsuredSpecialDispatch", "Versicherter Sonderversand (z.B. M\366bel, KFZ)");
        hashmap.put("193_CH_UrgentSendungenInternational", "URGENT Sendungen");
        hashmap.put("193_CH_VersicherterSonderversandZBSperrgutKFZ", "Versicherter Sonderversand (z.B. Sperrgut, KFZ)");
        hashmap.put("193_CH_SonderversandZBSperrgutKFZ", "Sonderversand (z.B. Sperrgut, KFZ)");
        hashmap.put("212_PromotionalShippingMethod", "Promocyjna us\u0142uga wysy\u0142kowa");
        hashmap.put("212_PL_DomesticSpecial", "Przesy\u0142ka krajowa \u2013 priorytetowa");
        hashmap.put("212_PL_DomesticRegular", "Przesy\u0142ka krajowa \u2013 zwyk\u0142a");
        hashmap.put("212_PL_InternationalSpecial", "Przesy\u0142ka zagraniczna - priorytetowa");
        hashmap.put("212_PL_UPSInternational", "UPS");
        hashmap.put("212_PL_InternationalRegular", "Przesy\u0142ka zagraniczna - zwyk\u0142a");
        hashmap.put("212_PL_DHLInternational", "DHL");
        hashmap.put("212_PL_PickUp", "Odbi\363r");
        hashmap.put("123_BENL_TPGPostTNTInternational", "TPG Post / TNT (Netherlands)");
        hashmap.put("123_BENL_OtherInternational", "Andere internationale verzending (zie beschrijving)");
        hashmap.put("123_BENL_DePostZendingPRIOR", "De Post zending - PRIOR (1 werkdag)");
        hashmap.put("123_BENL_DePostStandardShipping", "De Post - standaardverzending (1 tot 2 werkdagen)");
        hashmap.put("123_BENL_UPSInternational", "UPS");
        hashmap.put("123_BENL_ExpeditedInternational", "Vaste kosten versnelde internationale verzending");
        hashmap.put("123_BENL_DePostTaxipostLLS", "De Post - Taxipost LLS (2 werkdagen)");
        hashmap.put("123_BENL_TaxipostExpressverzending", "Taxipost expressverzending");
        hashmap.put("123_BENL_DePostTaxipost24h", "De Post - Taxipost 24u (1 werkdag)");
        hashmap.put("123_BENL_DePostZendingAangetekendInternational", "De Post zending - aangetekend");
        hashmap.put("123_BENL_StandardDelivery", "Standaardverzending");
        hashmap.put("123_BENL_TNTInternational", "TNT");
        hashmap.put("123_BENL_VerzekerdeVerzending", "Verzekerde verzending");
        hashmap.put("123_BENL_Pickup", "Ophalen bij de verkoper");
        hashmap.put("123_BENL_LaPosteInternational", "La Poste (France)");
        hashmap.put("123_PromotionalShippingMethod", "Korting op verzending");
        hashmap.put("123_BENL_DePostInternational", "De Post");
        hashmap.put("123_BENL_PostInternationalRegistered", "De Post - aangetekende zending");
        hashmap.put("123_BENL_PostInternationalStandard", "De Post - standaardverzending");
        hashmap.put("123_BENL_DePostZendingAangetekend", "De Post zending - aangetekend (1 werkdag)");
        hashmap.put("123_BENL_KilopostPakjeInternationaal", "Kilopost pakje Internationaal");
        hashmap.put("123_BENL_DePostTaxipostSecur", "De Post - Taxipost Secur (1 werkdag)");
        hashmap.put("123_BENL_DePostZendingPRIORInternational", "De Post zending - PRIOR");
        hashmap.put("123_BENL_RegisteredMail", "Verzending met ontvangstbevestiging");
        hashmap.put("123_BENL_VasteKostenVersneldeVerzending", "Vaste kosten versnelde verzending");
        hashmap.put("123_BENL_Taxipost", "Taxipost (express)");
        hashmap.put("123_BENL_DePostZendingNONPRIORInternational", "De Post zending - NON PRIOR");
        hashmap.put("123_BENL_ParcelPost", "Pakketpost");
        hashmap.put("123_BENL_OtherShippingMethods", "Andere verzending");
        hashmap.put("123_BENL_DHLInternational", "DHL");
        hashmap.put("123_BENL_DePostCetifiedShipping", "De Post - aangetekende zending (1 werkdag)");
        hashmap.put("123_BENL_Other", "Andere verzendservice");
        hashmap.put("123_BENL_StandardInternational", "Vaste kosten standaard internationale verzending");
        hashmap.put("123_BENL_KialaAfhaalpunt", "Kiala afhaalpunt (1 tot 4 werkdagen)");
        hashmap.put("123_BENL_VerzekerdeVerzendingInternational", "Verzekerde verzending");
        hashmap.put("123_BENL_DePostZendingNONPRIOR", "De Post zending - NON PRIOR (2 werkdagen)");
        hashmap.put("123_BENL_KilopostPakje", "Kilopost pakje (2 werkdagen)");
        hashmap.put("123_BENL_VasteKostenStandaardVerzending", "Vaste kosten standaard verzending");
        hashmap.put("123_BENL_PriorityDelivery", "Verzending met prioriteit");
        hashmap.put("123_BENL_FedExInternational", "Fedex");
        return hashmap;
    }

}
