// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.sponsorpay.utils;

import android.content.Context;
import android.content.SharedPreferences;
import java.util.UUID;

// Referenced classes of package com.sponsorpay.utils:
//            SignatureTools

public class UserId
{

    public static final String STATE_GENERATED_USERID_KEY = "STATE_GENERATED_USERID_KEY";

    public UserId()
    {
    }

    private static String generateUserId()
    {
        Object obj;
label0:
        {
            obj = new StringBuilder();
            ((StringBuilder) (obj)).append(UUID.randomUUID());
            String s = ((StringBuilder) (obj)).toString();
            String s1 = SignatureTools.generateSHA1ForString(s);
            if (s1 != null)
            {
                obj = s1;
                if (!s1.equals("nosha1"))
                {
                    break label0;
                }
            }
            obj = s;
        }
        return ((String) (obj));
    }

    public static String getAutoGenerated(Context context)
    {
        com/sponsorpay/utils/UserId;
        JVM INSTR monitorenter ;
        String s;
        SharedPreferences sharedpreferences;
        sharedpreferences = context.getSharedPreferences("SponsorPayPublisherState", 0);
        s = sharedpreferences.getString("STATE_GENERATED_USERID_KEY", null);
        context = s;
        if (s != null)
        {
            break MISSING_BLOCK_LABEL_55;
        }
        context = generateUserId();
        android.content.SharedPreferences.Editor editor = sharedpreferences.edit();
        editor.putString("STATE_GENERATED_USERID_KEY", context);
        editor.commit();
        com/sponsorpay/utils/UserId;
        JVM INSTR monitorexit ;
        return context;
        context;
        throw context;
    }
}
