// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 


public final class tl extends Enum
{

    public static final tl A;
    public static final tl B;
    public static final tl C;
    public static final tl D;
    public static final tl E;
    public static final tl F;
    public static final tl G;
    public static final tl H;
    public static final tl I;
    public static final tl J;
    public static final tl K;
    public static final tl L;
    public static final tl M;
    public static final tl N;
    public static final tl O;
    public static final tl P;
    public static final tl Q;
    public static final tl R;
    public static final tl S;
    public static final tl T;
    public static final tl U;
    public static final tl V;
    public static final tl W;
    public static final tl X;
    public static final tl Y;
    public static final tl Z;
    public static final tl a;
    public static final tl aA;
    public static final tl aB;
    public static final tl aC;
    public static final tl aD;
    public static final tl aE;
    public static final tl aF;
    public static final tl aG;
    public static final tl aH;
    public static final tl aI;
    public static final tl aJ;
    public static final tl aK;
    public static final tl aL;
    public static final tl aM;
    public static final tl aN;
    public static final tl aO;
    public static final tl aP;
    public static final tl aQ;
    public static final tl aR;
    public static final tl aS;
    public static final tl aT;
    public static final tl aU;
    public static final tl aV;
    public static final tl aW;
    public static final tl aX;
    public static final tl aY;
    public static final tl aZ;
    public static final tl aa;
    public static final tl ab;
    public static final tl ac;
    public static final tl ad;
    public static final tl ae;
    public static final tl af;
    public static final tl ag;
    public static final tl ah;
    public static final tl ai;
    public static final tl aj;
    public static final tl ak;
    public static final tl al;
    public static final tl am;
    public static final tl an;
    public static final tl ao;
    public static final tl ap;
    public static final tl aq;
    public static final tl ar;
    public static final tl as;
    public static final tl at;
    public static final tl au;
    public static final tl av;
    public static final tl aw;
    public static final tl ax;
    public static final tl ay;
    public static final tl az;
    public static final tl b;
    public static final tl bA;
    public static final tl bB;
    public static final tl bC;
    public static final tl bD;
    public static final tl bE;
    public static final tl bF;
    public static final tl bG;
    public static final tl bH;
    public static final tl bI;
    public static final tl bJ;
    public static final tl bK;
    public static final tl bL;
    public static final tl bM;
    public static final tl bN;
    public static final tl bO;
    public static final tl bP;
    public static final tl bQ;
    public static final tl bR;
    public static final tl bS;
    public static final tl bT;
    public static final tl bU;
    public static final tl bV;
    public static final tl bW;
    public static final tl bX;
    public static final tl bY;
    public static final tl bZ;
    public static final tl ba;
    public static final tl bb;
    public static final tl bc;
    public static final tl bd;
    public static final tl be;
    public static final tl bf;
    public static final tl bg;
    public static final tl bh;
    public static final tl bi;
    public static final tl bj;
    public static final tl bk;
    public static final tl bl;
    public static final tl bm;
    public static final tl bn;
    public static final tl bo;
    public static final tl bp;
    public static final tl bq;
    public static final tl br;
    public static final tl bs;
    public static final tl bt;
    public static final tl bu;
    public static final tl bv;
    public static final tl bw;
    public static final tl bx;
    public static final tl by;
    public static final tl bz;
    public static final tl c;
    public static final tl cA;
    public static final tl cB;
    public static final tl cC;
    public static final tl cD;
    public static final tl cE;
    public static final tl cF;
    public static final tl cG;
    public static final tl cH;
    public static final tl cI;
    public static final tl cJ;
    public static final tl cK;
    public static final tl cL;
    public static final tl cM;
    public static final tl cN;
    public static final tl cO;
    public static final tl cP;
    public static final tl cQ;
    public static final tl cR;
    public static final tl cS;
    public static final tl cT;
    public static final tl cU;
    public static final tl cV;
    public static final tl cW;
    public static final tl cX;
    public static final tl cY;
    public static final tl cZ;
    public static final tl ca;
    public static final tl cb;
    public static final tl cc;
    public static final tl cd;
    public static final tl ce;
    public static final tl cf;
    public static final tl cg;
    public static final tl ch;
    public static final tl ci;
    public static final tl cj;
    public static final tl ck;
    public static final tl cl;
    public static final tl cm;
    public static final tl cn;
    public static final tl co;
    public static final tl cp;
    public static final tl cq;
    public static final tl cr;
    public static final tl cs;
    public static final tl ct;
    public static final tl cu;
    public static final tl cv;
    public static final tl cw;
    public static final tl cx;
    public static final tl cy;
    public static final tl cz;
    public static final tl d;
    public static final tl da;
    public static final tl db;
    private static final tl dd[];
    public static final tl e;
    public static final tl f;
    public static final tl g;
    public static final tl h;
    public static final tl i;
    public static final tl j;
    public static final tl k;
    public static final tl l;
    public static final tl m;
    public static final tl n;
    public static final tl o;
    public static final tl p;
    public static final tl q;
    public static final tl r;
    public static final tl s;
    public static final tl t;
    public static final tl u;
    public static final tl v;
    public static final tl w;
    public static final tl x;
    public static final tl y;
    public static final tl z;
    private final String dc;

    private tl(String s1, int i1, String s2)
    {
        super(s1, i1);
        dc = s2;
    }

    public String toString()
    {
        return dc;
    }

    static 
    {
        a = new tl("ACCOUNT", 0, "account");
        b = new tl("ACTIVITY", 1, "activity");
        c = new tl("ADDITIONAL_PARAMS", 2, "additional_params");
        d = new tl("ADVERTISER", 3, "advertiser");
        e = new tl("ALGORITHM", 4, "algorithm");
        f = new tl("ALLOW_ANCHOR", 5, "allow_anchor");
        g = new tl("ALLOW_HASH", 6, "allow_hash");
        h = new tl("ALLOW_LINKER", 7, "allow_linker");
        i = new tl("ANALYTICS_FIELDS", 8, "analytics_fields");
        j = new tl("ANALYTICS_PASS_THROUGH", 9, "analytics_pass_through");
        k = new tl("ANONYMIZE_IP", 10, "anonymize_ip");
        l = new tl("APP_NAME", 11, "app_name");
        m = new tl("APP_VERSION", 12, "app_version");
        n = new tl("ARG0", 13, "arg0");
        o = new tl("ARG1", 14, "arg1");
        p = new tl("ATTRIBUTE", 15, "attribute");
        q = new tl("AUTO_LINK_DOMAINS", 16, "auto_link_domains");
        r = new tl("BLACKLISTED_BEHAVIOR", 17, "blacklisted_behavior");
        s = new tl("CACHE_BUSTER", 18, "cache_buster");
        t = new tl("CACHE_BUSTER_VALUE", 19, "cache_buster_value");
        u = new tl("CAMPAIGN_CONTENT_KEY", 20, "campaign_content_key");
        v = new tl("CAMPAIGN_CONTENT_OVERRIDE", 21, "campaign_content_override");
        w = new tl("CAMPAIGN_COOKIE_TIMEOUT", 22, "campaign_cookie_timeout");
        x = new tl("CAMPAIGN_MEDIUM_KEY", 23, "campaign_medium_key");
        y = new tl("CAMPAIGN_MEDIUM_OVERRIDE", 24, "campaign_medium_override");
        z = new tl("CAMPAIGN_NAME_KEY", 25, "campaign_name_key");
        A = new tl("CAMPAIGN_NAME_OVERRIDE", 26, "campaign_name_override");
        B = new tl("CAMPAIGN_NO_KEY", 27, "campaign_no_key");
        C = new tl("CAMPAIGN_SOURCE_KEY", 28, "campaign_source_key");
        D = new tl("CAMPAIGN_SOURCE_OVERRIDE", 29, "campaign_source_override");
        E = new tl("CAMPAIGN_TERM_KEY", 30, "campaign_term_key");
        F = new tl("CAMPAIGN_TERM_OVERRIDE", 31, "campaign_term_override");
        G = new tl("CAMPAIGN_TRACK", 32, "campaign_track");
        H = new tl("CATEGORY", 33, "category");
        I = new tl("CHECK_VALIDATION", 34, "check_validation");
        J = new tl("CLEAR_PERSISTENT_DATA_LAYER_PREFIX", 35, "clear_data_layer_prefix");
        K = new tl("CLICK_ID", 36, "click_id");
        L = new tl("CLIENT_INFO", 37, "client_info");
        M = new tl("COMPANY", 38, "company");
        N = new tl("COMPONENT", 39, "component");
        O = new tl("CONTENT_DESCRIPTION", 40, "content_description");
        P = new tl("CONTENT_GROUP", 41, "content_group");
        Q = new tl("CONVERSION_ID", 42, "conversion_id");
        R = new tl("COOKIE_DOMAIN", 43, "cookie_domain");
        S = new tl("COOKIE_EXPIRATION", 44, "cookie_expiration");
        T = new tl("COOKIE_NAME", 45, "cookie_name");
        U = new tl("COOKIE_PATH", 46, "cookie_path");
        V = new tl("COOKIE_PATH_COPY", 47, "cookie_path_copy");
        W = new tl("COUNTRY", 48, "country");
        X = new tl("CURRENCY_CODE", 49, "currency_code");
        Y = new tl("CUSTOM_URL_SOURCE", 50, "custom_url_source");
        Z = new tl("CUSTOM_VARS", 51, "custom_vars");
        aa = new tl("CUSTOMER_ID", 52, "customer_id");
        ab = new tl("DATA_LAYER_VERSION", 53, "data_layer_version");
        ac = new tl("DATA_PROVIDER_ID", 54, "data_provider_id");
        ad = new tl("DEBUG", 55, "debug");
        ae = new tl("DECORATE_FORM", 56, "decorate_form");
        af = new tl("DECORATE_FORMS_AUTO_LINK", 57, "decorate_forms_auto_link");
        ag = new tl("DECORATE_LINK", 58, "decorate_link");
        ah = new tl("DEFAULT_PAGES", 59, "default_pages");
        ai = new tl("DEFAULT_VALUE", 60, "default_value");
        aj = new tl("DEPENDENCIES", 61, "dependencies");
        ak = new tl("DETECT_FLASH", 62, "detect_flash");
        al = new tl("DETECT_TITLE", 63, "detect_title");
        am = new tl("DIMENSION", 64, "dimension");
        an = new tl("DOMAIN_NAME", 65, "domain_name");
        ao = new tl("DOUBLE_CLICK", 66, "double_click");
        ap = new tl("ECOMMERCE_MACRO_DATA", 67, "ecommerce_macro_data");
        aq = new tl("ECOMMERCE_USE_DATA_LAYER", 68, "ecommerce_use_data_layer");
        ar = new tl("ELEMENT", 69, "element");
        as = new tl("ELEMENTS", 70, "elements");
        at = new tl("EMAIL", 71, "email");
        au = new tl("EMPLOYEE_RANGE", 72, "employee_range");
        av = new tl("ENABLE_ECOMMERCE", 73, "enable_ecommerce");
        aw = new tl("ENABLE_ALL_VIDEOS", 74, "enable_all_videos");
        ax = new tl("ENABLE_PRODUCT_REPORTING", 75, "enable_product_reporting");
        ay = new tl("ESCAPE", 76, "escape");
        az = new tl("EVENT_ACTION", 77, "event_action");
        aA = new tl("EVENT_CATEGORY", 78, "event_category");
        aB = new tl("EVENT_LABEL", 79, "event_label");
        aC = new tl("EVENT_VALUE", 80, "event_value");
        aD = new tl("EXCEPTION_DESCRIPTION", 81, "exception_description");
        aE = new tl("EXCEPTION_FATAL", 82, "exception_fatal");
        aF = new tl("EXPERIMENT_KEY", 83, "experiment_key");
        aG = new tl("FAILED_BEHAVIOR", 84, "failed_behavior");
        aH = new tl("SECTION_INDEX", 85, "section_index");
        aI = new tl("FIELDS_TO_SET", 86, "fields_to_set");
        aJ = new tl("FORCE_SSL", 87, "force_ssl");
        aK = new tl("FORM_OBJECT", 88, "form_object");
        aL = new tl("FUNCTION", 89, "function");
        aM = new tl("FUNCTION_CALL_NAME", 90, "function_call_macro_name");
        aN = new tl("GROUP", 91, "group");
        aO = new tl("HIT_CALLBACK", 92, "hit_callback");
        aP = new tl("HTML", 93, "html");
        aQ = new tl("ID", 94, "id");
        aR = new tl("IGNORED_ORGANIC", 95, "ignored_organic");
        aS = new tl("IGNORED_REF", 96, "ignored_ref");
        aT = new tl("IGNORE_CASE", 97, "ignore_case");
        aU = new tl("INPUT", 98, "input");
        aV = new tl("INPUT_FORMAT", 99, "input_format");
        aW = new tl("INSTANCE_NAME", 100, "instance_name");
        aX = new tl("INSTANCE_LABEL", 101, "instance_label");
        aY = new tl("INTERVAL", 102, "interval");
        aZ = new tl("ITEM_SEPARATOR", 103, "item_separator");
        ba = new tl("JAVASCRIPT", 104, "javascript");
        bb = new tl("JSON", 105, "json");
        bc = new tl("KEYWORD", 106, "keyword");
        bd = new tl("KEY_VALUE_SEPARATOR", 107, "key_value_separator");
        be = new tl("LABEL", 108, "label");
        bf = new tl("LANGUAGE", 109, "language");
        bg = new tl("LIMIT", 110, "limit");
        bh = new tl("LINK", 111, "link");
        bi = new tl("LINK_BY_POST", 112, "link_by_post");
        bj = new tl("LINK_ID", 113, "link_id");
        bk = new tl("LIVE_ONLY", 114, "live_only");
        bl = new tl("LOCAL_GIF_PATH", 115, "local_gif_path");
        bm = new tl("LOCALE", 116, "locale");
        bn = new tl("LOCATION", 117, "location");
        bo = new tl("MAP", 118, "map");
        bp = new tl("MAX", 119, "max");
        bq = new tl("MIN", 120, "min");
        br = new tl("METRIC", 121, "metric");
        bs = new tl("NAME", 122, "name");
        bt = new tl("NAMESPACE_CODE", 123, "namespace_code");
        bu = new tl("NAMESPACE_ID", 124, "namespace_id");
        bv = new tl("NAMESPACE_VALUE", 125, "namespace_value");
        bw = new tl("NONINTERACTION", 126, "noninteraction");
        bx = new tl("NOT_DEFAULT_MACRO", 127, "not_default_macro");
        by = new tl("NO_PADDING", 128, "no_padding");
        bz = new tl("NUMBER", 129, "number");
        bA = new tl("OPTOUT", 130, "optout");
        bB = new tl("ORDER", 131, "order");
        bC = new tl("ORDER_ID", 132, "order_id");
        bD = new tl("ORDER_VALUE", 133, "order_value");
        bE = new tl("ORDINAL", 134, "ordinal");
        bF = new tl("ORGANIC", 135, "organic");
        bG = new tl("OUTPUT_FORMAT", 136, "output_format");
        bH = new tl("PAGE", 137, "page");
        bI = new tl("PAGE_PATH", 138, "page_path");
        bJ = new tl("PARTITION", 139, "partition");
        bK = new tl("PERCENTAGE", 140, "percentage");
        bL = new tl("PIXEL", 141, "pixel");
        bM = new tl("PLATFORM", 142, "platform");
        bN = new tl("PRICES", 143, "prices");
        bO = new tl("PRIORITY", 144, "priority");
        bP = new tl("PRODUCT", 145, "product");
        bQ = new tl("PRODUCT_DATA", 146, "product_data");
        bR = new tl("PRODUCT_ID", 147, "product_id");
        bS = new tl("PRODUCT_IDS", 148, "product_ids");
        bT = new tl("PUSH_AFTER_EVALUATE", 149, "push_after_evaluate");
        bU = new tl("QUANTITY", 150, "quantity");
        bV = new tl("QUERY_KEY", 151, "query_key");
        bW = new tl("QUERY_LISTS", 152, "query_lists");
        bX = new tl("REFERRER", 153, "referrer");
        bY = new tl("REFERRER_OVERRIDE", 154, "referrer_override");
        bZ = new tl("REVENUE", 155, "revenue");
        ca = new tl("SAMPLE_RATE", 156, "sample_rate");
        cb = new tl("SELECTOR", 157, "selector");
        cc = new tl("SEND_HITS_TO_GOOGLE", 158, "send_hits_to_google");
        cd = new tl("SESSION_CONTROL", 159, "session_control");
        ce = new tl("SESSION_COOKIE_TIMEOUT", 160, "session_cookie_timeout");
        cf = new tl("SITE_SPEED_SAMPLE_RATE", 161, "site_speed_sample_rate");
        cg = new tl("SOCIAL_ACTION", 162, "social_action");
        ch = new tl("SOCIAL_ACTION_TARGET", 163, "social_action_target");
        ci = new tl("SOCIAL_NETWORK", 164, "social_network");
        cj = new tl("SOCIAL_USE_DATA_LAYER", 165, "social_use_data_layer");
        ck = new tl("SERVER_SIDE", 166, "server_side");
        cl = new tl("STANDARD_INDUSTRIAL_CLASSIFICATION", 167, "standard_industrial_classification");
        cm = new tl("STRING", 168, "string");
        cn = new tl("STRIP_WWW", 169, "strip_www");
        co = new tl("TAG_ID", 170, "tag_id");
        cp = new tl("TAG_LIST", 171, "tag_list");
        cq = new tl("TAG_REFERENCE", 172, "tag_reference");
        cr = new tl("TARGET_URL", 173, "target_url");
        cs = new tl("TIMING_CATEGORY", 174, "timing_category");
        ct = new tl("TIMING_LABEL", 175, "timing_label");
        cu = new tl("TIMING_SAMPLE_RATE", 176, "timing_sample_rate");
        cv = new tl("TIMING_VALUE", 177, "timing_value");
        cw = new tl("TIMING_VAR", 178, "timing_var");
        cx = new tl("TITLE", 179, "title");
        cy = new tl("TRACK_APPVIEW", 180, "track_appview");
        cz = new tl("TRACK_DATA", 181, "track_data");
        cA = new tl("TRACK_EVENT", 182, "track_event");
        cB = new tl("TRACK_EXCEPTION", 183, "track_exception");
        cC = new tl("TRACK_SOCIAL", 184, "track_social");
        cD = new tl("TRACK_TIMING", 185, "track_timing");
        cE = new tl("TRACK_TRANSACTION", 186, "track_transaction");
        cF = new tl("TRACKER_NAME", 187, "tracker_name");
        cG = new tl("TRACKING_ID", 188, "tracking_id");
        cH = new tl("TRANSACTION_DATALAYER_MAP", 189, "transaction_datalayer_map");
        cI = new tl("TRANSACTION_ID", 190, "transaction_id");
        cJ = new tl("TRANSACTION_ITEM_DATALAYER_MAP", 191, "transaction_item_datalayer_map");
        cK = new tl("TRANSACTION_VARIABLE", 192, "transaction_variable");
        cL = new tl("TYPE", 193, "type");
        cM = new tl("UNIQUE_TRIGGER_ID", 194, "unique_trigger_id");
        cN = new tl("UNREPEATABLE", 195, "unrepeatable");
        cO = new tl("URL", 196, "url");
        cP = new tl("USE_DATA_LAYER", 197, "use_data_layer");
        cQ = new tl("USE_HASH", 198, "use_hash");
        cR = new tl("USE_IFRAME", 199, "use_iframe");
        cS = new tl("USE_IMAGE_TAG", 200, "use_image_tag");
        cT = new tl("USE_POSTSCRIBE", 201, "use_postscribe");
        cU = new tl("USER_ID", 202, "user_id");
        cV = new tl("USER_VARIABLE", 203, "user_variable");
        cW = new tl("VALUE", 204, "value");
        cX = new tl("VALUE_IN_DOLLARS", 205, "value_in_dollars");
        cY = new tl("VISITOR_COOKIE_TIMEOUT", 206, "visitor_cookie_timeout");
        cZ = new tl("WAIT_FOR_TAGS", 207, "wait_for_tags");
        da = new tl("WAIT_FOR_TAGS_TIMEOUT", 208, "wait_for_tags_timeout");
        db = new tl("WIDGET_IDS", 209, "widget_ids");
        dd = (new tl[] {
            a, b, c, d, e, f, g, h, i, j, 
            k, l, m, n, o, p, q, r, s, t, 
            u, v, w, x, y, z, A, B, C, D, 
            E, F, G, H, I, J, K, L, M, N, 
            O, P, Q, R, S, T, U, V, W, X, 
            Y, Z, aa, ab, ac, ad, ae, af, ag, ah, 
            ai, aj, ak, al, am, an, ao, ap, aq, ar, 
            as, at, au, av, aw, ax, ay, az, aA, aB, 
            aC, aD, aE, aF, aG, aH, aI, aJ, aK, aL, 
            aM, aN, aO, aP, aQ, aR, aS, aT, aU, aV, 
            aW, aX, aY, aZ, ba, bb, bc, bd, be, bf, 
            bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, 
            bq, br, bs, bt, bu, bv, bw, bx, by, bz, 
            bA, bB, bC, bD, bE, bF, bG, bH, bI, bJ, 
            bK, bL, bM, bN, bO, bP, bQ, bR, bS, bT, 
            bU, bV, bW, bX, bY, bZ, ca, cb, cc, cd, 
            ce, cf, cg, ch, ci, cj, ck, cl, cm, cn, 
            co, cp, cq, cr, cs, ct, cu, cv, cw, cx, 
            cy, cz, cA, cB, cC, cD, cE, cF, cG, cH, 
            cI, cJ, cK, cL, cM, cN, cO, cP, cQ, cR, 
            cS, cT, cU, cV, cW, cX, cY, cZ, da, db
        });
    }
}
