// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package com.google.android.gms.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

// Referenced classes of package com.google.android.gms.internal:
//            zzlc

public final class zzln extends OptionalPendingResult
{

    private final zzlc zzacI;

    public zzln(PendingResult pendingresult)
    {
        if (!(pendingresult instanceof zzlc))
        {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        } else
        {
            zzacI = (zzlc)pendingresult;
            return;
        }
    }

    public final Result await()
    {
        return zzacI.await();
    }

    public final Result await(long l, TimeUnit timeunit)
    {
        return zzacI.await(l, timeunit);
    }

    public final void cancel()
    {
        zzacI.cancel();
    }

    public final Result get()
    {
        if (isDone())
        {
            return await(0L, TimeUnit.MILLISECONDS);
        } else
        {
            throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
        }
    }

    public final boolean isCanceled()
    {
        return zzacI.isCanceled();
    }

    public final boolean isDone()
    {
        return zzacI.isReady();
    }

    public final void setResultCallback(ResultCallback resultcallback)
    {
        zzacI.setResultCallback(resultcallback);
    }

    public final void setResultCallback(ResultCallback resultcallback, long l, TimeUnit timeunit)
    {
        zzacI.setResultCallback(resultcallback, l, timeunit);
    }

    public final void zza(com.google.android.gms.common.api.PendingResult.zza zza1)
    {
        zzacI.zza(zza1);
    }

    public final Integer zznF()
    {
        return zzacI.zznF();
    }
}
